/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc;
import vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuocModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the KeHoachKiemDemNuoc service. Represents a row in the &quot;ME_KEHOACHKIEMDEMNUOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuocModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KeHoachKiemDemNuocImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see KeHoachKiemDemNuocImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc
 * @see vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuocModel
 * @generated
 */
public class KeHoachKiemDemNuocModelImpl extends BaseModelImpl<KeHoachKiemDemNuoc>
	implements KeHoachKiemDemNuocModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ke hoach kiem dem nuoc model instance should use the {@link vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc} interface instead.
	 */
	public static final String TABLE_NAME = "ME_KEHOACHKIEMDEMNUOC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "NAM", Types.INTEGER },
			{ "TRAMCAPNUOCID", Types.INTEGER },
			{ "KIEMDEMVIENID", Types.INTEGER },
			{ "NGAYBATDAU", Types.TIMESTAMP },
			{ "NGAYKETTHUC", Types.TIMESTAMP },
			{ "MOTA", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.INTEGER },
			{ "NGAYXUATBAN", Types.TIMESTAMP },
			{ "IDNGUOIXUATBAN", Types.INTEGER },
			{ "NGAYDONG", Types.TIMESTAMP },
			{ "IDNGUOIDONG", Types.INTEGER },
			{ "lastsavepoint", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_KEHOACHKIEMDEMNUOC (ID INTEGER not null primary key,NAM INTEGER,TRAMCAPNUOCID INTEGER,KIEMDEMVIENID INTEGER,NGAYBATDAU DATE null,NGAYKETTHUC DATE null,MOTA VARCHAR(75) null,NGAYTAO DATE null,IDNGUOITAO INTEGER,NGAYXUATBAN DATE null,IDNGUOIXUATBAN INTEGER,NGAYDONG DATE null,IDNGUOIDONG INTEGER,lastsavepoint DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ME_KEHOACHKIEMDEMNUOC";
	public static final String ORDER_BY_JPQL = " ORDER BY keHoachKiemDemNuoc.tramCapNuocId ASC, keHoachKiemDemNuoc.kiemDemVienId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_KEHOACHKIEMDEMNUOC.TRAMCAPNUOCID ASC, ME_KEHOACHKIEMDEMNUOC.KIEMDEMVIENID ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc"));

	public KeHoachKiemDemNuocModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KeHoachKiemDemNuoc.class;
	}

	@Override
	public String getModelClassName() {
		return KeHoachKiemDemNuoc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("nam", getNam());
		attributes.put("tramCapNuocId", getTramCapNuocId());
		attributes.put("kiemDemVienId", getKiemDemVienId());
		attributes.put("ngayBatDau", getNgayBatDau());
		attributes.put("ngayKetThuc", getNgayKetThuc());
		attributes.put("moTa", getMoTa());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("ngayXuatBan", getNgayXuatBan());
		attributes.put("idNguoiXuatBan", getIdNguoiXuatBan());
		attributes.put("ngayDong", getNgayDong());
		attributes.put("idNguoiDong", getIdNguoiDong());
		attributes.put("lastSavePoint", getLastSavePoint());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Integer tramCapNuocId = (Integer)attributes.get("tramCapNuocId");

		if (tramCapNuocId != null) {
			setTramCapNuocId(tramCapNuocId);
		}

		Integer kiemDemVienId = (Integer)attributes.get("kiemDemVienId");

		if (kiemDemVienId != null) {
			setKiemDemVienId(kiemDemVienId);
		}

		Date ngayBatDau = (Date)attributes.get("ngayBatDau");

		if (ngayBatDau != null) {
			setNgayBatDau(ngayBatDau);
		}

		Date ngayKetThuc = (Date)attributes.get("ngayKetThuc");

		if (ngayKetThuc != null) {
			setNgayKetThuc(ngayKetThuc);
		}

		String moTa = (String)attributes.get("moTa");

		if (moTa != null) {
			setMoTa(moTa);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Integer idNguoiTao = (Integer)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		Date ngayXuatBan = (Date)attributes.get("ngayXuatBan");

		if (ngayXuatBan != null) {
			setNgayXuatBan(ngayXuatBan);
		}

		Integer idNguoiXuatBan = (Integer)attributes.get("idNguoiXuatBan");

		if (idNguoiXuatBan != null) {
			setIdNguoiXuatBan(idNguoiXuatBan);
		}

		Date ngayDong = (Date)attributes.get("ngayDong");

		if (ngayDong != null) {
			setNgayDong(ngayDong);
		}

		Integer idNguoiDong = (Integer)attributes.get("idNguoiDong");

		if (idNguoiDong != null) {
			setIdNguoiDong(idNguoiDong);
		}

		Date lastSavePoint = (Date)attributes.get("lastSavePoint");

		if (lastSavePoint != null) {
			setLastSavePoint(lastSavePoint);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_nam = nam;
	}

	@Override
	public int getTramCapNuocId() {
		return _tramCapNuocId;
	}

	@Override
	public void setTramCapNuocId(int tramCapNuocId) {
		_tramCapNuocId = tramCapNuocId;
	}

	@Override
	public int getKiemDemVienId() {
		return _kiemDemVienId;
	}

	@Override
	public void setKiemDemVienId(int kiemDemVienId) {
		_kiemDemVienId = kiemDemVienId;
	}

	@Override
	public Date getNgayBatDau() {
		return _ngayBatDau;
	}

	@Override
	public void setNgayBatDau(Date ngayBatDau) {
		_ngayBatDau = ngayBatDau;
	}

	@Override
	public Date getNgayKetThuc() {
		return _ngayKetThuc;
	}

	@Override
	public void setNgayKetThuc(Date ngayKetThuc) {
		_ngayKetThuc = ngayKetThuc;
	}

	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public int getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(int idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public Date getNgayXuatBan() {
		return _ngayXuatBan;
	}

	@Override
	public void setNgayXuatBan(Date ngayXuatBan) {
		_ngayXuatBan = ngayXuatBan;
	}

	@Override
	public int getIdNguoiXuatBan() {
		return _idNguoiXuatBan;
	}

	@Override
	public void setIdNguoiXuatBan(int idNguoiXuatBan) {
		_idNguoiXuatBan = idNguoiXuatBan;
	}

	@Override
	public Date getNgayDong() {
		return _ngayDong;
	}

	@Override
	public void setNgayDong(Date ngayDong) {
		_ngayDong = ngayDong;
	}

	@Override
	public int getIdNguoiDong() {
		return _idNguoiDong;
	}

	@Override
	public void setIdNguoiDong(int idNguoiDong) {
		_idNguoiDong = idNguoiDong;
	}

	@Override
	public Date getLastSavePoint() {
		return _lastSavePoint;
	}

	@Override
	public void setLastSavePoint(Date lastSavePoint) {
		_lastSavePoint = lastSavePoint;
	}

	@Override
	public KeHoachKiemDemNuoc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (KeHoachKiemDemNuoc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KeHoachKiemDemNuocImpl keHoachKiemDemNuocImpl = new KeHoachKiemDemNuocImpl();

		keHoachKiemDemNuocImpl.setId(getId());
		keHoachKiemDemNuocImpl.setNam(getNam());
		keHoachKiemDemNuocImpl.setTramCapNuocId(getTramCapNuocId());
		keHoachKiemDemNuocImpl.setKiemDemVienId(getKiemDemVienId());
		keHoachKiemDemNuocImpl.setNgayBatDau(getNgayBatDau());
		keHoachKiemDemNuocImpl.setNgayKetThuc(getNgayKetThuc());
		keHoachKiemDemNuocImpl.setMoTa(getMoTa());
		keHoachKiemDemNuocImpl.setNgayTao(getNgayTao());
		keHoachKiemDemNuocImpl.setIdNguoiTao(getIdNguoiTao());
		keHoachKiemDemNuocImpl.setNgayXuatBan(getNgayXuatBan());
		keHoachKiemDemNuocImpl.setIdNguoiXuatBan(getIdNguoiXuatBan());
		keHoachKiemDemNuocImpl.setNgayDong(getNgayDong());
		keHoachKiemDemNuocImpl.setIdNguoiDong(getIdNguoiDong());
		keHoachKiemDemNuocImpl.setLastSavePoint(getLastSavePoint());

		keHoachKiemDemNuocImpl.resetOriginalValues();

		return keHoachKiemDemNuocImpl;
	}

	@Override
	public int compareTo(KeHoachKiemDemNuoc keHoachKiemDemNuoc) {
		int value = 0;

		if (getTramCapNuocId() < keHoachKiemDemNuoc.getTramCapNuocId()) {
			value = -1;
		}
		else if (getTramCapNuocId() > keHoachKiemDemNuoc.getTramCapNuocId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getKiemDemVienId() < keHoachKiemDemNuoc.getKiemDemVienId()) {
			value = -1;
		}
		else if (getKiemDemVienId() > keHoachKiemDemNuoc.getKiemDemVienId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof KeHoachKiemDemNuoc)) {
			return false;
		}

		KeHoachKiemDemNuoc keHoachKiemDemNuoc = (KeHoachKiemDemNuoc)obj;

		int primaryKey = keHoachKiemDemNuoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<KeHoachKiemDemNuoc> toCacheModel() {
		KeHoachKiemDemNuocCacheModel keHoachKiemDemNuocCacheModel = new KeHoachKiemDemNuocCacheModel();

		keHoachKiemDemNuocCacheModel.id = getId();

		keHoachKiemDemNuocCacheModel.nam = getNam();

		keHoachKiemDemNuocCacheModel.tramCapNuocId = getTramCapNuocId();

		keHoachKiemDemNuocCacheModel.kiemDemVienId = getKiemDemVienId();

		Date ngayBatDau = getNgayBatDau();

		if (ngayBatDau != null) {
			keHoachKiemDemNuocCacheModel.ngayBatDau = ngayBatDau.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.ngayBatDau = Long.MIN_VALUE;
		}

		Date ngayKetThuc = getNgayKetThuc();

		if (ngayKetThuc != null) {
			keHoachKiemDemNuocCacheModel.ngayKetThuc = ngayKetThuc.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.ngayKetThuc = Long.MIN_VALUE;
		}

		keHoachKiemDemNuocCacheModel.moTa = getMoTa();

		String moTa = keHoachKiemDemNuocCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			keHoachKiemDemNuocCacheModel.moTa = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			keHoachKiemDemNuocCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.ngayTao = Long.MIN_VALUE;
		}

		keHoachKiemDemNuocCacheModel.idNguoiTao = getIdNguoiTao();

		Date ngayXuatBan = getNgayXuatBan();

		if (ngayXuatBan != null) {
			keHoachKiemDemNuocCacheModel.ngayXuatBan = ngayXuatBan.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.ngayXuatBan = Long.MIN_VALUE;
		}

		keHoachKiemDemNuocCacheModel.idNguoiXuatBan = getIdNguoiXuatBan();

		Date ngayDong = getNgayDong();

		if (ngayDong != null) {
			keHoachKiemDemNuocCacheModel.ngayDong = ngayDong.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.ngayDong = Long.MIN_VALUE;
		}

		keHoachKiemDemNuocCacheModel.idNguoiDong = getIdNguoiDong();

		Date lastSavePoint = getLastSavePoint();

		if (lastSavePoint != null) {
			keHoachKiemDemNuocCacheModel.lastSavePoint = lastSavePoint.getTime();
		}
		else {
			keHoachKiemDemNuocCacheModel.lastSavePoint = Long.MIN_VALUE;
		}

		return keHoachKiemDemNuocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", tramCapNuocId=");
		sb.append(getTramCapNuocId());
		sb.append(", kiemDemVienId=");
		sb.append(getKiemDemVienId());
		sb.append(", ngayBatDau=");
		sb.append(getNgayBatDau());
		sb.append(", ngayKetThuc=");
		sb.append(getNgayKetThuc());
		sb.append(", moTa=");
		sb.append(getMoTa());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", ngayXuatBan=");
		sb.append(getNgayXuatBan());
		sb.append(", idNguoiXuatBan=");
		sb.append(getIdNguoiXuatBan());
		sb.append(", ngayDong=");
		sb.append(getNgayDong());
		sb.append(", idNguoiDong=");
		sb.append(getIdNguoiDong());
		sb.append(", lastSavePoint=");
		sb.append(getLastSavePoint());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.tramcap.dao.model.KeHoachKiemDemNuoc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tramCapNuocId</column-name><column-value><![CDATA[");
		sb.append(getTramCapNuocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kiemDemVienId</column-name><column-value><![CDATA[");
		sb.append(getKiemDemVienId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBatDau</column-name><column-value><![CDATA[");
		sb.append(getNgayBatDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKetThuc</column-name><column-value><![CDATA[");
		sb.append(getNgayKetThuc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTa</column-name><column-value><![CDATA[");
		sb.append(getMoTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayXuatBan</column-name><column-value><![CDATA[");
		sb.append(getNgayXuatBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiXuatBan</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiXuatBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDong</column-name><column-value><![CDATA[");
		sb.append(getNgayDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiDong</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastSavePoint</column-name><column-value><![CDATA[");
		sb.append(getLastSavePoint());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = KeHoachKiemDemNuoc.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			KeHoachKiemDemNuoc.class
		};
	private int _id;
	private int _nam;
	private int _tramCapNuocId;
	private int _kiemDemVienId;
	private Date _ngayBatDau;
	private Date _ngayKetThuc;
	private String _moTa;
	private Date _ngayTao;
	private int _idNguoiTao;
	private Date _ngayXuatBan;
	private int _idNguoiXuatBan;
	private Date _ngayDong;
	private int _idNguoiDong;
	private Date _lastSavePoint;
	private KeHoachKiemDemNuoc _escapedModel;
}