/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.cmon.user.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserTramCap service. Represents a row in the &quot;ME_DIABANQLY_TRAMCAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.cmon.user.dao.model.impl.UserTramCapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.cmon.user.dao.model.impl.UserTramCapImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see UserTramCap
 * @see vn.dtt.cmon.user.dao.model.impl.UserTramCapImpl
 * @see vn.dtt.cmon.user.dao.model.impl.UserTramCapModelImpl
 * @generated
 */
public interface UserTramCapModel extends BaseModel<UserTramCap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user tram cap model instance should use the {@link UserTramCap} interface instead.
	 */

	/**
	 * Returns the primary key of this user tram cap.
	 *
	 * @return the primary key of this user tram cap
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user tram cap.
	 *
	 * @param primaryKey the primary key of this user tram cap
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this user tram cap.
	 *
	 * @return the ID of this user tram cap
	 */
	public long getId();

	/**
	 * Sets the ID of this user tram cap.
	 *
	 * @param id the ID of this user tram cap
	 */
	public void setId(long id);

	/**
	 * Returns the ma tinh of this user tram cap.
	 *
	 * @return the ma tinh of this user tram cap
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this user tram cap.
	 *
	 * @param maTinh the ma tinh of this user tram cap
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this user tram cap.
	 *
	 * @return the ma huyen of this user tram cap
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this user tram cap.
	 *
	 * @param maHuyen the ma huyen of this user tram cap
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this user tram cap.
	 *
	 * @return the ma xa of this user tram cap
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this user tram cap.
	 *
	 * @param maXa the ma xa of this user tram cap
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the name of this user tram cap.
	 *
	 * @return the name of this user tram cap
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user tram cap.
	 *
	 * @param name the name of this user tram cap
	 */
	public void setName(String name);

	/**
	 * Returns the ma tram cap of this user tram cap.
	 *
	 * @return the ma tram cap of this user tram cap
	 */
	public long getMaTramCap();

	/**
	 * Sets the ma tram cap of this user tram cap.
	 *
	 * @param maTramCap the ma tram cap of this user tram cap
	 */
	public void setMaTramCap(long maTramCap);

	/**
	 * Returns the user ID of this user tram cap.
	 *
	 * @return the user ID of this user tram cap
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user tram cap.
	 *
	 * @param userId the user ID of this user tram cap
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user tram cap.
	 *
	 * @return the user uuid of this user tram cap
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user tram cap.
	 *
	 * @param userUuid the user uuid of this user tram cap
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserTramCap userTramCap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserTramCap> toCacheModel();

	@Override
	public UserTramCap toEscapedModel();

	@Override
	public UserTramCap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}