/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TramCapNuoc service. Represents a row in the &quot;ME_TRAMCAPNUOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.tramcap.dao.model.impl.TramCapNuocModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.tramcap.dao.model.impl.TramCapNuocImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see TramCapNuoc
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.TramCapNuocImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.TramCapNuocModelImpl
 * @generated
 */
public interface TramCapNuocModel extends BaseModel<TramCapNuoc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tram cap nuoc model instance should use the {@link TramCapNuoc} interface instead.
	 */

	/**
	 * Returns the primary key of this tram cap nuoc.
	 *
	 * @return the primary key of this tram cap nuoc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tram cap nuoc.
	 *
	 * @param primaryKey the primary key of this tram cap nuoc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tram cap nuoc.
	 *
	 * @return the ID of this tram cap nuoc
	 */
	public long getId();

	/**
	 * Sets the ID of this tram cap nuoc.
	 *
	 * @param id the ID of this tram cap nuoc
	 */
	public void setId(long id);

	/**
	 * Returns the ma tram of this tram cap nuoc.
	 *
	 * @return the ma tram of this tram cap nuoc
	 */
	@AutoEscape
	public String getMaTram();

	/**
	 * Sets the ma tram of this tram cap nuoc.
	 *
	 * @param maTram the ma tram of this tram cap nuoc
	 */
	public void setMaTram(String maTram);

	/**
	 * Returns the ten tram of this tram cap nuoc.
	 *
	 * @return the ten tram of this tram cap nuoc
	 */
	@AutoEscape
	public String getTenTram();

	/**
	 * Sets the ten tram of this tram cap nuoc.
	 *
	 * @param tenTram the ten tram of this tram cap nuoc
	 */
	public void setTenTram(String tenTram);

	/**
	 * Returns the ma tinh of this tram cap nuoc.
	 *
	 * @return the ma tinh of this tram cap nuoc
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this tram cap nuoc.
	 *
	 * @param maTinh the ma tinh of this tram cap nuoc
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ten tinh of this tram cap nuoc.
	 *
	 * @return the ten tinh of this tram cap nuoc
	 */
	@AutoEscape
	public String getTenTinh();

	/**
	 * Sets the ten tinh of this tram cap nuoc.
	 *
	 * @param tenTinh the ten tinh of this tram cap nuoc
	 */
	public void setTenTinh(String tenTinh);

	/**
	 * Returns the ma huyen of this tram cap nuoc.
	 *
	 * @return the ma huyen of this tram cap nuoc
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this tram cap nuoc.
	 *
	 * @param maHuyen the ma huyen of this tram cap nuoc
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ten huyen of this tram cap nuoc.
	 *
	 * @return the ten huyen of this tram cap nuoc
	 */
	@AutoEscape
	public String getTenHuyen();

	/**
	 * Sets the ten huyen of this tram cap nuoc.
	 *
	 * @param tenHuyen the ten huyen of this tram cap nuoc
	 */
	public void setTenHuyen(String tenHuyen);

	/**
	 * Returns the ma xa of this tram cap nuoc.
	 *
	 * @return the ma xa of this tram cap nuoc
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this tram cap nuoc.
	 *
	 * @param maXa the ma xa of this tram cap nuoc
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the ten xa of this tram cap nuoc.
	 *
	 * @return the ten xa of this tram cap nuoc
	 */
	@AutoEscape
	public String getTenXa();

	/**
	 * Sets the ten xa of this tram cap nuoc.
	 *
	 * @param tenXa the ten xa of this tram cap nuoc
	 */
	public void setTenXa(String tenXa);

	/**
	 * Returns the dia chi of this tram cap nuoc.
	 *
	 * @return the dia chi of this tram cap nuoc
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this tram cap nuoc.
	 *
	 * @param diaChi the dia chi of this tram cap nuoc
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the kinh do of this tram cap nuoc.
	 *
	 * @return the kinh do of this tram cap nuoc
	 */
	@AutoEscape
	public String getKinhDo();

	/**
	 * Sets the kinh do of this tram cap nuoc.
	 *
	 * @param kinhDo the kinh do of this tram cap nuoc
	 */
	public void setKinhDo(String kinhDo);

	/**
	 * Returns the vi do of this tram cap nuoc.
	 *
	 * @return the vi do of this tram cap nuoc
	 */
	@AutoEscape
	public String getViDo();

	/**
	 * Sets the vi do of this tram cap nuoc.
	 *
	 * @param viDo the vi do of this tram cap nuoc
	 */
	public void setViDo(String viDo);

	/**
	 * Returns the loai hinh of this tram cap nuoc.
	 *
	 * @return the loai hinh of this tram cap nuoc
	 */
	public int getLoaiHinh();

	/**
	 * Sets the loai hinh of this tram cap nuoc.
	 *
	 * @param loaiHinh the loai hinh of this tram cap nuoc
	 */
	public void setLoaiHinh(int loaiHinh);

	/**
	 * Returns the ma mo hinh of this tram cap nuoc.
	 *
	 * @return the ma mo hinh of this tram cap nuoc
	 */
	@AutoEscape
	public String getMaMoHinh();

	/**
	 * Sets the ma mo hinh of this tram cap nuoc.
	 *
	 * @param maMoHinh the ma mo hinh of this tram cap nuoc
	 */
	public void setMaMoHinh(String maMoHinh);

	/**
	 * Returns the ten mo hinh of this tram cap nuoc.
	 *
	 * @return the ten mo hinh of this tram cap nuoc
	 */
	@AutoEscape
	public String getTenMoHinh();

	/**
	 * Sets the ten mo hinh of this tram cap nuoc.
	 *
	 * @param tenMoHinh the ten mo hinh of this tram cap nuoc
	 */
	public void setTenMoHinh(String tenMoHinh);

	/**
	 * Returns the cong xuat thiet ke of this tram cap nuoc.
	 *
	 * @return the cong xuat thiet ke of this tram cap nuoc
	 */
	public int getCongXuatThietKe();

	/**
	 * Sets the cong xuat thiet ke of this tram cap nuoc.
	 *
	 * @param congXuatThietKe the cong xuat thiet ke of this tram cap nuoc
	 */
	public void setCongXuatThietKe(int congXuatThietKe);

	/**
	 * Returns the tong dau noi thiet ke of this tram cap nuoc.
	 *
	 * @return the tong dau noi thiet ke of this tram cap nuoc
	 */
	public int getTongDauNoiThietKe();

	/**
	 * Sets the tong dau noi thiet ke of this tram cap nuoc.
	 *
	 * @param tongDauNoiThietKe the tong dau noi thiet ke of this tram cap nuoc
	 */
	public void setTongDauNoiThietKe(int tongDauNoiThietKe);

	/**
	 * Returns the so nguoi cap thiet ke of this tram cap nuoc.
	 *
	 * @return the so nguoi cap thiet ke of this tram cap nuoc
	 */
	public int getSoNguoiCapThietKe();

	/**
	 * Sets the so nguoi cap thiet ke of this tram cap nuoc.
	 *
	 * @param soNguoiCapThietKe the so nguoi cap thiet ke of this tram cap nuoc
	 */
	public void setSoNguoiCapThietKe(int soNguoiCapThietKe);

	/**
	 * Returns the tinh trang du an of this tram cap nuoc.
	 *
	 * @return the tinh trang du an of this tram cap nuoc
	 */
	public int getTinhTrangDuAn();

	/**
	 * Sets the tinh trang du an of this tram cap nuoc.
	 *
	 * @param tinhTrangDuAn the tinh trang du an of this tram cap nuoc
	 */
	public void setTinhTrangDuAn(int tinhTrangDuAn);

	/**
	 * Returns the tien do xay dung of this tram cap nuoc.
	 *
	 * @return the tien do xay dung of this tram cap nuoc
	 */
	public int getTienDoXayDung();

	/**
	 * Sets the tien do xay dung of this tram cap nuoc.
	 *
	 * @param tienDoXayDung the tien do xay dung of this tram cap nuoc
	 */
	public void setTienDoXayDung(int tienDoXayDung);

	/**
	 * Returns the nam xay dung of this tram cap nuoc.
	 *
	 * @return the nam xay dung of this tram cap nuoc
	 */
	public int getNamXayDung();

	/**
	 * Sets the nam xay dung of this tram cap nuoc.
	 *
	 * @param namXayDung the nam xay dung of this tram cap nuoc
	 */
	public void setNamXayDung(int namXayDung);

	/**
	 * Returns the nam hoan thanh of this tram cap nuoc.
	 *
	 * @return the nam hoan thanh of this tram cap nuoc
	 */
	public int getNamHoanThanh();

	/**
	 * Sets the nam hoan thanh of this tram cap nuoc.
	 *
	 * @param namHoanThanh the nam hoan thanh of this tram cap nuoc
	 */
	public void setNamHoanThanh(int namHoanThanh);

	/**
	 * Returns the ngay van hanh of this tram cap nuoc.
	 *
	 * @return the ngay van hanh of this tram cap nuoc
	 */
	public Date getNgayVanHanh();

	/**
	 * Sets the ngay van hanh of this tram cap nuoc.
	 *
	 * @param ngayVanHanh the ngay van hanh of this tram cap nuoc
	 */
	public void setNgayVanHanh(Date ngayVanHanh);

	/**
	 * Returns the bo may van hanh of this tram cap nuoc.
	 *
	 * @return the bo may van hanh of this tram cap nuoc
	 */
	public int getBoMayVanHanh();

	/**
	 * Sets the bo may van hanh of this tram cap nuoc.
	 *
	 * @param boMayVanHanh the bo may van hanh of this tram cap nuoc
	 */
	public void setBoMayVanHanh(int boMayVanHanh);

	/**
	 * Returns the ghi chu of this tram cap nuoc.
	 *
	 * @return the ghi chu of this tram cap nuoc
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this tram cap nuoc.
	 *
	 * @param ghiChu the ghi chu of this tram cap nuoc
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the ngay tao of this tram cap nuoc.
	 *
	 * @return the ngay tao of this tram cap nuoc
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this tram cap nuoc.
	 *
	 * @param ngayTao the ngay tao of this tram cap nuoc
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this tram cap nuoc.
	 *
	 * @return the id nguoi tao of this tram cap nuoc
	 */
	public long getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this tram cap nuoc.
	 *
	 * @param idNguoiTao the id nguoi tao of this tram cap nuoc
	 */
	public void setIdNguoiTao(long idNguoiTao);

	/**
	 * Returns the id nguoi danh gia of this tram cap nuoc.
	 *
	 * @return the id nguoi danh gia of this tram cap nuoc
	 */
	public long getIdNguoiDanhGia();

	/**
	 * Sets the id nguoi danh gia of this tram cap nuoc.
	 *
	 * @param idNguoiDanhGia the id nguoi danh gia of this tram cap nuoc
	 */
	public void setIdNguoiDanhGia(long idNguoiDanhGia);

	/**
	 * Returns the ngay danh gia of this tram cap nuoc.
	 *
	 * @return the ngay danh gia of this tram cap nuoc
	 */
	public Date getNgayDanhGia();

	/**
	 * Sets the ngay danh gia of this tram cap nuoc.
	 *
	 * @param ngayDanhGia the ngay danh gia of this tram cap nuoc
	 */
	public void setNgayDanhGia(Date ngayDanhGia);

	/**
	 * Returns the trang thai cap nuoc of this tram cap nuoc.
	 *
	 * @return the trang thai cap nuoc of this tram cap nuoc
	 */
	public int getTrangThaiCapNuoc();

	/**
	 * Sets the trang thai cap nuoc of this tram cap nuoc.
	 *
	 * @param trangThaiCapNuoc the trang thai cap nuoc of this tram cap nuoc
	 */
	public void setTrangThaiCapNuoc(int trangThaiCapNuoc);

	/**
	 * Returns the cong xuat thuc te of this tram cap nuoc.
	 *
	 * @return the cong xuat thuc te of this tram cap nuoc
	 */
	public int getCongXuatThucTe();

	/**
	 * Sets the cong xuat thuc te of this tram cap nuoc.
	 *
	 * @param congXuatThucTe the cong xuat thuc te of this tram cap nuoc
	 */
	public void setCongXuatThucTe(int congXuatThucTe);

	/**
	 * Returns the tong dau noi thuc te of this tram cap nuoc.
	 *
	 * @return the tong dau noi thuc te of this tram cap nuoc
	 */
	public int getTongDauNoiThucTe();

	/**
	 * Sets the tong dau noi thuc te of this tram cap nuoc.
	 *
	 * @param tongDauNoiThucTe the tong dau noi thuc te of this tram cap nuoc
	 */
	public void setTongDauNoiThucTe(int tongDauNoiThucTe);

	/**
	 * Returns the so nguoi cap thuc te of this tram cap nuoc.
	 *
	 * @return the so nguoi cap thuc te of this tram cap nuoc
	 */
	public int getSoNguoiCapThucTe();

	/**
	 * Sets the so nguoi cap thuc te of this tram cap nuoc.
	 *
	 * @param soNguoiCapThucTe the so nguoi cap thuc te of this tram cap nuoc
	 */
	public void setSoNguoiCapThucTe(int soNguoiCapThucTe);

	/**
	 * Returns the tong chi phi of this tram cap nuoc.
	 *
	 * @return the tong chi phi of this tram cap nuoc
	 */
	public int getTongChiPhi();

	/**
	 * Sets the tong chi phi of this tram cap nuoc.
	 *
	 * @param tongChiPhi the tong chi phi of this tram cap nuoc
	 */
	public void setTongChiPhi(int tongChiPhi);

	/**
	 * Returns the tong doanh thu of this tram cap nuoc.
	 *
	 * @return the tong doanh thu of this tram cap nuoc
	 */
	public int getTongDoanhThu();

	/**
	 * Sets the tong doanh thu of this tram cap nuoc.
	 *
	 * @param tongDoanhThu the tong doanh thu of this tram cap nuoc
	 */
	public void setTongDoanhThu(int tongDoanhThu);

	/**
	 * Returns the nuoc dat tieu chuan of this tram cap nuoc.
	 *
	 * @return the nuoc dat tieu chuan of this tram cap nuoc
	 */
	public int getNuocDatTieuChuan();

	/**
	 * Sets the nuoc dat tieu chuan of this tram cap nuoc.
	 *
	 * @param nuocDatTieuChuan the nuoc dat tieu chuan of this tram cap nuoc
	 */
	public void setNuocDatTieuChuan(int nuocDatTieuChuan);

	/**
	 * Returns the nuoc co asen of this tram cap nuoc.
	 *
	 * @return the nuoc co asen of this tram cap nuoc
	 */
	public int getNuocCoAsen();

	/**
	 * Sets the nuoc co asen of this tram cap nuoc.
	 *
	 * @param nuocCoAsen the nuoc co asen of this tram cap nuoc
	 */
	public void setNuocCoAsen(int nuocCoAsen);

	/**
	 * Returns the nuoc that thoat of this tram cap nuoc.
	 *
	 * @return the nuoc that thoat of this tram cap nuoc
	 */
	public int getNuocThatThoat();

	/**
	 * Sets the nuoc that thoat of this tram cap nuoc.
	 *
	 * @param nuocThatThoat the nuoc that thoat of this tram cap nuoc
	 */
	public void setNuocThatThoat(int nuocThatThoat);

	/**
	 * Returns the trang thai danh gia of this tram cap nuoc.
	 *
	 * @return the trang thai danh gia of this tram cap nuoc
	 */
	public int getTrangThaiDanhGia();

	/**
	 * Sets the trang thai danh gia of this tram cap nuoc.
	 *
	 * @param trangThaiDanhGia the trang thai danh gia of this tram cap nuoc
	 */
	public void setTrangThaiDanhGia(int trangThaiDanhGia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TramCapNuoc tramCapNuoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TramCapNuoc> toCacheModel();

	@Override
	public TramCapNuoc toEscapedModel();

	@Override
	public TramCapNuoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}