/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the keHoachVeSinhXaNew service. Represents a row in the &quot;ME_KEHOACHVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.keHoachVeSinhXaNewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.keHoachVeSinhXaNewImpl}.
 * </p>
 *
 * @author BinhTH
 * @see keHoachVeSinhXaNew
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.keHoachVeSinhXaNewImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.keHoachVeSinhXaNewModelImpl
 * @generated
 */
public interface keHoachVeSinhXaNewModel extends BaseModel<keHoachVeSinhXaNew> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ke hoach ve sinh xa new model instance should use the {@link keHoachVeSinhXaNew} interface instead.
	 */

	/**
	 * Returns the primary key of this ke hoach ve sinh xa new.
	 *
	 * @return the primary key of this ke hoach ve sinh xa new
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ke hoach ve sinh xa new.
	 *
	 * @param primaryKey the primary key of this ke hoach ve sinh xa new
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ke hoach ve sinh xa new.
	 *
	 * @return the ID of this ke hoach ve sinh xa new
	 */
	public int getId();

	/**
	 * Sets the ID of this ke hoach ve sinh xa new.
	 *
	 * @param id the ID of this ke hoach ve sinh xa new
	 */
	public void setId(int id);

	/**
	 * Returns the ma tinh of this ke hoach ve sinh xa new.
	 *
	 * @return the ma tinh of this ke hoach ve sinh xa new
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this ke hoach ve sinh xa new.
	 *
	 * @param maTinh the ma tinh of this ke hoach ve sinh xa new
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this ke hoach ve sinh xa new.
	 *
	 * @return the ma huyen of this ke hoach ve sinh xa new
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this ke hoach ve sinh xa new.
	 *
	 * @param maHuyen the ma huyen of this ke hoach ve sinh xa new
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this ke hoach ve sinh xa new.
	 *
	 * @return the ma xa of this ke hoach ve sinh xa new
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this ke hoach ve sinh xa new.
	 *
	 * @param maXa the ma xa of this ke hoach ve sinh xa new
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the nam of this ke hoach ve sinh xa new.
	 *
	 * @return the nam of this ke hoach ve sinh xa new
	 */
	public int getNam();

	/**
	 * Sets the nam of this ke hoach ve sinh xa new.
	 *
	 * @param nam the nam of this ke hoach ve sinh xa new
	 */
	public void setNam(int nam);

	/**
	 * Returns the so nha tieu h v s moi of this ke hoach ve sinh xa new.
	 *
	 * @return the so nha tieu h v s moi of this ke hoach ve sinh xa new
	 */
	public int getSoNhaTieuHVSMoi();

	/**
	 * Sets the so nha tieu h v s moi of this ke hoach ve sinh xa new.
	 *
	 * @param soNhaTieuHVSMoi the so nha tieu h v s moi of this ke hoach ve sinh xa new
	 */
	public void setSoNhaTieuHVSMoi(int soNhaTieuHVSMoi);

	/**
	 * Returns the so dan of this ke hoach ve sinh xa new.
	 *
	 * @return the so dan of this ke hoach ve sinh xa new
	 */
	public int getSoDan();

	/**
	 * Sets the so dan of this ke hoach ve sinh xa new.
	 *
	 * @param soDan the so dan of this ke hoach ve sinh xa new
	 */
	public void setSoDan(int soDan);

	/**
	 * Returns the dang ky v s t x of this ke hoach ve sinh xa new.
	 *
	 * @return the dang ky v s t x of this ke hoach ve sinh xa new
	 */
	public int getDangKyVSTX();

	/**
	 * Sets the dang ky v s t x of this ke hoach ve sinh xa new.
	 *
	 * @param dangKyVSTX the dang ky v s t x of this ke hoach ve sinh xa new
	 */
	public void setDangKyVSTX(int dangKyVSTX);

	/**
	 * Returns the ghi chu of this ke hoach ve sinh xa new.
	 *
	 * @return the ghi chu of this ke hoach ve sinh xa new
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this ke hoach ve sinh xa new.
	 *
	 * @param ghiChu the ghi chu of this ke hoach ve sinh xa new
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the bao cao d l i of this ke hoach ve sinh xa new.
	 *
	 * @return the bao cao d l i of this ke hoach ve sinh xa new
	 */
	public int getBaoCaoDLI();

	/**
	 * Sets the bao cao d l i of this ke hoach ve sinh xa new.
	 *
	 * @param baoCaoDLI the bao cao d l i of this ke hoach ve sinh xa new
	 */
	public void setBaoCaoDLI(int baoCaoDLI);

	/**
	 * Returns the ngay tao of this ke hoach ve sinh xa new.
	 *
	 * @return the ngay tao of this ke hoach ve sinh xa new
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ke hoach ve sinh xa new.
	 *
	 * @param ngayTao the ngay tao of this ke hoach ve sinh xa new
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this ke hoach ve sinh xa new.
	 *
	 * @return the id nguoi tao of this ke hoach ve sinh xa new
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this ke hoach ve sinh xa new.
	 *
	 * @param idNguoiTao the id nguoi tao of this ke hoach ve sinh xa new
	 */
	public void setIdNguoiTao(int idNguoiTao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(keHoachVeSinhXaNew keHoachVeSinhXaNew);

	@Override
	public int hashCode();

	@Override
	public CacheModel<keHoachVeSinhXaNew> toCacheModel();

	@Override
	public keHoachVeSinhXaNew toEscapedModel();

	@Override
	public keHoachVeSinhXaNew toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}