/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.kehoachvesinh.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KeHoachVeSinh service. Represents a row in the &quot;ME_KEHOACHVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.kehoachvesinh.dao.model.impl.KeHoachVeSinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.kehoachvesinh.dao.model.impl.KeHoachVeSinhImpl}.
 * </p>
 *
 * @author HANT
 * @see KeHoachVeSinh
 * @see vn.dtt.sol.ns.kehoachvesinh.dao.model.impl.KeHoachVeSinhImpl
 * @see vn.dtt.sol.ns.kehoachvesinh.dao.model.impl.KeHoachVeSinhModelImpl
 * @generated
 */
public interface KeHoachVeSinhModel extends BaseModel<KeHoachVeSinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ke hoach ve sinh model instance should use the {@link KeHoachVeSinh} interface instead.
	 */

	/**
	 * Returns the primary key of this ke hoach ve sinh.
	 *
	 * @return the primary key of this ke hoach ve sinh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ke hoach ve sinh.
	 *
	 * @param primaryKey the primary key of this ke hoach ve sinh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ke hoach ve sinh.
	 *
	 * @return the ID of this ke hoach ve sinh
	 */
	public long getId();

	/**
	 * Sets the ID of this ke hoach ve sinh.
	 *
	 * @param id the ID of this ke hoach ve sinh
	 */
	public void setId(long id);

	/**
	 * Returns the ma tinh of this ke hoach ve sinh.
	 *
	 * @return the ma tinh of this ke hoach ve sinh
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this ke hoach ve sinh.
	 *
	 * @param maTinh the ma tinh of this ke hoach ve sinh
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this ke hoach ve sinh.
	 *
	 * @return the ma huyen of this ke hoach ve sinh
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this ke hoach ve sinh.
	 *
	 * @param maHuyen the ma huyen of this ke hoach ve sinh
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this ke hoach ve sinh.
	 *
	 * @return the ma xa of this ke hoach ve sinh
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this ke hoach ve sinh.
	 *
	 * @param maXa the ma xa of this ke hoach ve sinh
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the nam of this ke hoach ve sinh.
	 *
	 * @return the nam of this ke hoach ve sinh
	 */
	public long getNam();

	/**
	 * Sets the nam of this ke hoach ve sinh.
	 *
	 * @param nam the nam of this ke hoach ve sinh
	 */
	public void setNam(long nam);

	/**
	 * Returns the so nha tieu h v s moi of this ke hoach ve sinh.
	 *
	 * @return the so nha tieu h v s moi of this ke hoach ve sinh
	 */
	public long getSoNhaTieuHVSMoi();

	/**
	 * Sets the so nha tieu h v s moi of this ke hoach ve sinh.
	 *
	 * @param soNhaTieuHVSMoi the so nha tieu h v s moi of this ke hoach ve sinh
	 */
	public void setSoNhaTieuHVSMoi(long soNhaTieuHVSMoi);

	/**
	 * Returns the so dan of this ke hoach ve sinh.
	 *
	 * @return the so dan of this ke hoach ve sinh
	 */
	public long getSoDan();

	/**
	 * Sets the so dan of this ke hoach ve sinh.
	 *
	 * @param soDan the so dan of this ke hoach ve sinh
	 */
	public void setSoDan(long soDan);

	/**
	 * Returns the dang ky v s t x of this ke hoach ve sinh.
	 *
	 * @return the dang ky v s t x of this ke hoach ve sinh
	 */
	public long getDangKyVSTX();

	/**
	 * Sets the dang ky v s t x of this ke hoach ve sinh.
	 *
	 * @param dangKyVSTX the dang ky v s t x of this ke hoach ve sinh
	 */
	public void setDangKyVSTX(long dangKyVSTX);

	/**
	 * Returns the ghi chu of this ke hoach ve sinh.
	 *
	 * @return the ghi chu of this ke hoach ve sinh
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this ke hoach ve sinh.
	 *
	 * @param ghiChu the ghi chu of this ke hoach ve sinh
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the bao cao d l i of this ke hoach ve sinh.
	 *
	 * @return the bao cao d l i of this ke hoach ve sinh
	 */
	public long getBaoCaoDLI();

	/**
	 * Sets the bao cao d l i of this ke hoach ve sinh.
	 *
	 * @param baoCaoDLI the bao cao d l i of this ke hoach ve sinh
	 */
	public void setBaoCaoDLI(long baoCaoDLI);

	/**
	 * Returns the ngay tao of this ke hoach ve sinh.
	 *
	 * @return the ngay tao of this ke hoach ve sinh
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ke hoach ve sinh.
	 *
	 * @param ngayTao the ngay tao of this ke hoach ve sinh
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this ke hoach ve sinh.
	 *
	 * @return the id nguoi tao of this ke hoach ve sinh
	 */
	public long getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this ke hoach ve sinh.
	 *
	 * @param idNguoiTao the id nguoi tao of this ke hoach ve sinh
	 */
	public void setIdNguoiTao(long idNguoiTao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KeHoachVeSinh keHoachVeSinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KeHoachVeSinh> toCacheModel();

	@Override
	public KeHoachVeSinh toEscapedModel();

	@Override
	public KeHoachVeSinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}