/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ChiTietKiemDemCongTrinh service. Represents a row in the &quot;ME_CHITIETKIEMDEMCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ChiTietKiemDemCongTrinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ChiTietKiemDemCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ChiTietKiemDemCongTrinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ChiTietKiemDemCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ChiTietKiemDemCongTrinhModelImpl
 * @generated
 */
public interface ChiTietKiemDemCongTrinhModel extends BaseModel<ChiTietKiemDemCongTrinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chi tiet kiem dem cong trinh model instance should use the {@link ChiTietKiemDemCongTrinh} interface instead.
	 */

	/**
	 * Returns the primary key of this chi tiet kiem dem cong trinh.
	 *
	 * @return the primary key of this chi tiet kiem dem cong trinh
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this chi tiet kiem dem cong trinh.
	 *
	 * @param primaryKey the primary key of this chi tiet kiem dem cong trinh
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this chi tiet kiem dem cong trinh.
	 *
	 * @return the ID of this chi tiet kiem dem cong trinh
	 */
	public int getId();

	/**
	 * Sets the ID of this chi tiet kiem dem cong trinh.
	 *
	 * @param id the ID of this chi tiet kiem dem cong trinh
	 */
	public void setId(int id);

	/**
	 * Returns the thong tin kiem dem cong trinh ID of this chi tiet kiem dem cong trinh.
	 *
	 * @return the thong tin kiem dem cong trinh ID of this chi tiet kiem dem cong trinh
	 */
	public int getThongTinKiemDemCongTrinhId();

	/**
	 * Sets the thong tin kiem dem cong trinh ID of this chi tiet kiem dem cong trinh.
	 *
	 * @param thongTinKiemDemCongTrinhId the thong tin kiem dem cong trinh ID of this chi tiet kiem dem cong trinh
	 */
	public void setThongTinKiemDemCongTrinhId(int thongTinKiemDemCongTrinhId);

	/**
	 * Returns the so ho tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @return the so ho tieu of this chi tiet kiem dem cong trinh
	 */
	public int getSoHoTieu();

	/**
	 * Sets the so ho tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @param soHoTieu the so ho tieu of this chi tiet kiem dem cong trinh
	 */
	public void setSoHoTieu(int soHoTieu);

	/**
	 * Returns the loai nha tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @return the loai nha tieu of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getLoaiNhaTieu();

	/**
	 * Sets the loai nha tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @param loaiNhaTieu the loai nha tieu of this chi tiet kiem dem cong trinh
	 */
	public void setLoaiNhaTieu(String loaiNhaTieu);

	/**
	 * Returns the anh toan canh of this chi tiet kiem dem cong trinh.
	 *
	 * @return the anh toan canh of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getAnhToanCanh();

	/**
	 * Sets the anh toan canh of this chi tiet kiem dem cong trinh.
	 *
	 * @param anhToanCanh the anh toan canh of this chi tiet kiem dem cong trinh
	 */
	public void setAnhToanCanh(String anhToanCanh);

	/**
	 * Returns the anh trong nha tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @return the anh trong nha tieu of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getAnhTrongNhaTieu();

	/**
	 * Sets the anh trong nha tieu of this chi tiet kiem dem cong trinh.
	 *
	 * @param anhTrongNhaTieu the anh trong nha tieu of this chi tiet kiem dem cong trinh
	 */
	public void setAnhTrongNhaTieu(String anhTrongNhaTieu);

	/**
	 * Returns the ve sinh sach se of this chi tiet kiem dem cong trinh.
	 *
	 * @return the ve sinh sach se of this chi tiet kiem dem cong trinh
	 */
	public int getVeSinhSachSe();

	/**
	 * Sets the ve sinh sach se of this chi tiet kiem dem cong trinh.
	 *
	 * @param veSinhSachSe the ve sinh sach se of this chi tiet kiem dem cong trinh
	 */
	public void setVeSinhSachSe(int veSinhSachSe);

	/**
	 * Returns the de lam ve sinh of this chi tiet kiem dem cong trinh.
	 *
	 * @return the de lam ve sinh of this chi tiet kiem dem cong trinh
	 */
	public int getDeLamVeSinh();

	/**
	 * Sets the de lam ve sinh of this chi tiet kiem dem cong trinh.
	 *
	 * @param deLamVeSinh the de lam ve sinh of this chi tiet kiem dem cong trinh
	 */
	public void setDeLamVeSinh(int deLamVeSinh);

	/**
	 * Returns the mui ve sinh of this chi tiet kiem dem cong trinh.
	 *
	 * @return the mui ve sinh of this chi tiet kiem dem cong trinh
	 */
	public int getMuiVeSinh();

	/**
	 * Sets the mui ve sinh of this chi tiet kiem dem cong trinh.
	 *
	 * @param muiVeSinh the mui ve sinh of this chi tiet kiem dem cong trinh
	 */
	public void setMuiVeSinh(int muiVeSinh);

	/**
	 * Returns the phia tren kin dao of this chi tiet kiem dem cong trinh.
	 *
	 * @return the phia tren kin dao of this chi tiet kiem dem cong trinh
	 */
	public int getPhiaTrenKinDao();

	/**
	 * Sets the phia tren kin dao of this chi tiet kiem dem cong trinh.
	 *
	 * @param phiaTrenKinDao the phia tren kin dao of this chi tiet kiem dem cong trinh
	 */
	public void setPhiaTrenKinDao(int phiaTrenKinDao);

	/**
	 * Returns the du che mua gio of this chi tiet kiem dem cong trinh.
	 *
	 * @return the du che mua gio of this chi tiet kiem dem cong trinh
	 */
	public int getDuCheMuaGio();

	/**
	 * Sets the du che mua gio of this chi tiet kiem dem cong trinh.
	 *
	 * @param duCheMuaGio the du che mua gio of this chi tiet kiem dem cong trinh
	 */
	public void setDuCheMuaGio(int duCheMuaGio);

	/**
	 * Returns the san cao tren toi thieu of this chi tiet kiem dem cong trinh.
	 *
	 * @return the san cao tren toi thieu of this chi tiet kiem dem cong trinh
	 */
	public int getSanCaoTrenToiThieu();

	/**
	 * Sets the san cao tren toi thieu of this chi tiet kiem dem cong trinh.
	 *
	 * @param sanCaoTrenToiThieu the san cao tren toi thieu of this chi tiet kiem dem cong trinh
	 */
	public void setSanCaoTrenToiThieu(int sanCaoTrenToiThieu);

	/**
	 * Returns the co cong trinh rua tay of this chi tiet kiem dem cong trinh.
	 *
	 * @return the co cong trinh rua tay of this chi tiet kiem dem cong trinh
	 */
	public int getCoCongTrinhRuaTay();

	/**
	 * Sets the co cong trinh rua tay of this chi tiet kiem dem cong trinh.
	 *
	 * @param coCongTrinhRuaTay the co cong trinh rua tay of this chi tiet kiem dem cong trinh
	 */
	public void setCoCongTrinhRuaTay(int coCongTrinhRuaTay);

	/**
	 * Returns the chi tiet cong trinh rua tay of this chi tiet kiem dem cong trinh.
	 *
	 * @return the chi tiet cong trinh rua tay of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getChiTietCongTrinhRuaTay();

	/**
	 * Sets the chi tiet cong trinh rua tay of this chi tiet kiem dem cong trinh.
	 *
	 * @param chiTietCongTrinhRuaTay the chi tiet cong trinh rua tay of this chi tiet kiem dem cong trinh
	 */
	public void setChiTietCongTrinhRuaTay(String chiTietCongTrinhRuaTay);

	/**
	 * Returns the anh be chua of this chi tiet kiem dem cong trinh.
	 *
	 * @return the anh be chua of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getAnhBeChua();

	/**
	 * Sets the anh be chua of this chi tiet kiem dem cong trinh.
	 *
	 * @param anhBeChua the anh be chua of this chi tiet kiem dem cong trinh
	 */
	public void setAnhBeChua(String anhBeChua);

	/**
	 * Returns the nap be con tot of this chi tiet kiem dem cong trinh.
	 *
	 * @return the nap be con tot of this chi tiet kiem dem cong trinh
	 */
	public int getNapBeConTot();

	/**
	 * Sets the nap be con tot of this chi tiet kiem dem cong trinh.
	 *
	 * @param napBeConTot the nap be con tot of this chi tiet kiem dem cong trinh
	 */
	public void setNapBeConTot(int napBeConTot);

	/**
	 * Returns the cua phan bit kin of this chi tiet kiem dem cong trinh.
	 *
	 * @return the cua phan bit kin of this chi tiet kiem dem cong trinh
	 */
	public int getCuaPhanBitKin();

	/**
	 * Sets the cua phan bit kin of this chi tiet kiem dem cong trinh.
	 *
	 * @param cuaPhanBitKin the cua phan bit kin of this chi tiet kiem dem cong trinh
	 */
	public void setCuaPhanBitKin(int cuaPhanBitKin);

	/**
	 * Returns the tran ra ngoai of this chi tiet kiem dem cong trinh.
	 *
	 * @return the tran ra ngoai of this chi tiet kiem dem cong trinh
	 */
	public int getTranRaNgoai();

	/**
	 * Sets the tran ra ngoai of this chi tiet kiem dem cong trinh.
	 *
	 * @param tranRaNgoai the tran ra ngoai of this chi tiet kiem dem cong trinh
	 */
	public void setTranRaNgoai(int tranRaNgoai);

	/**
	 * Returns the nuoc thai di dau of this chi tiet kiem dem cong trinh.
	 *
	 * @return the nuoc thai di dau of this chi tiet kiem dem cong trinh
	 */
	public int getNuocThaiDiDau();

	/**
	 * Sets the nuoc thai di dau of this chi tiet kiem dem cong trinh.
	 *
	 * @param nuocThaiDiDau the nuoc thai di dau of this chi tiet kiem dem cong trinh
	 */
	public void setNuocThaiDiDau(int nuocThaiDiDau);

	/**
	 * Returns the khoang cach nguon nuoc of this chi tiet kiem dem cong trinh.
	 *
	 * @return the khoang cach nguon nuoc of this chi tiet kiem dem cong trinh
	 */
	public int getKhoangCachNguonNuoc();

	/**
	 * Sets the khoang cach nguon nuoc of this chi tiet kiem dem cong trinh.
	 *
	 * @param khoangCachNguonNuoc the khoang cach nguon nuoc of this chi tiet kiem dem cong trinh
	 */
	public void setKhoangCachNguonNuoc(int khoangCachNguonNuoc);

	/**
	 * Returns the ngap khi mua lon of this chi tiet kiem dem cong trinh.
	 *
	 * @return the ngap khi mua lon of this chi tiet kiem dem cong trinh
	 */
	public int getNgapKhiMuaLon();

	/**
	 * Sets the ngap khi mua lon of this chi tiet kiem dem cong trinh.
	 *
	 * @param ngapKhiMuaLon the ngap khi mua lon of this chi tiet kiem dem cong trinh
	 */
	public void setNgapKhiMuaLon(int ngapKhiMuaLon);

	/**
	 * Returns the ten cong trinh of this chi tiet kiem dem cong trinh.
	 *
	 * @return the ten cong trinh of this chi tiet kiem dem cong trinh
	 */
	@AutoEscape
	public String getTenCongTrinh();

	/**
	 * Sets the ten cong trinh of this chi tiet kiem dem cong trinh.
	 *
	 * @param tenCongTrinh the ten cong trinh of this chi tiet kiem dem cong trinh
	 */
	public void setTenCongTrinh(String tenCongTrinh);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ChiTietKiemDemCongTrinh chiTietKiemDemCongTrinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChiTietKiemDemCongTrinh> toCacheModel();

	@Override
	public ChiTietKiemDemCongTrinh toEscapedModel();

	@Override
	public ChiTietKiemDemCongTrinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}