/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VeSinhGiaDinh service. Represents a row in the &quot;ME_VESINHGIADINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.VeSinhGiaDinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.VeSinhGiaDinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see VeSinhGiaDinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.VeSinhGiaDinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.VeSinhGiaDinhModelImpl
 * @generated
 */
public interface VeSinhGiaDinhModel extends BaseModel<VeSinhGiaDinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ve sinh gia dinh model instance should use the {@link VeSinhGiaDinh} interface instead.
	 */

	/**
	 * Returns the primary key of this ve sinh gia dinh.
	 *
	 * @return the primary key of this ve sinh gia dinh
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ve sinh gia dinh.
	 *
	 * @param primaryKey the primary key of this ve sinh gia dinh
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ve sinh gia dinh.
	 *
	 * @return the ID of this ve sinh gia dinh
	 */
	public int getId();

	/**
	 * Sets the ID of this ve sinh gia dinh.
	 *
	 * @param id the ID of this ve sinh gia dinh
	 */
	public void setId(int id);

	/**
	 * Returns the ma tinh of this ve sinh gia dinh.
	 *
	 * @return the ma tinh of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this ve sinh gia dinh.
	 *
	 * @param maTinh the ma tinh of this ve sinh gia dinh
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this ve sinh gia dinh.
	 *
	 * @return the ma huyen of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this ve sinh gia dinh.
	 *
	 * @param maHuyen the ma huyen of this ve sinh gia dinh
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this ve sinh gia dinh.
	 *
	 * @return the ma xa of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this ve sinh gia dinh.
	 *
	 * @param maXa the ma xa of this ve sinh gia dinh
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the thon xom of this ve sinh gia dinh.
	 *
	 * @return the thon xom of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getThonXom();

	/**
	 * Sets the thon xom of this ve sinh gia dinh.
	 *
	 * @param thonXom the thon xom of this ve sinh gia dinh
	 */
	public void setThonXom(String thonXom);

	/**
	 * Returns the ten chu ho of this ve sinh gia dinh.
	 *
	 * @return the ten chu ho of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getTenChuHo();

	/**
	 * Sets the ten chu ho of this ve sinh gia dinh.
	 *
	 * @param tenChuHo the ten chu ho of this ve sinh gia dinh
	 */
	public void setTenChuHo(String tenChuHo);

	/**
	 * Returns the gioi tinh chu ho of this ve sinh gia dinh.
	 *
	 * @return the gioi tinh chu ho of this ve sinh gia dinh
	 */
	public int getGioiTinhChuHo();

	/**
	 * Sets the gioi tinh chu ho of this ve sinh gia dinh.
	 *
	 * @param gioiTinhChuHo the gioi tinh chu ho of this ve sinh gia dinh
	 */
	public void setGioiTinhChuHo(int gioiTinhChuHo);

	/**
	 * Returns the trang thai of this ve sinh gia dinh.
	 *
	 * @return the trang thai of this ve sinh gia dinh
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this ve sinh gia dinh.
	 *
	 * @param trangThai the trang thai of this ve sinh gia dinh
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the mau ngau nhien of this ve sinh gia dinh.
	 *
	 * @return the mau ngau nhien of this ve sinh gia dinh
	 */
	public int getMauNgauNhien();

	/**
	 * Sets the mau ngau nhien of this ve sinh gia dinh.
	 *
	 * @param mauNgauNhien the mau ngau nhien of this ve sinh gia dinh
	 */
	public void setMauNgauNhien(int mauNgauNhien);

	/**
	 * Returns the nam bao cao of this ve sinh gia dinh.
	 *
	 * @return the nam bao cao of this ve sinh gia dinh
	 */
	public int getNamBaoCao();

	/**
	 * Sets the nam bao cao of this ve sinh gia dinh.
	 *
	 * @param namBaoCao the nam bao cao of this ve sinh gia dinh
	 */
	public void setNamBaoCao(int namBaoCao);

	/**
	 * Returns the ghi chu of this ve sinh gia dinh.
	 *
	 * @return the ghi chu of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this ve sinh gia dinh.
	 *
	 * @param ghiChu the ghi chu of this ve sinh gia dinh
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the ngay tao of this ve sinh gia dinh.
	 *
	 * @return the ngay tao of this ve sinh gia dinh
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ve sinh gia dinh.
	 *
	 * @param ngayTao the ngay tao of this ve sinh gia dinh
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this ve sinh gia dinh.
	 *
	 * @return the id nguoi tao of this ve sinh gia dinh
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this ve sinh gia dinh.
	 *
	 * @param idNguoiTao the id nguoi tao of this ve sinh gia dinh
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the so nguoi trong ho of this ve sinh gia dinh.
	 *
	 * @return the so nguoi trong ho of this ve sinh gia dinh
	 */
	public int getSoNguoiTrongHo();

	/**
	 * Sets the so nguoi trong ho of this ve sinh gia dinh.
	 *
	 * @param soNguoiTrongHo the so nguoi trong ho of this ve sinh gia dinh
	 */
	public void setSoNguoiTrongHo(int soNguoiTrongHo);

	/**
	 * Returns the thanh phan ho g d of this ve sinh gia dinh.
	 *
	 * @return the thanh phan ho g d of this ve sinh gia dinh
	 */
	public int getThanhPhanHoGD();

	/**
	 * Sets the thanh phan ho g d of this ve sinh gia dinh.
	 *
	 * @param thanhPhanHoGD the thanh phan ho g d of this ve sinh gia dinh
	 */
	public void setThanhPhanHoGD(int thanhPhanHoGD);

	/**
	 * Returns the kinh do of this ve sinh gia dinh.
	 *
	 * @return the kinh do of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getKinhDo();

	/**
	 * Sets the kinh do of this ve sinh gia dinh.
	 *
	 * @param kinhDo the kinh do of this ve sinh gia dinh
	 */
	public void setKinhDo(String kinhDo);

	/**
	 * Returns the vi do of this ve sinh gia dinh.
	 *
	 * @return the vi do of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getViDo();

	/**
	 * Sets the vi do of this ve sinh gia dinh.
	 *
	 * @param viDo the vi do of this ve sinh gia dinh
	 */
	public void setViDo(String viDo);

	/**
	 * Returns the co nha tieu of this ve sinh gia dinh.
	 *
	 * @return the co nha tieu of this ve sinh gia dinh
	 */
	public int getCoNhaTieu();

	/**
	 * Sets the co nha tieu of this ve sinh gia dinh.
	 *
	 * @param coNhaTieu the co nha tieu of this ve sinh gia dinh
	 */
	public void setCoNhaTieu(int coNhaTieu);

	/**
	 * Returns the nha tieu h v s of this ve sinh gia dinh.
	 *
	 * @return the nha tieu h v s of this ve sinh gia dinh
	 */
	public int getNhaTieuHVS();

	/**
	 * Sets the nha tieu h v s of this ve sinh gia dinh.
	 *
	 * @param nhaTieuHVS the nha tieu h v s of this ve sinh gia dinh
	 */
	public void setNhaTieuHVS(int nhaTieuHVS);

	/**
	 * Returns the loai nha tieu of this ve sinh gia dinh.
	 *
	 * @return the loai nha tieu of this ve sinh gia dinh
	 */
	@AutoEscape
	public String getLoaiNhaTieu();

	/**
	 * Sets the loai nha tieu of this ve sinh gia dinh.
	 *
	 * @param loaiNhaTieu the loai nha tieu of this ve sinh gia dinh
	 */
	public void setLoaiNhaTieu(String loaiNhaTieu);

	/**
	 * Returns the duoc cai tao of this ve sinh gia dinh.
	 *
	 * @return the duoc cai tao of this ve sinh gia dinh
	 */
	public int getDuocCaiTao();

	/**
	 * Sets the duoc cai tao of this ve sinh gia dinh.
	 *
	 * @param duocCaiTao the duoc cai tao of this ve sinh gia dinh
	 */
	public void setDuocCaiTao(int duocCaiTao);

	/**
	 * Returns the thang xay dung of this ve sinh gia dinh.
	 *
	 * @return the thang xay dung of this ve sinh gia dinh
	 */
	public int getThangXayDung();

	/**
	 * Sets the thang xay dung of this ve sinh gia dinh.
	 *
	 * @param thangXayDung the thang xay dung of this ve sinh gia dinh
	 */
	public void setThangXayDung(int thangXayDung);

	/**
	 * Returns the nam xay dung of this ve sinh gia dinh.
	 *
	 * @return the nam xay dung of this ve sinh gia dinh
	 */
	public int getNamXayDung();

	/**
	 * Sets the nam xay dung of this ve sinh gia dinh.
	 *
	 * @param namXayDung the nam xay dung of this ve sinh gia dinh
	 */
	public void setNamXayDung(int namXayDung);

	/**
	 * Returns the nguon von of this ve sinh gia dinh.
	 *
	 * @return the nguon von of this ve sinh gia dinh
	 */
	public int getNguonVon();

	/**
	 * Sets the nguon von of this ve sinh gia dinh.
	 *
	 * @param nguonVon the nguon von of this ve sinh gia dinh
	 */
	public void setNguonVon(int nguonVon);

	/**
	 * Returns the ngay kiem dem of this ve sinh gia dinh.
	 *
	 * @return the ngay kiem dem of this ve sinh gia dinh
	 */
	public Date getNgayKiemDem();

	/**
	 * Sets the ngay kiem dem of this ve sinh gia dinh.
	 *
	 * @param ngayKiemDem the ngay kiem dem of this ve sinh gia dinh
	 */
	public void setNgayKiemDem(Date ngayKiemDem);

	/**
	 * Returns the ngay danh gia of this ve sinh gia dinh.
	 *
	 * @return the ngay danh gia of this ve sinh gia dinh
	 */
	public Date getNgayDanhGia();

	/**
	 * Sets the ngay danh gia of this ve sinh gia dinh.
	 *
	 * @param ngayDanhGia the ngay danh gia of this ve sinh gia dinh
	 */
	public void setNgayDanhGia(Date ngayDanhGia);

	/**
	 * Returns the id nguoi danh gia of this ve sinh gia dinh.
	 *
	 * @return the id nguoi danh gia of this ve sinh gia dinh
	 */
	public int getIdNguoiDanhGia();

	/**
	 * Sets the id nguoi danh gia of this ve sinh gia dinh.
	 *
	 * @param idNguoiDanhGia the id nguoi danh gia of this ve sinh gia dinh
	 */
	public void setIdNguoiDanhGia(int idNguoiDanhGia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VeSinhGiaDinh veSinhGiaDinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VeSinhGiaDinh> toCacheModel();

	@Override
	public VeSinhGiaDinh toEscapedModel();

	@Override
	public VeSinhGiaDinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}