/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VeSinhCongTrinh service. Represents a row in the &quot;ME_VESINHCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VeSinhCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see VeSinhCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinhModel
 * @generated
 */
public class VeSinhCongTrinhModelImpl extends BaseModelImpl<VeSinhCongTrinh>
	implements VeSinhCongTrinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ve sinh cong trinh model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_VESINHCONGTRINH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "TENCONGTRINH", Types.VARCHAR },
			{ "LOAICONGTRINH", Types.INTEGER },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "DIACHI", Types.VARCHAR },
			{ "TRANGTHAI", Types.INTEGER },
			{ "NAMBAOCAO", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.VARCHAR },
			{ "KINHDO", Types.VARCHAR },
			{ "VIDO", Types.VARCHAR },
			{ "LOAINGUONNUOC", Types.VARCHAR },
			{ "NGUONNUOCHVS", Types.INTEGER },
			{ "LOAINHATIEU", Types.VARCHAR },
			{ "NHATIEUHVS", Types.INTEGER },
			{ "KETLUANHVS", Types.INTEGER },
			{ "NGAYKIEMDEM", Types.TIMESTAMP },
			{ "NGAYDANHGIA", Types.TIMESTAMP },
			{ "IDNGUOIDANHGIA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_VESINHCONGTRINH (ID INTEGER not null primary key,TENCONGTRINH VARCHAR(75) null,LOAICONGTRINH INTEGER,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,DIACHI VARCHAR(75) null,TRANGTHAI INTEGER,NAMBAOCAO INTEGER,GHICHU VARCHAR(75) null,NGAYTAO DATE null,IDNGUOITAO VARCHAR(75) null,KINHDO VARCHAR(75) null,VIDO VARCHAR(75) null,LOAINGUONNUOC VARCHAR(75) null,NGUONNUOCHVS INTEGER,LOAINHATIEU VARCHAR(75) null,NHATIEUHVS INTEGER,KETLUANHVS INTEGER,NGAYKIEMDEM DATE null,NGAYDANHGIA DATE null,IDNGUOIDANHGIA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ME_VESINHCONGTRINH";
	public static final String ORDER_BY_JPQL = " ORDER BY veSinhCongTrinh.maTinh ASC, veSinhCongTrinh.maHuyen ASC, veSinhCongTrinh.maXa ASC, veSinhCongTrinh.diaChi ASC, veSinhCongTrinh.loaiNhaTieu ASC, veSinhCongTrinh.tenCongTrinh ASC, veSinhCongTrinh.trangThai ASC, veSinhCongTrinh.namBaoCao ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_VESINHCONGTRINH.MATINH ASC, ME_VESINHCONGTRINH.MAHUYEN ASC, ME_VESINHCONGTRINH.MAXA ASC, ME_VESINHCONGTRINH.DIACHI ASC, ME_VESINHCONGTRINH.LOAINHATIEU ASC, ME_VESINHCONGTRINH.TENCONGTRINH ASC, ME_VESINHCONGTRINH.TRANGTHAI ASC, ME_VESINHCONGTRINH.NAMBAOCAO ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh"));

	public VeSinhCongTrinhModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VeSinhCongTrinh.class;
	}

	@Override
	public String getModelClassName() {
		return VeSinhCongTrinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("tenCongTrinh", getTenCongTrinh());
		attributes.put("loaiCongTrinh", getLoaiCongTrinh());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("diaChi", getDiaChi());
		attributes.put("trangThai", getTrangThai());
		attributes.put("namBaoCao", getNamBaoCao());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("loaiNguonNuoc", getLoaiNguonNuoc());
		attributes.put("nguonNuocHVS", getNguonNuocHVS());
		attributes.put("loaiNhaTieu", getLoaiNhaTieu());
		attributes.put("nhaTieuHVS", getNhaTieuHVS());
		attributes.put("ketLuanHVS", getKetLuanHVS());
		attributes.put("ngayKiemDem", getNgayKiemDem());
		attributes.put("ngayDanhGia", getNgayDanhGia());
		attributes.put("idNguoiDanhGia", getIdNguoiDanhGia());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String tenCongTrinh = (String)attributes.get("tenCongTrinh");

		if (tenCongTrinh != null) {
			setTenCongTrinh(tenCongTrinh);
		}

		Integer loaiCongTrinh = (Integer)attributes.get("loaiCongTrinh");

		if (loaiCongTrinh != null) {
			setLoaiCongTrinh(loaiCongTrinh);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		Integer trangThai = (Integer)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Integer namBaoCao = (Integer)attributes.get("namBaoCao");

		if (namBaoCao != null) {
			setNamBaoCao(namBaoCao);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		String idNguoiTao = (String)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		String loaiNguonNuoc = (String)attributes.get("loaiNguonNuoc");

		if (loaiNguonNuoc != null) {
			setLoaiNguonNuoc(loaiNguonNuoc);
		}

		Integer nguonNuocHVS = (Integer)attributes.get("nguonNuocHVS");

		if (nguonNuocHVS != null) {
			setNguonNuocHVS(nguonNuocHVS);
		}

		String loaiNhaTieu = (String)attributes.get("loaiNhaTieu");

		if (loaiNhaTieu != null) {
			setLoaiNhaTieu(loaiNhaTieu);
		}

		Integer nhaTieuHVS = (Integer)attributes.get("nhaTieuHVS");

		if (nhaTieuHVS != null) {
			setNhaTieuHVS(nhaTieuHVS);
		}

		Integer ketLuanHVS = (Integer)attributes.get("ketLuanHVS");

		if (ketLuanHVS != null) {
			setKetLuanHVS(ketLuanHVS);
		}

		Date ngayKiemDem = (Date)attributes.get("ngayKiemDem");

		if (ngayKiemDem != null) {
			setNgayKiemDem(ngayKiemDem);
		}

		Date ngayDanhGia = (Date)attributes.get("ngayDanhGia");

		if (ngayDanhGia != null) {
			setNgayDanhGia(ngayDanhGia);
		}

		Integer idNguoiDanhGia = (Integer)attributes.get("idNguoiDanhGia");

		if (idNguoiDanhGia != null) {
			setIdNguoiDanhGia(idNguoiDanhGia);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public String getTenCongTrinh() {
		if (_tenCongTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCongTrinh;
		}
	}

	@Override
	public void setTenCongTrinh(String tenCongTrinh) {
		_tenCongTrinh = tenCongTrinh;
	}

	@Override
	public int getLoaiCongTrinh() {
		return _loaiCongTrinh;
	}

	@Override
	public void setLoaiCongTrinh(int loaiCongTrinh) {
		_loaiCongTrinh = loaiCongTrinh;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_maTinh = maTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@Override
	public int getTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public int getNamBaoCao() {
		return _namBaoCao;
	}

	@Override
	public void setNamBaoCao(int namBaoCao) {
		_namBaoCao = namBaoCao;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public String getIdNguoiTao() {
		if (_idNguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _idNguoiTao;
		}
	}

	@Override
	public void setIdNguoiTao(String idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public String getLoaiNguonNuoc() {
		if (_loaiNguonNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNguonNuoc;
		}
	}

	@Override
	public void setLoaiNguonNuoc(String loaiNguonNuoc) {
		_loaiNguonNuoc = loaiNguonNuoc;
	}

	@Override
	public int getNguonNuocHVS() {
		return _nguonNuocHVS;
	}

	@Override
	public void setNguonNuocHVS(int nguonNuocHVS) {
		_nguonNuocHVS = nguonNuocHVS;
	}

	@Override
	public String getLoaiNhaTieu() {
		if (_loaiNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNhaTieu;
		}
	}

	@Override
	public void setLoaiNhaTieu(String loaiNhaTieu) {
		_loaiNhaTieu = loaiNhaTieu;
	}

	@Override
	public int getNhaTieuHVS() {
		return _nhaTieuHVS;
	}

	@Override
	public void setNhaTieuHVS(int nhaTieuHVS) {
		_nhaTieuHVS = nhaTieuHVS;
	}

	@Override
	public int getKetLuanHVS() {
		return _ketLuanHVS;
	}

	@Override
	public void setKetLuanHVS(int ketLuanHVS) {
		_ketLuanHVS = ketLuanHVS;
	}

	@Override
	public Date getNgayKiemDem() {
		return _ngayKiemDem;
	}

	@Override
	public void setNgayKiemDem(Date ngayKiemDem) {
		_ngayKiemDem = ngayKiemDem;
	}

	@Override
	public Date getNgayDanhGia() {
		return _ngayDanhGia;
	}

	@Override
	public void setNgayDanhGia(Date ngayDanhGia) {
		_ngayDanhGia = ngayDanhGia;
	}

	@Override
	public int getIdNguoiDanhGia() {
		return _idNguoiDanhGia;
	}

	@Override
	public void setIdNguoiDanhGia(int idNguoiDanhGia) {
		_idNguoiDanhGia = idNguoiDanhGia;
	}

	@Override
	public VeSinhCongTrinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VeSinhCongTrinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VeSinhCongTrinhImpl veSinhCongTrinhImpl = new VeSinhCongTrinhImpl();

		veSinhCongTrinhImpl.setId(getId());
		veSinhCongTrinhImpl.setTenCongTrinh(getTenCongTrinh());
		veSinhCongTrinhImpl.setLoaiCongTrinh(getLoaiCongTrinh());
		veSinhCongTrinhImpl.setMaTinh(getMaTinh());
		veSinhCongTrinhImpl.setMaHuyen(getMaHuyen());
		veSinhCongTrinhImpl.setMaXa(getMaXa());
		veSinhCongTrinhImpl.setDiaChi(getDiaChi());
		veSinhCongTrinhImpl.setTrangThai(getTrangThai());
		veSinhCongTrinhImpl.setNamBaoCao(getNamBaoCao());
		veSinhCongTrinhImpl.setGhiChu(getGhiChu());
		veSinhCongTrinhImpl.setNgayTao(getNgayTao());
		veSinhCongTrinhImpl.setIdNguoiTao(getIdNguoiTao());
		veSinhCongTrinhImpl.setKinhDo(getKinhDo());
		veSinhCongTrinhImpl.setViDo(getViDo());
		veSinhCongTrinhImpl.setLoaiNguonNuoc(getLoaiNguonNuoc());
		veSinhCongTrinhImpl.setNguonNuocHVS(getNguonNuocHVS());
		veSinhCongTrinhImpl.setLoaiNhaTieu(getLoaiNhaTieu());
		veSinhCongTrinhImpl.setNhaTieuHVS(getNhaTieuHVS());
		veSinhCongTrinhImpl.setKetLuanHVS(getKetLuanHVS());
		veSinhCongTrinhImpl.setNgayKiemDem(getNgayKiemDem());
		veSinhCongTrinhImpl.setNgayDanhGia(getNgayDanhGia());
		veSinhCongTrinhImpl.setIdNguoiDanhGia(getIdNguoiDanhGia());

		veSinhCongTrinhImpl.resetOriginalValues();

		return veSinhCongTrinhImpl;
	}

	@Override
	public int compareTo(VeSinhCongTrinh veSinhCongTrinh) {
		int value = 0;

		value = getMaTinh().compareTo(veSinhCongTrinh.getMaTinh());

		if (value != 0) {
			return value;
		}

		value = getMaHuyen().compareTo(veSinhCongTrinh.getMaHuyen());

		if (value != 0) {
			return value;
		}

		value = getMaXa().compareTo(veSinhCongTrinh.getMaXa());

		if (value != 0) {
			return value;
		}

		value = getDiaChi().compareTo(veSinhCongTrinh.getDiaChi());

		if (value != 0) {
			return value;
		}

		value = getLoaiNhaTieu().compareTo(veSinhCongTrinh.getLoaiNhaTieu());

		if (value != 0) {
			return value;
		}

		value = getTenCongTrinh().compareTo(veSinhCongTrinh.getTenCongTrinh());

		if (value != 0) {
			return value;
		}

		if (getTrangThai() < veSinhCongTrinh.getTrangThai()) {
			value = -1;
		}
		else if (getTrangThai() > veSinhCongTrinh.getTrangThai()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getNamBaoCao() < veSinhCongTrinh.getNamBaoCao()) {
			value = -1;
		}
		else if (getNamBaoCao() > veSinhCongTrinh.getNamBaoCao()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VeSinhCongTrinh)) {
			return false;
		}

		VeSinhCongTrinh veSinhCongTrinh = (VeSinhCongTrinh)obj;

		int primaryKey = veSinhCongTrinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VeSinhCongTrinh> toCacheModel() {
		VeSinhCongTrinhCacheModel veSinhCongTrinhCacheModel = new VeSinhCongTrinhCacheModel();

		veSinhCongTrinhCacheModel.id = getId();

		veSinhCongTrinhCacheModel.tenCongTrinh = getTenCongTrinh();

		String tenCongTrinh = veSinhCongTrinhCacheModel.tenCongTrinh;

		if ((tenCongTrinh != null) && (tenCongTrinh.length() == 0)) {
			veSinhCongTrinhCacheModel.tenCongTrinh = null;
		}

		veSinhCongTrinhCacheModel.loaiCongTrinh = getLoaiCongTrinh();

		veSinhCongTrinhCacheModel.maTinh = getMaTinh();

		String maTinh = veSinhCongTrinhCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			veSinhCongTrinhCacheModel.maTinh = null;
		}

		veSinhCongTrinhCacheModel.maHuyen = getMaHuyen();

		String maHuyen = veSinhCongTrinhCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			veSinhCongTrinhCacheModel.maHuyen = null;
		}

		veSinhCongTrinhCacheModel.maXa = getMaXa();

		String maXa = veSinhCongTrinhCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			veSinhCongTrinhCacheModel.maXa = null;
		}

		veSinhCongTrinhCacheModel.diaChi = getDiaChi();

		String diaChi = veSinhCongTrinhCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			veSinhCongTrinhCacheModel.diaChi = null;
		}

		veSinhCongTrinhCacheModel.trangThai = getTrangThai();

		veSinhCongTrinhCacheModel.namBaoCao = getNamBaoCao();

		veSinhCongTrinhCacheModel.ghiChu = getGhiChu();

		String ghiChu = veSinhCongTrinhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			veSinhCongTrinhCacheModel.ghiChu = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			veSinhCongTrinhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			veSinhCongTrinhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		veSinhCongTrinhCacheModel.idNguoiTao = getIdNguoiTao();

		String idNguoiTao = veSinhCongTrinhCacheModel.idNguoiTao;

		if ((idNguoiTao != null) && (idNguoiTao.length() == 0)) {
			veSinhCongTrinhCacheModel.idNguoiTao = null;
		}

		veSinhCongTrinhCacheModel.kinhDo = getKinhDo();

		String kinhDo = veSinhCongTrinhCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			veSinhCongTrinhCacheModel.kinhDo = null;
		}

		veSinhCongTrinhCacheModel.viDo = getViDo();

		String viDo = veSinhCongTrinhCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			veSinhCongTrinhCacheModel.viDo = null;
		}

		veSinhCongTrinhCacheModel.loaiNguonNuoc = getLoaiNguonNuoc();

		String loaiNguonNuoc = veSinhCongTrinhCacheModel.loaiNguonNuoc;

		if ((loaiNguonNuoc != null) && (loaiNguonNuoc.length() == 0)) {
			veSinhCongTrinhCacheModel.loaiNguonNuoc = null;
		}

		veSinhCongTrinhCacheModel.nguonNuocHVS = getNguonNuocHVS();

		veSinhCongTrinhCacheModel.loaiNhaTieu = getLoaiNhaTieu();

		String loaiNhaTieu = veSinhCongTrinhCacheModel.loaiNhaTieu;

		if ((loaiNhaTieu != null) && (loaiNhaTieu.length() == 0)) {
			veSinhCongTrinhCacheModel.loaiNhaTieu = null;
		}

		veSinhCongTrinhCacheModel.nhaTieuHVS = getNhaTieuHVS();

		veSinhCongTrinhCacheModel.ketLuanHVS = getKetLuanHVS();

		Date ngayKiemDem = getNgayKiemDem();

		if (ngayKiemDem != null) {
			veSinhCongTrinhCacheModel.ngayKiemDem = ngayKiemDem.getTime();
		}
		else {
			veSinhCongTrinhCacheModel.ngayKiemDem = Long.MIN_VALUE;
		}

		Date ngayDanhGia = getNgayDanhGia();

		if (ngayDanhGia != null) {
			veSinhCongTrinhCacheModel.ngayDanhGia = ngayDanhGia.getTime();
		}
		else {
			veSinhCongTrinhCacheModel.ngayDanhGia = Long.MIN_VALUE;
		}

		veSinhCongTrinhCacheModel.idNguoiDanhGia = getIdNguoiDanhGia();

		return veSinhCongTrinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", tenCongTrinh=");
		sb.append(getTenCongTrinh());
		sb.append(", loaiCongTrinh=");
		sb.append(getLoaiCongTrinh());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", namBaoCao=");
		sb.append(getNamBaoCao());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", loaiNguonNuoc=");
		sb.append(getLoaiNguonNuoc());
		sb.append(", nguonNuocHVS=");
		sb.append(getNguonNuocHVS());
		sb.append(", loaiNhaTieu=");
		sb.append(getLoaiNhaTieu());
		sb.append(", nhaTieuHVS=");
		sb.append(getNhaTieuHVS());
		sb.append(", ketLuanHVS=");
		sb.append(getKetLuanHVS());
		sb.append(", ngayKiemDem=");
		sb.append(getNgayKiemDem());
		sb.append(", ngayDanhGia=");
		sb.append(getNgayDanhGia());
		sb.append(", idNguoiDanhGia=");
		sb.append(getIdNguoiDanhGia());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhCongTrinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCongTrinh</column-name><column-value><![CDATA[");
		sb.append(getTenCongTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiCongTrinh</column-name><column-value><![CDATA[");
		sb.append(getLoaiCongTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namBaoCao</column-name><column-value><![CDATA[");
		sb.append(getNamBaoCao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNguonNuoc</column-name><column-value><![CDATA[");
		sb.append(getLoaiNguonNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguonNuocHVS</column-name><column-value><![CDATA[");
		sb.append(getNguonNuocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketLuanHVS</column-name><column-value><![CDATA[");
		sb.append(getKetLuanHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKiemDem</column-name><column-value><![CDATA[");
		sb.append(getNgayKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDanhGia</column-name><column-value><![CDATA[");
		sb.append(getNgayDanhGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiDanhGia</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiDanhGia());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VeSinhCongTrinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VeSinhCongTrinh.class
		};
	private int _id;
	private String _tenCongTrinh;
	private int _loaiCongTrinh;
	private String _maTinh;
	private String _maHuyen;
	private String _maXa;
	private String _diaChi;
	private int _trangThai;
	private int _namBaoCao;
	private String _ghiChu;
	private Date _ngayTao;
	private String _idNguoiTao;
	private String _kinhDo;
	private String _viDo;
	private String _loaiNguonNuoc;
	private int _nguonNuocHVS;
	private String _loaiNhaTieu;
	private int _nhaTieuHVS;
	private int _ketLuanHVS;
	private Date _ngayKiemDem;
	private Date _ngayDanhGia;
	private int _idNguoiDanhGia;
	private VeSinhCongTrinh _escapedModel;
}