/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DanhGiaBenVung service. Represents a row in the &quot;ME_DANHGIABENVUNG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaBenVungModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaBenVungImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DanhGiaBenVung
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaBenVungImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaBenVungModelImpl
 * @generated
 */
public interface DanhGiaBenVungModel extends BaseModel<DanhGiaBenVung> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh gia ben vung model instance should use the {@link DanhGiaBenVung} interface instead.
	 */

	/**
	 * Returns the primary key of this danh gia ben vung.
	 *
	 * @return the primary key of this danh gia ben vung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh gia ben vung.
	 *
	 * @param primaryKey the primary key of this danh gia ben vung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this danh gia ben vung.
	 *
	 * @return the ID of this danh gia ben vung
	 */
	public long getId();

	/**
	 * Sets the ID of this danh gia ben vung.
	 *
	 * @param id the ID of this danh gia ben vung
	 */
	public void setId(long id);

	/**
	 * Returns the tram cap nuoc ID of this danh gia ben vung.
	 *
	 * @return the tram cap nuoc ID of this danh gia ben vung
	 */
	public int getTramCapNuocId();

	/**
	 * Sets the tram cap nuoc ID of this danh gia ben vung.
	 *
	 * @param tramCapNuocId the tram cap nuoc ID of this danh gia ben vung
	 */
	public void setTramCapNuocId(int tramCapNuocId);

	/**
	 * Returns the nam of this danh gia ben vung.
	 *
	 * @return the nam of this danh gia ben vung
	 */
	public int getNam();

	/**
	 * Sets the nam of this danh gia ben vung.
	 *
	 * @param nam the nam of this danh gia ben vung
	 */
	public void setNam(int nam);

	/**
	 * Returns the trang thai cap nuoc of this danh gia ben vung.
	 *
	 * @return the trang thai cap nuoc of this danh gia ben vung
	 */
	public int getTrangThaiCapNuoc();

	/**
	 * Sets the trang thai cap nuoc of this danh gia ben vung.
	 *
	 * @param trangThaiCapNuoc the trang thai cap nuoc of this danh gia ben vung
	 */
	public void setTrangThaiCapNuoc(int trangThaiCapNuoc);

	/**
	 * Returns the cong xuat thuc te of this danh gia ben vung.
	 *
	 * @return the cong xuat thuc te of this danh gia ben vung
	 */
	public int getCongXuatThucTe();

	/**
	 * Sets the cong xuat thuc te of this danh gia ben vung.
	 *
	 * @param congXuatThucTe the cong xuat thuc te of this danh gia ben vung
	 */
	public void setCongXuatThucTe(int congXuatThucTe);

	/**
	 * Returns the tong dau noi moi of this danh gia ben vung.
	 *
	 * @return the tong dau noi moi of this danh gia ben vung
	 */
	public int getTongDauNoiMoi();

	/**
	 * Sets the tong dau noi moi of this danh gia ben vung.
	 *
	 * @param tongDauNoiMoi the tong dau noi moi of this danh gia ben vung
	 */
	public void setTongDauNoiMoi(int tongDauNoiMoi);

	/**
	 * Returns the tong dau noi thuc te of this danh gia ben vung.
	 *
	 * @return the tong dau noi thuc te of this danh gia ben vung
	 */
	public int getTongDauNoiThucTe();

	/**
	 * Sets the tong dau noi thuc te of this danh gia ben vung.
	 *
	 * @param tongDauNoiThucTe the tong dau noi thuc te of this danh gia ben vung
	 */
	public void setTongDauNoiThucTe(int tongDauNoiThucTe);

	/**
	 * Returns the so nguoi cap thuc te of this danh gia ben vung.
	 *
	 * @return the so nguoi cap thuc te of this danh gia ben vung
	 */
	public int getSoNguoiCapThucTe();

	/**
	 * Sets the so nguoi cap thuc te of this danh gia ben vung.
	 *
	 * @param soNguoiCapThucTe the so nguoi cap thuc te of this danh gia ben vung
	 */
	public void setSoNguoiCapThucTe(int soNguoiCapThucTe);

	/**
	 * Returns the nuoc that thoat of this danh gia ben vung.
	 *
	 * @return the nuoc that thoat of this danh gia ben vung
	 */
	public int getNuocThatThoat();

	/**
	 * Sets the nuoc that thoat of this danh gia ben vung.
	 *
	 * @param nuocThatThoat the nuoc that thoat of this danh gia ben vung
	 */
	public void setNuocThatThoat(int nuocThatThoat);

	/**
	 * Returns the nuoc dat tieu chuan of this danh gia ben vung.
	 *
	 * @return the nuoc dat tieu chuan of this danh gia ben vung
	 */
	public int getNuocDatTieuChuan();

	/**
	 * Sets the nuoc dat tieu chuan of this danh gia ben vung.
	 *
	 * @param nuocDatTieuChuan the nuoc dat tieu chuan of this danh gia ben vung
	 */
	public void setNuocDatTieuChuan(int nuocDatTieuChuan);

	/**
	 * Returns the nuoc co asen of this danh gia ben vung.
	 *
	 * @return the nuoc co asen of this danh gia ben vung
	 */
	public int getNuocCoAsen();

	/**
	 * Sets the nuoc co asen of this danh gia ben vung.
	 *
	 * @param nuocCoAsen the nuoc co asen of this danh gia ben vung
	 */
	public void setNuocCoAsen(int nuocCoAsen);

	/**
	 * Returns the tong chi phi of this danh gia ben vung.
	 *
	 * @return the tong chi phi of this danh gia ben vung
	 */
	public int getTongChiPhi();

	/**
	 * Sets the tong chi phi of this danh gia ben vung.
	 *
	 * @param tongChiPhi the tong chi phi of this danh gia ben vung
	 */
	public void setTongChiPhi(int tongChiPhi);

	/**
	 * Returns the tong doanh thu of this danh gia ben vung.
	 *
	 * @return the tong doanh thu of this danh gia ben vung
	 */
	public int getTongDoanhThu();

	/**
	 * Sets the tong doanh thu of this danh gia ben vung.
	 *
	 * @param tongDoanhThu the tong doanh thu of this danh gia ben vung
	 */
	public void setTongDoanhThu(int tongDoanhThu);

	/**
	 * Returns the ngay tao of this danh gia ben vung.
	 *
	 * @return the ngay tao of this danh gia ben vung
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this danh gia ben vung.
	 *
	 * @param ngayTao the ngay tao of this danh gia ben vung
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this danh gia ben vung.
	 *
	 * @return the id nguoi tao of this danh gia ben vung
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this danh gia ben vung.
	 *
	 * @param idNguoiTao the id nguoi tao of this danh gia ben vung
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the ghi chu of this danh gia ben vung.
	 *
	 * @return the ghi chu of this danh gia ben vung
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this danh gia ben vung.
	 *
	 * @param ghiChu the ghi chu of this danh gia ben vung
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the ket qua danh gia of this danh gia ben vung.
	 *
	 * @return the ket qua danh gia of this danh gia ben vung
	 */
	public int getKetQuaDanhGia();

	/**
	 * Sets the ket qua danh gia of this danh gia ben vung.
	 *
	 * @param ketQuaDanhGia the ket qua danh gia of this danh gia ben vung
	 */
	public void setKetQuaDanhGia(int ketQuaDanhGia);

	/**
	 * Returns the bao cao d l i of this danh gia ben vung.
	 *
	 * @return the bao cao d l i of this danh gia ben vung
	 */
	public int getBaoCaoDLI();

	/**
	 * Sets the bao cao d l i of this danh gia ben vung.
	 *
	 * @param baoCaoDLI the bao cao d l i of this danh gia ben vung
	 */
	public void setBaoCaoDLI(int baoCaoDLI);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DanhGiaBenVung danhGiaBenVung);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DanhGiaBenVung> toCacheModel();

	@Override
	public DanhGiaBenVung toEscapedModel();

	@Override
	public DanhGiaBenVung toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}