/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KeHoachKiemDemNuoc service. Represents a row in the &quot;ME_KEHOACHKIEMDEMNUOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.tramcap.dao.model.impl.KeHoachKiemDemNuocModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.tramcap.dao.model.impl.KeHoachKiemDemNuocImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see KeHoachKiemDemNuoc
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.KeHoachKiemDemNuocImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.KeHoachKiemDemNuocModelImpl
 * @generated
 */
public interface KeHoachKiemDemNuocModel extends BaseModel<KeHoachKiemDemNuoc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ke hoach kiem dem nuoc model instance should use the {@link KeHoachKiemDemNuoc} interface instead.
	 */

	/**
	 * Returns the primary key of this ke hoach kiem dem nuoc.
	 *
	 * @return the primary key of this ke hoach kiem dem nuoc
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ke hoach kiem dem nuoc.
	 *
	 * @param primaryKey the primary key of this ke hoach kiem dem nuoc
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ke hoach kiem dem nuoc.
	 *
	 * @return the ID of this ke hoach kiem dem nuoc
	 */
	public int getId();

	/**
	 * Sets the ID of this ke hoach kiem dem nuoc.
	 *
	 * @param id the ID of this ke hoach kiem dem nuoc
	 */
	public void setId(int id);

	/**
	 * Returns the nam of this ke hoach kiem dem nuoc.
	 *
	 * @return the nam of this ke hoach kiem dem nuoc
	 */
	public int getNam();

	/**
	 * Sets the nam of this ke hoach kiem dem nuoc.
	 *
	 * @param nam the nam of this ke hoach kiem dem nuoc
	 */
	public void setNam(int nam);

	/**
	 * Returns the tram cap nuoc ID of this ke hoach kiem dem nuoc.
	 *
	 * @return the tram cap nuoc ID of this ke hoach kiem dem nuoc
	 */
	public int getTramCapNuocId();

	/**
	 * Sets the tram cap nuoc ID of this ke hoach kiem dem nuoc.
	 *
	 * @param tramCapNuocId the tram cap nuoc ID of this ke hoach kiem dem nuoc
	 */
	public void setTramCapNuocId(int tramCapNuocId);

	/**
	 * Returns the kiem dem vien ID of this ke hoach kiem dem nuoc.
	 *
	 * @return the kiem dem vien ID of this ke hoach kiem dem nuoc
	 */
	public int getKiemDemVienId();

	/**
	 * Sets the kiem dem vien ID of this ke hoach kiem dem nuoc.
	 *
	 * @param kiemDemVienId the kiem dem vien ID of this ke hoach kiem dem nuoc
	 */
	public void setKiemDemVienId(int kiemDemVienId);

	/**
	 * Returns the ngay bat dau of this ke hoach kiem dem nuoc.
	 *
	 * @return the ngay bat dau of this ke hoach kiem dem nuoc
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this ke hoach kiem dem nuoc.
	 *
	 * @param ngayBatDau the ngay bat dau of this ke hoach kiem dem nuoc
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay ket thuc of this ke hoach kiem dem nuoc.
	 *
	 * @return the ngay ket thuc of this ke hoach kiem dem nuoc
	 */
	public Date getNgayKetThuc();

	/**
	 * Sets the ngay ket thuc of this ke hoach kiem dem nuoc.
	 *
	 * @param ngayKetThuc the ngay ket thuc of this ke hoach kiem dem nuoc
	 */
	public void setNgayKetThuc(Date ngayKetThuc);

	/**
	 * Returns the mo ta of this ke hoach kiem dem nuoc.
	 *
	 * @return the mo ta of this ke hoach kiem dem nuoc
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this ke hoach kiem dem nuoc.
	 *
	 * @param moTa the mo ta of this ke hoach kiem dem nuoc
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the ngay tao of this ke hoach kiem dem nuoc.
	 *
	 * @return the ngay tao of this ke hoach kiem dem nuoc
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ke hoach kiem dem nuoc.
	 *
	 * @param ngayTao the ngay tao of this ke hoach kiem dem nuoc
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this ke hoach kiem dem nuoc.
	 *
	 * @return the id nguoi tao of this ke hoach kiem dem nuoc
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this ke hoach kiem dem nuoc.
	 *
	 * @param idNguoiTao the id nguoi tao of this ke hoach kiem dem nuoc
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the ngay xuat ban of this ke hoach kiem dem nuoc.
	 *
	 * @return the ngay xuat ban of this ke hoach kiem dem nuoc
	 */
	public Date getNgayXuatBan();

	/**
	 * Sets the ngay xuat ban of this ke hoach kiem dem nuoc.
	 *
	 * @param ngayXuatBan the ngay xuat ban of this ke hoach kiem dem nuoc
	 */
	public void setNgayXuatBan(Date ngayXuatBan);

	/**
	 * Returns the id nguoi xuat ban of this ke hoach kiem dem nuoc.
	 *
	 * @return the id nguoi xuat ban of this ke hoach kiem dem nuoc
	 */
	public int getIdNguoiXuatBan();

	/**
	 * Sets the id nguoi xuat ban of this ke hoach kiem dem nuoc.
	 *
	 * @param idNguoiXuatBan the id nguoi xuat ban of this ke hoach kiem dem nuoc
	 */
	public void setIdNguoiXuatBan(int idNguoiXuatBan);

	/**
	 * Returns the ngay dong of this ke hoach kiem dem nuoc.
	 *
	 * @return the ngay dong of this ke hoach kiem dem nuoc
	 */
	public Date getNgayDong();

	/**
	 * Sets the ngay dong of this ke hoach kiem dem nuoc.
	 *
	 * @param ngayDong the ngay dong of this ke hoach kiem dem nuoc
	 */
	public void setNgayDong(Date ngayDong);

	/**
	 * Returns the id nguoi dong of this ke hoach kiem dem nuoc.
	 *
	 * @return the id nguoi dong of this ke hoach kiem dem nuoc
	 */
	public int getIdNguoiDong();

	/**
	 * Sets the id nguoi dong of this ke hoach kiem dem nuoc.
	 *
	 * @param idNguoiDong the id nguoi dong of this ke hoach kiem dem nuoc
	 */
	public void setIdNguoiDong(int idNguoiDong);

	/**
	 * Returns the last save point of this ke hoach kiem dem nuoc.
	 *
	 * @return the last save point of this ke hoach kiem dem nuoc
	 */
	public Date getLastSavePoint();

	/**
	 * Sets the last save point of this ke hoach kiem dem nuoc.
	 *
	 * @param lastSavePoint the last save point of this ke hoach kiem dem nuoc
	 */
	public void setLastSavePoint(Date lastSavePoint);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KeHoachKiemDemNuoc keHoachKiemDemNuoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KeHoachKiemDemNuoc> toCacheModel();

	@Override
	public KeHoachKiemDemNuoc toEscapedModel();

	@Override
	public KeHoachKiemDemNuoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}