/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DanhGiaVanHanh service. Represents a row in the &quot;ME_DANHGIAVANHANH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaVanHanhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaVanHanhImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DanhGiaVanHanh
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaVanHanhImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DanhGiaVanHanhModelImpl
 * @generated
 */
public interface DanhGiaVanHanhModel extends BaseModel<DanhGiaVanHanh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh gia van hanh model instance should use the {@link DanhGiaVanHanh} interface instead.
	 */

	/**
	 * Returns the primary key of this danh gia van hanh.
	 *
	 * @return the primary key of this danh gia van hanh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh gia van hanh.
	 *
	 * @param primaryKey the primary key of this danh gia van hanh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this danh gia van hanh.
	 *
	 * @return the ID of this danh gia van hanh
	 */
	public long getId();

	/**
	 * Sets the ID of this danh gia van hanh.
	 *
	 * @param id the ID of this danh gia van hanh
	 */
	public void setId(long id);

	/**
	 * Returns the tram cap nuoc ID of this danh gia van hanh.
	 *
	 * @return the tram cap nuoc ID of this danh gia van hanh
	 */
	public int getTramCapNuocId();

	/**
	 * Sets the tram cap nuoc ID of this danh gia van hanh.
	 *
	 * @param tramCapNuocId the tram cap nuoc ID of this danh gia van hanh
	 */
	public void setTramCapNuocId(int tramCapNuocId);

	/**
	 * Returns the thang of this danh gia van hanh.
	 *
	 * @return the thang of this danh gia van hanh
	 */
	public int getThang();

	/**
	 * Sets the thang of this danh gia van hanh.
	 *
	 * @param thang the thang of this danh gia van hanh
	 */
	public void setThang(int thang);

	/**
	 * Returns the nam of this danh gia van hanh.
	 *
	 * @return the nam of this danh gia van hanh
	 */
	public int getNam();

	/**
	 * Sets the nam of this danh gia van hanh.
	 *
	 * @param nam the nam of this danh gia van hanh
	 */
	public void setNam(int nam);

	/**
	 * Returns the cong xuat thuc te of this danh gia van hanh.
	 *
	 * @return the cong xuat thuc te of this danh gia van hanh
	 */
	public int getCongXuatThucTe();

	/**
	 * Sets the cong xuat thuc te of this danh gia van hanh.
	 *
	 * @param congXuatThucTe the cong xuat thuc te of this danh gia van hanh
	 */
	public void setCongXuatThucTe(int congXuatThucTe);

	/**
	 * Returns the nuoc that thoat of this danh gia van hanh.
	 *
	 * @return the nuoc that thoat of this danh gia van hanh
	 */
	public int getNuocThatThoat();

	/**
	 * Sets the nuoc that thoat of this danh gia van hanh.
	 *
	 * @param nuocThatThoat the nuoc that thoat of this danh gia van hanh
	 */
	public void setNuocThatThoat(int nuocThatThoat);

	/**
	 * Returns the nuoc dat tieu chuan of this danh gia van hanh.
	 *
	 * @return the nuoc dat tieu chuan of this danh gia van hanh
	 */
	public int getNuocDatTieuChuan();

	/**
	 * Sets the nuoc dat tieu chuan of this danh gia van hanh.
	 *
	 * @param nuocDatTieuChuan the nuoc dat tieu chuan of this danh gia van hanh
	 */
	public void setNuocDatTieuChuan(int nuocDatTieuChuan);

	/**
	 * Returns the nuoc co asen of this danh gia van hanh.
	 *
	 * @return the nuoc co asen of this danh gia van hanh
	 */
	public int getNuocCoAsen();

	/**
	 * Sets the nuoc co asen of this danh gia van hanh.
	 *
	 * @param nuocCoAsen the nuoc co asen of this danh gia van hanh
	 */
	public void setNuocCoAsen(int nuocCoAsen);

	/**
	 * Returns the trang thai cap nuoc of this danh gia van hanh.
	 *
	 * @return the trang thai cap nuoc of this danh gia van hanh
	 */
	public int getTrangThaiCapNuoc();

	/**
	 * Sets the trang thai cap nuoc of this danh gia van hanh.
	 *
	 * @param trangThaiCapNuoc the trang thai cap nuoc of this danh gia van hanh
	 */
	public void setTrangThaiCapNuoc(int trangThaiCapNuoc);

	/**
	 * Returns the chi phi hoa chat of this danh gia van hanh.
	 *
	 * @return the chi phi hoa chat of this danh gia van hanh
	 */
	public int getChiPhiHoaChat();

	/**
	 * Sets the chi phi hoa chat of this danh gia van hanh.
	 *
	 * @param chiPhiHoaChat the chi phi hoa chat of this danh gia van hanh
	 */
	public void setChiPhiHoaChat(int chiPhiHoaChat);

	/**
	 * Returns the chi phi dien of this danh gia van hanh.
	 *
	 * @return the chi phi dien of this danh gia van hanh
	 */
	public int getChiPhiDien();

	/**
	 * Sets the chi phi dien of this danh gia van hanh.
	 *
	 * @param chiPhiDien the chi phi dien of this danh gia van hanh
	 */
	public void setChiPhiDien(int chiPhiDien);

	/**
	 * Returns the luong nhan vien of this danh gia van hanh.
	 *
	 * @return the luong nhan vien of this danh gia van hanh
	 */
	public int getLuongNhanVien();

	/**
	 * Sets the luong nhan vien of this danh gia van hanh.
	 *
	 * @param luongNhanVien the luong nhan vien of this danh gia van hanh
	 */
	public void setLuongNhanVien(int luongNhanVien);

	/**
	 * Returns the chi phi sua chua of this danh gia van hanh.
	 *
	 * @return the chi phi sua chua of this danh gia van hanh
	 */
	public int getChiPhiSuaChua();

	/**
	 * Sets the chi phi sua chua of this danh gia van hanh.
	 *
	 * @param chiPhiSuaChua the chi phi sua chua of this danh gia van hanh
	 */
	public void setChiPhiSuaChua(int chiPhiSuaChua);

	/**
	 * Returns the doanh thu of this danh gia van hanh.
	 *
	 * @return the doanh thu of this danh gia van hanh
	 */
	public int getDoanhThu();

	/**
	 * Sets the doanh thu of this danh gia van hanh.
	 *
	 * @param doanhThu the doanh thu of this danh gia van hanh
	 */
	public void setDoanhThu(int doanhThu);

	/**
	 * Returns the ngay tao of this danh gia van hanh.
	 *
	 * @return the ngay tao of this danh gia van hanh
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this danh gia van hanh.
	 *
	 * @param ngayTao the ngay tao of this danh gia van hanh
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this danh gia van hanh.
	 *
	 * @return the id nguoi tao of this danh gia van hanh
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this danh gia van hanh.
	 *
	 * @param idNguoiTao the id nguoi tao of this danh gia van hanh
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the ghi chu of this danh gia van hanh.
	 *
	 * @return the ghi chu of this danh gia van hanh
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this danh gia van hanh.
	 *
	 * @param ghiChu the ghi chu of this danh gia van hanh
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the san luong san xuat of this danh gia van hanh.
	 *
	 * @return the san luong san xuat of this danh gia van hanh
	 */
	public int getSanLuongSanXuat();

	/**
	 * Sets the san luong san xuat of this danh gia van hanh.
	 *
	 * @param sanLuongSanXuat the san luong san xuat of this danh gia van hanh
	 */
	public void setSanLuongSanXuat(int sanLuongSanXuat);

	/**
	 * Returns the san luong tieu hao of this danh gia van hanh.
	 *
	 * @return the san luong tieu hao of this danh gia van hanh
	 */
	public int getSanLuongTieuHao();

	/**
	 * Sets the san luong tieu hao of this danh gia van hanh.
	 *
	 * @param sanLuongTieuHao the san luong tieu hao of this danh gia van hanh
	 */
	public void setSanLuongTieuHao(int sanLuongTieuHao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DanhGiaVanHanh danhGiaVanHanh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DanhGiaVanHanh> toCacheModel();

	@Override
	public DanhGiaVanHanh toEscapedModel();

	@Override
	public DanhGiaVanHanh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}