/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.danhgiavesinh.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA;
import vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXAModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DANHGIAVESINHXA service. Represents a row in the &quot;ME_DANHGIAVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXAModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DANHGIAVESINHXAImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DANHGIAVESINHXAImpl
 * @see vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA
 * @see vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXAModel
 * @generated
 */
public class DANHGIAVESINHXAModelImpl extends BaseModelImpl<DANHGIAVESINHXA>
	implements DANHGIAVESINHXAModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a d a n h g i a v e s i n h x a model instance should use the {@link vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA} interface instead.
	 */
	public static final String TABLE_NAME = "ME_DANHGIAVESINHXA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MAXA", Types.VARCHAR },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "NAM", Types.INTEGER },
			{ "SODAN", Types.INTEGER },
			{ "TILEHGDCONHATIEU", Types.INTEGER },
			{ "TILEHGDCONHATIEUHVS", Types.INTEGER },
			{ "TILETRUONGHOCHVS", Types.INTEGER },
			{ "TILETRAMYTEHVS", Types.INTEGER },
			{ "KETLUANVSTX", Types.INTEGER },
			{ "GHICHU", Types.BIGINT },
			{ "BAOCAODLI", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_DANHGIAVESINHXA (ID LONG not null primary key,MAXA VARCHAR(75) null,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,NAM INTEGER,SODAN INTEGER,TILEHGDCONHATIEU INTEGER,TILEHGDCONHATIEUHVS INTEGER,TILETRUONGHOCHVS INTEGER,TILETRAMYTEHVS INTEGER,KETLUANVSTX INTEGER,GHICHU LONG,BAOCAODLI INTEGER,NGAYTAO DATE null,IDNGUOITAO LONG)";
	public static final String TABLE_SQL_DROP = "drop table ME_DANHGIAVESINHXA";
	public static final String ORDER_BY_JPQL = " ORDER BY danhgiavesinhxa.nam ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_DANHGIAVESINHXA.NAM ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA"));

	public DANHGIAVESINHXAModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DANHGIAVESINHXA.class;
	}

	@Override
	public String getModelClassName() {
		return DANHGIAVESINHXA.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maXa", getMaXa());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("nam", getNam());
		attributes.put("soDan", getSoDan());
		attributes.put("tiLeHGDCoNhaTieu", getTiLeHGDCoNhaTieu());
		attributes.put("tiLeHGDCoNhaTieuHVS", getTiLeHGDCoNhaTieuHVS());
		attributes.put("tiLeTruongHocHVS", getTiLeTruongHocHVS());
		attributes.put("tiLeTramYTeHVS", getTiLeTramYTeHVS());
		attributes.put("ketLuanVSTX", getKetLuanVSTX());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("baoCaoDLI", getBaoCaoDLI());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Integer soDan = (Integer)attributes.get("soDan");

		if (soDan != null) {
			setSoDan(soDan);
		}

		Integer tiLeHGDCoNhaTieu = (Integer)attributes.get("tiLeHGDCoNhaTieu");

		if (tiLeHGDCoNhaTieu != null) {
			setTiLeHGDCoNhaTieu(tiLeHGDCoNhaTieu);
		}

		Integer tiLeHGDCoNhaTieuHVS = (Integer)attributes.get(
				"tiLeHGDCoNhaTieuHVS");

		if (tiLeHGDCoNhaTieuHVS != null) {
			setTiLeHGDCoNhaTieuHVS(tiLeHGDCoNhaTieuHVS);
		}

		Integer tiLeTruongHocHVS = (Integer)attributes.get("tiLeTruongHocHVS");

		if (tiLeTruongHocHVS != null) {
			setTiLeTruongHocHVS(tiLeTruongHocHVS);
		}

		Integer tiLeTramYTeHVS = (Integer)attributes.get("tiLeTramYTeHVS");

		if (tiLeTramYTeHVS != null) {
			setTiLeTramYTeHVS(tiLeTramYTeHVS);
		}

		Integer ketLuanVSTX = (Integer)attributes.get("ketLuanVSTX");

		if (ketLuanVSTX != null) {
			setKetLuanVSTX(ketLuanVSTX);
		}

		Long ghiChu = (Long)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer baoCaoDLI = (Integer)attributes.get("baoCaoDLI");

		if (baoCaoDLI != null) {
			setBaoCaoDLI(baoCaoDLI);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Long idNguoiTao = (Long)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_maTinh = maTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_nam = nam;
	}

	@Override
	public int getSoDan() {
		return _soDan;
	}

	@Override
	public void setSoDan(int soDan) {
		_soDan = soDan;
	}

	@Override
	public int getTiLeHGDCoNhaTieu() {
		return _tiLeHGDCoNhaTieu;
	}

	@Override
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu) {
		_tiLeHGDCoNhaTieu = tiLeHGDCoNhaTieu;
	}

	@Override
	public int getTiLeHGDCoNhaTieuHVS() {
		return _tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS) {
		_tiLeHGDCoNhaTieuHVS = tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public int getTiLeTruongHocHVS() {
		return _tiLeTruongHocHVS;
	}

	@Override
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS) {
		_tiLeTruongHocHVS = tiLeTruongHocHVS;
	}

	@Override
	public int getTiLeTramYTeHVS() {
		return _tiLeTramYTeHVS;
	}

	@Override
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS) {
		_tiLeTramYTeHVS = tiLeTramYTeHVS;
	}

	@Override
	public int getKetLuanVSTX() {
		return _ketLuanVSTX;
	}

	@Override
	public void setKetLuanVSTX(int ketLuanVSTX) {
		_ketLuanVSTX = ketLuanVSTX;
	}

	@Override
	public long getGhiChu() {
		return _ghiChu;
	}

	@Override
	public void setGhiChu(long ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getBaoCaoDLI() {
		return _baoCaoDLI;
	}

	@Override
	public void setBaoCaoDLI(int baoCaoDLI) {
		_baoCaoDLI = baoCaoDLI;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public long getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(long idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DANHGIAVESINHXA.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DANHGIAVESINHXA toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DANHGIAVESINHXA)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DANHGIAVESINHXAImpl danhgiavesinhxaImpl = new DANHGIAVESINHXAImpl();

		danhgiavesinhxaImpl.setId(getId());
		danhgiavesinhxaImpl.setMaXa(getMaXa());
		danhgiavesinhxaImpl.setMaTinh(getMaTinh());
		danhgiavesinhxaImpl.setMaHuyen(getMaHuyen());
		danhgiavesinhxaImpl.setNam(getNam());
		danhgiavesinhxaImpl.setSoDan(getSoDan());
		danhgiavesinhxaImpl.setTiLeHGDCoNhaTieu(getTiLeHGDCoNhaTieu());
		danhgiavesinhxaImpl.setTiLeHGDCoNhaTieuHVS(getTiLeHGDCoNhaTieuHVS());
		danhgiavesinhxaImpl.setTiLeTruongHocHVS(getTiLeTruongHocHVS());
		danhgiavesinhxaImpl.setTiLeTramYTeHVS(getTiLeTramYTeHVS());
		danhgiavesinhxaImpl.setKetLuanVSTX(getKetLuanVSTX());
		danhgiavesinhxaImpl.setGhiChu(getGhiChu());
		danhgiavesinhxaImpl.setBaoCaoDLI(getBaoCaoDLI());
		danhgiavesinhxaImpl.setNgayTao(getNgayTao());
		danhgiavesinhxaImpl.setIdNguoiTao(getIdNguoiTao());

		danhgiavesinhxaImpl.resetOriginalValues();

		return danhgiavesinhxaImpl;
	}

	@Override
	public int compareTo(DANHGIAVESINHXA danhgiavesinhxa) {
		int value = 0;

		if (getNam() < danhgiavesinhxa.getNam()) {
			value = -1;
		}
		else if (getNam() > danhgiavesinhxa.getNam()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DANHGIAVESINHXA)) {
			return false;
		}

		DANHGIAVESINHXA danhgiavesinhxa = (DANHGIAVESINHXA)obj;

		long primaryKey = danhgiavesinhxa.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DANHGIAVESINHXA> toCacheModel() {
		DANHGIAVESINHXACacheModel danhgiavesinhxaCacheModel = new DANHGIAVESINHXACacheModel();

		danhgiavesinhxaCacheModel.id = getId();

		danhgiavesinhxaCacheModel.maXa = getMaXa();

		String maXa = danhgiavesinhxaCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			danhgiavesinhxaCacheModel.maXa = null;
		}

		danhgiavesinhxaCacheModel.maTinh = getMaTinh();

		String maTinh = danhgiavesinhxaCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			danhgiavesinhxaCacheModel.maTinh = null;
		}

		danhgiavesinhxaCacheModel.maHuyen = getMaHuyen();

		String maHuyen = danhgiavesinhxaCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			danhgiavesinhxaCacheModel.maHuyen = null;
		}

		danhgiavesinhxaCacheModel.nam = getNam();

		danhgiavesinhxaCacheModel.soDan = getSoDan();

		danhgiavesinhxaCacheModel.tiLeHGDCoNhaTieu = getTiLeHGDCoNhaTieu();

		danhgiavesinhxaCacheModel.tiLeHGDCoNhaTieuHVS = getTiLeHGDCoNhaTieuHVS();

		danhgiavesinhxaCacheModel.tiLeTruongHocHVS = getTiLeTruongHocHVS();

		danhgiavesinhxaCacheModel.tiLeTramYTeHVS = getTiLeTramYTeHVS();

		danhgiavesinhxaCacheModel.ketLuanVSTX = getKetLuanVSTX();

		danhgiavesinhxaCacheModel.ghiChu = getGhiChu();

		danhgiavesinhxaCacheModel.baoCaoDLI = getBaoCaoDLI();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhgiavesinhxaCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhgiavesinhxaCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danhgiavesinhxaCacheModel.idNguoiTao = getIdNguoiTao();

		return danhgiavesinhxaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", soDan=");
		sb.append(getSoDan());
		sb.append(", tiLeHGDCoNhaTieu=");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append(", tiLeHGDCoNhaTieuHVS=");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append(", tiLeTruongHocHVS=");
		sb.append(getTiLeTruongHocHVS());
		sb.append(", tiLeTramYTeHVS=");
		sb.append(getTiLeTramYTeHVS());
		sb.append(", ketLuanVSTX=");
		sb.append(getKetLuanVSTX());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", baoCaoDLI=");
		sb.append(getBaoCaoDLI());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.danhgiavesinh.dao.model.DANHGIAVESINHXA");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDan</column-name><column-value><![CDATA[");
		sb.append(getSoDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTruongHocHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTruongHocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTramYTeHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTramYTeHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketLuanVSTX</column-name><column-value><![CDATA[");
		sb.append(getKetLuanVSTX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>baoCaoDLI</column-name><column-value><![CDATA[");
		sb.append(getBaoCaoDLI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DANHGIAVESINHXA.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DANHGIAVESINHXA.class
		};
	private long _id;
	private String _maXa;
	private String _maTinh;
	private String _maHuyen;
	private int _nam;
	private int _soDan;
	private int _tiLeHGDCoNhaTieu;
	private int _tiLeHGDCoNhaTieuHVS;
	private int _tiLeTruongHocHVS;
	private int _tiLeTramYTeHVS;
	private int _ketLuanVSTX;
	private long _ghiChu;
	private int _baoCaoDLI;
	private Date _ngayTao;
	private long _idNguoiTao;
	private DANHGIAVESINHXA _escapedModel;
}