/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DauNoiNuoc service. Represents a row in the &quot;ME_DAUNOINUOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DauNoiNuocModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.tramcap.dao.model.impl.DauNoiNuocImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DauNoiNuoc
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DauNoiNuocImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.impl.DauNoiNuocModelImpl
 * @generated
 */
public interface DauNoiNuocModel extends BaseModel<DauNoiNuoc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dau noi nuoc model instance should use the {@link DauNoiNuoc} interface instead.
	 */

	/**
	 * Returns the primary key of this dau noi nuoc.
	 *
	 * @return the primary key of this dau noi nuoc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dau noi nuoc.
	 *
	 * @param primaryKey the primary key of this dau noi nuoc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dau noi nuoc.
	 *
	 * @return the ID of this dau noi nuoc
	 */
	public long getId();

	/**
	 * Sets the ID of this dau noi nuoc.
	 *
	 * @param id the ID of this dau noi nuoc
	 */
	public void setId(long id);

	/**
	 * Returns the tram cap nuoc ID of this dau noi nuoc.
	 *
	 * @return the tram cap nuoc ID of this dau noi nuoc
	 */
	public int getTramCapNuocId();

	/**
	 * Sets the tram cap nuoc ID of this dau noi nuoc.
	 *
	 * @param tramCapNuocId the tram cap nuoc ID of this dau noi nuoc
	 */
	public void setTramCapNuocId(int tramCapNuocId);

	/**
	 * Returns the ma tinh of this dau noi nuoc.
	 *
	 * @return the ma tinh of this dau noi nuoc
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this dau noi nuoc.
	 *
	 * @param maTinh the ma tinh of this dau noi nuoc
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this dau noi nuoc.
	 *
	 * @return the ma huyen of this dau noi nuoc
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this dau noi nuoc.
	 *
	 * @param maHuyen the ma huyen of this dau noi nuoc
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this dau noi nuoc.
	 *
	 * @return the ma xa of this dau noi nuoc
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this dau noi nuoc.
	 *
	 * @param maXa the ma xa of this dau noi nuoc
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the thon xom of this dau noi nuoc.
	 *
	 * @return the thon xom of this dau noi nuoc
	 */
	@AutoEscape
	public String getThonXom();

	/**
	 * Sets the thon xom of this dau noi nuoc.
	 *
	 * @param thonXom the thon xom of this dau noi nuoc
	 */
	public void setThonXom(String thonXom);

	/**
	 * Returns the ten chu ho of this dau noi nuoc.
	 *
	 * @return the ten chu ho of this dau noi nuoc
	 */
	@AutoEscape
	public String getTenChuHo();

	/**
	 * Sets the ten chu ho of this dau noi nuoc.
	 *
	 * @param tenChuHo the ten chu ho of this dau noi nuoc
	 */
	public void setTenChuHo(String tenChuHo);

	/**
	 * Returns the gioi tinh of this dau noi nuoc.
	 *
	 * @return the gioi tinh of this dau noi nuoc
	 */
	public int getGioiTinh();

	/**
	 * Sets the gioi tinh of this dau noi nuoc.
	 *
	 * @param gioiTinh the gioi tinh of this dau noi nuoc
	 */
	public void setGioiTinh(int gioiTinh);

	/**
	 * Returns the ngay dau noi hop dong of this dau noi nuoc.
	 *
	 * @return the ngay dau noi hop dong of this dau noi nuoc
	 */
	public Date getNgayDauNoiHopDong();

	/**
	 * Sets the ngay dau noi hop dong of this dau noi nuoc.
	 *
	 * @param ngayDauNoiHopDong the ngay dau noi hop dong of this dau noi nuoc
	 */
	public void setNgayDauNoiHopDong(Date ngayDauNoiHopDong);

	/**
	 * Returns the trang thai of this dau noi nuoc.
	 *
	 * @return the trang thai of this dau noi nuoc
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this dau noi nuoc.
	 *
	 * @param trangThai the trang thai of this dau noi nuoc
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the nam bao cao of this dau noi nuoc.
	 *
	 * @return the nam bao cao of this dau noi nuoc
	 */
	public int getNamBaoCao();

	/**
	 * Sets the nam bao cao of this dau noi nuoc.
	 *
	 * @param namBaoCao the nam bao cao of this dau noi nuoc
	 */
	public void setNamBaoCao(int namBaoCao);

	/**
	 * Returns the ghi chu of this dau noi nuoc.
	 *
	 * @return the ghi chu of this dau noi nuoc
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this dau noi nuoc.
	 *
	 * @param ghiChu the ghi chu of this dau noi nuoc
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the ngay tao of this dau noi nuoc.
	 *
	 * @return the ngay tao of this dau noi nuoc
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this dau noi nuoc.
	 *
	 * @param ngayTao the ngay tao of this dau noi nuoc
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this dau noi nuoc.
	 *
	 * @return the id nguoi tao of this dau noi nuoc
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this dau noi nuoc.
	 *
	 * @param idNguoiTao the id nguoi tao of this dau noi nuoc
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the so nguoi trong ho of this dau noi nuoc.
	 *
	 * @return the so nguoi trong ho of this dau noi nuoc
	 */
	public int getSoNguoiTrongHo();

	/**
	 * Sets the so nguoi trong ho of this dau noi nuoc.
	 *
	 * @param soNguoiTrongHo the so nguoi trong ho of this dau noi nuoc
	 */
	public void setSoNguoiTrongHo(int soNguoiTrongHo);

	/**
	 * Returns the thanh phan ho gia dinh of this dau noi nuoc.
	 *
	 * @return the thanh phan ho gia dinh of this dau noi nuoc
	 */
	public int getThanhPhanHoGiaDinh();

	/**
	 * Sets the thanh phan ho gia dinh of this dau noi nuoc.
	 *
	 * @param thanhPhanHoGiaDinh the thanh phan ho gia dinh of this dau noi nuoc
	 */
	public void setThanhPhanHoGiaDinh(int thanhPhanHoGiaDinh);

	/**
	 * Returns the tong doanh thu of this dau noi nuoc.
	 *
	 * @return the tong doanh thu of this dau noi nuoc
	 */
	public int getTongDoanhThu();

	/**
	 * Sets the tong doanh thu of this dau noi nuoc.
	 *
	 * @param tongDoanhThu the tong doanh thu of this dau noi nuoc
	 */
	public void setTongDoanhThu(int tongDoanhThu);

	/**
	 * Returns the kinh do of this dau noi nuoc.
	 *
	 * @return the kinh do of this dau noi nuoc
	 */
	@AutoEscape
	public String getKinhDo();

	/**
	 * Sets the kinh do of this dau noi nuoc.
	 *
	 * @param kinhDo the kinh do of this dau noi nuoc
	 */
	public void setKinhDo(String kinhDo);

	/**
	 * Returns the vi do of this dau noi nuoc.
	 *
	 * @return the vi do of this dau noi nuoc
	 */
	@AutoEscape
	public String getViDo();

	/**
	 * Sets the vi do of this dau noi nuoc.
	 *
	 * @param viDo the vi do of this dau noi nuoc
	 */
	public void setViDo(String viDo);

	/**
	 * Returns the ngay dau noi thuc te of this dau noi nuoc.
	 *
	 * @return the ngay dau noi thuc te of this dau noi nuoc
	 */
	public Date getNgayDauNoiThucTe();

	/**
	 * Sets the ngay dau noi thuc te of this dau noi nuoc.
	 *
	 * @param ngayDauNoiThucTe the ngay dau noi thuc te of this dau noi nuoc
	 */
	public void setNgayDauNoiThucTe(Date ngayDauNoiThucTe);

	/**
	 * Returns the so sery dong ho of this dau noi nuoc.
	 *
	 * @return the so sery dong ho of this dau noi nuoc
	 */
	@AutoEscape
	public String getSoSeryDongHo();

	/**
	 * Sets the so sery dong ho of this dau noi nuoc.
	 *
	 * @param soSeryDongHo the so sery dong ho of this dau noi nuoc
	 */
	public void setSoSeryDongHo(String soSeryDongHo);

	/**
	 * Returns the danh gia nuoc h v s of this dau noi nuoc.
	 *
	 * @return the danh gia nuoc h v s of this dau noi nuoc
	 */
	@AutoEscape
	public String getDanhGiaNuocHVS();

	/**
	 * Sets the danh gia nuoc h v s of this dau noi nuoc.
	 *
	 * @param danhGiaNuocHVS the danh gia nuoc h v s of this dau noi nuoc
	 */
	public void setDanhGiaNuocHVS(String danhGiaNuocHVS);

	/**
	 * Returns the ngay kiem dem of this dau noi nuoc.
	 *
	 * @return the ngay kiem dem of this dau noi nuoc
	 */
	public Date getNgayKiemDem();

	/**
	 * Sets the ngay kiem dem of this dau noi nuoc.
	 *
	 * @param ngayKiemDem the ngay kiem dem of this dau noi nuoc
	 */
	public void setNgayKiemDem(Date ngayKiemDem);

	/**
	 * Returns the ngay danh gia of this dau noi nuoc.
	 *
	 * @return the ngay danh gia of this dau noi nuoc
	 */
	public Date getNgayDanhGia();

	/**
	 * Sets the ngay danh gia of this dau noi nuoc.
	 *
	 * @param ngayDanhGia the ngay danh gia of this dau noi nuoc
	 */
	public void setNgayDanhGia(Date ngayDanhGia);

	/**
	 * Returns the id nguoi danh gia of this dau noi nuoc.
	 *
	 * @return the id nguoi danh gia of this dau noi nuoc
	 */
	public int getIdNguoiDanhGia();

	/**
	 * Sets the id nguoi danh gia of this dau noi nuoc.
	 *
	 * @param idNguoiDanhGia the id nguoi danh gia of this dau noi nuoc
	 */
	public void setIdNguoiDanhGia(int idNguoiDanhGia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DauNoiNuoc dauNoiNuoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DauNoiNuoc> toCacheModel();

	@Override
	public DauNoiNuoc toEscapedModel();

	@Override
	public DauNoiNuoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}