/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.danhgiavesinh.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DANHGIAVESINHXA service. Represents a row in the &quot;ME_DANHGIAVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.danhgiavesinh.dao.model.impl.DANHGIAVESINHXAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.danhgiavesinh.dao.model.impl.DANHGIAVESINHXAImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DANHGIAVESINHXA
 * @see vn.dtt.sol.ns.danhgiavesinh.dao.model.impl.DANHGIAVESINHXAImpl
 * @see vn.dtt.sol.ns.danhgiavesinh.dao.model.impl.DANHGIAVESINHXAModelImpl
 * @generated
 */
public interface DANHGIAVESINHXAModel extends BaseModel<DANHGIAVESINHXA> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d a n h g i a v e s i n h x a model instance should use the {@link DANHGIAVESINHXA} interface instead.
	 */

	/**
	 * Returns the primary key of this d a n h g i a v e s i n h x a.
	 *
	 * @return the primary key of this d a n h g i a v e s i n h x a
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d a n h g i a v e s i n h x a.
	 *
	 * @param primaryKey the primary key of this d a n h g i a v e s i n h x a
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ID of this d a n h g i a v e s i n h x a
	 */
	public long getId();

	/**
	 * Sets the ID of this d a n h g i a v e s i n h x a.
	 *
	 * @param id the ID of this d a n h g i a v e s i n h x a
	 */
	public void setId(long id);

	/**
	 * Returns the ma xa of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ma xa of this d a n h g i a v e s i n h x a
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this d a n h g i a v e s i n h x a.
	 *
	 * @param maXa the ma xa of this d a n h g i a v e s i n h x a
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the ma tinh of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ma tinh of this d a n h g i a v e s i n h x a
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this d a n h g i a v e s i n h x a.
	 *
	 * @param maTinh the ma tinh of this d a n h g i a v e s i n h x a
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ma huyen of this d a n h g i a v e s i n h x a
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this d a n h g i a v e s i n h x a.
	 *
	 * @param maHuyen the ma huyen of this d a n h g i a v e s i n h x a
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the nam of this d a n h g i a v e s i n h x a.
	 *
	 * @return the nam of this d a n h g i a v e s i n h x a
	 */
	public int getNam();

	/**
	 * Sets the nam of this d a n h g i a v e s i n h x a.
	 *
	 * @param nam the nam of this d a n h g i a v e s i n h x a
	 */
	public void setNam(int nam);

	/**
	 * Returns the so dan of this d a n h g i a v e s i n h x a.
	 *
	 * @return the so dan of this d a n h g i a v e s i n h x a
	 */
	public int getSoDan();

	/**
	 * Sets the so dan of this d a n h g i a v e s i n h x a.
	 *
	 * @param soDan the so dan of this d a n h g i a v e s i n h x a
	 */
	public void setSoDan(int soDan);

	/**
	 * Returns the ti le h g d co nha tieu of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ti le h g d co nha tieu of this d a n h g i a v e s i n h x a
	 */
	public int getTiLeHGDCoNhaTieu();

	/**
	 * Sets the ti le h g d co nha tieu of this d a n h g i a v e s i n h x a.
	 *
	 * @param tiLeHGDCoNhaTieu the ti le h g d co nha tieu of this d a n h g i a v e s i n h x a
	 */
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu);

	/**
	 * Returns the ti le h g d co nha tieu h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ti le h g d co nha tieu h v s of this d a n h g i a v e s i n h x a
	 */
	public int getTiLeHGDCoNhaTieuHVS();

	/**
	 * Sets the ti le h g d co nha tieu h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @param tiLeHGDCoNhaTieuHVS the ti le h g d co nha tieu h v s of this d a n h g i a v e s i n h x a
	 */
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS);

	/**
	 * Returns the ti le truong hoc h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ti le truong hoc h v s of this d a n h g i a v e s i n h x a
	 */
	public int getTiLeTruongHocHVS();

	/**
	 * Sets the ti le truong hoc h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @param tiLeTruongHocHVS the ti le truong hoc h v s of this d a n h g i a v e s i n h x a
	 */
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS);

	/**
	 * Returns the ti le tram y te h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ti le tram y te h v s of this d a n h g i a v e s i n h x a
	 */
	public int getTiLeTramYTeHVS();

	/**
	 * Sets the ti le tram y te h v s of this d a n h g i a v e s i n h x a.
	 *
	 * @param tiLeTramYTeHVS the ti le tram y te h v s of this d a n h g i a v e s i n h x a
	 */
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS);

	/**
	 * Returns the ket luan v s t x of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ket luan v s t x of this d a n h g i a v e s i n h x a
	 */
	public int getKetLuanVSTX();

	/**
	 * Sets the ket luan v s t x of this d a n h g i a v e s i n h x a.
	 *
	 * @param ketLuanVSTX the ket luan v s t x of this d a n h g i a v e s i n h x a
	 */
	public void setKetLuanVSTX(int ketLuanVSTX);

	/**
	 * Returns the ghi chu of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ghi chu of this d a n h g i a v e s i n h x a
	 */
	public long getGhiChu();

	/**
	 * Sets the ghi chu of this d a n h g i a v e s i n h x a.
	 *
	 * @param ghiChu the ghi chu of this d a n h g i a v e s i n h x a
	 */
	public void setGhiChu(long ghiChu);

	/**
	 * Returns the bao cao d l i of this d a n h g i a v e s i n h x a.
	 *
	 * @return the bao cao d l i of this d a n h g i a v e s i n h x a
	 */
	public int getBaoCaoDLI();

	/**
	 * Sets the bao cao d l i of this d a n h g i a v e s i n h x a.
	 *
	 * @param baoCaoDLI the bao cao d l i of this d a n h g i a v e s i n h x a
	 */
	public void setBaoCaoDLI(int baoCaoDLI);

	/**
	 * Returns the ngay tao of this d a n h g i a v e s i n h x a.
	 *
	 * @return the ngay tao of this d a n h g i a v e s i n h x a
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this d a n h g i a v e s i n h x a.
	 *
	 * @param ngayTao the ngay tao of this d a n h g i a v e s i n h x a
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this d a n h g i a v e s i n h x a.
	 *
	 * @return the id nguoi tao of this d a n h g i a v e s i n h x a
	 */
	public long getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this d a n h g i a v e s i n h x a.
	 *
	 * @param idNguoiTao the id nguoi tao of this d a n h g i a v e s i n h x a
	 */
	public void setIdNguoiTao(long idNguoiTao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DANHGIAVESINHXA danhgiavesinhxa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DANHGIAVESINHXA> toCacheModel();

	@Override
	public DANHGIAVESINHXA toEscapedModel();

	@Override
	public DANHGIAVESINHXA toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}