/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh;
import vn.dtt.sol.ns.vesinhmoitruong.dao.service.ChiTietKiemDemCongTrinhLocalServiceUtil;

/**
 * The extended model base implementation for the ChiTietKiemDemCongTrinh service. Represents a row in the &quot;ME_CHITIETKIEMDEMCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiTietKiemDemCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ChiTietKiemDemCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh
 * @generated
 */
public abstract class ChiTietKiemDemCongTrinhBaseImpl
	extends ChiTietKiemDemCongTrinhModelImpl implements ChiTietKiemDemCongTrinh {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chi tiet kiem dem cong trinh model instance should use the {@link ChiTietKiemDemCongTrinh} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ChiTietKiemDemCongTrinhLocalServiceUtil.addChiTietKiemDemCongTrinh(this);
		}
		else {
			ChiTietKiemDemCongTrinhLocalServiceUtil.updateChiTietKiemDemCongTrinh(this);
		}
	}
}