/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DanhGiaVeSinhXaNew service. Represents a row in the &quot;ME_DANHGIAVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhGiaVeSinhXaNewImpl}.
 * </p>
 *
 * @author BinhTH
 * @see DanhGiaVeSinhXaNewImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewModel
 * @generated
 */
public class DanhGiaVeSinhXaNewModelImpl extends BaseModelImpl<DanhGiaVeSinhXaNew>
	implements DanhGiaVeSinhXaNewModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh gia ve sinh xa new model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew} interface instead.
	 */
	public static final String TABLE_NAME = "ME_DANHGIAVESINHXA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "NAM", Types.INTEGER },
			{ "SODAN", Types.INTEGER },
			{ "TONGSOHGD", Types.INTEGER },
			{ "SOHGDCONHATIEU", Types.INTEGER },
			{ "SOHGDCONHATIEUHVS", Types.INTEGER },
			{ "SONHATIEUHVSXAYMOI", Types.INTEGER },
			{ "TILEHGDCONHATIEU", Types.INTEGER },
			{ "TILEHGDCONHATIEUHVS", Types.INTEGER },
			{ "TONGSOTRUONGHOC", Types.INTEGER },
			{ "SOTRUONGHOCHVS", Types.INTEGER },
			{ "TONGSOTRAMYTE", Types.INTEGER },
			{ "SOTRAMYTEHVS", Types.INTEGER },
			{ "TILETRUONGHOCHVS", Types.INTEGER },
			{ "TILETRAMYTEHVS", Types.INTEGER },
			{ "KETLUANVSTX", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "BAOCAODLI", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_DANHGIAVESINHXA (ID INTEGER not null primary key,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,NAM INTEGER,SODAN INTEGER,TONGSOHGD INTEGER,SOHGDCONHATIEU INTEGER,SOHGDCONHATIEUHVS INTEGER,SONHATIEUHVSXAYMOI INTEGER,TILEHGDCONHATIEU INTEGER,TILEHGDCONHATIEUHVS INTEGER,TONGSOTRUONGHOC INTEGER,SOTRUONGHOCHVS INTEGER,TONGSOTRAMYTE INTEGER,SOTRAMYTEHVS INTEGER,TILETRUONGHOCHVS INTEGER,TILETRAMYTEHVS INTEGER,KETLUANVSTX INTEGER,GHICHU VARCHAR(75) null,BAOCAODLI INTEGER,NGAYTAO DATE null,IDNGUOITAO INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ME_DANHGIAVESINHXA";
	public static final String ORDER_BY_JPQL = " ORDER BY danhGiaVeSinhXaNew.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_DANHGIAVESINHXA.ID ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew"),
			true);
	public static long MAHUYEN_COLUMN_BITMASK = 1L;
	public static long MATINH_COLUMN_BITMASK = 2L;
	public static long NAM_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew"));

	public DanhGiaVeSinhXaNewModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DanhGiaVeSinhXaNew.class;
	}

	@Override
	public String getModelClassName() {
		return DanhGiaVeSinhXaNew.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("nam", getNam());
		attributes.put("soDan", getSoDan());
		attributes.put("tongSoHGD", getTongSoHGD());
		attributes.put("soHGDCoNhaTieu", getSoHGDCoNhaTieu());
		attributes.put("soHGDCoNhaTieuHVS", getSoHGDCoNhaTieuHVS());
		attributes.put("soNhaTieuHVSXayMoi", getSoNhaTieuHVSXayMoi());
		attributes.put("tiLeHGDCoNhaTieu", getTiLeHGDCoNhaTieu());
		attributes.put("tiLeHGDCoNhaTieuHVS", getTiLeHGDCoNhaTieuHVS());
		attributes.put("tongSoTruongHoc", getTongSoTruongHoc());
		attributes.put("soTruongHocHVS", getSoTruongHocHVS());
		attributes.put("tongSoTramYTe", getTongSoTramYTe());
		attributes.put("soTramYTeHVS", getSoTramYTeHVS());
		attributes.put("tiLeTruongHocHVS", getTiLeTruongHocHVS());
		attributes.put("tiLeTramYTeHVS", getTiLeTramYTeHVS());
		attributes.put("ketLuanVSTX", getKetLuanVSTX());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("baoCaoDLI", getBaoCaoDLI());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Integer soDan = (Integer)attributes.get("soDan");

		if (soDan != null) {
			setSoDan(soDan);
		}

		Integer tongSoHGD = (Integer)attributes.get("tongSoHGD");

		if (tongSoHGD != null) {
			setTongSoHGD(tongSoHGD);
		}

		Integer soHGDCoNhaTieu = (Integer)attributes.get("soHGDCoNhaTieu");

		if (soHGDCoNhaTieu != null) {
			setSoHGDCoNhaTieu(soHGDCoNhaTieu);
		}

		Integer soHGDCoNhaTieuHVS = (Integer)attributes.get("soHGDCoNhaTieuHVS");

		if (soHGDCoNhaTieuHVS != null) {
			setSoHGDCoNhaTieuHVS(soHGDCoNhaTieuHVS);
		}

		Integer soNhaTieuHVSXayMoi = (Integer)attributes.get(
				"soNhaTieuHVSXayMoi");

		if (soNhaTieuHVSXayMoi != null) {
			setSoNhaTieuHVSXayMoi(soNhaTieuHVSXayMoi);
		}

		Integer tiLeHGDCoNhaTieu = (Integer)attributes.get("tiLeHGDCoNhaTieu");

		if (tiLeHGDCoNhaTieu != null) {
			setTiLeHGDCoNhaTieu(tiLeHGDCoNhaTieu);
		}

		Integer tiLeHGDCoNhaTieuHVS = (Integer)attributes.get(
				"tiLeHGDCoNhaTieuHVS");

		if (tiLeHGDCoNhaTieuHVS != null) {
			setTiLeHGDCoNhaTieuHVS(tiLeHGDCoNhaTieuHVS);
		}

		Integer tongSoTruongHoc = (Integer)attributes.get("tongSoTruongHoc");

		if (tongSoTruongHoc != null) {
			setTongSoTruongHoc(tongSoTruongHoc);
		}

		Integer soTruongHocHVS = (Integer)attributes.get("soTruongHocHVS");

		if (soTruongHocHVS != null) {
			setSoTruongHocHVS(soTruongHocHVS);
		}

		Integer tongSoTramYTe = (Integer)attributes.get("tongSoTramYTe");

		if (tongSoTramYTe != null) {
			setTongSoTramYTe(tongSoTramYTe);
		}

		Integer soTramYTeHVS = (Integer)attributes.get("soTramYTeHVS");

		if (soTramYTeHVS != null) {
			setSoTramYTeHVS(soTramYTeHVS);
		}

		Integer tiLeTruongHocHVS = (Integer)attributes.get("tiLeTruongHocHVS");

		if (tiLeTruongHocHVS != null) {
			setTiLeTruongHocHVS(tiLeTruongHocHVS);
		}

		Integer tiLeTramYTeHVS = (Integer)attributes.get("tiLeTramYTeHVS");

		if (tiLeTramYTeHVS != null) {
			setTiLeTramYTeHVS(tiLeTramYTeHVS);
		}

		Integer ketLuanVSTX = (Integer)attributes.get("ketLuanVSTX");

		if (ketLuanVSTX != null) {
			setKetLuanVSTX(ketLuanVSTX);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer baoCaoDLI = (Integer)attributes.get("baoCaoDLI");

		if (baoCaoDLI != null) {
			setBaoCaoDLI(baoCaoDLI);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Integer idNguoiTao = (Integer)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_columnBitmask |= MATINH_COLUMN_BITMASK;

		if (_originalMaTinh == null) {
			_originalMaTinh = _maTinh;
		}

		_maTinh = maTinh;
	}

	public String getOriginalMaTinh() {
		return GetterUtil.getString(_originalMaTinh);
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_columnBitmask |= MAHUYEN_COLUMN_BITMASK;

		if (_originalMaHuyen == null) {
			_originalMaHuyen = _maHuyen;
		}

		_maHuyen = maHuyen;
	}

	public String getOriginalMaHuyen() {
		return GetterUtil.getString(_originalMaHuyen);
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_columnBitmask |= NAM_COLUMN_BITMASK;

		if (!_setOriginalNam) {
			_setOriginalNam = true;

			_originalNam = _nam;
		}

		_nam = nam;
	}

	public int getOriginalNam() {
		return _originalNam;
	}

	@Override
	public int getSoDan() {
		return _soDan;
	}

	@Override
	public void setSoDan(int soDan) {
		_soDan = soDan;
	}

	@Override
	public int getTongSoHGD() {
		return _tongSoHGD;
	}

	@Override
	public void setTongSoHGD(int tongSoHGD) {
		_tongSoHGD = tongSoHGD;
	}

	@Override
	public int getSoHGDCoNhaTieu() {
		return _soHGDCoNhaTieu;
	}

	@Override
	public void setSoHGDCoNhaTieu(int soHGDCoNhaTieu) {
		_soHGDCoNhaTieu = soHGDCoNhaTieu;
	}

	@Override
	public int getSoHGDCoNhaTieuHVS() {
		return _soHGDCoNhaTieuHVS;
	}

	@Override
	public void setSoHGDCoNhaTieuHVS(int soHGDCoNhaTieuHVS) {
		_soHGDCoNhaTieuHVS = soHGDCoNhaTieuHVS;
	}

	@Override
	public int getSoNhaTieuHVSXayMoi() {
		return _soNhaTieuHVSXayMoi;
	}

	@Override
	public void setSoNhaTieuHVSXayMoi(int soNhaTieuHVSXayMoi) {
		_soNhaTieuHVSXayMoi = soNhaTieuHVSXayMoi;
	}

	@Override
	public int getTiLeHGDCoNhaTieu() {
		return _tiLeHGDCoNhaTieu;
	}

	@Override
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu) {
		_tiLeHGDCoNhaTieu = tiLeHGDCoNhaTieu;
	}

	@Override
	public int getTiLeHGDCoNhaTieuHVS() {
		return _tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS) {
		_tiLeHGDCoNhaTieuHVS = tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public int getTongSoTruongHoc() {
		return _tongSoTruongHoc;
	}

	@Override
	public void setTongSoTruongHoc(int tongSoTruongHoc) {
		_tongSoTruongHoc = tongSoTruongHoc;
	}

	@Override
	public int getSoTruongHocHVS() {
		return _soTruongHocHVS;
	}

	@Override
	public void setSoTruongHocHVS(int soTruongHocHVS) {
		_soTruongHocHVS = soTruongHocHVS;
	}

	@Override
	public int getTongSoTramYTe() {
		return _tongSoTramYTe;
	}

	@Override
	public void setTongSoTramYTe(int tongSoTramYTe) {
		_tongSoTramYTe = tongSoTramYTe;
	}

	@Override
	public int getSoTramYTeHVS() {
		return _soTramYTeHVS;
	}

	@Override
	public void setSoTramYTeHVS(int soTramYTeHVS) {
		_soTramYTeHVS = soTramYTeHVS;
	}

	@Override
	public int getTiLeTruongHocHVS() {
		return _tiLeTruongHocHVS;
	}

	@Override
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS) {
		_tiLeTruongHocHVS = tiLeTruongHocHVS;
	}

	@Override
	public int getTiLeTramYTeHVS() {
		return _tiLeTramYTeHVS;
	}

	@Override
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS) {
		_tiLeTramYTeHVS = tiLeTramYTeHVS;
	}

	@Override
	public int getKetLuanVSTX() {
		return _ketLuanVSTX;
	}

	@Override
	public void setKetLuanVSTX(int ketLuanVSTX) {
		_ketLuanVSTX = ketLuanVSTX;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getBaoCaoDLI() {
		return _baoCaoDLI;
	}

	@Override
	public void setBaoCaoDLI(int baoCaoDLI) {
		_baoCaoDLI = baoCaoDLI;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public int getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(int idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DanhGiaVeSinhXaNew toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DanhGiaVeSinhXaNew)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DanhGiaVeSinhXaNewImpl danhGiaVeSinhXaNewImpl = new DanhGiaVeSinhXaNewImpl();

		danhGiaVeSinhXaNewImpl.setId(getId());
		danhGiaVeSinhXaNewImpl.setMaTinh(getMaTinh());
		danhGiaVeSinhXaNewImpl.setMaHuyen(getMaHuyen());
		danhGiaVeSinhXaNewImpl.setMaXa(getMaXa());
		danhGiaVeSinhXaNewImpl.setNam(getNam());
		danhGiaVeSinhXaNewImpl.setSoDan(getSoDan());
		danhGiaVeSinhXaNewImpl.setTongSoHGD(getTongSoHGD());
		danhGiaVeSinhXaNewImpl.setSoHGDCoNhaTieu(getSoHGDCoNhaTieu());
		danhGiaVeSinhXaNewImpl.setSoHGDCoNhaTieuHVS(getSoHGDCoNhaTieuHVS());
		danhGiaVeSinhXaNewImpl.setSoNhaTieuHVSXayMoi(getSoNhaTieuHVSXayMoi());
		danhGiaVeSinhXaNewImpl.setTiLeHGDCoNhaTieu(getTiLeHGDCoNhaTieu());
		danhGiaVeSinhXaNewImpl.setTiLeHGDCoNhaTieuHVS(getTiLeHGDCoNhaTieuHVS());
		danhGiaVeSinhXaNewImpl.setTongSoTruongHoc(getTongSoTruongHoc());
		danhGiaVeSinhXaNewImpl.setSoTruongHocHVS(getSoTruongHocHVS());
		danhGiaVeSinhXaNewImpl.setTongSoTramYTe(getTongSoTramYTe());
		danhGiaVeSinhXaNewImpl.setSoTramYTeHVS(getSoTramYTeHVS());
		danhGiaVeSinhXaNewImpl.setTiLeTruongHocHVS(getTiLeTruongHocHVS());
		danhGiaVeSinhXaNewImpl.setTiLeTramYTeHVS(getTiLeTramYTeHVS());
		danhGiaVeSinhXaNewImpl.setKetLuanVSTX(getKetLuanVSTX());
		danhGiaVeSinhXaNewImpl.setGhiChu(getGhiChu());
		danhGiaVeSinhXaNewImpl.setBaoCaoDLI(getBaoCaoDLI());
		danhGiaVeSinhXaNewImpl.setNgayTao(getNgayTao());
		danhGiaVeSinhXaNewImpl.setIdNguoiTao(getIdNguoiTao());

		danhGiaVeSinhXaNewImpl.resetOriginalValues();

		return danhGiaVeSinhXaNewImpl;
	}

	@Override
	public int compareTo(DanhGiaVeSinhXaNew danhGiaVeSinhXaNew) {
		int value = 0;

		if (getId() < danhGiaVeSinhXaNew.getId()) {
			value = -1;
		}
		else if (getId() > danhGiaVeSinhXaNew.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DanhGiaVeSinhXaNew)) {
			return false;
		}

		DanhGiaVeSinhXaNew danhGiaVeSinhXaNew = (DanhGiaVeSinhXaNew)obj;

		int primaryKey = danhGiaVeSinhXaNew.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhGiaVeSinhXaNewModelImpl danhGiaVeSinhXaNewModelImpl = this;

		danhGiaVeSinhXaNewModelImpl._originalMaTinh = danhGiaVeSinhXaNewModelImpl._maTinh;

		danhGiaVeSinhXaNewModelImpl._originalMaHuyen = danhGiaVeSinhXaNewModelImpl._maHuyen;

		danhGiaVeSinhXaNewModelImpl._originalNam = danhGiaVeSinhXaNewModelImpl._nam;

		danhGiaVeSinhXaNewModelImpl._setOriginalNam = false;

		danhGiaVeSinhXaNewModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhGiaVeSinhXaNew> toCacheModel() {
		DanhGiaVeSinhXaNewCacheModel danhGiaVeSinhXaNewCacheModel = new DanhGiaVeSinhXaNewCacheModel();

		danhGiaVeSinhXaNewCacheModel.id = getId();

		danhGiaVeSinhXaNewCacheModel.maTinh = getMaTinh();

		String maTinh = danhGiaVeSinhXaNewCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			danhGiaVeSinhXaNewCacheModel.maTinh = null;
		}

		danhGiaVeSinhXaNewCacheModel.maHuyen = getMaHuyen();

		String maHuyen = danhGiaVeSinhXaNewCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			danhGiaVeSinhXaNewCacheModel.maHuyen = null;
		}

		danhGiaVeSinhXaNewCacheModel.maXa = getMaXa();

		String maXa = danhGiaVeSinhXaNewCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			danhGiaVeSinhXaNewCacheModel.maXa = null;
		}

		danhGiaVeSinhXaNewCacheModel.nam = getNam();

		danhGiaVeSinhXaNewCacheModel.soDan = getSoDan();

		danhGiaVeSinhXaNewCacheModel.tongSoHGD = getTongSoHGD();

		danhGiaVeSinhXaNewCacheModel.soHGDCoNhaTieu = getSoHGDCoNhaTieu();

		danhGiaVeSinhXaNewCacheModel.soHGDCoNhaTieuHVS = getSoHGDCoNhaTieuHVS();

		danhGiaVeSinhXaNewCacheModel.soNhaTieuHVSXayMoi = getSoNhaTieuHVSXayMoi();

		danhGiaVeSinhXaNewCacheModel.tiLeHGDCoNhaTieu = getTiLeHGDCoNhaTieu();

		danhGiaVeSinhXaNewCacheModel.tiLeHGDCoNhaTieuHVS = getTiLeHGDCoNhaTieuHVS();

		danhGiaVeSinhXaNewCacheModel.tongSoTruongHoc = getTongSoTruongHoc();

		danhGiaVeSinhXaNewCacheModel.soTruongHocHVS = getSoTruongHocHVS();

		danhGiaVeSinhXaNewCacheModel.tongSoTramYTe = getTongSoTramYTe();

		danhGiaVeSinhXaNewCacheModel.soTramYTeHVS = getSoTramYTeHVS();

		danhGiaVeSinhXaNewCacheModel.tiLeTruongHocHVS = getTiLeTruongHocHVS();

		danhGiaVeSinhXaNewCacheModel.tiLeTramYTeHVS = getTiLeTramYTeHVS();

		danhGiaVeSinhXaNewCacheModel.ketLuanVSTX = getKetLuanVSTX();

		danhGiaVeSinhXaNewCacheModel.ghiChu = getGhiChu();

		String ghiChu = danhGiaVeSinhXaNewCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			danhGiaVeSinhXaNewCacheModel.ghiChu = null;
		}

		danhGiaVeSinhXaNewCacheModel.baoCaoDLI = getBaoCaoDLI();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhGiaVeSinhXaNewCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhGiaVeSinhXaNewCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danhGiaVeSinhXaNewCacheModel.idNguoiTao = getIdNguoiTao();

		return danhGiaVeSinhXaNewCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(47);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", soDan=");
		sb.append(getSoDan());
		sb.append(", tongSoHGD=");
		sb.append(getTongSoHGD());
		sb.append(", soHGDCoNhaTieu=");
		sb.append(getSoHGDCoNhaTieu());
		sb.append(", soHGDCoNhaTieuHVS=");
		sb.append(getSoHGDCoNhaTieuHVS());
		sb.append(", soNhaTieuHVSXayMoi=");
		sb.append(getSoNhaTieuHVSXayMoi());
		sb.append(", tiLeHGDCoNhaTieu=");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append(", tiLeHGDCoNhaTieuHVS=");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append(", tongSoTruongHoc=");
		sb.append(getTongSoTruongHoc());
		sb.append(", soTruongHocHVS=");
		sb.append(getSoTruongHocHVS());
		sb.append(", tongSoTramYTe=");
		sb.append(getTongSoTramYTe());
		sb.append(", soTramYTeHVS=");
		sb.append(getSoTramYTeHVS());
		sb.append(", tiLeTruongHocHVS=");
		sb.append(getTiLeTruongHocHVS());
		sb.append(", tiLeTramYTeHVS=");
		sb.append(getTiLeTramYTeHVS());
		sb.append(", ketLuanVSTX=");
		sb.append(getKetLuanVSTX());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", baoCaoDLI=");
		sb.append(getBaoCaoDLI());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(73);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNew");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDan</column-name><column-value><![CDATA[");
		sb.append(getSoDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoHGD</column-name><column-value><![CDATA[");
		sb.append(getTongSoHGD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHGDCoNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getSoHGDCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHGDCoNhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getSoHGDCoNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNhaTieuHVSXayMoi</column-name><column-value><![CDATA[");
		sb.append(getSoNhaTieuHVSXayMoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoTruongHoc</column-name><column-value><![CDATA[");
		sb.append(getTongSoTruongHoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTruongHocHVS</column-name><column-value><![CDATA[");
		sb.append(getSoTruongHocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoTramYTe</column-name><column-value><![CDATA[");
		sb.append(getTongSoTramYTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTramYTeHVS</column-name><column-value><![CDATA[");
		sb.append(getSoTramYTeHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTruongHocHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTruongHocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTramYTeHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTramYTeHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketLuanVSTX</column-name><column-value><![CDATA[");
		sb.append(getKetLuanVSTX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>baoCaoDLI</column-name><column-value><![CDATA[");
		sb.append(getBaoCaoDLI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhGiaVeSinhXaNew.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DanhGiaVeSinhXaNew.class
		};
	private int _id;
	private String _maTinh;
	private String _originalMaTinh;
	private String _maHuyen;
	private String _originalMaHuyen;
	private String _maXa;
	private int _nam;
	private int _originalNam;
	private boolean _setOriginalNam;
	private int _soDan;
	private int _tongSoHGD;
	private int _soHGDCoNhaTieu;
	private int _soHGDCoNhaTieuHVS;
	private int _soNhaTieuHVSXayMoi;
	private int _tiLeHGDCoNhaTieu;
	private int _tiLeHGDCoNhaTieuHVS;
	private int _tongSoTruongHoc;
	private int _soTruongHocHVS;
	private int _tongSoTramYTe;
	private int _soTramYTeHVS;
	private int _tiLeTruongHocHVS;
	private int _tiLeTramYTeHVS;
	private int _ketLuanVSTX;
	private String _ghiChu;
	private int _baoCaoDLI;
	private Date _ngayTao;
	private int _idNguoiTao;
	private long _columnBitmask;
	private DanhGiaVeSinhXaNew _escapedModel;
}