/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ThongTinKiemDemCongTrinh service. Represents a row in the &quot;ME_THONGTINKIEMDEMCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongTinKiemDemCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ThongTinKiemDemCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinhModel
 * @generated
 */
public class ThongTinKiemDemCongTrinhModelImpl extends BaseModelImpl<ThongTinKiemDemCongTrinh>
	implements ThongTinKiemDemCongTrinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong tin kiem dem cong trinh model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_THONGTINKIEMDEMCONGTRINH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "VESINHCONGTRINHID", Types.INTEGER },
			{ "KEHOACHKIEMDEMVESINHID", Types.INTEGER },
			{ "TENCONGTRINH", Types.VARCHAR },
			{ "LOAICONGTRINH", Types.INTEGER },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "DIACHI", Types.VARCHAR },
			{ "NGAYKIEMDEM", Types.TIMESTAMP },
			{ "HOTENNGUOITRALOI", Types.VARCHAR },
			{ "SODIENTHOAI", Types.VARCHAR },
			{ "GIOITINHNGUOITRALOI", Types.VARCHAR },
			{ "VAITROCHUCDANH", Types.VARCHAR },
			{ "SOCA", Types.INTEGER },
			{ "SONGUOITRONGCA", Types.INTEGER },
			{ "KINHDO", Types.VARCHAR },
			{ "VIDO", Types.VARCHAR },
			{ "LOAINGUONNUOC", Types.VARCHAR },
			{ "DATQCVN", Types.INTEGER },
			{ "DATTIEUCHUANHVS", Types.INTEGER },
			{ "ANHCHUPCHUNGNHAN", Types.VARCHAR },
			{ "SONHATIEU", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "DAKETTHUCDIEUTRA", Types.INTEGER },
			{ "LYDOKHONGHOANTHANH", Types.VARCHAR },
			{ "IMEI", Types.VARCHAR },
			{ "TAIKHOAN", Types.VARCHAR },
			{ "DANHGIAKIEMDEM", Types.INTEGER },
			{ "SAVEPOINT", Types.TIMESTAMP },
			{ "sophieuxetnghiem", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_THONGTINKIEMDEMCONGTRINH (ID INTEGER not null primary key,VESINHCONGTRINHID INTEGER,KEHOACHKIEMDEMVESINHID INTEGER,TENCONGTRINH VARCHAR(75) null,LOAICONGTRINH INTEGER,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,DIACHI VARCHAR(75) null,NGAYKIEMDEM DATE null,HOTENNGUOITRALOI VARCHAR(75) null,SODIENTHOAI VARCHAR(75) null,GIOITINHNGUOITRALOI VARCHAR(75) null,VAITROCHUCDANH VARCHAR(75) null,SOCA INTEGER,SONGUOITRONGCA INTEGER,KINHDO VARCHAR(75) null,VIDO VARCHAR(75) null,LOAINGUONNUOC VARCHAR(75) null,DATQCVN INTEGER,DATTIEUCHUANHVS INTEGER,ANHCHUPCHUNGNHAN VARCHAR(75) null,SONHATIEU INTEGER,GHICHU VARCHAR(75) null,DAKETTHUCDIEUTRA INTEGER,LYDOKHONGHOANTHANH VARCHAR(75) null,IMEI VARCHAR(75) null,TAIKHOAN VARCHAR(75) null,DANHGIAKIEMDEM INTEGER,SAVEPOINT DATE null,sophieuxetnghiem VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ME_THONGTINKIEMDEMCONGTRINH";
	public static final String ORDER_BY_JPQL = " ORDER BY thongTinKiemDemCongTrinh.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_THONGTINKIEMDEMCONGTRINH.ID ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh"),
			true);
	public static long DAKETTHUCDIEUTRA_COLUMN_BITMASK = 1L;
	public static long DANHGIAKIEMDEM_COLUMN_BITMASK = 2L;
	public static long KEHOACHKIEMDEMVESINHID_COLUMN_BITMASK = 4L;
	public static long VESINHCONTRINHID_COLUMN_BITMASK = 8L;
	public static long ID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh"));

	public ThongTinKiemDemCongTrinhModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThongTinKiemDemCongTrinh.class;
	}

	@Override
	public String getModelClassName() {
		return ThongTinKiemDemCongTrinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("veSinhConTrinhId", getVeSinhConTrinhId());
		attributes.put("keHoachKiemDemVeSinhId", getKeHoachKiemDemVeSinhId());
		attributes.put("tenCongTrinh", getTenCongTrinh());
		attributes.put("loaiCongTrinh", getLoaiCongTrinh());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("diaChi", getDiaChi());
		attributes.put("ngayKiemDem", getNgayKiemDem());
		attributes.put("hoTenNguoiTraLoi", getHoTenNguoiTraLoi());
		attributes.put("soDienThoai", getSoDienThoai());
		attributes.put("gioiTinhNguoiTraLoi", getGioiTinhNguoiTraLoi());
		attributes.put("vaiTroChucDanh", getVaiTroChucDanh());
		attributes.put("soCa", getSoCa());
		attributes.put("soNguoiTrongCa", getSoNguoiTrongCa());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("loaiNguonNuoc", getLoaiNguonNuoc());
		attributes.put("daTQCVN", getDaTQCVN());
		attributes.put("datTieuChuanHVS", getDatTieuChuanHVS());
		attributes.put("anhChupChungNhan", getAnhChupChungNhan());
		attributes.put("soNhaTieu", getSoNhaTieu());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("daKetThucDieuTra", getDaKetThucDieuTra());
		attributes.put("lyDoKhongHoanThanh", getLyDoKhongHoanThanh());
		attributes.put("imei", getImei());
		attributes.put("taiKhoan", getTaiKhoan());
		attributes.put("danhGiaKiemDem", getDanhGiaKiemDem());
		attributes.put("savePoint", getSavePoint());
		attributes.put("sophieuxetnghiem", getSophieuxetnghiem());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer veSinhConTrinhId = (Integer)attributes.get("veSinhConTrinhId");

		if (veSinhConTrinhId != null) {
			setVeSinhConTrinhId(veSinhConTrinhId);
		}

		Integer keHoachKiemDemVeSinhId = (Integer)attributes.get(
				"keHoachKiemDemVeSinhId");

		if (keHoachKiemDemVeSinhId != null) {
			setKeHoachKiemDemVeSinhId(keHoachKiemDemVeSinhId);
		}

		String tenCongTrinh = (String)attributes.get("tenCongTrinh");

		if (tenCongTrinh != null) {
			setTenCongTrinh(tenCongTrinh);
		}

		Integer loaiCongTrinh = (Integer)attributes.get("loaiCongTrinh");

		if (loaiCongTrinh != null) {
			setLoaiCongTrinh(loaiCongTrinh);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		Date ngayKiemDem = (Date)attributes.get("ngayKiemDem");

		if (ngayKiemDem != null) {
			setNgayKiemDem(ngayKiemDem);
		}

		String hoTenNguoiTraLoi = (String)attributes.get("hoTenNguoiTraLoi");

		if (hoTenNguoiTraLoi != null) {
			setHoTenNguoiTraLoi(hoTenNguoiTraLoi);
		}

		String soDienThoai = (String)attributes.get("soDienThoai");

		if (soDienThoai != null) {
			setSoDienThoai(soDienThoai);
		}

		String gioiTinhNguoiTraLoi = (String)attributes.get(
				"gioiTinhNguoiTraLoi");

		if (gioiTinhNguoiTraLoi != null) {
			setGioiTinhNguoiTraLoi(gioiTinhNguoiTraLoi);
		}

		String vaiTroChucDanh = (String)attributes.get("vaiTroChucDanh");

		if (vaiTroChucDanh != null) {
			setVaiTroChucDanh(vaiTroChucDanh);
		}

		Integer soCa = (Integer)attributes.get("soCa");

		if (soCa != null) {
			setSoCa(soCa);
		}

		Integer soNguoiTrongCa = (Integer)attributes.get("soNguoiTrongCa");

		if (soNguoiTrongCa != null) {
			setSoNguoiTrongCa(soNguoiTrongCa);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		String loaiNguonNuoc = (String)attributes.get("loaiNguonNuoc");

		if (loaiNguonNuoc != null) {
			setLoaiNguonNuoc(loaiNguonNuoc);
		}

		Integer daTQCVN = (Integer)attributes.get("daTQCVN");

		if (daTQCVN != null) {
			setDaTQCVN(daTQCVN);
		}

		Integer datTieuChuanHVS = (Integer)attributes.get("datTieuChuanHVS");

		if (datTieuChuanHVS != null) {
			setDatTieuChuanHVS(datTieuChuanHVS);
		}

		String anhChupChungNhan = (String)attributes.get("anhChupChungNhan");

		if (anhChupChungNhan != null) {
			setAnhChupChungNhan(anhChupChungNhan);
		}

		Integer soNhaTieu = (Integer)attributes.get("soNhaTieu");

		if (soNhaTieu != null) {
			setSoNhaTieu(soNhaTieu);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer daKetThucDieuTra = (Integer)attributes.get("daKetThucDieuTra");

		if (daKetThucDieuTra != null) {
			setDaKetThucDieuTra(daKetThucDieuTra);
		}

		String lyDoKhongHoanThanh = (String)attributes.get("lyDoKhongHoanThanh");

		if (lyDoKhongHoanThanh != null) {
			setLyDoKhongHoanThanh(lyDoKhongHoanThanh);
		}

		String imei = (String)attributes.get("imei");

		if (imei != null) {
			setImei(imei);
		}

		String taiKhoan = (String)attributes.get("taiKhoan");

		if (taiKhoan != null) {
			setTaiKhoan(taiKhoan);
		}

		Integer danhGiaKiemDem = (Integer)attributes.get("danhGiaKiemDem");

		if (danhGiaKiemDem != null) {
			setDanhGiaKiemDem(danhGiaKiemDem);
		}

		Date savePoint = (Date)attributes.get("savePoint");

		if (savePoint != null) {
			setSavePoint(savePoint);
		}

		String sophieuxetnghiem = (String)attributes.get("sophieuxetnghiem");

		if (sophieuxetnghiem != null) {
			setSophieuxetnghiem(sophieuxetnghiem);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public int getVeSinhConTrinhId() {
		return _veSinhConTrinhId;
	}

	@Override
	public void setVeSinhConTrinhId(int veSinhConTrinhId) {
		_columnBitmask |= VESINHCONTRINHID_COLUMN_BITMASK;

		if (!_setOriginalVeSinhConTrinhId) {
			_setOriginalVeSinhConTrinhId = true;

			_originalVeSinhConTrinhId = _veSinhConTrinhId;
		}

		_veSinhConTrinhId = veSinhConTrinhId;
	}

	public int getOriginalVeSinhConTrinhId() {
		return _originalVeSinhConTrinhId;
	}

	@Override
	public int getKeHoachKiemDemVeSinhId() {
		return _keHoachKiemDemVeSinhId;
	}

	@Override
	public void setKeHoachKiemDemVeSinhId(int keHoachKiemDemVeSinhId) {
		_columnBitmask |= KEHOACHKIEMDEMVESINHID_COLUMN_BITMASK;

		if (!_setOriginalKeHoachKiemDemVeSinhId) {
			_setOriginalKeHoachKiemDemVeSinhId = true;

			_originalKeHoachKiemDemVeSinhId = _keHoachKiemDemVeSinhId;
		}

		_keHoachKiemDemVeSinhId = keHoachKiemDemVeSinhId;
	}

	public int getOriginalKeHoachKiemDemVeSinhId() {
		return _originalKeHoachKiemDemVeSinhId;
	}

	@Override
	public String getTenCongTrinh() {
		if (_tenCongTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCongTrinh;
		}
	}

	@Override
	public void setTenCongTrinh(String tenCongTrinh) {
		_tenCongTrinh = tenCongTrinh;
	}

	@Override
	public int getLoaiCongTrinh() {
		return _loaiCongTrinh;
	}

	@Override
	public void setLoaiCongTrinh(int loaiCongTrinh) {
		_loaiCongTrinh = loaiCongTrinh;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_maTinh = maTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@Override
	public Date getNgayKiemDem() {
		return _ngayKiemDem;
	}

	@Override
	public void setNgayKiemDem(Date ngayKiemDem) {
		_ngayKiemDem = ngayKiemDem;
	}

	@Override
	public String getHoTenNguoiTraLoi() {
		if (_hoTenNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenNguoiTraLoi;
		}
	}

	@Override
	public void setHoTenNguoiTraLoi(String hoTenNguoiTraLoi) {
		_hoTenNguoiTraLoi = hoTenNguoiTraLoi;
	}

	@Override
	public String getSoDienThoai() {
		if (_soDienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDienThoai;
		}
	}

	@Override
	public void setSoDienThoai(String soDienThoai) {
		_soDienThoai = soDienThoai;
	}

	@Override
	public String getGioiTinhNguoiTraLoi() {
		if (_gioiTinhNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _gioiTinhNguoiTraLoi;
		}
	}

	@Override
	public void setGioiTinhNguoiTraLoi(String gioiTinhNguoiTraLoi) {
		_gioiTinhNguoiTraLoi = gioiTinhNguoiTraLoi;
	}

	@Override
	public String getVaiTroChucDanh() {
		if (_vaiTroChucDanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _vaiTroChucDanh;
		}
	}

	@Override
	public void setVaiTroChucDanh(String vaiTroChucDanh) {
		_vaiTroChucDanh = vaiTroChucDanh;
	}

	@Override
	public int getSoCa() {
		return _soCa;
	}

	@Override
	public void setSoCa(int soCa) {
		_soCa = soCa;
	}

	@Override
	public int getSoNguoiTrongCa() {
		return _soNguoiTrongCa;
	}

	@Override
	public void setSoNguoiTrongCa(int soNguoiTrongCa) {
		_soNguoiTrongCa = soNguoiTrongCa;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public String getLoaiNguonNuoc() {
		if (_loaiNguonNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNguonNuoc;
		}
	}

	@Override
	public void setLoaiNguonNuoc(String loaiNguonNuoc) {
		_loaiNguonNuoc = loaiNguonNuoc;
	}

	@Override
	public int getDaTQCVN() {
		return _daTQCVN;
	}

	@Override
	public void setDaTQCVN(int daTQCVN) {
		_daTQCVN = daTQCVN;
	}

	@Override
	public int getDatTieuChuanHVS() {
		return _datTieuChuanHVS;
	}

	@Override
	public void setDatTieuChuanHVS(int datTieuChuanHVS) {
		_datTieuChuanHVS = datTieuChuanHVS;
	}

	@Override
	public String getAnhChupChungNhan() {
		if (_anhChupChungNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhChupChungNhan;
		}
	}

	@Override
	public void setAnhChupChungNhan(String anhChupChungNhan) {
		_anhChupChungNhan = anhChupChungNhan;
	}

	@Override
	public int getSoNhaTieu() {
		return _soNhaTieu;
	}

	@Override
	public void setSoNhaTieu(int soNhaTieu) {
		_soNhaTieu = soNhaTieu;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getDaKetThucDieuTra() {
		return _daKetThucDieuTra;
	}

	@Override
	public void setDaKetThucDieuTra(int daKetThucDieuTra) {
		_columnBitmask |= DAKETTHUCDIEUTRA_COLUMN_BITMASK;

		if (!_setOriginalDaKetThucDieuTra) {
			_setOriginalDaKetThucDieuTra = true;

			_originalDaKetThucDieuTra = _daKetThucDieuTra;
		}

		_daKetThucDieuTra = daKetThucDieuTra;
	}

	public int getOriginalDaKetThucDieuTra() {
		return _originalDaKetThucDieuTra;
	}

	@Override
	public String getLyDoKhongHoanThanh() {
		if (_lyDoKhongHoanThanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongHoanThanh;
		}
	}

	@Override
	public void setLyDoKhongHoanThanh(String lyDoKhongHoanThanh) {
		_lyDoKhongHoanThanh = lyDoKhongHoanThanh;
	}

	@Override
	public String getImei() {
		if (_imei == null) {
			return StringPool.BLANK;
		}
		else {
			return _imei;
		}
	}

	@Override
	public void setImei(String imei) {
		_imei = imei;
	}

	@Override
	public String getTaiKhoan() {
		if (_taiKhoan == null) {
			return StringPool.BLANK;
		}
		else {
			return _taiKhoan;
		}
	}

	@Override
	public void setTaiKhoan(String taiKhoan) {
		_taiKhoan = taiKhoan;
	}

	@Override
	public int getDanhGiaKiemDem() {
		return _danhGiaKiemDem;
	}

	@Override
	public void setDanhGiaKiemDem(int danhGiaKiemDem) {
		_columnBitmask |= DANHGIAKIEMDEM_COLUMN_BITMASK;

		if (!_setOriginalDanhGiaKiemDem) {
			_setOriginalDanhGiaKiemDem = true;

			_originalDanhGiaKiemDem = _danhGiaKiemDem;
		}

		_danhGiaKiemDem = danhGiaKiemDem;
	}

	public int getOriginalDanhGiaKiemDem() {
		return _originalDanhGiaKiemDem;
	}

	@Override
	public Date getSavePoint() {
		return _savePoint;
	}

	@Override
	public void setSavePoint(Date savePoint) {
		_savePoint = savePoint;
	}

	@Override
	public String getSophieuxetnghiem() {
		if (_sophieuxetnghiem == null) {
			return StringPool.BLANK;
		}
		else {
			return _sophieuxetnghiem;
		}
	}

	@Override
	public void setSophieuxetnghiem(String sophieuxetnghiem) {
		_sophieuxetnghiem = sophieuxetnghiem;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ThongTinKiemDemCongTrinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ThongTinKiemDemCongTrinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThongTinKiemDemCongTrinhImpl thongTinKiemDemCongTrinhImpl = new ThongTinKiemDemCongTrinhImpl();

		thongTinKiemDemCongTrinhImpl.setId(getId());
		thongTinKiemDemCongTrinhImpl.setVeSinhConTrinhId(getVeSinhConTrinhId());
		thongTinKiemDemCongTrinhImpl.setKeHoachKiemDemVeSinhId(getKeHoachKiemDemVeSinhId());
		thongTinKiemDemCongTrinhImpl.setTenCongTrinh(getTenCongTrinh());
		thongTinKiemDemCongTrinhImpl.setLoaiCongTrinh(getLoaiCongTrinh());
		thongTinKiemDemCongTrinhImpl.setMaTinh(getMaTinh());
		thongTinKiemDemCongTrinhImpl.setMaHuyen(getMaHuyen());
		thongTinKiemDemCongTrinhImpl.setMaXa(getMaXa());
		thongTinKiemDemCongTrinhImpl.setDiaChi(getDiaChi());
		thongTinKiemDemCongTrinhImpl.setNgayKiemDem(getNgayKiemDem());
		thongTinKiemDemCongTrinhImpl.setHoTenNguoiTraLoi(getHoTenNguoiTraLoi());
		thongTinKiemDemCongTrinhImpl.setSoDienThoai(getSoDienThoai());
		thongTinKiemDemCongTrinhImpl.setGioiTinhNguoiTraLoi(getGioiTinhNguoiTraLoi());
		thongTinKiemDemCongTrinhImpl.setVaiTroChucDanh(getVaiTroChucDanh());
		thongTinKiemDemCongTrinhImpl.setSoCa(getSoCa());
		thongTinKiemDemCongTrinhImpl.setSoNguoiTrongCa(getSoNguoiTrongCa());
		thongTinKiemDemCongTrinhImpl.setKinhDo(getKinhDo());
		thongTinKiemDemCongTrinhImpl.setViDo(getViDo());
		thongTinKiemDemCongTrinhImpl.setLoaiNguonNuoc(getLoaiNguonNuoc());
		thongTinKiemDemCongTrinhImpl.setDaTQCVN(getDaTQCVN());
		thongTinKiemDemCongTrinhImpl.setDatTieuChuanHVS(getDatTieuChuanHVS());
		thongTinKiemDemCongTrinhImpl.setAnhChupChungNhan(getAnhChupChungNhan());
		thongTinKiemDemCongTrinhImpl.setSoNhaTieu(getSoNhaTieu());
		thongTinKiemDemCongTrinhImpl.setGhiChu(getGhiChu());
		thongTinKiemDemCongTrinhImpl.setDaKetThucDieuTra(getDaKetThucDieuTra());
		thongTinKiemDemCongTrinhImpl.setLyDoKhongHoanThanh(getLyDoKhongHoanThanh());
		thongTinKiemDemCongTrinhImpl.setImei(getImei());
		thongTinKiemDemCongTrinhImpl.setTaiKhoan(getTaiKhoan());
		thongTinKiemDemCongTrinhImpl.setDanhGiaKiemDem(getDanhGiaKiemDem());
		thongTinKiemDemCongTrinhImpl.setSavePoint(getSavePoint());
		thongTinKiemDemCongTrinhImpl.setSophieuxetnghiem(getSophieuxetnghiem());

		thongTinKiemDemCongTrinhImpl.resetOriginalValues();

		return thongTinKiemDemCongTrinhImpl;
	}

	@Override
	public int compareTo(ThongTinKiemDemCongTrinh thongTinKiemDemCongTrinh) {
		int value = 0;

		if (getId() < thongTinKiemDemCongTrinh.getId()) {
			value = -1;
		}
		else if (getId() > thongTinKiemDemCongTrinh.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ThongTinKiemDemCongTrinh)) {
			return false;
		}

		ThongTinKiemDemCongTrinh thongTinKiemDemCongTrinh = (ThongTinKiemDemCongTrinh)obj;

		int primaryKey = thongTinKiemDemCongTrinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ThongTinKiemDemCongTrinhModelImpl thongTinKiemDemCongTrinhModelImpl = this;

		thongTinKiemDemCongTrinhModelImpl._originalVeSinhConTrinhId = thongTinKiemDemCongTrinhModelImpl._veSinhConTrinhId;

		thongTinKiemDemCongTrinhModelImpl._setOriginalVeSinhConTrinhId = false;

		thongTinKiemDemCongTrinhModelImpl._originalKeHoachKiemDemVeSinhId = thongTinKiemDemCongTrinhModelImpl._keHoachKiemDemVeSinhId;

		thongTinKiemDemCongTrinhModelImpl._setOriginalKeHoachKiemDemVeSinhId = false;

		thongTinKiemDemCongTrinhModelImpl._originalDaKetThucDieuTra = thongTinKiemDemCongTrinhModelImpl._daKetThucDieuTra;

		thongTinKiemDemCongTrinhModelImpl._setOriginalDaKetThucDieuTra = false;

		thongTinKiemDemCongTrinhModelImpl._originalDanhGiaKiemDem = thongTinKiemDemCongTrinhModelImpl._danhGiaKiemDem;

		thongTinKiemDemCongTrinhModelImpl._setOriginalDanhGiaKiemDem = false;

		thongTinKiemDemCongTrinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ThongTinKiemDemCongTrinh> toCacheModel() {
		ThongTinKiemDemCongTrinhCacheModel thongTinKiemDemCongTrinhCacheModel = new ThongTinKiemDemCongTrinhCacheModel();

		thongTinKiemDemCongTrinhCacheModel.id = getId();

		thongTinKiemDemCongTrinhCacheModel.veSinhConTrinhId = getVeSinhConTrinhId();

		thongTinKiemDemCongTrinhCacheModel.keHoachKiemDemVeSinhId = getKeHoachKiemDemVeSinhId();

		thongTinKiemDemCongTrinhCacheModel.tenCongTrinh = getTenCongTrinh();

		String tenCongTrinh = thongTinKiemDemCongTrinhCacheModel.tenCongTrinh;

		if ((tenCongTrinh != null) && (tenCongTrinh.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.tenCongTrinh = null;
		}

		thongTinKiemDemCongTrinhCacheModel.loaiCongTrinh = getLoaiCongTrinh();

		thongTinKiemDemCongTrinhCacheModel.maTinh = getMaTinh();

		String maTinh = thongTinKiemDemCongTrinhCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.maTinh = null;
		}

		thongTinKiemDemCongTrinhCacheModel.maHuyen = getMaHuyen();

		String maHuyen = thongTinKiemDemCongTrinhCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.maHuyen = null;
		}

		thongTinKiemDemCongTrinhCacheModel.maXa = getMaXa();

		String maXa = thongTinKiemDemCongTrinhCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.maXa = null;
		}

		thongTinKiemDemCongTrinhCacheModel.diaChi = getDiaChi();

		String diaChi = thongTinKiemDemCongTrinhCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.diaChi = null;
		}

		Date ngayKiemDem = getNgayKiemDem();

		if (ngayKiemDem != null) {
			thongTinKiemDemCongTrinhCacheModel.ngayKiemDem = ngayKiemDem.getTime();
		}
		else {
			thongTinKiemDemCongTrinhCacheModel.ngayKiemDem = Long.MIN_VALUE;
		}

		thongTinKiemDemCongTrinhCacheModel.hoTenNguoiTraLoi = getHoTenNguoiTraLoi();

		String hoTenNguoiTraLoi = thongTinKiemDemCongTrinhCacheModel.hoTenNguoiTraLoi;

		if ((hoTenNguoiTraLoi != null) && (hoTenNguoiTraLoi.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.hoTenNguoiTraLoi = null;
		}

		thongTinKiemDemCongTrinhCacheModel.soDienThoai = getSoDienThoai();

		String soDienThoai = thongTinKiemDemCongTrinhCacheModel.soDienThoai;

		if ((soDienThoai != null) && (soDienThoai.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.soDienThoai = null;
		}

		thongTinKiemDemCongTrinhCacheModel.gioiTinhNguoiTraLoi = getGioiTinhNguoiTraLoi();

		String gioiTinhNguoiTraLoi = thongTinKiemDemCongTrinhCacheModel.gioiTinhNguoiTraLoi;

		if ((gioiTinhNguoiTraLoi != null) &&
				(gioiTinhNguoiTraLoi.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.gioiTinhNguoiTraLoi = null;
		}

		thongTinKiemDemCongTrinhCacheModel.vaiTroChucDanh = getVaiTroChucDanh();

		String vaiTroChucDanh = thongTinKiemDemCongTrinhCacheModel.vaiTroChucDanh;

		if ((vaiTroChucDanh != null) && (vaiTroChucDanh.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.vaiTroChucDanh = null;
		}

		thongTinKiemDemCongTrinhCacheModel.soCa = getSoCa();

		thongTinKiemDemCongTrinhCacheModel.soNguoiTrongCa = getSoNguoiTrongCa();

		thongTinKiemDemCongTrinhCacheModel.kinhDo = getKinhDo();

		String kinhDo = thongTinKiemDemCongTrinhCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.kinhDo = null;
		}

		thongTinKiemDemCongTrinhCacheModel.viDo = getViDo();

		String viDo = thongTinKiemDemCongTrinhCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.viDo = null;
		}

		thongTinKiemDemCongTrinhCacheModel.loaiNguonNuoc = getLoaiNguonNuoc();

		String loaiNguonNuoc = thongTinKiemDemCongTrinhCacheModel.loaiNguonNuoc;

		if ((loaiNguonNuoc != null) && (loaiNguonNuoc.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.loaiNguonNuoc = null;
		}

		thongTinKiemDemCongTrinhCacheModel.daTQCVN = getDaTQCVN();

		thongTinKiemDemCongTrinhCacheModel.datTieuChuanHVS = getDatTieuChuanHVS();

		thongTinKiemDemCongTrinhCacheModel.anhChupChungNhan = getAnhChupChungNhan();

		String anhChupChungNhan = thongTinKiemDemCongTrinhCacheModel.anhChupChungNhan;

		if ((anhChupChungNhan != null) && (anhChupChungNhan.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.anhChupChungNhan = null;
		}

		thongTinKiemDemCongTrinhCacheModel.soNhaTieu = getSoNhaTieu();

		thongTinKiemDemCongTrinhCacheModel.ghiChu = getGhiChu();

		String ghiChu = thongTinKiemDemCongTrinhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.ghiChu = null;
		}

		thongTinKiemDemCongTrinhCacheModel.daKetThucDieuTra = getDaKetThucDieuTra();

		thongTinKiemDemCongTrinhCacheModel.lyDoKhongHoanThanh = getLyDoKhongHoanThanh();

		String lyDoKhongHoanThanh = thongTinKiemDemCongTrinhCacheModel.lyDoKhongHoanThanh;

		if ((lyDoKhongHoanThanh != null) && (lyDoKhongHoanThanh.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.lyDoKhongHoanThanh = null;
		}

		thongTinKiemDemCongTrinhCacheModel.imei = getImei();

		String imei = thongTinKiemDemCongTrinhCacheModel.imei;

		if ((imei != null) && (imei.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.imei = null;
		}

		thongTinKiemDemCongTrinhCacheModel.taiKhoan = getTaiKhoan();

		String taiKhoan = thongTinKiemDemCongTrinhCacheModel.taiKhoan;

		if ((taiKhoan != null) && (taiKhoan.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.taiKhoan = null;
		}

		thongTinKiemDemCongTrinhCacheModel.danhGiaKiemDem = getDanhGiaKiemDem();

		Date savePoint = getSavePoint();

		if (savePoint != null) {
			thongTinKiemDemCongTrinhCacheModel.savePoint = savePoint.getTime();
		}
		else {
			thongTinKiemDemCongTrinhCacheModel.savePoint = Long.MIN_VALUE;
		}

		thongTinKiemDemCongTrinhCacheModel.sophieuxetnghiem = getSophieuxetnghiem();

		String sophieuxetnghiem = thongTinKiemDemCongTrinhCacheModel.sophieuxetnghiem;

		if ((sophieuxetnghiem != null) && (sophieuxetnghiem.length() == 0)) {
			thongTinKiemDemCongTrinhCacheModel.sophieuxetnghiem = null;
		}

		return thongTinKiemDemCongTrinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(63);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", veSinhConTrinhId=");
		sb.append(getVeSinhConTrinhId());
		sb.append(", keHoachKiemDemVeSinhId=");
		sb.append(getKeHoachKiemDemVeSinhId());
		sb.append(", tenCongTrinh=");
		sb.append(getTenCongTrinh());
		sb.append(", loaiCongTrinh=");
		sb.append(getLoaiCongTrinh());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", ngayKiemDem=");
		sb.append(getNgayKiemDem());
		sb.append(", hoTenNguoiTraLoi=");
		sb.append(getHoTenNguoiTraLoi());
		sb.append(", soDienThoai=");
		sb.append(getSoDienThoai());
		sb.append(", gioiTinhNguoiTraLoi=");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append(", vaiTroChucDanh=");
		sb.append(getVaiTroChucDanh());
		sb.append(", soCa=");
		sb.append(getSoCa());
		sb.append(", soNguoiTrongCa=");
		sb.append(getSoNguoiTrongCa());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", loaiNguonNuoc=");
		sb.append(getLoaiNguonNuoc());
		sb.append(", daTQCVN=");
		sb.append(getDaTQCVN());
		sb.append(", datTieuChuanHVS=");
		sb.append(getDatTieuChuanHVS());
		sb.append(", anhChupChungNhan=");
		sb.append(getAnhChupChungNhan());
		sb.append(", soNhaTieu=");
		sb.append(getSoNhaTieu());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", daKetThucDieuTra=");
		sb.append(getDaKetThucDieuTra());
		sb.append(", lyDoKhongHoanThanh=");
		sb.append(getLyDoKhongHoanThanh());
		sb.append(", imei=");
		sb.append(getImei());
		sb.append(", taiKhoan=");
		sb.append(getTaiKhoan());
		sb.append(", danhGiaKiemDem=");
		sb.append(getDanhGiaKiemDem());
		sb.append(", savePoint=");
		sb.append(getSavePoint());
		sb.append(", sophieuxetnghiem=");
		sb.append(getSophieuxetnghiem());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(97);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemCongTrinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>veSinhConTrinhId</column-name><column-value><![CDATA[");
		sb.append(getVeSinhConTrinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keHoachKiemDemVeSinhId</column-name><column-value><![CDATA[");
		sb.append(getKeHoachKiemDemVeSinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCongTrinh</column-name><column-value><![CDATA[");
		sb.append(getTenCongTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiCongTrinh</column-name><column-value><![CDATA[");
		sb.append(getLoaiCongTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKiemDem</column-name><column-value><![CDATA[");
		sb.append(getNgayKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoai</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vaiTroChucDanh</column-name><column-value><![CDATA[");
		sb.append(getVaiTroChucDanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCa</column-name><column-value><![CDATA[");
		sb.append(getSoCa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiTrongCa</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiTrongCa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNguonNuoc</column-name><column-value><![CDATA[");
		sb.append(getLoaiNguonNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daTQCVN</column-name><column-value><![CDATA[");
		sb.append(getDaTQCVN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>datTieuChuanHVS</column-name><column-value><![CDATA[");
		sb.append(getDatTieuChuanHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhChupChungNhan</column-name><column-value><![CDATA[");
		sb.append(getAnhChupChungNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getSoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daKetThucDieuTra</column-name><column-value><![CDATA[");
		sb.append(getDaKetThucDieuTra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongHoanThanh</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongHoanThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imei</column-name><column-value><![CDATA[");
		sb.append(getImei());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoan</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danhGiaKiemDem</column-name><column-value><![CDATA[");
		sb.append(getDanhGiaKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>savePoint</column-name><column-value><![CDATA[");
		sb.append(getSavePoint());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sophieuxetnghiem</column-name><column-value><![CDATA[");
		sb.append(getSophieuxetnghiem());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ThongTinKiemDemCongTrinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ThongTinKiemDemCongTrinh.class
		};
	private int _id;
	private int _veSinhConTrinhId;
	private int _originalVeSinhConTrinhId;
	private boolean _setOriginalVeSinhConTrinhId;
	private int _keHoachKiemDemVeSinhId;
	private int _originalKeHoachKiemDemVeSinhId;
	private boolean _setOriginalKeHoachKiemDemVeSinhId;
	private String _tenCongTrinh;
	private int _loaiCongTrinh;
	private String _maTinh;
	private String _maHuyen;
	private String _maXa;
	private String _diaChi;
	private Date _ngayKiemDem;
	private String _hoTenNguoiTraLoi;
	private String _soDienThoai;
	private String _gioiTinhNguoiTraLoi;
	private String _vaiTroChucDanh;
	private int _soCa;
	private int _soNguoiTrongCa;
	private String _kinhDo;
	private String _viDo;
	private String _loaiNguonNuoc;
	private int _daTQCVN;
	private int _datTieuChuanHVS;
	private String _anhChupChungNhan;
	private int _soNhaTieu;
	private String _ghiChu;
	private int _daKetThucDieuTra;
	private int _originalDaKetThucDieuTra;
	private boolean _setOriginalDaKetThucDieuTra;
	private String _lyDoKhongHoanThanh;
	private String _imei;
	private String _taiKhoan;
	private int _danhGiaKiemDem;
	private int _originalDanhGiaKiemDem;
	private boolean _setOriginalDanhGiaKiemDem;
	private Date _savePoint;
	private String _sophieuxetnghiem;
	private long _columnBitmask;
	private ThongTinKiemDemCongTrinh _escapedModel;
}