/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DanhGiaVeSinhXaNew service. Represents a row in the &quot;ME_DANHGIAVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.DanhGiaVeSinhXaNewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.DanhGiaVeSinhXaNewImpl}.
 * </p>
 *
 * @author BinhTH
 * @see DanhGiaVeSinhXaNew
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.DanhGiaVeSinhXaNewImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.DanhGiaVeSinhXaNewModelImpl
 * @generated
 */
public interface DanhGiaVeSinhXaNewModel extends BaseModel<DanhGiaVeSinhXaNew> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh gia ve sinh xa new model instance should use the {@link DanhGiaVeSinhXaNew} interface instead.
	 */

	/**
	 * Returns the primary key of this danh gia ve sinh xa new.
	 *
	 * @return the primary key of this danh gia ve sinh xa new
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this danh gia ve sinh xa new.
	 *
	 * @param primaryKey the primary key of this danh gia ve sinh xa new
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this danh gia ve sinh xa new.
	 *
	 * @return the ID of this danh gia ve sinh xa new
	 */
	public int getId();

	/**
	 * Sets the ID of this danh gia ve sinh xa new.
	 *
	 * @param id the ID of this danh gia ve sinh xa new
	 */
	public void setId(int id);

	/**
	 * Returns the ma tinh of this danh gia ve sinh xa new.
	 *
	 * @return the ma tinh of this danh gia ve sinh xa new
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this danh gia ve sinh xa new.
	 *
	 * @param maTinh the ma tinh of this danh gia ve sinh xa new
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this danh gia ve sinh xa new.
	 *
	 * @return the ma huyen of this danh gia ve sinh xa new
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this danh gia ve sinh xa new.
	 *
	 * @param maHuyen the ma huyen of this danh gia ve sinh xa new
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this danh gia ve sinh xa new.
	 *
	 * @return the ma xa of this danh gia ve sinh xa new
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this danh gia ve sinh xa new.
	 *
	 * @param maXa the ma xa of this danh gia ve sinh xa new
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the nam of this danh gia ve sinh xa new.
	 *
	 * @return the nam of this danh gia ve sinh xa new
	 */
	public int getNam();

	/**
	 * Sets the nam of this danh gia ve sinh xa new.
	 *
	 * @param nam the nam of this danh gia ve sinh xa new
	 */
	public void setNam(int nam);

	/**
	 * Returns the so dan of this danh gia ve sinh xa new.
	 *
	 * @return the so dan of this danh gia ve sinh xa new
	 */
	public int getSoDan();

	/**
	 * Sets the so dan of this danh gia ve sinh xa new.
	 *
	 * @param soDan the so dan of this danh gia ve sinh xa new
	 */
	public void setSoDan(int soDan);

	/**
	 * Returns the tong so h g d of this danh gia ve sinh xa new.
	 *
	 * @return the tong so h g d of this danh gia ve sinh xa new
	 */
	public int getTongSoHGD();

	/**
	 * Sets the tong so h g d of this danh gia ve sinh xa new.
	 *
	 * @param tongSoHGD the tong so h g d of this danh gia ve sinh xa new
	 */
	public void setTongSoHGD(int tongSoHGD);

	/**
	 * Returns the so h g d co nha tieu of this danh gia ve sinh xa new.
	 *
	 * @return the so h g d co nha tieu of this danh gia ve sinh xa new
	 */
	public int getSoHGDCoNhaTieu();

	/**
	 * Sets the so h g d co nha tieu of this danh gia ve sinh xa new.
	 *
	 * @param soHGDCoNhaTieu the so h g d co nha tieu of this danh gia ve sinh xa new
	 */
	public void setSoHGDCoNhaTieu(int soHGDCoNhaTieu);

	/**
	 * Returns the so h g d co nha tieu h v s of this danh gia ve sinh xa new.
	 *
	 * @return the so h g d co nha tieu h v s of this danh gia ve sinh xa new
	 */
	public int getSoHGDCoNhaTieuHVS();

	/**
	 * Sets the so h g d co nha tieu h v s of this danh gia ve sinh xa new.
	 *
	 * @param soHGDCoNhaTieuHVS the so h g d co nha tieu h v s of this danh gia ve sinh xa new
	 */
	public void setSoHGDCoNhaTieuHVS(int soHGDCoNhaTieuHVS);

	/**
	 * Returns the so nha tieu h v s xay moi of this danh gia ve sinh xa new.
	 *
	 * @return the so nha tieu h v s xay moi of this danh gia ve sinh xa new
	 */
	public int getSoNhaTieuHVSXayMoi();

	/**
	 * Sets the so nha tieu h v s xay moi of this danh gia ve sinh xa new.
	 *
	 * @param soNhaTieuHVSXayMoi the so nha tieu h v s xay moi of this danh gia ve sinh xa new
	 */
	public void setSoNhaTieuHVSXayMoi(int soNhaTieuHVSXayMoi);

	/**
	 * Returns the ti le h g d co nha tieu of this danh gia ve sinh xa new.
	 *
	 * @return the ti le h g d co nha tieu of this danh gia ve sinh xa new
	 */
	public int getTiLeHGDCoNhaTieu();

	/**
	 * Sets the ti le h g d co nha tieu of this danh gia ve sinh xa new.
	 *
	 * @param tiLeHGDCoNhaTieu the ti le h g d co nha tieu of this danh gia ve sinh xa new
	 */
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu);

	/**
	 * Returns the ti le h g d co nha tieu h v s of this danh gia ve sinh xa new.
	 *
	 * @return the ti le h g d co nha tieu h v s of this danh gia ve sinh xa new
	 */
	public int getTiLeHGDCoNhaTieuHVS();

	/**
	 * Sets the ti le h g d co nha tieu h v s of this danh gia ve sinh xa new.
	 *
	 * @param tiLeHGDCoNhaTieuHVS the ti le h g d co nha tieu h v s of this danh gia ve sinh xa new
	 */
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS);

	/**
	 * Returns the tong so truong hoc of this danh gia ve sinh xa new.
	 *
	 * @return the tong so truong hoc of this danh gia ve sinh xa new
	 */
	public int getTongSoTruongHoc();

	/**
	 * Sets the tong so truong hoc of this danh gia ve sinh xa new.
	 *
	 * @param tongSoTruongHoc the tong so truong hoc of this danh gia ve sinh xa new
	 */
	public void setTongSoTruongHoc(int tongSoTruongHoc);

	/**
	 * Returns the so truong hoc h v s of this danh gia ve sinh xa new.
	 *
	 * @return the so truong hoc h v s of this danh gia ve sinh xa new
	 */
	public int getSoTruongHocHVS();

	/**
	 * Sets the so truong hoc h v s of this danh gia ve sinh xa new.
	 *
	 * @param soTruongHocHVS the so truong hoc h v s of this danh gia ve sinh xa new
	 */
	public void setSoTruongHocHVS(int soTruongHocHVS);

	/**
	 * Returns the tong so tram y te of this danh gia ve sinh xa new.
	 *
	 * @return the tong so tram y te of this danh gia ve sinh xa new
	 */
	public int getTongSoTramYTe();

	/**
	 * Sets the tong so tram y te of this danh gia ve sinh xa new.
	 *
	 * @param tongSoTramYTe the tong so tram y te of this danh gia ve sinh xa new
	 */
	public void setTongSoTramYTe(int tongSoTramYTe);

	/**
	 * Returns the so tram y te h v s of this danh gia ve sinh xa new.
	 *
	 * @return the so tram y te h v s of this danh gia ve sinh xa new
	 */
	public int getSoTramYTeHVS();

	/**
	 * Sets the so tram y te h v s of this danh gia ve sinh xa new.
	 *
	 * @param soTramYTeHVS the so tram y te h v s of this danh gia ve sinh xa new
	 */
	public void setSoTramYTeHVS(int soTramYTeHVS);

	/**
	 * Returns the ti le truong hoc h v s of this danh gia ve sinh xa new.
	 *
	 * @return the ti le truong hoc h v s of this danh gia ve sinh xa new
	 */
	public int getTiLeTruongHocHVS();

	/**
	 * Sets the ti le truong hoc h v s of this danh gia ve sinh xa new.
	 *
	 * @param tiLeTruongHocHVS the ti le truong hoc h v s of this danh gia ve sinh xa new
	 */
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS);

	/**
	 * Returns the ti le tram y te h v s of this danh gia ve sinh xa new.
	 *
	 * @return the ti le tram y te h v s of this danh gia ve sinh xa new
	 */
	public int getTiLeTramYTeHVS();

	/**
	 * Sets the ti le tram y te h v s of this danh gia ve sinh xa new.
	 *
	 * @param tiLeTramYTeHVS the ti le tram y te h v s of this danh gia ve sinh xa new
	 */
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS);

	/**
	 * Returns the ket luan v s t x of this danh gia ve sinh xa new.
	 *
	 * @return the ket luan v s t x of this danh gia ve sinh xa new
	 */
	public int getKetLuanVSTX();

	/**
	 * Sets the ket luan v s t x of this danh gia ve sinh xa new.
	 *
	 * @param ketLuanVSTX the ket luan v s t x of this danh gia ve sinh xa new
	 */
	public void setKetLuanVSTX(int ketLuanVSTX);

	/**
	 * Returns the ghi chu of this danh gia ve sinh xa new.
	 *
	 * @return the ghi chu of this danh gia ve sinh xa new
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this danh gia ve sinh xa new.
	 *
	 * @param ghiChu the ghi chu of this danh gia ve sinh xa new
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the bao cao d l i of this danh gia ve sinh xa new.
	 *
	 * @return the bao cao d l i of this danh gia ve sinh xa new
	 */
	public int getBaoCaoDLI();

	/**
	 * Sets the bao cao d l i of this danh gia ve sinh xa new.
	 *
	 * @param baoCaoDLI the bao cao d l i of this danh gia ve sinh xa new
	 */
	public void setBaoCaoDLI(int baoCaoDLI);

	/**
	 * Returns the ngay tao of this danh gia ve sinh xa new.
	 *
	 * @return the ngay tao of this danh gia ve sinh xa new
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this danh gia ve sinh xa new.
	 *
	 * @param ngayTao the ngay tao of this danh gia ve sinh xa new
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this danh gia ve sinh xa new.
	 *
	 * @return the id nguoi tao of this danh gia ve sinh xa new
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this danh gia ve sinh xa new.
	 *
	 * @param idNguoiTao the id nguoi tao of this danh gia ve sinh xa new
	 */
	public void setIdNguoiTao(int idNguoiTao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DanhGiaVeSinhXaNew danhGiaVeSinhXaNew);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DanhGiaVeSinhXaNew> toCacheModel();

	@Override
	public DanhGiaVeSinhXaNew toEscapedModel();

	@Override
	public DanhGiaVeSinhXaNew toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}