/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KeHoachKiemDemVeSinh service. Represents a row in the &quot;ME_KEHOACHKIEMDEMVESINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.KeHoachKiemDemVeSinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.KeHoachKiemDemVeSinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see KeHoachKiemDemVeSinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.KeHoachKiemDemVeSinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.KeHoachKiemDemVeSinhModelImpl
 * @generated
 */
public interface KeHoachKiemDemVeSinhModel extends BaseModel<KeHoachKiemDemVeSinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ke hoach kiem dem ve sinh model instance should use the {@link KeHoachKiemDemVeSinh} interface instead.
	 */

	/**
	 * Returns the primary key of this ke hoach kiem dem ve sinh.
	 *
	 * @return the primary key of this ke hoach kiem dem ve sinh
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ke hoach kiem dem ve sinh.
	 *
	 * @param primaryKey the primary key of this ke hoach kiem dem ve sinh
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ID of this ke hoach kiem dem ve sinh
	 */
	public int getId();

	/**
	 * Sets the ID of this ke hoach kiem dem ve sinh.
	 *
	 * @param id the ID of this ke hoach kiem dem ve sinh
	 */
	public void setId(int id);

	/**
	 * Returns the nam of this ke hoach kiem dem ve sinh.
	 *
	 * @return the nam of this ke hoach kiem dem ve sinh
	 */
	public int getNam();

	/**
	 * Sets the nam of this ke hoach kiem dem ve sinh.
	 *
	 * @param nam the nam of this ke hoach kiem dem ve sinh
	 */
	public void setNam(int nam);

	/**
	 * Returns the ma tinh of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ma tinh of this ke hoach kiem dem ve sinh
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this ke hoach kiem dem ve sinh.
	 *
	 * @param maTinh the ma tinh of this ke hoach kiem dem ve sinh
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ma huyen of this ke hoach kiem dem ve sinh
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this ke hoach kiem dem ve sinh.
	 *
	 * @param maHuyen the ma huyen of this ke hoach kiem dem ve sinh
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the kiem dem vien i d of this ke hoach kiem dem ve sinh.
	 *
	 * @return the kiem dem vien i d of this ke hoach kiem dem ve sinh
	 */
	public int getKiemDemVienID();

	/**
	 * Sets the kiem dem vien i d of this ke hoach kiem dem ve sinh.
	 *
	 * @param kiemDemVienID the kiem dem vien i d of this ke hoach kiem dem ve sinh
	 */
	public void setKiemDemVienID(int kiemDemVienID);

	/**
	 * Returns the ngay bat dau of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ngay bat dau of this ke hoach kiem dem ve sinh
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this ke hoach kiem dem ve sinh.
	 *
	 * @param ngayBatDau the ngay bat dau of this ke hoach kiem dem ve sinh
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay ket thuc of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ngay ket thuc of this ke hoach kiem dem ve sinh
	 */
	public Date getNgayKetThuc();

	/**
	 * Sets the ngay ket thuc of this ke hoach kiem dem ve sinh.
	 *
	 * @param ngayKetThuc the ngay ket thuc of this ke hoach kiem dem ve sinh
	 */
	public void setNgayKetThuc(Date ngayKetThuc);

	/**
	 * Returns the mo ta of this ke hoach kiem dem ve sinh.
	 *
	 * @return the mo ta of this ke hoach kiem dem ve sinh
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this ke hoach kiem dem ve sinh.
	 *
	 * @param moTa the mo ta of this ke hoach kiem dem ve sinh
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the ngay tao of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ngay tao of this ke hoach kiem dem ve sinh
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ke hoach kiem dem ve sinh.
	 *
	 * @param ngayTao the ngay tao of this ke hoach kiem dem ve sinh
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the id nguoi tao of this ke hoach kiem dem ve sinh.
	 *
	 * @return the id nguoi tao of this ke hoach kiem dem ve sinh
	 */
	public int getIdNguoiTao();

	/**
	 * Sets the id nguoi tao of this ke hoach kiem dem ve sinh.
	 *
	 * @param idNguoiTao the id nguoi tao of this ke hoach kiem dem ve sinh
	 */
	public void setIdNguoiTao(int idNguoiTao);

	/**
	 * Returns the ngay xuat ban of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ngay xuat ban of this ke hoach kiem dem ve sinh
	 */
	public Date getNgayXuatBan();

	/**
	 * Sets the ngay xuat ban of this ke hoach kiem dem ve sinh.
	 *
	 * @param ngayXuatBan the ngay xuat ban of this ke hoach kiem dem ve sinh
	 */
	public void setNgayXuatBan(Date ngayXuatBan);

	/**
	 * Returns the id nguoi xuat ban of this ke hoach kiem dem ve sinh.
	 *
	 * @return the id nguoi xuat ban of this ke hoach kiem dem ve sinh
	 */
	public int getIdNguoiXuatBan();

	/**
	 * Sets the id nguoi xuat ban of this ke hoach kiem dem ve sinh.
	 *
	 * @param idNguoiXuatBan the id nguoi xuat ban of this ke hoach kiem dem ve sinh
	 */
	public void setIdNguoiXuatBan(int idNguoiXuatBan);

	/**
	 * Returns the table ID of this ke hoach kiem dem ve sinh.
	 *
	 * @return the table ID of this ke hoach kiem dem ve sinh
	 */
	@AutoEscape
	public String getTableId();

	/**
	 * Sets the table ID of this ke hoach kiem dem ve sinh.
	 *
	 * @param tableId the table ID of this ke hoach kiem dem ve sinh
	 */
	public void setTableId(String tableId);

	/**
	 * Returns the ngay dong of this ke hoach kiem dem ve sinh.
	 *
	 * @return the ngay dong of this ke hoach kiem dem ve sinh
	 */
	public Date getNgayDong();

	/**
	 * Sets the ngay dong of this ke hoach kiem dem ve sinh.
	 *
	 * @param ngayDong the ngay dong of this ke hoach kiem dem ve sinh
	 */
	public void setNgayDong(Date ngayDong);

	/**
	 * Returns the id nguoi dong of this ke hoach kiem dem ve sinh.
	 *
	 * @return the id nguoi dong of this ke hoach kiem dem ve sinh
	 */
	public int getIdNguoiDong();

	/**
	 * Sets the id nguoi dong of this ke hoach kiem dem ve sinh.
	 *
	 * @param idNguoiDong the id nguoi dong of this ke hoach kiem dem ve sinh
	 */
	public void setIdNguoiDong(int idNguoiDong);

	/**
	 * Returns the last save point of this ke hoach kiem dem ve sinh.
	 *
	 * @return the last save point of this ke hoach kiem dem ve sinh
	 */
	public Date getLastSavePoint();

	/**
	 * Sets the last save point of this ke hoach kiem dem ve sinh.
	 *
	 * @param lastSavePoint the last save point of this ke hoach kiem dem ve sinh
	 */
	public void setLastSavePoint(Date lastSavePoint);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KeHoachKiemDemVeSinh keHoachKiemDemVeSinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KeHoachKiemDemVeSinh> toCacheModel();

	@Override
	public KeHoachKiemDemVeSinh toEscapedModel();

	@Override
	public KeHoachKiemDemVeSinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}