/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThongTinKiemDemCongTrinh service. Represents a row in the &quot;ME_THONGTINKIEMDEMCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemCongTrinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ThongTinKiemDemCongTrinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemCongTrinhModelImpl
 * @generated
 */
public interface ThongTinKiemDemCongTrinhModel extends BaseModel<ThongTinKiemDemCongTrinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thong tin kiem dem cong trinh model instance should use the {@link ThongTinKiemDemCongTrinh} interface instead.
	 */

	/**
	 * Returns the primary key of this thong tin kiem dem cong trinh.
	 *
	 * @return the primary key of this thong tin kiem dem cong trinh
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this thong tin kiem dem cong trinh.
	 *
	 * @param primaryKey the primary key of this thong tin kiem dem cong trinh
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this thong tin kiem dem cong trinh.
	 *
	 * @return the ID of this thong tin kiem dem cong trinh
	 */
	public int getId();

	/**
	 * Sets the ID of this thong tin kiem dem cong trinh.
	 *
	 * @param id the ID of this thong tin kiem dem cong trinh
	 */
	public void setId(int id);

	/**
	 * Returns the ve sinh con trinh ID of this thong tin kiem dem cong trinh.
	 *
	 * @return the ve sinh con trinh ID of this thong tin kiem dem cong trinh
	 */
	public int getVeSinhConTrinhId();

	/**
	 * Sets the ve sinh con trinh ID of this thong tin kiem dem cong trinh.
	 *
	 * @param veSinhConTrinhId the ve sinh con trinh ID of this thong tin kiem dem cong trinh
	 */
	public void setVeSinhConTrinhId(int veSinhConTrinhId);

	/**
	 * Returns the ke hoach kiem dem ve sinh ID of this thong tin kiem dem cong trinh.
	 *
	 * @return the ke hoach kiem dem ve sinh ID of this thong tin kiem dem cong trinh
	 */
	public int getKeHoachKiemDemVeSinhId();

	/**
	 * Sets the ke hoach kiem dem ve sinh ID of this thong tin kiem dem cong trinh.
	 *
	 * @param keHoachKiemDemVeSinhId the ke hoach kiem dem ve sinh ID of this thong tin kiem dem cong trinh
	 */
	public void setKeHoachKiemDemVeSinhId(int keHoachKiemDemVeSinhId);

	/**
	 * Returns the ten cong trinh of this thong tin kiem dem cong trinh.
	 *
	 * @return the ten cong trinh of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getTenCongTrinh();

	/**
	 * Sets the ten cong trinh of this thong tin kiem dem cong trinh.
	 *
	 * @param tenCongTrinh the ten cong trinh of this thong tin kiem dem cong trinh
	 */
	public void setTenCongTrinh(String tenCongTrinh);

	/**
	 * Returns the loai cong trinh of this thong tin kiem dem cong trinh.
	 *
	 * @return the loai cong trinh of this thong tin kiem dem cong trinh
	 */
	public int getLoaiCongTrinh();

	/**
	 * Sets the loai cong trinh of this thong tin kiem dem cong trinh.
	 *
	 * @param loaiCongTrinh the loai cong trinh of this thong tin kiem dem cong trinh
	 */
	public void setLoaiCongTrinh(int loaiCongTrinh);

	/**
	 * Returns the ma tinh of this thong tin kiem dem cong trinh.
	 *
	 * @return the ma tinh of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this thong tin kiem dem cong trinh.
	 *
	 * @param maTinh the ma tinh of this thong tin kiem dem cong trinh
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this thong tin kiem dem cong trinh.
	 *
	 * @return the ma huyen of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this thong tin kiem dem cong trinh.
	 *
	 * @param maHuyen the ma huyen of this thong tin kiem dem cong trinh
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this thong tin kiem dem cong trinh.
	 *
	 * @return the ma xa of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this thong tin kiem dem cong trinh.
	 *
	 * @param maXa the ma xa of this thong tin kiem dem cong trinh
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the dia chi of this thong tin kiem dem cong trinh.
	 *
	 * @return the dia chi of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this thong tin kiem dem cong trinh.
	 *
	 * @param diaChi the dia chi of this thong tin kiem dem cong trinh
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the ngay kiem dem of this thong tin kiem dem cong trinh.
	 *
	 * @return the ngay kiem dem of this thong tin kiem dem cong trinh
	 */
	public Date getNgayKiemDem();

	/**
	 * Sets the ngay kiem dem of this thong tin kiem dem cong trinh.
	 *
	 * @param ngayKiemDem the ngay kiem dem of this thong tin kiem dem cong trinh
	 */
	public void setNgayKiemDem(Date ngayKiemDem);

	/**
	 * Returns the ho ten nguoi tra loi of this thong tin kiem dem cong trinh.
	 *
	 * @return the ho ten nguoi tra loi of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getHoTenNguoiTraLoi();

	/**
	 * Sets the ho ten nguoi tra loi of this thong tin kiem dem cong trinh.
	 *
	 * @param hoTenNguoiTraLoi the ho ten nguoi tra loi of this thong tin kiem dem cong trinh
	 */
	public void setHoTenNguoiTraLoi(String hoTenNguoiTraLoi);

	/**
	 * Returns the so dien thoai of this thong tin kiem dem cong trinh.
	 *
	 * @return the so dien thoai of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getSoDienThoai();

	/**
	 * Sets the so dien thoai of this thong tin kiem dem cong trinh.
	 *
	 * @param soDienThoai the so dien thoai of this thong tin kiem dem cong trinh
	 */
	public void setSoDienThoai(String soDienThoai);

	/**
	 * Returns the gioi tinh nguoi tra loi of this thong tin kiem dem cong trinh.
	 *
	 * @return the gioi tinh nguoi tra loi of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getGioiTinhNguoiTraLoi();

	/**
	 * Sets the gioi tinh nguoi tra loi of this thong tin kiem dem cong trinh.
	 *
	 * @param gioiTinhNguoiTraLoi the gioi tinh nguoi tra loi of this thong tin kiem dem cong trinh
	 */
	public void setGioiTinhNguoiTraLoi(String gioiTinhNguoiTraLoi);

	/**
	 * Returns the vai tro chuc danh of this thong tin kiem dem cong trinh.
	 *
	 * @return the vai tro chuc danh of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getVaiTroChucDanh();

	/**
	 * Sets the vai tro chuc danh of this thong tin kiem dem cong trinh.
	 *
	 * @param vaiTroChucDanh the vai tro chuc danh of this thong tin kiem dem cong trinh
	 */
	public void setVaiTroChucDanh(String vaiTroChucDanh);

	/**
	 * Returns the so ca of this thong tin kiem dem cong trinh.
	 *
	 * @return the so ca of this thong tin kiem dem cong trinh
	 */
	public int getSoCa();

	/**
	 * Sets the so ca of this thong tin kiem dem cong trinh.
	 *
	 * @param soCa the so ca of this thong tin kiem dem cong trinh
	 */
	public void setSoCa(int soCa);

	/**
	 * Returns the so nguoi trong ca of this thong tin kiem dem cong trinh.
	 *
	 * @return the so nguoi trong ca of this thong tin kiem dem cong trinh
	 */
	public int getSoNguoiTrongCa();

	/**
	 * Sets the so nguoi trong ca of this thong tin kiem dem cong trinh.
	 *
	 * @param soNguoiTrongCa the so nguoi trong ca of this thong tin kiem dem cong trinh
	 */
	public void setSoNguoiTrongCa(int soNguoiTrongCa);

	/**
	 * Returns the kinh do of this thong tin kiem dem cong trinh.
	 *
	 * @return the kinh do of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getKinhDo();

	/**
	 * Sets the kinh do of this thong tin kiem dem cong trinh.
	 *
	 * @param kinhDo the kinh do of this thong tin kiem dem cong trinh
	 */
	public void setKinhDo(String kinhDo);

	/**
	 * Returns the vi do of this thong tin kiem dem cong trinh.
	 *
	 * @return the vi do of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getViDo();

	/**
	 * Sets the vi do of this thong tin kiem dem cong trinh.
	 *
	 * @param viDo the vi do of this thong tin kiem dem cong trinh
	 */
	public void setViDo(String viDo);

	/**
	 * Returns the loai nguon nuoc of this thong tin kiem dem cong trinh.
	 *
	 * @return the loai nguon nuoc of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getLoaiNguonNuoc();

	/**
	 * Sets the loai nguon nuoc of this thong tin kiem dem cong trinh.
	 *
	 * @param loaiNguonNuoc the loai nguon nuoc of this thong tin kiem dem cong trinh
	 */
	public void setLoaiNguonNuoc(String loaiNguonNuoc);

	/**
	 * Returns the da t q c v n of this thong tin kiem dem cong trinh.
	 *
	 * @return the da t q c v n of this thong tin kiem dem cong trinh
	 */
	public int getDaTQCVN();

	/**
	 * Sets the da t q c v n of this thong tin kiem dem cong trinh.
	 *
	 * @param daTQCVN the da t q c v n of this thong tin kiem dem cong trinh
	 */
	public void setDaTQCVN(int daTQCVN);

	/**
	 * Returns the dat tieu chuan h v s of this thong tin kiem dem cong trinh.
	 *
	 * @return the dat tieu chuan h v s of this thong tin kiem dem cong trinh
	 */
	public int getDatTieuChuanHVS();

	/**
	 * Sets the dat tieu chuan h v s of this thong tin kiem dem cong trinh.
	 *
	 * @param datTieuChuanHVS the dat tieu chuan h v s of this thong tin kiem dem cong trinh
	 */
	public void setDatTieuChuanHVS(int datTieuChuanHVS);

	/**
	 * Returns the anh chup chung nhan of this thong tin kiem dem cong trinh.
	 *
	 * @return the anh chup chung nhan of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getAnhChupChungNhan();

	/**
	 * Sets the anh chup chung nhan of this thong tin kiem dem cong trinh.
	 *
	 * @param anhChupChungNhan the anh chup chung nhan of this thong tin kiem dem cong trinh
	 */
	public void setAnhChupChungNhan(String anhChupChungNhan);

	/**
	 * Returns the so nha tieu of this thong tin kiem dem cong trinh.
	 *
	 * @return the so nha tieu of this thong tin kiem dem cong trinh
	 */
	public int getSoNhaTieu();

	/**
	 * Sets the so nha tieu of this thong tin kiem dem cong trinh.
	 *
	 * @param soNhaTieu the so nha tieu of this thong tin kiem dem cong trinh
	 */
	public void setSoNhaTieu(int soNhaTieu);

	/**
	 * Returns the ghi chu of this thong tin kiem dem cong trinh.
	 *
	 * @return the ghi chu of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this thong tin kiem dem cong trinh.
	 *
	 * @param ghiChu the ghi chu of this thong tin kiem dem cong trinh
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the da ket thuc dieu tra of this thong tin kiem dem cong trinh.
	 *
	 * @return the da ket thuc dieu tra of this thong tin kiem dem cong trinh
	 */
	public int getDaKetThucDieuTra();

	/**
	 * Sets the da ket thuc dieu tra of this thong tin kiem dem cong trinh.
	 *
	 * @param daKetThucDieuTra the da ket thuc dieu tra of this thong tin kiem dem cong trinh
	 */
	public void setDaKetThucDieuTra(int daKetThucDieuTra);

	/**
	 * Returns the ly do khong hoan thanh of this thong tin kiem dem cong trinh.
	 *
	 * @return the ly do khong hoan thanh of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getLyDoKhongHoanThanh();

	/**
	 * Sets the ly do khong hoan thanh of this thong tin kiem dem cong trinh.
	 *
	 * @param lyDoKhongHoanThanh the ly do khong hoan thanh of this thong tin kiem dem cong trinh
	 */
	public void setLyDoKhongHoanThanh(String lyDoKhongHoanThanh);

	/**
	 * Returns the imei of this thong tin kiem dem cong trinh.
	 *
	 * @return the imei of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getImei();

	/**
	 * Sets the imei of this thong tin kiem dem cong trinh.
	 *
	 * @param imei the imei of this thong tin kiem dem cong trinh
	 */
	public void setImei(String imei);

	/**
	 * Returns the tai khoan of this thong tin kiem dem cong trinh.
	 *
	 * @return the tai khoan of this thong tin kiem dem cong trinh
	 */
	@AutoEscape
	public String getTaiKhoan();

	/**
	 * Sets the tai khoan of this thong tin kiem dem cong trinh.
	 *
	 * @param taiKhoan the tai khoan of this thong tin kiem dem cong trinh
	 */
	public void setTaiKhoan(String taiKhoan);

	/**
	 * Returns the danh gia kiem dem of this thong tin kiem dem cong trinh.
	 *
	 * @return the danh gia kiem dem of this thong tin kiem dem cong trinh
	 */
	public int getDanhGiaKiemDem();

	/**
	 * Sets the danh gia kiem dem of this thong tin kiem dem cong trinh.
	 *
	 * @param danhGiaKiemDem the danh gia kiem dem of this thong tin kiem dem cong trinh
	 */
	public void setDanhGiaKiemDem(int danhGiaKiemDem);

	/**
	 * Returns the save point of this thong tin kiem dem cong trinh.
	 *
	 * @return the save point of this thong tin kiem dem cong trinh
	 */
	public Date getSavePoint();

	/**
	 * Sets the save point of this thong tin kiem dem cong trinh.
	 *
	 * @param savePoint the save point of this thong tin kiem dem cong trinh
	 */
	public void setSavePoint(Date savePoint);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThongTinKiemDemCongTrinh thongTinKiemDemCongTrinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThongTinKiemDemCongTrinh> toCacheModel();

	@Override
	public ThongTinKiemDemCongTrinh toEscapedModel();

	@Override
	public ThongTinKiemDemCongTrinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}