/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.kehoachvesinh.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh;
import vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the KeHoachVeSinh service. Represents a row in the &quot;ME_KEHOACHVESINHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KeHoachVeSinhImpl}.
 * </p>
 *
 * @author HANT
 * @see KeHoachVeSinhImpl
 * @see vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh
 * @see vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinhModel
 * @generated
 */
public class KeHoachVeSinhModelImpl extends BaseModelImpl<KeHoachVeSinh>
	implements KeHoachVeSinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ke hoach ve sinh model instance should use the {@link vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_KEHOACHVESINHXA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "NAM", Types.BIGINT },
			{ "SONHATIEUHVSMOI", Types.BIGINT },
			{ "SODAN", Types.BIGINT },
			{ "DANGKYVSTX", Types.BIGINT },
			{ "GHICHU", Types.VARCHAR },
			{ "BAOCAODLI", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_KEHOACHVESINHXA (ID LONG not null primary key,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,NAM LONG,SONHATIEUHVSMOI LONG,SODAN LONG,DANGKYVSTX LONG,GHICHU VARCHAR(75) null,BAOCAODLI LONG,NGAYTAO DATE null,IDNGUOITAO LONG)";
	public static final String TABLE_SQL_DROP = "drop table ME_KEHOACHVESINHXA";
	public static final String ORDER_BY_JPQL = " ORDER BY keHoachVeSinh.nam DESC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_KEHOACHVESINHXA.NAM DESC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh"),
			true);
	public static long BAOCAODLI_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static long IDNGUOITAO_COLUMN_BITMASK = 4L;
	public static long MAHUYEN_COLUMN_BITMASK = 8L;
	public static long MATINH_COLUMN_BITMASK = 16L;
	public static long MAXA_COLUMN_BITMASK = 32L;
	public static long NAM_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh"));

	public KeHoachVeSinhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KeHoachVeSinh.class;
	}

	@Override
	public String getModelClassName() {
		return KeHoachVeSinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("nam", getNam());
		attributes.put("soNhaTieuHVSMoi", getSoNhaTieuHVSMoi());
		attributes.put("soDan", getSoDan());
		attributes.put("dangKyVSTX", getDangKyVSTX());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("baoCaoDLI", getBaoCaoDLI());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		Long nam = (Long)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Long soNhaTieuHVSMoi = (Long)attributes.get("soNhaTieuHVSMoi");

		if (soNhaTieuHVSMoi != null) {
			setSoNhaTieuHVSMoi(soNhaTieuHVSMoi);
		}

		Long soDan = (Long)attributes.get("soDan");

		if (soDan != null) {
			setSoDan(soDan);
		}

		Long dangKyVSTX = (Long)attributes.get("dangKyVSTX");

		if (dangKyVSTX != null) {
			setDangKyVSTX(dangKyVSTX);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Long baoCaoDLI = (Long)attributes.get("baoCaoDLI");

		if (baoCaoDLI != null) {
			setBaoCaoDLI(baoCaoDLI);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Long idNguoiTao = (Long)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_columnBitmask |= MATINH_COLUMN_BITMASK;

		if (_originalMaTinh == null) {
			_originalMaTinh = _maTinh;
		}

		_maTinh = maTinh;
	}

	public String getOriginalMaTinh() {
		return GetterUtil.getString(_originalMaTinh);
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_columnBitmask |= MAHUYEN_COLUMN_BITMASK;

		if (_originalMaHuyen == null) {
			_originalMaHuyen = _maHuyen;
		}

		_maHuyen = maHuyen;
	}

	public String getOriginalMaHuyen() {
		return GetterUtil.getString(_originalMaHuyen);
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_columnBitmask |= MAXA_COLUMN_BITMASK;

		if (_originalMaXa == null) {
			_originalMaXa = _maXa;
		}

		_maXa = maXa;
	}

	public String getOriginalMaXa() {
		return GetterUtil.getString(_originalMaXa);
	}

	@Override
	public long getNam() {
		return _nam;
	}

	@Override
	public void setNam(long nam) {
		_columnBitmask = -1L;

		if (!_setOriginalNam) {
			_setOriginalNam = true;

			_originalNam = _nam;
		}

		_nam = nam;
	}

	public long getOriginalNam() {
		return _originalNam;
	}

	@Override
	public long getSoNhaTieuHVSMoi() {
		return _soNhaTieuHVSMoi;
	}

	@Override
	public void setSoNhaTieuHVSMoi(long soNhaTieuHVSMoi) {
		_soNhaTieuHVSMoi = soNhaTieuHVSMoi;
	}

	@Override
	public long getSoDan() {
		return _soDan;
	}

	@Override
	public void setSoDan(long soDan) {
		_soDan = soDan;
	}

	@Override
	public long getDangKyVSTX() {
		return _dangKyVSTX;
	}

	@Override
	public void setDangKyVSTX(long dangKyVSTX) {
		_dangKyVSTX = dangKyVSTX;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public long getBaoCaoDLI() {
		return _baoCaoDLI;
	}

	@Override
	public void setBaoCaoDLI(long baoCaoDLI) {
		_columnBitmask |= BAOCAODLI_COLUMN_BITMASK;

		if (!_setOriginalBaoCaoDLI) {
			_setOriginalBaoCaoDLI = true;

			_originalBaoCaoDLI = _baoCaoDLI;
		}

		_baoCaoDLI = baoCaoDLI;
	}

	public long getOriginalBaoCaoDLI() {
		return _originalBaoCaoDLI;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public long getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(long idNguoiTao) {
		_columnBitmask |= IDNGUOITAO_COLUMN_BITMASK;

		if (!_setOriginalIdNguoiTao) {
			_setOriginalIdNguoiTao = true;

			_originalIdNguoiTao = _idNguoiTao;
		}

		_idNguoiTao = idNguoiTao;
	}

	public long getOriginalIdNguoiTao() {
		return _originalIdNguoiTao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			KeHoachVeSinh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KeHoachVeSinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (KeHoachVeSinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KeHoachVeSinhImpl keHoachVeSinhImpl = new KeHoachVeSinhImpl();

		keHoachVeSinhImpl.setId(getId());
		keHoachVeSinhImpl.setMaTinh(getMaTinh());
		keHoachVeSinhImpl.setMaHuyen(getMaHuyen());
		keHoachVeSinhImpl.setMaXa(getMaXa());
		keHoachVeSinhImpl.setNam(getNam());
		keHoachVeSinhImpl.setSoNhaTieuHVSMoi(getSoNhaTieuHVSMoi());
		keHoachVeSinhImpl.setSoDan(getSoDan());
		keHoachVeSinhImpl.setDangKyVSTX(getDangKyVSTX());
		keHoachVeSinhImpl.setGhiChu(getGhiChu());
		keHoachVeSinhImpl.setBaoCaoDLI(getBaoCaoDLI());
		keHoachVeSinhImpl.setNgayTao(getNgayTao());
		keHoachVeSinhImpl.setIdNguoiTao(getIdNguoiTao());

		keHoachVeSinhImpl.resetOriginalValues();

		return keHoachVeSinhImpl;
	}

	@Override
	public int compareTo(KeHoachVeSinh keHoachVeSinh) {
		int value = 0;

		if (getNam() < keHoachVeSinh.getNam()) {
			value = -1;
		}
		else if (getNam() > keHoachVeSinh.getNam()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof KeHoachVeSinh)) {
			return false;
		}

		KeHoachVeSinh keHoachVeSinh = (KeHoachVeSinh)obj;

		long primaryKey = keHoachVeSinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		KeHoachVeSinhModelImpl keHoachVeSinhModelImpl = this;

		keHoachVeSinhModelImpl._originalId = keHoachVeSinhModelImpl._id;

		keHoachVeSinhModelImpl._setOriginalId = false;

		keHoachVeSinhModelImpl._originalMaTinh = keHoachVeSinhModelImpl._maTinh;

		keHoachVeSinhModelImpl._originalMaHuyen = keHoachVeSinhModelImpl._maHuyen;

		keHoachVeSinhModelImpl._originalMaXa = keHoachVeSinhModelImpl._maXa;

		keHoachVeSinhModelImpl._originalNam = keHoachVeSinhModelImpl._nam;

		keHoachVeSinhModelImpl._setOriginalNam = false;

		keHoachVeSinhModelImpl._originalBaoCaoDLI = keHoachVeSinhModelImpl._baoCaoDLI;

		keHoachVeSinhModelImpl._setOriginalBaoCaoDLI = false;

		keHoachVeSinhModelImpl._originalIdNguoiTao = keHoachVeSinhModelImpl._idNguoiTao;

		keHoachVeSinhModelImpl._setOriginalIdNguoiTao = false;

		keHoachVeSinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<KeHoachVeSinh> toCacheModel() {
		KeHoachVeSinhCacheModel keHoachVeSinhCacheModel = new KeHoachVeSinhCacheModel();

		keHoachVeSinhCacheModel.id = getId();

		keHoachVeSinhCacheModel.maTinh = getMaTinh();

		String maTinh = keHoachVeSinhCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			keHoachVeSinhCacheModel.maTinh = null;
		}

		keHoachVeSinhCacheModel.maHuyen = getMaHuyen();

		String maHuyen = keHoachVeSinhCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			keHoachVeSinhCacheModel.maHuyen = null;
		}

		keHoachVeSinhCacheModel.maXa = getMaXa();

		String maXa = keHoachVeSinhCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			keHoachVeSinhCacheModel.maXa = null;
		}

		keHoachVeSinhCacheModel.nam = getNam();

		keHoachVeSinhCacheModel.soNhaTieuHVSMoi = getSoNhaTieuHVSMoi();

		keHoachVeSinhCacheModel.soDan = getSoDan();

		keHoachVeSinhCacheModel.dangKyVSTX = getDangKyVSTX();

		keHoachVeSinhCacheModel.ghiChu = getGhiChu();

		String ghiChu = keHoachVeSinhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			keHoachVeSinhCacheModel.ghiChu = null;
		}

		keHoachVeSinhCacheModel.baoCaoDLI = getBaoCaoDLI();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			keHoachVeSinhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			keHoachVeSinhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		keHoachVeSinhCacheModel.idNguoiTao = getIdNguoiTao();

		return keHoachVeSinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", soNhaTieuHVSMoi=");
		sb.append(getSoNhaTieuHVSMoi());
		sb.append(", soDan=");
		sb.append(getSoDan());
		sb.append(", dangKyVSTX=");
		sb.append(getDangKyVSTX());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", baoCaoDLI=");
		sb.append(getBaoCaoDLI());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.kehoachvesinh.dao.model.KeHoachVeSinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNhaTieuHVSMoi</column-name><column-value><![CDATA[");
		sb.append(getSoNhaTieuHVSMoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDan</column-name><column-value><![CDATA[");
		sb.append(getSoDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dangKyVSTX</column-name><column-value><![CDATA[");
		sb.append(getDangKyVSTX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>baoCaoDLI</column-name><column-value><![CDATA[");
		sb.append(getBaoCaoDLI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = KeHoachVeSinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			KeHoachVeSinh.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _maTinh;
	private String _originalMaTinh;
	private String _maHuyen;
	private String _originalMaHuyen;
	private String _maXa;
	private String _originalMaXa;
	private long _nam;
	private long _originalNam;
	private boolean _setOriginalNam;
	private long _soNhaTieuHVSMoi;
	private long _soDan;
	private long _dangKyVSTX;
	private String _ghiChu;
	private long _baoCaoDLI;
	private long _originalBaoCaoDLI;
	private boolean _setOriginalBaoCaoDLI;
	private Date _ngayTao;
	private long _idNguoiTao;
	private long _originalIdNguoiTao;
	private boolean _setOriginalIdNguoiTao;
	private long _columnBitmask;
	private KeHoachVeSinh _escapedModel;
}