/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD;
import vn.dtt.sol.ns.vesinhmoitruong.dao.service.ThongTinKiemDemHoGDLocalServiceUtil;

/**
 * The extended model base implementation for the ThongTinKiemDemHoGD service. Represents a row in the &quot;ME_THONGTINKIEMDEMHOGD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongTinKiemDemHoGDImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ThongTinKiemDemHoGDImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD
 * @generated
 */
public abstract class ThongTinKiemDemHoGDBaseImpl
	extends ThongTinKiemDemHoGDModelImpl implements ThongTinKiemDemHoGD {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong tin kiem dem ho g d model instance should use the {@link ThongTinKiemDemHoGD} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ThongTinKiemDemHoGDLocalServiceUtil.addThongTinKiemDemHoGD(this);
		}
		else {
			ThongTinKiemDemHoGDLocalServiceUtil.updateThongTinKiemDemHoGD(this);
		}
	}
}