/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VeSinhGiaDinh service. Represents a row in the &quot;ME_VESINHGIADINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VeSinhGiaDinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see VeSinhGiaDinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinhModel
 * @generated
 */
public class VeSinhGiaDinhModelImpl extends BaseModelImpl<VeSinhGiaDinh>
	implements VeSinhGiaDinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ve sinh gia dinh model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_VESINHGIADINH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "THONXOM", Types.VARCHAR },
			{ "TENCHUHO", Types.VARCHAR },
			{ "GIOITINHCHUHO", Types.INTEGER },
			{ "TRANGTHAI", Types.INTEGER },
			{ "MAUNGAUNHIEN", Types.INTEGER },
			{ "NAMBAOCAO", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.INTEGER },
			{ "SONGUOITRONGHO", Types.INTEGER },
			{ "THANHPHANHOGD", Types.INTEGER },
			{ "KINHDO", Types.VARCHAR },
			{ "VIDO", Types.VARCHAR },
			{ "CONHATIEU", Types.INTEGER },
			{ "NHATIEUHVS", Types.INTEGER },
			{ "LOAINHATIEU", Types.VARCHAR },
			{ "DUOCCAITAO", Types.INTEGER },
			{ "THANGXAYDUNG", Types.INTEGER },
			{ "NAMXAYDUNG", Types.INTEGER },
			{ "NGUONVON", Types.INTEGER },
			{ "NGAYKIEMDEM", Types.TIMESTAMP },
			{ "NGAYDANHGIA", Types.TIMESTAMP },
			{ "IDNGUOIDANHGIA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_VESINHGIADINH (ID INTEGER not null primary key,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,THONXOM VARCHAR(75) null,TENCHUHO VARCHAR(75) null,GIOITINHCHUHO INTEGER,TRANGTHAI INTEGER,MAUNGAUNHIEN INTEGER,NAMBAOCAO INTEGER,GHICHU VARCHAR(75) null,NGAYTAO DATE null,IDNGUOITAO INTEGER,SONGUOITRONGHO INTEGER,THANHPHANHOGD INTEGER,KINHDO VARCHAR(75) null,VIDO VARCHAR(75) null,CONHATIEU INTEGER,NHATIEUHVS INTEGER,LOAINHATIEU VARCHAR(75) null,DUOCCAITAO INTEGER,THANGXAYDUNG INTEGER,NAMXAYDUNG INTEGER,NGUONVON INTEGER,NGAYKIEMDEM DATE null,NGAYDANHGIA DATE null,IDNGUOIDANHGIA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ME_VESINHGIADINH";
	public static final String ORDER_BY_JPQL = " ORDER BY veSinhGiaDinh.maTinh ASC, veSinhGiaDinh.maHuyen ASC, veSinhGiaDinh.maXa ASC, veSinhGiaDinh.thonXom ASC, veSinhGiaDinh.loaiNhaTieu ASC, veSinhGiaDinh.tenChuHo ASC, veSinhGiaDinh.trangThai ASC, veSinhGiaDinh.namBaoCao ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_VESINHGIADINH.MATINH ASC, ME_VESINHGIADINH.MAHUYEN ASC, ME_VESINHGIADINH.MAXA ASC, ME_VESINHGIADINH.THONXOM ASC, ME_VESINHGIADINH.LOAINHATIEU ASC, ME_VESINHGIADINH.TENCHUHO ASC, ME_VESINHGIADINH.TRANGTHAI ASC, ME_VESINHGIADINH.NAMBAOCAO ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh"),
			true);
	public static long IDNGUOITAO_COLUMN_BITMASK = 1L;
	public static long MAHUYEN_COLUMN_BITMASK = 2L;
	public static long MATINH_COLUMN_BITMASK = 4L;
	public static long MAXA_COLUMN_BITMASK = 8L;
	public static long MAUNGAUNHIEN_COLUMN_BITMASK = 16L;
	public static long TENCHUHO_COLUMN_BITMASK = 32L;
	public static long THONXOM_COLUMN_BITMASK = 64L;
	public static long LOAINHATIEU_COLUMN_BITMASK = 128L;
	public static long TRANGTHAI_COLUMN_BITMASK = 256L;
	public static long NAMBAOCAO_COLUMN_BITMASK = 512L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh"));

	public VeSinhGiaDinhModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VeSinhGiaDinh.class;
	}

	@Override
	public String getModelClassName() {
		return VeSinhGiaDinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("thonXom", getThonXom());
		attributes.put("tenChuHo", getTenChuHo());
		attributes.put("gioiTinhChuHo", getGioiTinhChuHo());
		attributes.put("trangThai", getTrangThai());
		attributes.put("mauNgauNhien", getMauNgauNhien());
		attributes.put("namBaoCao", getNamBaoCao());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("soNguoiTrongHo", getSoNguoiTrongHo());
		attributes.put("thanhPhanHoGD", getThanhPhanHoGD());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("coNhaTieu", getCoNhaTieu());
		attributes.put("nhaTieuHVS", getNhaTieuHVS());
		attributes.put("loaiNhaTieu", getLoaiNhaTieu());
		attributes.put("duocCaiTao", getDuocCaiTao());
		attributes.put("thangXayDung", getThangXayDung());
		attributes.put("namXayDung", getNamXayDung());
		attributes.put("nguonVon", getNguonVon());
		attributes.put("ngayKiemDem", getNgayKiemDem());
		attributes.put("ngayDanhGia", getNgayDanhGia());
		attributes.put("idNguoiDanhGia", getIdNguoiDanhGia());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String thonXom = (String)attributes.get("thonXom");

		if (thonXom != null) {
			setThonXom(thonXom);
		}

		String tenChuHo = (String)attributes.get("tenChuHo");

		if (tenChuHo != null) {
			setTenChuHo(tenChuHo);
		}

		Integer gioiTinhChuHo = (Integer)attributes.get("gioiTinhChuHo");

		if (gioiTinhChuHo != null) {
			setGioiTinhChuHo(gioiTinhChuHo);
		}

		Integer trangThai = (Integer)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Integer mauNgauNhien = (Integer)attributes.get("mauNgauNhien");

		if (mauNgauNhien != null) {
			setMauNgauNhien(mauNgauNhien);
		}

		Integer namBaoCao = (Integer)attributes.get("namBaoCao");

		if (namBaoCao != null) {
			setNamBaoCao(namBaoCao);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Integer idNguoiTao = (Integer)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		Integer soNguoiTrongHo = (Integer)attributes.get("soNguoiTrongHo");

		if (soNguoiTrongHo != null) {
			setSoNguoiTrongHo(soNguoiTrongHo);
		}

		Integer thanhPhanHoGD = (Integer)attributes.get("thanhPhanHoGD");

		if (thanhPhanHoGD != null) {
			setThanhPhanHoGD(thanhPhanHoGD);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		Integer coNhaTieu = (Integer)attributes.get("coNhaTieu");

		if (coNhaTieu != null) {
			setCoNhaTieu(coNhaTieu);
		}

		Integer nhaTieuHVS = (Integer)attributes.get("nhaTieuHVS");

		if (nhaTieuHVS != null) {
			setNhaTieuHVS(nhaTieuHVS);
		}

		String loaiNhaTieu = (String)attributes.get("loaiNhaTieu");

		if (loaiNhaTieu != null) {
			setLoaiNhaTieu(loaiNhaTieu);
		}

		Integer duocCaiTao = (Integer)attributes.get("duocCaiTao");

		if (duocCaiTao != null) {
			setDuocCaiTao(duocCaiTao);
		}

		Integer thangXayDung = (Integer)attributes.get("thangXayDung");

		if (thangXayDung != null) {
			setThangXayDung(thangXayDung);
		}

		Integer namXayDung = (Integer)attributes.get("namXayDung");

		if (namXayDung != null) {
			setNamXayDung(namXayDung);
		}

		Integer nguonVon = (Integer)attributes.get("nguonVon");

		if (nguonVon != null) {
			setNguonVon(nguonVon);
		}

		Date ngayKiemDem = (Date)attributes.get("ngayKiemDem");

		if (ngayKiemDem != null) {
			setNgayKiemDem(ngayKiemDem);
		}

		Date ngayDanhGia = (Date)attributes.get("ngayDanhGia");

		if (ngayDanhGia != null) {
			setNgayDanhGia(ngayDanhGia);
		}

		Integer idNguoiDanhGia = (Integer)attributes.get("idNguoiDanhGia");

		if (idNguoiDanhGia != null) {
			setIdNguoiDanhGia(idNguoiDanhGia);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_columnBitmask = -1L;

		if (_originalMaTinh == null) {
			_originalMaTinh = _maTinh;
		}

		_maTinh = maTinh;
	}

	public String getOriginalMaTinh() {
		return GetterUtil.getString(_originalMaTinh);
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_columnBitmask = -1L;

		if (_originalMaHuyen == null) {
			_originalMaHuyen = _maHuyen;
		}

		_maHuyen = maHuyen;
	}

	public String getOriginalMaHuyen() {
		return GetterUtil.getString(_originalMaHuyen);
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_columnBitmask = -1L;

		if (_originalMaXa == null) {
			_originalMaXa = _maXa;
		}

		_maXa = maXa;
	}

	public String getOriginalMaXa() {
		return GetterUtil.getString(_originalMaXa);
	}

	@Override
	public String getThonXom() {
		if (_thonXom == null) {
			return StringPool.BLANK;
		}
		else {
			return _thonXom;
		}
	}

	@Override
	public void setThonXom(String thonXom) {
		_columnBitmask = -1L;

		if (_originalThonXom == null) {
			_originalThonXom = _thonXom;
		}

		_thonXom = thonXom;
	}

	public String getOriginalThonXom() {
		return GetterUtil.getString(_originalThonXom);
	}

	@Override
	public String getTenChuHo() {
		if (_tenChuHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHo;
		}
	}

	@Override
	public void setTenChuHo(String tenChuHo) {
		_columnBitmask = -1L;

		if (_originalTenChuHo == null) {
			_originalTenChuHo = _tenChuHo;
		}

		_tenChuHo = tenChuHo;
	}

	public String getOriginalTenChuHo() {
		return GetterUtil.getString(_originalTenChuHo);
	}

	@Override
	public int getGioiTinhChuHo() {
		return _gioiTinhChuHo;
	}

	@Override
	public void setGioiTinhChuHo(int gioiTinhChuHo) {
		_gioiTinhChuHo = gioiTinhChuHo;
	}

	@Override
	public int getTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(int trangThai) {
		_columnBitmask = -1L;

		_trangThai = trangThai;
	}

	@Override
	public int getMauNgauNhien() {
		return _mauNgauNhien;
	}

	@Override
	public void setMauNgauNhien(int mauNgauNhien) {
		_columnBitmask |= MAUNGAUNHIEN_COLUMN_BITMASK;

		if (!_setOriginalMauNgauNhien) {
			_setOriginalMauNgauNhien = true;

			_originalMauNgauNhien = _mauNgauNhien;
		}

		_mauNgauNhien = mauNgauNhien;
	}

	public int getOriginalMauNgauNhien() {
		return _originalMauNgauNhien;
	}

	@Override
	public int getNamBaoCao() {
		return _namBaoCao;
	}

	@Override
	public void setNamBaoCao(int namBaoCao) {
		_columnBitmask = -1L;

		_namBaoCao = namBaoCao;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public int getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(int idNguoiTao) {
		_columnBitmask |= IDNGUOITAO_COLUMN_BITMASK;

		if (!_setOriginalIdNguoiTao) {
			_setOriginalIdNguoiTao = true;

			_originalIdNguoiTao = _idNguoiTao;
		}

		_idNguoiTao = idNguoiTao;
	}

	public int getOriginalIdNguoiTao() {
		return _originalIdNguoiTao;
	}

	@Override
	public int getSoNguoiTrongHo() {
		return _soNguoiTrongHo;
	}

	@Override
	public void setSoNguoiTrongHo(int soNguoiTrongHo) {
		_soNguoiTrongHo = soNguoiTrongHo;
	}

	@Override
	public int getThanhPhanHoGD() {
		return _thanhPhanHoGD;
	}

	@Override
	public void setThanhPhanHoGD(int thanhPhanHoGD) {
		_thanhPhanHoGD = thanhPhanHoGD;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public int getCoNhaTieu() {
		return _coNhaTieu;
	}

	@Override
	public void setCoNhaTieu(int coNhaTieu) {
		_coNhaTieu = coNhaTieu;
	}

	@Override
	public int getNhaTieuHVS() {
		return _nhaTieuHVS;
	}

	@Override
	public void setNhaTieuHVS(int nhaTieuHVS) {
		_nhaTieuHVS = nhaTieuHVS;
	}

	@Override
	public String getLoaiNhaTieu() {
		if (_loaiNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNhaTieu;
		}
	}

	@Override
	public void setLoaiNhaTieu(String loaiNhaTieu) {
		_columnBitmask = -1L;

		_loaiNhaTieu = loaiNhaTieu;
	}

	@Override
	public int getDuocCaiTao() {
		return _duocCaiTao;
	}

	@Override
	public void setDuocCaiTao(int duocCaiTao) {
		_duocCaiTao = duocCaiTao;
	}

	@Override
	public int getThangXayDung() {
		return _thangXayDung;
	}

	@Override
	public void setThangXayDung(int thangXayDung) {
		_thangXayDung = thangXayDung;
	}

	@Override
	public int getNamXayDung() {
		return _namXayDung;
	}

	@Override
	public void setNamXayDung(int namXayDung) {
		_namXayDung = namXayDung;
	}

	@Override
	public int getNguonVon() {
		return _nguonVon;
	}

	@Override
	public void setNguonVon(int nguonVon) {
		_nguonVon = nguonVon;
	}

	@Override
	public Date getNgayKiemDem() {
		return _ngayKiemDem;
	}

	@Override
	public void setNgayKiemDem(Date ngayKiemDem) {
		_ngayKiemDem = ngayKiemDem;
	}

	@Override
	public Date getNgayDanhGia() {
		return _ngayDanhGia;
	}

	@Override
	public void setNgayDanhGia(Date ngayDanhGia) {
		_ngayDanhGia = ngayDanhGia;
	}

	@Override
	public int getIdNguoiDanhGia() {
		return _idNguoiDanhGia;
	}

	@Override
	public void setIdNguoiDanhGia(int idNguoiDanhGia) {
		_idNguoiDanhGia = idNguoiDanhGia;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VeSinhGiaDinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VeSinhGiaDinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VeSinhGiaDinhImpl veSinhGiaDinhImpl = new VeSinhGiaDinhImpl();

		veSinhGiaDinhImpl.setId(getId());
		veSinhGiaDinhImpl.setMaTinh(getMaTinh());
		veSinhGiaDinhImpl.setMaHuyen(getMaHuyen());
		veSinhGiaDinhImpl.setMaXa(getMaXa());
		veSinhGiaDinhImpl.setThonXom(getThonXom());
		veSinhGiaDinhImpl.setTenChuHo(getTenChuHo());
		veSinhGiaDinhImpl.setGioiTinhChuHo(getGioiTinhChuHo());
		veSinhGiaDinhImpl.setTrangThai(getTrangThai());
		veSinhGiaDinhImpl.setMauNgauNhien(getMauNgauNhien());
		veSinhGiaDinhImpl.setNamBaoCao(getNamBaoCao());
		veSinhGiaDinhImpl.setGhiChu(getGhiChu());
		veSinhGiaDinhImpl.setNgayTao(getNgayTao());
		veSinhGiaDinhImpl.setIdNguoiTao(getIdNguoiTao());
		veSinhGiaDinhImpl.setSoNguoiTrongHo(getSoNguoiTrongHo());
		veSinhGiaDinhImpl.setThanhPhanHoGD(getThanhPhanHoGD());
		veSinhGiaDinhImpl.setKinhDo(getKinhDo());
		veSinhGiaDinhImpl.setViDo(getViDo());
		veSinhGiaDinhImpl.setCoNhaTieu(getCoNhaTieu());
		veSinhGiaDinhImpl.setNhaTieuHVS(getNhaTieuHVS());
		veSinhGiaDinhImpl.setLoaiNhaTieu(getLoaiNhaTieu());
		veSinhGiaDinhImpl.setDuocCaiTao(getDuocCaiTao());
		veSinhGiaDinhImpl.setThangXayDung(getThangXayDung());
		veSinhGiaDinhImpl.setNamXayDung(getNamXayDung());
		veSinhGiaDinhImpl.setNguonVon(getNguonVon());
		veSinhGiaDinhImpl.setNgayKiemDem(getNgayKiemDem());
		veSinhGiaDinhImpl.setNgayDanhGia(getNgayDanhGia());
		veSinhGiaDinhImpl.setIdNguoiDanhGia(getIdNguoiDanhGia());

		veSinhGiaDinhImpl.resetOriginalValues();

		return veSinhGiaDinhImpl;
	}

	@Override
	public int compareTo(VeSinhGiaDinh veSinhGiaDinh) {
		int value = 0;

		value = getMaTinh().compareTo(veSinhGiaDinh.getMaTinh());

		if (value != 0) {
			return value;
		}

		value = getMaHuyen().compareTo(veSinhGiaDinh.getMaHuyen());

		if (value != 0) {
			return value;
		}

		value = getMaXa().compareTo(veSinhGiaDinh.getMaXa());

		if (value != 0) {
			return value;
		}

		value = getThonXom().compareTo(veSinhGiaDinh.getThonXom());

		if (value != 0) {
			return value;
		}

		value = getLoaiNhaTieu().compareTo(veSinhGiaDinh.getLoaiNhaTieu());

		if (value != 0) {
			return value;
		}

		value = getTenChuHo().compareTo(veSinhGiaDinh.getTenChuHo());

		if (value != 0) {
			return value;
		}

		if (getTrangThai() < veSinhGiaDinh.getTrangThai()) {
			value = -1;
		}
		else if (getTrangThai() > veSinhGiaDinh.getTrangThai()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getNamBaoCao() < veSinhGiaDinh.getNamBaoCao()) {
			value = -1;
		}
		else if (getNamBaoCao() > veSinhGiaDinh.getNamBaoCao()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VeSinhGiaDinh)) {
			return false;
		}

		VeSinhGiaDinh veSinhGiaDinh = (VeSinhGiaDinh)obj;

		int primaryKey = veSinhGiaDinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VeSinhGiaDinhModelImpl veSinhGiaDinhModelImpl = this;

		veSinhGiaDinhModelImpl._originalMaTinh = veSinhGiaDinhModelImpl._maTinh;

		veSinhGiaDinhModelImpl._originalMaHuyen = veSinhGiaDinhModelImpl._maHuyen;

		veSinhGiaDinhModelImpl._originalMaXa = veSinhGiaDinhModelImpl._maXa;

		veSinhGiaDinhModelImpl._originalThonXom = veSinhGiaDinhModelImpl._thonXom;

		veSinhGiaDinhModelImpl._originalTenChuHo = veSinhGiaDinhModelImpl._tenChuHo;

		veSinhGiaDinhModelImpl._originalMauNgauNhien = veSinhGiaDinhModelImpl._mauNgauNhien;

		veSinhGiaDinhModelImpl._setOriginalMauNgauNhien = false;

		veSinhGiaDinhModelImpl._originalIdNguoiTao = veSinhGiaDinhModelImpl._idNguoiTao;

		veSinhGiaDinhModelImpl._setOriginalIdNguoiTao = false;

		veSinhGiaDinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VeSinhGiaDinh> toCacheModel() {
		VeSinhGiaDinhCacheModel veSinhGiaDinhCacheModel = new VeSinhGiaDinhCacheModel();

		veSinhGiaDinhCacheModel.id = getId();

		veSinhGiaDinhCacheModel.maTinh = getMaTinh();

		String maTinh = veSinhGiaDinhCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			veSinhGiaDinhCacheModel.maTinh = null;
		}

		veSinhGiaDinhCacheModel.maHuyen = getMaHuyen();

		String maHuyen = veSinhGiaDinhCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			veSinhGiaDinhCacheModel.maHuyen = null;
		}

		veSinhGiaDinhCacheModel.maXa = getMaXa();

		String maXa = veSinhGiaDinhCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			veSinhGiaDinhCacheModel.maXa = null;
		}

		veSinhGiaDinhCacheModel.thonXom = getThonXom();

		String thonXom = veSinhGiaDinhCacheModel.thonXom;

		if ((thonXom != null) && (thonXom.length() == 0)) {
			veSinhGiaDinhCacheModel.thonXom = null;
		}

		veSinhGiaDinhCacheModel.tenChuHo = getTenChuHo();

		String tenChuHo = veSinhGiaDinhCacheModel.tenChuHo;

		if ((tenChuHo != null) && (tenChuHo.length() == 0)) {
			veSinhGiaDinhCacheModel.tenChuHo = null;
		}

		veSinhGiaDinhCacheModel.gioiTinhChuHo = getGioiTinhChuHo();

		veSinhGiaDinhCacheModel.trangThai = getTrangThai();

		veSinhGiaDinhCacheModel.mauNgauNhien = getMauNgauNhien();

		veSinhGiaDinhCacheModel.namBaoCao = getNamBaoCao();

		veSinhGiaDinhCacheModel.ghiChu = getGhiChu();

		String ghiChu = veSinhGiaDinhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			veSinhGiaDinhCacheModel.ghiChu = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			veSinhGiaDinhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			veSinhGiaDinhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		veSinhGiaDinhCacheModel.idNguoiTao = getIdNguoiTao();

		veSinhGiaDinhCacheModel.soNguoiTrongHo = getSoNguoiTrongHo();

		veSinhGiaDinhCacheModel.thanhPhanHoGD = getThanhPhanHoGD();

		veSinhGiaDinhCacheModel.kinhDo = getKinhDo();

		String kinhDo = veSinhGiaDinhCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			veSinhGiaDinhCacheModel.kinhDo = null;
		}

		veSinhGiaDinhCacheModel.viDo = getViDo();

		String viDo = veSinhGiaDinhCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			veSinhGiaDinhCacheModel.viDo = null;
		}

		veSinhGiaDinhCacheModel.coNhaTieu = getCoNhaTieu();

		veSinhGiaDinhCacheModel.nhaTieuHVS = getNhaTieuHVS();

		veSinhGiaDinhCacheModel.loaiNhaTieu = getLoaiNhaTieu();

		String loaiNhaTieu = veSinhGiaDinhCacheModel.loaiNhaTieu;

		if ((loaiNhaTieu != null) && (loaiNhaTieu.length() == 0)) {
			veSinhGiaDinhCacheModel.loaiNhaTieu = null;
		}

		veSinhGiaDinhCacheModel.duocCaiTao = getDuocCaiTao();

		veSinhGiaDinhCacheModel.thangXayDung = getThangXayDung();

		veSinhGiaDinhCacheModel.namXayDung = getNamXayDung();

		veSinhGiaDinhCacheModel.nguonVon = getNguonVon();

		Date ngayKiemDem = getNgayKiemDem();

		if (ngayKiemDem != null) {
			veSinhGiaDinhCacheModel.ngayKiemDem = ngayKiemDem.getTime();
		}
		else {
			veSinhGiaDinhCacheModel.ngayKiemDem = Long.MIN_VALUE;
		}

		Date ngayDanhGia = getNgayDanhGia();

		if (ngayDanhGia != null) {
			veSinhGiaDinhCacheModel.ngayDanhGia = ngayDanhGia.getTime();
		}
		else {
			veSinhGiaDinhCacheModel.ngayDanhGia = Long.MIN_VALUE;
		}

		veSinhGiaDinhCacheModel.idNguoiDanhGia = getIdNguoiDanhGia();

		return veSinhGiaDinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(55);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", thonXom=");
		sb.append(getThonXom());
		sb.append(", tenChuHo=");
		sb.append(getTenChuHo());
		sb.append(", gioiTinhChuHo=");
		sb.append(getGioiTinhChuHo());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", mauNgauNhien=");
		sb.append(getMauNgauNhien());
		sb.append(", namBaoCao=");
		sb.append(getNamBaoCao());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", soNguoiTrongHo=");
		sb.append(getSoNguoiTrongHo());
		sb.append(", thanhPhanHoGD=");
		sb.append(getThanhPhanHoGD());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", coNhaTieu=");
		sb.append(getCoNhaTieu());
		sb.append(", nhaTieuHVS=");
		sb.append(getNhaTieuHVS());
		sb.append(", loaiNhaTieu=");
		sb.append(getLoaiNhaTieu());
		sb.append(", duocCaiTao=");
		sb.append(getDuocCaiTao());
		sb.append(", thangXayDung=");
		sb.append(getThangXayDung());
		sb.append(", namXayDung=");
		sb.append(getNamXayDung());
		sb.append(", nguonVon=");
		sb.append(getNguonVon());
		sb.append(", ngayKiemDem=");
		sb.append(getNgayKiemDem());
		sb.append(", ngayDanhGia=");
		sb.append(getNgayDanhGia());
		sb.append(", idNguoiDanhGia=");
		sb.append(getIdNguoiDanhGia());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(85);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.vesinhmoitruong.dao.model.VeSinhGiaDinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thonXom</column-name><column-value><![CDATA[");
		sb.append(getThonXom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHo</column-name><column-value><![CDATA[");
		sb.append(getTenChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhChuHo</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mauNgauNhien</column-name><column-value><![CDATA[");
		sb.append(getMauNgauNhien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namBaoCao</column-name><column-value><![CDATA[");
		sb.append(getNamBaoCao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiTrongHo</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiTrongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhPhanHoGD</column-name><column-value><![CDATA[");
		sb.append(getThanhPhanHoGD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duocCaiTao</column-name><column-value><![CDATA[");
		sb.append(getDuocCaiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thangXayDung</column-name><column-value><![CDATA[");
		sb.append(getThangXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namXayDung</column-name><column-value><![CDATA[");
		sb.append(getNamXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguonVon</column-name><column-value><![CDATA[");
		sb.append(getNguonVon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKiemDem</column-name><column-value><![CDATA[");
		sb.append(getNgayKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDanhGia</column-name><column-value><![CDATA[");
		sb.append(getNgayDanhGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiDanhGia</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiDanhGia());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VeSinhGiaDinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VeSinhGiaDinh.class
		};
	private int _id;
	private String _maTinh;
	private String _originalMaTinh;
	private String _maHuyen;
	private String _originalMaHuyen;
	private String _maXa;
	private String _originalMaXa;
	private String _thonXom;
	private String _originalThonXom;
	private String _tenChuHo;
	private String _originalTenChuHo;
	private int _gioiTinhChuHo;
	private int _trangThai;
	private int _mauNgauNhien;
	private int _originalMauNgauNhien;
	private boolean _setOriginalMauNgauNhien;
	private int _namBaoCao;
	private String _ghiChu;
	private Date _ngayTao;
	private int _idNguoiTao;
	private int _originalIdNguoiTao;
	private boolean _setOriginalIdNguoiTao;
	private int _soNguoiTrongHo;
	private int _thanhPhanHoGD;
	private String _kinhDo;
	private String _viDo;
	private int _coNhaTieu;
	private int _nhaTieuHVS;
	private String _loaiNhaTieu;
	private int _duocCaiTao;
	private int _thangXayDung;
	private int _namXayDung;
	private int _nguonVon;
	private Date _ngayKiemDem;
	private Date _ngayDanhGia;
	private int _idNguoiDanhGia;
	private long _columnBitmask;
	private VeSinhGiaDinh _escapedModel;
}