/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThongTinKiemDemHoGD service. Represents a row in the &quot;ME_THONGTINKIEMDEMHOGD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemHoGDModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemHoGDImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ThongTinKiemDemHoGD
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemHoGDImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl.ThongTinKiemDemHoGDModelImpl
 * @generated
 */
public interface ThongTinKiemDemHoGDModel extends BaseModel<ThongTinKiemDemHoGD> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thong tin kiem dem ho g d model instance should use the {@link ThongTinKiemDemHoGD} interface instead.
	 */

	/**
	 * Returns the primary key of this thong tin kiem dem ho g d.
	 *
	 * @return the primary key of this thong tin kiem dem ho g d
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this thong tin kiem dem ho g d.
	 *
	 * @param primaryKey the primary key of this thong tin kiem dem ho g d
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this thong tin kiem dem ho g d.
	 *
	 * @return the ID of this thong tin kiem dem ho g d
	 */
	public int getId();

	/**
	 * Sets the ID of this thong tin kiem dem ho g d.
	 *
	 * @param id the ID of this thong tin kiem dem ho g d
	 */
	public void setId(int id);

	/**
	 * Returns the ve sinh gia dinh ID of this thong tin kiem dem ho g d.
	 *
	 * @return the ve sinh gia dinh ID of this thong tin kiem dem ho g d
	 */
	public int getVeSinhGiaDinhId();

	/**
	 * Sets the ve sinh gia dinh ID of this thong tin kiem dem ho g d.
	 *
	 * @param veSinhGiaDinhId the ve sinh gia dinh ID of this thong tin kiem dem ho g d
	 */
	public void setVeSinhGiaDinhId(int veSinhGiaDinhId);

	/**
	 * Returns the ke hoach kiem dem ve sinh ID of this thong tin kiem dem ho g d.
	 *
	 * @return the ke hoach kiem dem ve sinh ID of this thong tin kiem dem ho g d
	 */
	public int getKeHoachKiemDemVeSinhId();

	/**
	 * Sets the ke hoach kiem dem ve sinh ID of this thong tin kiem dem ho g d.
	 *
	 * @param keHoachKiemDemVeSinhId the ke hoach kiem dem ve sinh ID of this thong tin kiem dem ho g d
	 */
	public void setKeHoachKiemDemVeSinhId(int keHoachKiemDemVeSinhId);

	/**
	 * Returns the ma tinh of this thong tin kiem dem ho g d.
	 *
	 * @return the ma tinh of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this thong tin kiem dem ho g d.
	 *
	 * @param maTinh the ma tinh of this thong tin kiem dem ho g d
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this thong tin kiem dem ho g d.
	 *
	 * @return the ma huyen of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this thong tin kiem dem ho g d.
	 *
	 * @param maHuyen the ma huyen of this thong tin kiem dem ho g d
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this thong tin kiem dem ho g d.
	 *
	 * @return the ma xa of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this thong tin kiem dem ho g d.
	 *
	 * @param maXa the ma xa of this thong tin kiem dem ho g d
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the thon xom of this thong tin kiem dem ho g d.
	 *
	 * @return the thon xom of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getThonXom();

	/**
	 * Sets the thon xom of this thong tin kiem dem ho g d.
	 *
	 * @param thonXom the thon xom of this thong tin kiem dem ho g d
	 */
	public void setThonXom(String thonXom);

	/**
	 * Returns the ten chu ho of this thong tin kiem dem ho g d.
	 *
	 * @return the ten chu ho of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getTenChuHo();

	/**
	 * Sets the ten chu ho of this thong tin kiem dem ho g d.
	 *
	 * @param tenChuHo the ten chu ho of this thong tin kiem dem ho g d
	 */
	public void setTenChuHo(String tenChuHo);

	/**
	 * Returns the gioi tinh chu ho of this thong tin kiem dem ho g d.
	 *
	 * @return the gioi tinh chu ho of this thong tin kiem dem ho g d
	 */
	public int getGioiTinhChuHo();

	/**
	 * Sets the gioi tinh chu ho of this thong tin kiem dem ho g d.
	 *
	 * @param gioiTinhChuHo the gioi tinh chu ho of this thong tin kiem dem ho g d
	 */
	public void setGioiTinhChuHo(int gioiTinhChuHo);

	/**
	 * Returns the ngay kiem dem of this thong tin kiem dem ho g d.
	 *
	 * @return the ngay kiem dem of this thong tin kiem dem ho g d
	 */
	public Date getNgayKiemDem();

	/**
	 * Sets the ngay kiem dem of this thong tin kiem dem ho g d.
	 *
	 * @param ngayKiemDem the ngay kiem dem of this thong tin kiem dem ho g d
	 */
	public void setNgayKiemDem(Date ngayKiemDem);

	/**
	 * Returns the tim thay nha of this thong tin kiem dem ho g d.
	 *
	 * @return the tim thay nha of this thong tin kiem dem ho g d
	 */
	public int getTimThayNha();

	/**
	 * Sets the tim thay nha of this thong tin kiem dem ho g d.
	 *
	 * @param timThayNha the tim thay nha of this thong tin kiem dem ho g d
	 */
	public void setTimThayNha(int timThayNha);

	/**
	 * Returns the co nguoi o nha of this thong tin kiem dem ho g d.
	 *
	 * @return the co nguoi o nha of this thong tin kiem dem ho g d
	 */
	public int getCoNguoiONha();

	/**
	 * Sets the co nguoi o nha of this thong tin kiem dem ho g d.
	 *
	 * @param coNguoiONha the co nguoi o nha of this thong tin kiem dem ho g d
	 */
	public void setCoNguoiONha(int coNguoiONha);

	/**
	 * Returns the so nguoi trong ho of this thong tin kiem dem ho g d.
	 *
	 * @return the so nguoi trong ho of this thong tin kiem dem ho g d
	 */
	public int getSoNguoiTrongHo();

	/**
	 * Sets the so nguoi trong ho of this thong tin kiem dem ho g d.
	 *
	 * @param soNguoiTrongHo the so nguoi trong ho of this thong tin kiem dem ho g d
	 */
	public void setSoNguoiTrongHo(int soNguoiTrongHo);

	/**
	 * Returns the ho ten nguoi tra loi of this thong tin kiem dem ho g d.
	 *
	 * @return the ho ten nguoi tra loi of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getHoTenNguoiTraLoi();

	/**
	 * Sets the ho ten nguoi tra loi of this thong tin kiem dem ho g d.
	 *
	 * @param hoTenNguoiTraLoi the ho ten nguoi tra loi of this thong tin kiem dem ho g d
	 */
	public void setHoTenNguoiTraLoi(String hoTenNguoiTraLoi);

	/**
	 * Returns the la chu ho khong of this thong tin kiem dem ho g d.
	 *
	 * @return the la chu ho khong of this thong tin kiem dem ho g d
	 */
	public int getLaChuHoKhong();

	/**
	 * Sets the la chu ho khong of this thong tin kiem dem ho g d.
	 *
	 * @param laChuHoKhong the la chu ho khong of this thong tin kiem dem ho g d
	 */
	public void setLaChuHoKhong(int laChuHoKhong);

	/**
	 * Returns the gioi tinh nguoi tra loi of this thong tin kiem dem ho g d.
	 *
	 * @return the gioi tinh nguoi tra loi of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getGioiTinhNguoiTraLoi();

	/**
	 * Sets the gioi tinh nguoi tra loi of this thong tin kiem dem ho g d.
	 *
	 * @param gioiTinhNguoiTraLoi the gioi tinh nguoi tra loi of this thong tin kiem dem ho g d
	 */
	public void setGioiTinhNguoiTraLoi(String gioiTinhNguoiTraLoi);

	/**
	 * Returns the ten dan toc of this thong tin kiem dem ho g d.
	 *
	 * @return the ten dan toc of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getTenDanToc();

	/**
	 * Sets the ten dan toc of this thong tin kiem dem ho g d.
	 *
	 * @param tenDanToc the ten dan toc of this thong tin kiem dem ho g d
	 */
	public void setTenDanToc(String tenDanToc);

	/**
	 * Returns the kinh do of this thong tin kiem dem ho g d.
	 *
	 * @return the kinh do of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getKinhDo();

	/**
	 * Sets the kinh do of this thong tin kiem dem ho g d.
	 *
	 * @param kinhDo the kinh do of this thong tin kiem dem ho g d
	 */
	public void setKinhDo(String kinhDo);

	/**
	 * Returns the vi do of this thong tin kiem dem ho g d.
	 *
	 * @return the vi do of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getViDo();

	/**
	 * Sets the vi do of this thong tin kiem dem ho g d.
	 *
	 * @param viDo the vi do of this thong tin kiem dem ho g d
	 */
	public void setViDo(String viDo);

	/**
	 * Returns the thanh phan ho g d of this thong tin kiem dem ho g d.
	 *
	 * @return the thanh phan ho g d of this thong tin kiem dem ho g d
	 */
	public int getThanhPhanHoGD();

	/**
	 * Sets the thanh phan ho g d of this thong tin kiem dem ho g d.
	 *
	 * @param thanhPhanHoGD the thanh phan ho g d of this thong tin kiem dem ho g d
	 */
	public void setThanhPhanHoGD(int thanhPhanHoGD);

	/**
	 * Returns the chu ho dung d s of this thong tin kiem dem ho g d.
	 *
	 * @return the chu ho dung d s of this thong tin kiem dem ho g d
	 */
	public int getChuHoDungDS();

	/**
	 * Sets the chu ho dung d s of this thong tin kiem dem ho g d.
	 *
	 * @param chuHoDungDS the chu ho dung d s of this thong tin kiem dem ho g d
	 */
	public void setChuHoDungDS(int chuHoDungDS);

	/**
	 * Returns the ly do khong dung d s of this thong tin kiem dem ho g d.
	 *
	 * @return the ly do khong dung d s of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getLyDoKhongDungDS();

	/**
	 * Sets the ly do khong dung d s of this thong tin kiem dem ho g d.
	 *
	 * @param lyDoKhongDungDS the ly do khong dung d s of this thong tin kiem dem ho g d
	 */
	public void setLyDoKhongDungDS(String lyDoKhongDungDS);

	/**
	 * Returns the ten chu ho hien tai of this thong tin kiem dem ho g d.
	 *
	 * @return the ten chu ho hien tai of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getTenChuHoHienTai();

	/**
	 * Sets the ten chu ho hien tai of this thong tin kiem dem ho g d.
	 *
	 * @param tenChuHoHienTai the ten chu ho hien tai of this thong tin kiem dem ho g d
	 */
	public void setTenChuHoHienTai(String tenChuHoHienTai);

	/**
	 * Returns the gioi tinh chu ho hien tai of this thong tin kiem dem ho g d.
	 *
	 * @return the gioi tinh chu ho hien tai of this thong tin kiem dem ho g d
	 */
	public int getGioiTinhChuHoHienTai();

	/**
	 * Sets the gioi tinh chu ho hien tai of this thong tin kiem dem ho g d.
	 *
	 * @param gioiTinhChuHoHienTai the gioi tinh chu ho hien tai of this thong tin kiem dem ho g d
	 */
	public void setGioiTinhChuHoHienTai(int gioiTinhChuHoHienTai);

	/**
	 * Returns the co nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @return the co nha tieu of this thong tin kiem dem ho g d
	 */
	public int getCoNhaTieu();

	/**
	 * Sets the co nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @param coNhaTieu the co nha tieu of this thong tin kiem dem ho g d
	 */
	public void setCoNhaTieu(int coNhaTieu);

	/**
	 * Returns the loai nguon nuoc of this thong tin kiem dem ho g d.
	 *
	 * @return the loai nguon nuoc of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getLoaiNguonNuoc();

	/**
	 * Sets the loai nguon nuoc of this thong tin kiem dem ho g d.
	 *
	 * @param loaiNguonNuoc the loai nguon nuoc of this thong tin kiem dem ho g d
	 */
	public void setLoaiNguonNuoc(String loaiNguonNuoc);

	/**
	 * Returns the loai nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @return the loai nha tieu of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getLoaiNhaTieu();

	/**
	 * Sets the loai nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @param loaiNhaTieu the loai nha tieu of this thong tin kiem dem ho g d
	 */
	public void setLoaiNhaTieu(String loaiNhaTieu);

	/**
	 * Returns the anh toan canh of this thong tin kiem dem ho g d.
	 *
	 * @return the anh toan canh of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getAnhToanCanh();

	/**
	 * Sets the anh toan canh of this thong tin kiem dem ho g d.
	 *
	 * @param anhToanCanh the anh toan canh of this thong tin kiem dem ho g d
	 */
	public void setAnhToanCanh(String anhToanCanh);

	/**
	 * Returns the anh trong nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @return the anh trong nha tieu of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getAnhTrongNhaTieu();

	/**
	 * Sets the anh trong nha tieu of this thong tin kiem dem ho g d.
	 *
	 * @param anhTrongNhaTieu the anh trong nha tieu of this thong tin kiem dem ho g d
	 */
	public void setAnhTrongNhaTieu(String anhTrongNhaTieu);

	/**
	 * Returns the thang xay dung of this thong tin kiem dem ho g d.
	 *
	 * @return the thang xay dung of this thong tin kiem dem ho g d
	 */
	public int getThangXayDung();

	/**
	 * Sets the thang xay dung of this thong tin kiem dem ho g d.
	 *
	 * @param thangXayDung the thang xay dung of this thong tin kiem dem ho g d
	 */
	public void setThangXayDung(int thangXayDung);

	/**
	 * Returns the nam xay dung of this thong tin kiem dem ho g d.
	 *
	 * @return the nam xay dung of this thong tin kiem dem ho g d
	 */
	public int getNamXayDung();

	/**
	 * Sets the nam xay dung of this thong tin kiem dem ho g d.
	 *
	 * @param namXayDung the nam xay dung of this thong tin kiem dem ho g d
	 */
	public void setNamXayDung(int namXayDung);

	/**
	 * Returns the nguon von of this thong tin kiem dem ho g d.
	 *
	 * @return the nguon von of this thong tin kiem dem ho g d
	 */
	public int getNguonVon();

	/**
	 * Sets the nguon von of this thong tin kiem dem ho g d.
	 *
	 * @param nguonVon the nguon von of this thong tin kiem dem ho g d
	 */
	public void setNguonVon(int nguonVon);

	/**
	 * Returns the chi tiet von vay of this thong tin kiem dem ho g d.
	 *
	 * @return the chi tiet von vay of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getChiTietVonVay();

	/**
	 * Sets the chi tiet von vay of this thong tin kiem dem ho g d.
	 *
	 * @param chiTietVonVay the chi tiet von vay of this thong tin kiem dem ho g d
	 */
	public void setChiTietVonVay(String chiTietVonVay);

	/**
	 * Returns the duoc cai tao of this thong tin kiem dem ho g d.
	 *
	 * @return the duoc cai tao of this thong tin kiem dem ho g d
	 */
	public int getDuocCaiTao();

	/**
	 * Sets the duoc cai tao of this thong tin kiem dem ho g d.
	 *
	 * @param duocCaiTao the duoc cai tao of this thong tin kiem dem ho g d
	 */
	public void setDuocCaiTao(int duocCaiTao);

	/**
	 * Returns the loai nha tieu cu of this thong tin kiem dem ho g d.
	 *
	 * @return the loai nha tieu cu of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getLoaiNhaTieuCu();

	/**
	 * Sets the loai nha tieu cu of this thong tin kiem dem ho g d.
	 *
	 * @param loaiNhaTieuCu the loai nha tieu cu of this thong tin kiem dem ho g d
	 */
	public void setLoaiNhaTieuCu(String loaiNhaTieuCu);

	/**
	 * Returns the anh be chua of this thong tin kiem dem ho g d.
	 *
	 * @return the anh be chua of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getAnhBeChua();

	/**
	 * Sets the anh be chua of this thong tin kiem dem ho g d.
	 *
	 * @param anhBeChua the anh be chua of this thong tin kiem dem ho g d
	 */
	public void setAnhBeChua(String anhBeChua);

	/**
	 * Returns the ve sinh sach se of this thong tin kiem dem ho g d.
	 *
	 * @return the ve sinh sach se of this thong tin kiem dem ho g d
	 */
	public int getVeSinhSachSe();

	/**
	 * Sets the ve sinh sach se of this thong tin kiem dem ho g d.
	 *
	 * @param veSinhSachSe the ve sinh sach se of this thong tin kiem dem ho g d
	 */
	public void setVeSinhSachSe(int veSinhSachSe);

	/**
	 * Returns the de lam ve sinh of this thong tin kiem dem ho g d.
	 *
	 * @return the de lam ve sinh of this thong tin kiem dem ho g d
	 */
	public int getDeLamVeSinh();

	/**
	 * Sets the de lam ve sinh of this thong tin kiem dem ho g d.
	 *
	 * @param deLamVeSinh the de lam ve sinh of this thong tin kiem dem ho g d
	 */
	public void setDeLamVeSinh(int deLamVeSinh);

	/**
	 * Returns the mui ve sinh of this thong tin kiem dem ho g d.
	 *
	 * @return the mui ve sinh of this thong tin kiem dem ho g d
	 */
	public int getMuiVeSinh();

	/**
	 * Sets the mui ve sinh of this thong tin kiem dem ho g d.
	 *
	 * @param muiVeSinh the mui ve sinh of this thong tin kiem dem ho g d
	 */
	public void setMuiVeSinh(int muiVeSinh);

	/**
	 * Returns the phia tren kin dao of this thong tin kiem dem ho g d.
	 *
	 * @return the phia tren kin dao of this thong tin kiem dem ho g d
	 */
	public int getPhiaTrenKinDao();

	/**
	 * Sets the phia tren kin dao of this thong tin kiem dem ho g d.
	 *
	 * @param phiaTrenKinDao the phia tren kin dao of this thong tin kiem dem ho g d
	 */
	public void setPhiaTrenKinDao(int phiaTrenKinDao);

	/**
	 * Returns the du che mua gio of this thong tin kiem dem ho g d.
	 *
	 * @return the du che mua gio of this thong tin kiem dem ho g d
	 */
	public int getDuCheMuaGio();

	/**
	 * Sets the du che mua gio of this thong tin kiem dem ho g d.
	 *
	 * @param duCheMuaGio the du che mua gio of this thong tin kiem dem ho g d
	 */
	public void setDuCheMuaGio(int duCheMuaGio);

	/**
	 * Returns the san cao tren toi thieu of this thong tin kiem dem ho g d.
	 *
	 * @return the san cao tren toi thieu of this thong tin kiem dem ho g d
	 */
	public int getSanCaoTrenToiThieu();

	/**
	 * Sets the san cao tren toi thieu of this thong tin kiem dem ho g d.
	 *
	 * @param sanCaoTrenToiThieu the san cao tren toi thieu of this thong tin kiem dem ho g d
	 */
	public void setSanCaoTrenToiThieu(int sanCaoTrenToiThieu);

	/**
	 * Returns the nap be con tot of this thong tin kiem dem ho g d.
	 *
	 * @return the nap be con tot of this thong tin kiem dem ho g d
	 */
	public int getNapBeConTot();

	/**
	 * Sets the nap be con tot of this thong tin kiem dem ho g d.
	 *
	 * @param napBeConTot the nap be con tot of this thong tin kiem dem ho g d
	 */
	public void setNapBeConTot(int napBeConTot);

	/**
	 * Returns the cua phan bit kin of this thong tin kiem dem ho g d.
	 *
	 * @return the cua phan bit kin of this thong tin kiem dem ho g d
	 */
	public int getCuaPhanBitKin();

	/**
	 * Sets the cua phan bit kin of this thong tin kiem dem ho g d.
	 *
	 * @param cuaPhanBitKin the cua phan bit kin of this thong tin kiem dem ho g d
	 */
	public void setCuaPhanBitKin(int cuaPhanBitKin);

	/**
	 * Returns the tran ra ngoai of this thong tin kiem dem ho g d.
	 *
	 * @return the tran ra ngoai of this thong tin kiem dem ho g d
	 */
	public int getTranRaNgoai();

	/**
	 * Sets the tran ra ngoai of this thong tin kiem dem ho g d.
	 *
	 * @param tranRaNgoai the tran ra ngoai of this thong tin kiem dem ho g d
	 */
	public void setTranRaNgoai(int tranRaNgoai);

	/**
	 * Returns the nuoc thai di dau of this thong tin kiem dem ho g d.
	 *
	 * @return the nuoc thai di dau of this thong tin kiem dem ho g d
	 */
	public int getNuocThaiDiDau();

	/**
	 * Sets the nuoc thai di dau of this thong tin kiem dem ho g d.
	 *
	 * @param nuocThaiDiDau the nuoc thai di dau of this thong tin kiem dem ho g d
	 */
	public void setNuocThaiDiDau(int nuocThaiDiDau);

	/**
	 * Returns the khoang cach nguon nuoc of this thong tin kiem dem ho g d.
	 *
	 * @return the khoang cach nguon nuoc of this thong tin kiem dem ho g d
	 */
	public int getKhoangCachNguonNuoc();

	/**
	 * Sets the khoang cach nguon nuoc of this thong tin kiem dem ho g d.
	 *
	 * @param khoangCachNguonNuoc the khoang cach nguon nuoc of this thong tin kiem dem ho g d
	 */
	public void setKhoangCachNguonNuoc(int khoangCachNguonNuoc);

	/**
	 * Returns the ngap khi mua lon of this thong tin kiem dem ho g d.
	 *
	 * @return the ngap khi mua lon of this thong tin kiem dem ho g d
	 */
	public int getNgapKhiMuaLon();

	/**
	 * Sets the ngap khi mua lon of this thong tin kiem dem ho g d.
	 *
	 * @param ngapKhiMuaLon the ngap khi mua lon of this thong tin kiem dem ho g d
	 */
	public void setNgapKhiMuaLon(int ngapKhiMuaLon);

	/**
	 * Returns the ghi chu of this thong tin kiem dem ho g d.
	 *
	 * @return the ghi chu of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this thong tin kiem dem ho g d.
	 *
	 * @param ghiChu the ghi chu of this thong tin kiem dem ho g d
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the da ket thuc dieu tra of this thong tin kiem dem ho g d.
	 *
	 * @return the da ket thuc dieu tra of this thong tin kiem dem ho g d
	 */
	public int getDaKetThucDieuTra();

	/**
	 * Sets the da ket thuc dieu tra of this thong tin kiem dem ho g d.
	 *
	 * @param daKetThucDieuTra the da ket thuc dieu tra of this thong tin kiem dem ho g d
	 */
	public void setDaKetThucDieuTra(int daKetThucDieuTra);

	/**
	 * Returns the ly do khong hoan thanh of this thong tin kiem dem ho g d.
	 *
	 * @return the ly do khong hoan thanh of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getLyDoKhongHoanThanh();

	/**
	 * Sets the ly do khong hoan thanh of this thong tin kiem dem ho g d.
	 *
	 * @param lyDoKhongHoanThanh the ly do khong hoan thanh of this thong tin kiem dem ho g d
	 */
	public void setLyDoKhongHoanThanh(String lyDoKhongHoanThanh);

	/**
	 * Returns the imei of this thong tin kiem dem ho g d.
	 *
	 * @return the imei of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getImei();

	/**
	 * Sets the imei of this thong tin kiem dem ho g d.
	 *
	 * @param imei the imei of this thong tin kiem dem ho g d
	 */
	public void setImei(String imei);

	/**
	 * Returns the tai khoan of this thong tin kiem dem ho g d.
	 *
	 * @return the tai khoan of this thong tin kiem dem ho g d
	 */
	@AutoEscape
	public String getTaiKhoan();

	/**
	 * Sets the tai khoan of this thong tin kiem dem ho g d.
	 *
	 * @param taiKhoan the tai khoan of this thong tin kiem dem ho g d
	 */
	public void setTaiKhoan(String taiKhoan);

	/**
	 * Returns the danh gia kiem dem of this thong tin kiem dem ho g d.
	 *
	 * @return the danh gia kiem dem of this thong tin kiem dem ho g d
	 */
	public int getDanhGiaKiemDem();

	/**
	 * Sets the danh gia kiem dem of this thong tin kiem dem ho g d.
	 *
	 * @param danhGiaKiemDem the danh gia kiem dem of this thong tin kiem dem ho g d
	 */
	public void setDanhGiaKiemDem(int danhGiaKiemDem);

	/**
	 * Returns the save point of this thong tin kiem dem ho g d.
	 *
	 * @return the save point of this thong tin kiem dem ho g d
	 */
	public Date getSavePoint();

	/**
	 * Sets the save point of this thong tin kiem dem ho g d.
	 *
	 * @param savePoint the save point of this thong tin kiem dem ho g d
	 */
	public void setSavePoint(Date savePoint);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThongTinKiemDemHoGD thongTinKiemDemHoGD);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThongTinKiemDemHoGD> toCacheModel();

	@Override
	public ThongTinKiemDemHoGD toEscapedModel();

	@Override
	public ThongTinKiemDemHoGD toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}