/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh;
import vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DanhGiaVanHanh service. Represents a row in the &quot;ME_DANHGIAVANHANH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhGiaVanHanhImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see DanhGiaVanHanhImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh
 * @see vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanhModel
 * @generated
 */
public class DanhGiaVanHanhModelImpl extends BaseModelImpl<DanhGiaVanHanh>
	implements DanhGiaVanHanhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh gia van hanh model instance should use the {@link vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_DANHGIAVANHANH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TRAMCAPNUOCID", Types.INTEGER },
			{ "THANG", Types.INTEGER },
			{ "NAM", Types.INTEGER },
			{ "CONGXUATTHUCTE", Types.INTEGER },
			{ "NUOCTHATTHOAT", Types.INTEGER },
			{ "NUOCDATTIEUCHUAN", Types.INTEGER },
			{ "NUOCCOASEN", Types.INTEGER },
			{ "TRANGTHAICAPNUOC", Types.INTEGER },
			{ "CHIPHIHOACHAT", Types.INTEGER },
			{ "CHIPHIDIEN", Types.INTEGER },
			{ "LUONGNHANVIEN", Types.INTEGER },
			{ "CHIPHISUACHUA", Types.INTEGER },
			{ "DOANHTHU", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "idNguoiTao", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "SANLUONGSANXUAT", Types.INTEGER },
			{ "SANLUONGTIEUHAO", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_DANHGIAVANHANH (ID LONG not null primary key,TRAMCAPNUOCID INTEGER,THANG INTEGER,NAM INTEGER,CONGXUATTHUCTE INTEGER,NUOCTHATTHOAT INTEGER,NUOCDATTIEUCHUAN INTEGER,NUOCCOASEN INTEGER,TRANGTHAICAPNUOC INTEGER,CHIPHIHOACHAT INTEGER,CHIPHIDIEN INTEGER,LUONGNHANVIEN INTEGER,CHIPHISUACHUA INTEGER,DOANHTHU INTEGER,NGAYTAO DATE null,idNguoiTao INTEGER,GHICHU VARCHAR(75) null,SANLUONGSANXUAT INTEGER,SANLUONGTIEUHAO INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ME_DANHGIAVANHANH";
	public static final String ORDER_BY_JPQL = " ORDER BY danhGiaVanHanh.nam DESC, danhGiaVanHanh.thang DESC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_DANHGIAVANHANH.NAM DESC, ME_DANHGIAVANHANH.THANG DESC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh"),
			true);
	public static long NAM_COLUMN_BITMASK = 1L;
	public static long THANG_COLUMN_BITMASK = 2L;
	public static long TRAMCAPNUOCID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh"));

	public DanhGiaVanHanhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DanhGiaVanHanh.class;
	}

	@Override
	public String getModelClassName() {
		return DanhGiaVanHanh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("tramCapNuocId", getTramCapNuocId());
		attributes.put("thang", getThang());
		attributes.put("nam", getNam());
		attributes.put("congXuatThucTe", getCongXuatThucTe());
		attributes.put("nuocThatThoat", getNuocThatThoat());
		attributes.put("nuocDatTieuChuan", getNuocDatTieuChuan());
		attributes.put("nuocCoAsen", getNuocCoAsen());
		attributes.put("trangThaiCapNuoc", getTrangThaiCapNuoc());
		attributes.put("chiPhiHoaChat", getChiPhiHoaChat());
		attributes.put("chiPhiDien", getChiPhiDien());
		attributes.put("luongNhanVien", getLuongNhanVien());
		attributes.put("chiPhiSuaChua", getChiPhiSuaChua());
		attributes.put("doanhThu", getDoanhThu());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("sanLuongSanXuat", getSanLuongSanXuat());
		attributes.put("sanLuongTieuHao", getSanLuongTieuHao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer tramCapNuocId = (Integer)attributes.get("tramCapNuocId");

		if (tramCapNuocId != null) {
			setTramCapNuocId(tramCapNuocId);
		}

		Integer thang = (Integer)attributes.get("thang");

		if (thang != null) {
			setThang(thang);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Integer congXuatThucTe = (Integer)attributes.get("congXuatThucTe");

		if (congXuatThucTe != null) {
			setCongXuatThucTe(congXuatThucTe);
		}

		Integer nuocThatThoat = (Integer)attributes.get("nuocThatThoat");

		if (nuocThatThoat != null) {
			setNuocThatThoat(nuocThatThoat);
		}

		Integer nuocDatTieuChuan = (Integer)attributes.get("nuocDatTieuChuan");

		if (nuocDatTieuChuan != null) {
			setNuocDatTieuChuan(nuocDatTieuChuan);
		}

		Integer nuocCoAsen = (Integer)attributes.get("nuocCoAsen");

		if (nuocCoAsen != null) {
			setNuocCoAsen(nuocCoAsen);
		}

		Integer trangThaiCapNuoc = (Integer)attributes.get("trangThaiCapNuoc");

		if (trangThaiCapNuoc != null) {
			setTrangThaiCapNuoc(trangThaiCapNuoc);
		}

		Integer chiPhiHoaChat = (Integer)attributes.get("chiPhiHoaChat");

		if (chiPhiHoaChat != null) {
			setChiPhiHoaChat(chiPhiHoaChat);
		}

		Integer chiPhiDien = (Integer)attributes.get("chiPhiDien");

		if (chiPhiDien != null) {
			setChiPhiDien(chiPhiDien);
		}

		Integer luongNhanVien = (Integer)attributes.get("luongNhanVien");

		if (luongNhanVien != null) {
			setLuongNhanVien(luongNhanVien);
		}

		Integer chiPhiSuaChua = (Integer)attributes.get("chiPhiSuaChua");

		if (chiPhiSuaChua != null) {
			setChiPhiSuaChua(chiPhiSuaChua);
		}

		Integer doanhThu = (Integer)attributes.get("doanhThu");

		if (doanhThu != null) {
			setDoanhThu(doanhThu);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Integer idNguoiTao = (Integer)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer sanLuongSanXuat = (Integer)attributes.get("sanLuongSanXuat");

		if (sanLuongSanXuat != null) {
			setSanLuongSanXuat(sanLuongSanXuat);
		}

		Integer sanLuongTieuHao = (Integer)attributes.get("sanLuongTieuHao");

		if (sanLuongTieuHao != null) {
			setSanLuongTieuHao(sanLuongTieuHao);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public int getTramCapNuocId() {
		return _tramCapNuocId;
	}

	@Override
	public void setTramCapNuocId(int tramCapNuocId) {
		_columnBitmask |= TRAMCAPNUOCID_COLUMN_BITMASK;

		if (!_setOriginalTramCapNuocId) {
			_setOriginalTramCapNuocId = true;

			_originalTramCapNuocId = _tramCapNuocId;
		}

		_tramCapNuocId = tramCapNuocId;
	}

	public int getOriginalTramCapNuocId() {
		return _originalTramCapNuocId;
	}

	@Override
	public int getThang() {
		return _thang;
	}

	@Override
	public void setThang(int thang) {
		_columnBitmask = -1L;

		if (!_setOriginalThang) {
			_setOriginalThang = true;

			_originalThang = _thang;
		}

		_thang = thang;
	}

	public int getOriginalThang() {
		return _originalThang;
	}

	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_columnBitmask = -1L;

		if (!_setOriginalNam) {
			_setOriginalNam = true;

			_originalNam = _nam;
		}

		_nam = nam;
	}

	public int getOriginalNam() {
		return _originalNam;
	}

	@Override
	public int getCongXuatThucTe() {
		return _congXuatThucTe;
	}

	@Override
	public void setCongXuatThucTe(int congXuatThucTe) {
		_congXuatThucTe = congXuatThucTe;
	}

	@Override
	public int getNuocThatThoat() {
		return _nuocThatThoat;
	}

	@Override
	public void setNuocThatThoat(int nuocThatThoat) {
		_nuocThatThoat = nuocThatThoat;
	}

	@Override
	public int getNuocDatTieuChuan() {
		return _nuocDatTieuChuan;
	}

	@Override
	public void setNuocDatTieuChuan(int nuocDatTieuChuan) {
		_nuocDatTieuChuan = nuocDatTieuChuan;
	}

	@Override
	public int getNuocCoAsen() {
		return _nuocCoAsen;
	}

	@Override
	public void setNuocCoAsen(int nuocCoAsen) {
		_nuocCoAsen = nuocCoAsen;
	}

	@Override
	public int getTrangThaiCapNuoc() {
		return _trangThaiCapNuoc;
	}

	@Override
	public void setTrangThaiCapNuoc(int trangThaiCapNuoc) {
		_trangThaiCapNuoc = trangThaiCapNuoc;
	}

	@Override
	public int getChiPhiHoaChat() {
		return _chiPhiHoaChat;
	}

	@Override
	public void setChiPhiHoaChat(int chiPhiHoaChat) {
		_chiPhiHoaChat = chiPhiHoaChat;
	}

	@Override
	public int getChiPhiDien() {
		return _chiPhiDien;
	}

	@Override
	public void setChiPhiDien(int chiPhiDien) {
		_chiPhiDien = chiPhiDien;
	}

	@Override
	public int getLuongNhanVien() {
		return _luongNhanVien;
	}

	@Override
	public void setLuongNhanVien(int luongNhanVien) {
		_luongNhanVien = luongNhanVien;
	}

	@Override
	public int getChiPhiSuaChua() {
		return _chiPhiSuaChua;
	}

	@Override
	public void setChiPhiSuaChua(int chiPhiSuaChua) {
		_chiPhiSuaChua = chiPhiSuaChua;
	}

	@Override
	public int getDoanhThu() {
		return _doanhThu;
	}

	@Override
	public void setDoanhThu(int doanhThu) {
		_doanhThu = doanhThu;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public int getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(int idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getSanLuongSanXuat() {
		return _sanLuongSanXuat;
	}

	@Override
	public void setSanLuongSanXuat(int sanLuongSanXuat) {
		_sanLuongSanXuat = sanLuongSanXuat;
	}

	@Override
	public int getSanLuongTieuHao() {
		return _sanLuongTieuHao;
	}

	@Override
	public void setSanLuongTieuHao(int sanLuongTieuHao) {
		_sanLuongTieuHao = sanLuongTieuHao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DanhGiaVanHanh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DanhGiaVanHanh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DanhGiaVanHanh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DanhGiaVanHanhImpl danhGiaVanHanhImpl = new DanhGiaVanHanhImpl();

		danhGiaVanHanhImpl.setId(getId());
		danhGiaVanHanhImpl.setTramCapNuocId(getTramCapNuocId());
		danhGiaVanHanhImpl.setThang(getThang());
		danhGiaVanHanhImpl.setNam(getNam());
		danhGiaVanHanhImpl.setCongXuatThucTe(getCongXuatThucTe());
		danhGiaVanHanhImpl.setNuocThatThoat(getNuocThatThoat());
		danhGiaVanHanhImpl.setNuocDatTieuChuan(getNuocDatTieuChuan());
		danhGiaVanHanhImpl.setNuocCoAsen(getNuocCoAsen());
		danhGiaVanHanhImpl.setTrangThaiCapNuoc(getTrangThaiCapNuoc());
		danhGiaVanHanhImpl.setChiPhiHoaChat(getChiPhiHoaChat());
		danhGiaVanHanhImpl.setChiPhiDien(getChiPhiDien());
		danhGiaVanHanhImpl.setLuongNhanVien(getLuongNhanVien());
		danhGiaVanHanhImpl.setChiPhiSuaChua(getChiPhiSuaChua());
		danhGiaVanHanhImpl.setDoanhThu(getDoanhThu());
		danhGiaVanHanhImpl.setNgayTao(getNgayTao());
		danhGiaVanHanhImpl.setIdNguoiTao(getIdNguoiTao());
		danhGiaVanHanhImpl.setGhiChu(getGhiChu());
		danhGiaVanHanhImpl.setSanLuongSanXuat(getSanLuongSanXuat());
		danhGiaVanHanhImpl.setSanLuongTieuHao(getSanLuongTieuHao());

		danhGiaVanHanhImpl.resetOriginalValues();

		return danhGiaVanHanhImpl;
	}

	@Override
	public int compareTo(DanhGiaVanHanh danhGiaVanHanh) {
		int value = 0;

		if (getNam() < danhGiaVanHanh.getNam()) {
			value = -1;
		}
		else if (getNam() > danhGiaVanHanh.getNam()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		if (getThang() < danhGiaVanHanh.getThang()) {
			value = -1;
		}
		else if (getThang() > danhGiaVanHanh.getThang()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DanhGiaVanHanh)) {
			return false;
		}

		DanhGiaVanHanh danhGiaVanHanh = (DanhGiaVanHanh)obj;

		long primaryKey = danhGiaVanHanh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhGiaVanHanhModelImpl danhGiaVanHanhModelImpl = this;

		danhGiaVanHanhModelImpl._originalTramCapNuocId = danhGiaVanHanhModelImpl._tramCapNuocId;

		danhGiaVanHanhModelImpl._setOriginalTramCapNuocId = false;

		danhGiaVanHanhModelImpl._originalThang = danhGiaVanHanhModelImpl._thang;

		danhGiaVanHanhModelImpl._setOriginalThang = false;

		danhGiaVanHanhModelImpl._originalNam = danhGiaVanHanhModelImpl._nam;

		danhGiaVanHanhModelImpl._setOriginalNam = false;

		danhGiaVanHanhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhGiaVanHanh> toCacheModel() {
		DanhGiaVanHanhCacheModel danhGiaVanHanhCacheModel = new DanhGiaVanHanhCacheModel();

		danhGiaVanHanhCacheModel.id = getId();

		danhGiaVanHanhCacheModel.tramCapNuocId = getTramCapNuocId();

		danhGiaVanHanhCacheModel.thang = getThang();

		danhGiaVanHanhCacheModel.nam = getNam();

		danhGiaVanHanhCacheModel.congXuatThucTe = getCongXuatThucTe();

		danhGiaVanHanhCacheModel.nuocThatThoat = getNuocThatThoat();

		danhGiaVanHanhCacheModel.nuocDatTieuChuan = getNuocDatTieuChuan();

		danhGiaVanHanhCacheModel.nuocCoAsen = getNuocCoAsen();

		danhGiaVanHanhCacheModel.trangThaiCapNuoc = getTrangThaiCapNuoc();

		danhGiaVanHanhCacheModel.chiPhiHoaChat = getChiPhiHoaChat();

		danhGiaVanHanhCacheModel.chiPhiDien = getChiPhiDien();

		danhGiaVanHanhCacheModel.luongNhanVien = getLuongNhanVien();

		danhGiaVanHanhCacheModel.chiPhiSuaChua = getChiPhiSuaChua();

		danhGiaVanHanhCacheModel.doanhThu = getDoanhThu();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhGiaVanHanhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhGiaVanHanhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danhGiaVanHanhCacheModel.idNguoiTao = getIdNguoiTao();

		danhGiaVanHanhCacheModel.ghiChu = getGhiChu();

		String ghiChu = danhGiaVanHanhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			danhGiaVanHanhCacheModel.ghiChu = null;
		}

		danhGiaVanHanhCacheModel.sanLuongSanXuat = getSanLuongSanXuat();

		danhGiaVanHanhCacheModel.sanLuongTieuHao = getSanLuongTieuHao();

		return danhGiaVanHanhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", tramCapNuocId=");
		sb.append(getTramCapNuocId());
		sb.append(", thang=");
		sb.append(getThang());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", congXuatThucTe=");
		sb.append(getCongXuatThucTe());
		sb.append(", nuocThatThoat=");
		sb.append(getNuocThatThoat());
		sb.append(", nuocDatTieuChuan=");
		sb.append(getNuocDatTieuChuan());
		sb.append(", nuocCoAsen=");
		sb.append(getNuocCoAsen());
		sb.append(", trangThaiCapNuoc=");
		sb.append(getTrangThaiCapNuoc());
		sb.append(", chiPhiHoaChat=");
		sb.append(getChiPhiHoaChat());
		sb.append(", chiPhiDien=");
		sb.append(getChiPhiDien());
		sb.append(", luongNhanVien=");
		sb.append(getLuongNhanVien());
		sb.append(", chiPhiSuaChua=");
		sb.append(getChiPhiSuaChua());
		sb.append(", doanhThu=");
		sb.append(getDoanhThu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", sanLuongSanXuat=");
		sb.append(getSanLuongSanXuat());
		sb.append(", sanLuongTieuHao=");
		sb.append(getSanLuongTieuHao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.tramcap.dao.model.DanhGiaVanHanh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tramCapNuocId</column-name><column-value><![CDATA[");
		sb.append(getTramCapNuocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thang</column-name><column-value><![CDATA[");
		sb.append(getThang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>congXuatThucTe</column-name><column-value><![CDATA[");
		sb.append(getCongXuatThucTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocThatThoat</column-name><column-value><![CDATA[");
		sb.append(getNuocThatThoat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocDatTieuChuan</column-name><column-value><![CDATA[");
		sb.append(getNuocDatTieuChuan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocCoAsen</column-name><column-value><![CDATA[");
		sb.append(getNuocCoAsen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiCapNuoc</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiCapNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiPhiHoaChat</column-name><column-value><![CDATA[");
		sb.append(getChiPhiHoaChat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiPhiDien</column-name><column-value><![CDATA[");
		sb.append(getChiPhiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>luongNhanVien</column-name><column-value><![CDATA[");
		sb.append(getLuongNhanVien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiPhiSuaChua</column-name><column-value><![CDATA[");
		sb.append(getChiPhiSuaChua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doanhThu</column-name><column-value><![CDATA[");
		sb.append(getDoanhThu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sanLuongSanXuat</column-name><column-value><![CDATA[");
		sb.append(getSanLuongSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sanLuongTieuHao</column-name><column-value><![CDATA[");
		sb.append(getSanLuongTieuHao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhGiaVanHanh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DanhGiaVanHanh.class
		};
	private long _id;
	private int _tramCapNuocId;
	private int _originalTramCapNuocId;
	private boolean _setOriginalTramCapNuocId;
	private int _thang;
	private int _originalThang;
	private boolean _setOriginalThang;
	private int _nam;
	private int _originalNam;
	private boolean _setOriginalNam;
	private int _congXuatThucTe;
	private int _nuocThatThoat;
	private int _nuocDatTieuChuan;
	private int _nuocCoAsen;
	private int _trangThaiCapNuoc;
	private int _chiPhiHoaChat;
	private int _chiPhiDien;
	private int _luongNhanVien;
	private int _chiPhiSuaChua;
	private int _doanhThu;
	private Date _ngayTao;
	private int _idNguoiTao;
	private String _ghiChu;
	private int _sanLuongSanXuat;
	private int _sanLuongTieuHao;
	private long _columnBitmask;
	private DanhGiaVanHanh _escapedModel;
}