/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.baocaodli.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BaoCaoDLITongHop service. Represents a row in the &quot;ME_TONGHOPDLI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.sol.ns.baocaodli.dao.model.impl.BaoCaoDLITongHopModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.sol.ns.baocaodli.dao.model.impl.BaoCaoDLITongHopImpl}.
 * </p>
 *
 * @author HuyMQ
 * @see BaoCaoDLITongHop
 * @see vn.dtt.sol.ns.baocaodli.dao.model.impl.BaoCaoDLITongHopImpl
 * @see vn.dtt.sol.ns.baocaodli.dao.model.impl.BaoCaoDLITongHopModelImpl
 * @generated
 */
public interface BaoCaoDLITongHopModel extends BaseModel<BaoCaoDLITongHop> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bao cao d l i tong hop model instance should use the {@link BaoCaoDLITongHop} interface instead.
	 */

	/**
	 * Returns the primary key of this bao cao d l i tong hop.
	 *
	 * @return the primary key of this bao cao d l i tong hop
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bao cao d l i tong hop.
	 *
	 * @param primaryKey the primary key of this bao cao d l i tong hop
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this bao cao d l i tong hop.
	 *
	 * @return the ID of this bao cao d l i tong hop
	 */
	public long getId();

	/**
	 * Sets the ID of this bao cao d l i tong hop.
	 *
	 * @param id the ID of this bao cao d l i tong hop
	 */
	public void setId(long id);

	/**
	 * Returns the ma tinh of this bao cao d l i tong hop.
	 *
	 * @return the ma tinh of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this bao cao d l i tong hop.
	 *
	 * @param maTinh the ma tinh of this bao cao d l i tong hop
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the nam of this bao cao d l i tong hop.
	 *
	 * @return the nam of this bao cao d l i tong hop
	 */
	public int getNam();

	/**
	 * Sets the nam of this bao cao d l i tong hop.
	 *
	 * @param nam the nam of this bao cao d l i tong hop
	 */
	public void setNam(int nam);

	/**
	 * Returns the so dau noi theo ke hoach of this bao cao d l i tong hop.
	 *
	 * @return the so dau noi theo ke hoach of this bao cao d l i tong hop
	 */
	public int getSoDauNoiTheoKeHoach();

	/**
	 * Sets the so dau noi theo ke hoach of this bao cao d l i tong hop.
	 *
	 * @param soDauNoiTheoKeHoach the so dau noi theo ke hoach of this bao cao d l i tong hop
	 */
	public void setSoDauNoiTheoKeHoach(int soDauNoiTheoKeHoach);

	/**
	 * Returns the so dau noi moi of this bao cao d l i tong hop.
	 *
	 * @return the so dau noi moi of this bao cao d l i tong hop
	 */
	public int getSoDauNoiMoi();

	/**
	 * Sets the so dau noi moi of this bao cao d l i tong hop.
	 *
	 * @param soDauNoiMoi the so dau noi moi of this bao cao d l i tong hop
	 */
	public void setSoDauNoiMoi(int soDauNoiMoi);

	/**
	 * Returns the so nha tieu h v s theo k h of this bao cao d l i tong hop.
	 *
	 * @return the so nha tieu h v s theo k h of this bao cao d l i tong hop
	 */
	public int getSoNhaTieuHVSTheoKH();

	/**
	 * Sets the so nha tieu h v s theo k h of this bao cao d l i tong hop.
	 *
	 * @param soNhaTieuHVSTheoKH the so nha tieu h v s theo k h of this bao cao d l i tong hop
	 */
	public void setSoNhaTieuHVSTheoKH(int soNhaTieuHVSTheoKH);

	/**
	 * Returns the so nha tieu h v s moi of this bao cao d l i tong hop.
	 *
	 * @return the so nha tieu h v s moi of this bao cao d l i tong hop
	 */
	public int getSoNhaTieuHVSMoi();

	/**
	 * Sets the so nha tieu h v s moi of this bao cao d l i tong hop.
	 *
	 * @param soNhaTieuHVSMoi the so nha tieu h v s moi of this bao cao d l i tong hop
	 */
	public void setSoNhaTieuHVSMoi(int soNhaTieuHVSMoi);

	/**
	 * Returns the so nguoi huong loi nuoc sach of this bao cao d l i tong hop.
	 *
	 * @return the so nguoi huong loi nuoc sach of this bao cao d l i tong hop
	 */
	public int getSoNguoiHuongLoiNuocSach();

	/**
	 * Sets the so nguoi huong loi nuoc sach of this bao cao d l i tong hop.
	 *
	 * @param soNguoiHuongLoiNuocSach the so nguoi huong loi nuoc sach of this bao cao d l i tong hop
	 */
	public void setSoNguoiHuongLoiNuocSach(int soNguoiHuongLoiNuocSach);

	/**
	 * Returns the so xa of this bao cao d l i tong hop.
	 *
	 * @return the so xa of this bao cao d l i tong hop
	 */
	public int getSoXa();

	/**
	 * Sets the so xa of this bao cao d l i tong hop.
	 *
	 * @param soXa the so xa of this bao cao d l i tong hop
	 */
	public void setSoXa(int soXa);

	/**
	 * Returns the ti le h g d co nha tieu of this bao cao d l i tong hop.
	 *
	 * @return the ti le h g d co nha tieu of this bao cao d l i tong hop
	 */
	public int getTiLeHGDCoNhaTieu();

	/**
	 * Sets the ti le h g d co nha tieu of this bao cao d l i tong hop.
	 *
	 * @param tiLeHGDCoNhaTieu the ti le h g d co nha tieu of this bao cao d l i tong hop
	 */
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu);

	/**
	 * Returns the ti le h g d co nha tieu h v s of this bao cao d l i tong hop.
	 *
	 * @return the ti le h g d co nha tieu h v s of this bao cao d l i tong hop
	 */
	public int getTiLeHGDCoNhaTieuHVS();

	/**
	 * Sets the ti le h g d co nha tieu h v s of this bao cao d l i tong hop.
	 *
	 * @param tiLeHGDCoNhaTieuHVS the ti le h g d co nha tieu h v s of this bao cao d l i tong hop
	 */
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS);

	/**
	 * Returns the ti le truong hoc h v s of this bao cao d l i tong hop.
	 *
	 * @return the ti le truong hoc h v s of this bao cao d l i tong hop
	 */
	public int getTiLeTruongHocHVS();

	/**
	 * Sets the ti le truong hoc h v s of this bao cao d l i tong hop.
	 *
	 * @param tiLeTruongHocHVS the ti le truong hoc h v s of this bao cao d l i tong hop
	 */
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS);

	/**
	 * Returns the ti le tram y te h v s of this bao cao d l i tong hop.
	 *
	 * @return the ti le tram y te h v s of this bao cao d l i tong hop
	 */
	public int getTiLeTramYTeHVS();

	/**
	 * Sets the ti le tram y te h v s of this bao cao d l i tong hop.
	 *
	 * @param tiLeTramYTeHVS the ti le tram y te h v s of this bao cao d l i tong hop
	 */
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS);

	/**
	 * Returns the so nguoi huong loi v s t x of this bao cao d l i tong hop.
	 *
	 * @return the so nguoi huong loi v s t x of this bao cao d l i tong hop
	 */
	public int getSoNguoiHuongLoiVSTX();

	/**
	 * Sets the so nguoi huong loi v s t x of this bao cao d l i tong hop.
	 *
	 * @param soNguoiHuongLoiVSTX the so nguoi huong loi v s t x of this bao cao d l i tong hop
	 */
	public void setSoNguoiHuongLoiVSTX(int soNguoiHuongLoiVSTX);

	/**
	 * Returns the ke hoach phe duyet of this bao cao d l i tong hop.
	 *
	 * @return the ke hoach phe duyet of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getKeHoachPheDuyet();

	/**
	 * Sets the ke hoach phe duyet of this bao cao d l i tong hop.
	 *
	 * @param keHoachPheDuyet the ke hoach phe duyet of this bao cao d l i tong hop
	 */
	public void setKeHoachPheDuyet(String keHoachPheDuyet);

	/**
	 * Returns the ngay duyet ke hoach of this bao cao d l i tong hop.
	 *
	 * @return the ngay duyet ke hoach of this bao cao d l i tong hop
	 */
	public Date getNgayDuyetKeHoach();

	/**
	 * Sets the ngay duyet ke hoach of this bao cao d l i tong hop.
	 *
	 * @param ngayDuyetKeHoach the ngay duyet ke hoach of this bao cao d l i tong hop
	 */
	public void setNgayDuyetKeHoach(Date ngayDuyetKeHoach);

	/**
	 * Returns the bao cao chuong trinh of this bao cao d l i tong hop.
	 *
	 * @return the bao cao chuong trinh of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getBaoCaoChuongTrinh();

	/**
	 * Sets the bao cao chuong trinh of this bao cao d l i tong hop.
	 *
	 * @param baoCaoChuongTrinh the bao cao chuong trinh of this bao cao d l i tong hop
	 */
	public void setBaoCaoChuongTrinh(String baoCaoChuongTrinh);

	/**
	 * Returns the ngay dang tai of this bao cao d l i tong hop.
	 *
	 * @return the ngay dang tai of this bao cao d l i tong hop
	 */
	public Date getNgayDangTai();

	/**
	 * Sets the ngay dang tai of this bao cao d l i tong hop.
	 *
	 * @param ngayDangTai the ngay dang tai of this bao cao d l i tong hop
	 */
	public void setNgayDangTai(Date ngayDangTai);

	/**
	 * Returns the nguoi lap of this bao cao d l i tong hop.
	 *
	 * @return the nguoi lap of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getNguoiLap();

	/**
	 * Sets the nguoi lap of this bao cao d l i tong hop.
	 *
	 * @param nguoiLap the nguoi lap of this bao cao d l i tong hop
	 */
	public void setNguoiLap(String nguoiLap);

	/**
	 * Returns the nguoi duyet of this bao cao d l i tong hop.
	 *
	 * @return the nguoi duyet of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getNguoiDuyet();

	/**
	 * Sets the nguoi duyet of this bao cao d l i tong hop.
	 *
	 * @param nguoiDuyet the nguoi duyet of this bao cao d l i tong hop
	 */
	public void setNguoiDuyet(String nguoiDuyet);

	/**
	 * Returns the so bao cao of this bao cao d l i tong hop.
	 *
	 * @return the so bao cao of this bao cao d l i tong hop
	 */
	@AutoEscape
	public String getSoBaoCao();

	/**
	 * Sets the so bao cao of this bao cao d l i tong hop.
	 *
	 * @param soBaoCao the so bao cao of this bao cao d l i tong hop
	 */
	public void setSoBaoCao(String soBaoCao);

	/**
	 * Returns the ngay bao cao of this bao cao d l i tong hop.
	 *
	 * @return the ngay bao cao of this bao cao d l i tong hop
	 */
	public Date getNgayBaoCao();

	/**
	 * Sets the ngay bao cao of this bao cao d l i tong hop.
	 *
	 * @param ngayBaoCao the ngay bao cao of this bao cao d l i tong hop
	 */
	public void setNgayBaoCao(Date ngayBaoCao);

	/**
	 * Returns the trang thai of this bao cao d l i tong hop.
	 *
	 * @return the trang thai of this bao cao d l i tong hop
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this bao cao d l i tong hop.
	 *
	 * @param trangThai the trang thai of this bao cao d l i tong hop
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the luu tru pdf t h of this bao cao d l i tong hop.
	 *
	 * @return the luu tru pdf t h of this bao cao d l i tong hop
	 */
	public int getLuuTruPdfTH();

	/**
	 * Sets the luu tru pdf t h of this bao cao d l i tong hop.
	 *
	 * @param luuTruPdfTH the luu tru pdf t h of this bao cao d l i tong hop
	 */
	public void setLuuTruPdfTH(int luuTruPdfTH);

	/**
	 * Returns the luu tru pdf of this bao cao d l i tong hop.
	 *
	 * @return the luu tru pdf of this bao cao d l i tong hop
	 */
	public int getLuuTruPdf();

	/**
	 * Sets the luu tru pdf of this bao cao d l i tong hop.
	 *
	 * @param luuTruPdf the luu tru pdf of this bao cao d l i tong hop
	 */
	public void setLuuTruPdf(int luuTruPdf);

	/**
	 * Returns the luu tru csv of this bao cao d l i tong hop.
	 *
	 * @return the luu tru csv of this bao cao d l i tong hop
	 */
	public int getLuuTruCsv();

	/**
	 * Sets the luu tru csv of this bao cao d l i tong hop.
	 *
	 * @param luuTruCsv the luu tru csv of this bao cao d l i tong hop
	 */
	public void setLuuTruCsv(int luuTruCsv);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BaoCaoDLITongHop baoCaoDLITongHop);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BaoCaoDLITongHop> toCacheModel();

	@Override
	public BaoCaoDLITongHop toEscapedModel();

	@Override
	public BaoCaoDLITongHop toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}