/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ChiTietKiemDemCongTrinh service. Represents a row in the &quot;ME_CHITIETKIEMDEMCONGTRINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiTietKiemDemCongTrinhImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ChiTietKiemDemCongTrinhImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinhModel
 * @generated
 */
public class ChiTietKiemDemCongTrinhModelImpl extends BaseModelImpl<ChiTietKiemDemCongTrinh>
	implements ChiTietKiemDemCongTrinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chi tiet kiem dem cong trinh model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh} interface instead.
	 */
	public static final String TABLE_NAME = "ME_CHITIETKIEMDEMCONGTRINH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "THONGTINKIEMDEMCONGTRINHID", Types.INTEGER },
			{ "SOHOTIEU", Types.INTEGER },
			{ "LOAINHATIEU", Types.VARCHAR },
			{ "ANHTOANCANH", Types.VARCHAR },
			{ "ANHTRONGNHATIEU", Types.VARCHAR },
			{ "VESINHSACHSE", Types.INTEGER },
			{ "DELAMVESINH", Types.INTEGER },
			{ "MUIVESINH", Types.INTEGER },
			{ "PHIATRENKINDAO", Types.INTEGER },
			{ "DUCHEMUAGIO", Types.INTEGER },
			{ "SANCAOTRENTOITHIEU", Types.INTEGER },
			{ "COCONGTRINHRUATAY", Types.INTEGER },
			{ "CHITIETCONGTRINHRUATAY", Types.VARCHAR },
			{ "ANHBECHUA", Types.VARCHAR },
			{ "NAPBECONTOT", Types.INTEGER },
			{ "CUAPHANBITKIN", Types.INTEGER },
			{ "TRANRANGOAI", Types.INTEGER },
			{ "NUOCTHAIDIDAU", Types.INTEGER },
			{ "KHOANGCACHNGUONNUOC", Types.INTEGER },
			{ "NGAPKHIMUALON", Types.INTEGER },
			{ "TENCONGTRINH", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_CHITIETKIEMDEMCONGTRINH (ID INTEGER not null primary key,THONGTINKIEMDEMCONGTRINHID INTEGER,SOHOTIEU INTEGER,LOAINHATIEU VARCHAR(75) null,ANHTOANCANH VARCHAR(75) null,ANHTRONGNHATIEU VARCHAR(75) null,VESINHSACHSE INTEGER,DELAMVESINH INTEGER,MUIVESINH INTEGER,PHIATRENKINDAO INTEGER,DUCHEMUAGIO INTEGER,SANCAOTRENTOITHIEU INTEGER,COCONGTRINHRUATAY INTEGER,CHITIETCONGTRINHRUATAY VARCHAR(75) null,ANHBECHUA VARCHAR(75) null,NAPBECONTOT INTEGER,CUAPHANBITKIN INTEGER,TRANRANGOAI INTEGER,NUOCTHAIDIDAU INTEGER,KHOANGCACHNGUONNUOC INTEGER,NGAPKHIMUALON INTEGER,TENCONGTRINH VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ME_CHITIETKIEMDEMCONGTRINH";
	public static final String ORDER_BY_JPQL = " ORDER BY chiTietKiemDemCongTrinh.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_CHITIETKIEMDEMCONGTRINH.ID ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh"),
			true);
	public static long THONGTINKIEMDEMCONGTRINHID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh"));

	public ChiTietKiemDemCongTrinhModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChiTietKiemDemCongTrinh.class;
	}

	@Override
	public String getModelClassName() {
		return ChiTietKiemDemCongTrinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongTinKiemDemCongTrinhId",
			getThongTinKiemDemCongTrinhId());
		attributes.put("soHoTieu", getSoHoTieu());
		attributes.put("loaiNhaTieu", getLoaiNhaTieu());
		attributes.put("anhToanCanh", getAnhToanCanh());
		attributes.put("anhTrongNhaTieu", getAnhTrongNhaTieu());
		attributes.put("veSinhSachSe", getVeSinhSachSe());
		attributes.put("deLamVeSinh", getDeLamVeSinh());
		attributes.put("muiVeSinh", getMuiVeSinh());
		attributes.put("phiaTrenKinDao", getPhiaTrenKinDao());
		attributes.put("duCheMuaGio", getDuCheMuaGio());
		attributes.put("sanCaoTrenToiThieu", getSanCaoTrenToiThieu());
		attributes.put("coCongTrinhRuaTay", getCoCongTrinhRuaTay());
		attributes.put("chiTietCongTrinhRuaTay", getChiTietCongTrinhRuaTay());
		attributes.put("anhBeChua", getAnhBeChua());
		attributes.put("napBeConTot", getNapBeConTot());
		attributes.put("cuaPhanBitKin", getCuaPhanBitKin());
		attributes.put("tranRaNgoai", getTranRaNgoai());
		attributes.put("nuocThaiDiDau", getNuocThaiDiDau());
		attributes.put("khoangCachNguonNuoc", getKhoangCachNguonNuoc());
		attributes.put("ngapKhiMuaLon", getNgapKhiMuaLon());
		attributes.put("tenCongTrinh", getTenCongTrinh());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer thongTinKiemDemCongTrinhId = (Integer)attributes.get(
				"thongTinKiemDemCongTrinhId");

		if (thongTinKiemDemCongTrinhId != null) {
			setThongTinKiemDemCongTrinhId(thongTinKiemDemCongTrinhId);
		}

		Integer soHoTieu = (Integer)attributes.get("soHoTieu");

		if (soHoTieu != null) {
			setSoHoTieu(soHoTieu);
		}

		String loaiNhaTieu = (String)attributes.get("loaiNhaTieu");

		if (loaiNhaTieu != null) {
			setLoaiNhaTieu(loaiNhaTieu);
		}

		String anhToanCanh = (String)attributes.get("anhToanCanh");

		if (anhToanCanh != null) {
			setAnhToanCanh(anhToanCanh);
		}

		String anhTrongNhaTieu = (String)attributes.get("anhTrongNhaTieu");

		if (anhTrongNhaTieu != null) {
			setAnhTrongNhaTieu(anhTrongNhaTieu);
		}

		Integer veSinhSachSe = (Integer)attributes.get("veSinhSachSe");

		if (veSinhSachSe != null) {
			setVeSinhSachSe(veSinhSachSe);
		}

		Integer deLamVeSinh = (Integer)attributes.get("deLamVeSinh");

		if (deLamVeSinh != null) {
			setDeLamVeSinh(deLamVeSinh);
		}

		Integer muiVeSinh = (Integer)attributes.get("muiVeSinh");

		if (muiVeSinh != null) {
			setMuiVeSinh(muiVeSinh);
		}

		Integer phiaTrenKinDao = (Integer)attributes.get("phiaTrenKinDao");

		if (phiaTrenKinDao != null) {
			setPhiaTrenKinDao(phiaTrenKinDao);
		}

		Integer duCheMuaGio = (Integer)attributes.get("duCheMuaGio");

		if (duCheMuaGio != null) {
			setDuCheMuaGio(duCheMuaGio);
		}

		Integer sanCaoTrenToiThieu = (Integer)attributes.get(
				"sanCaoTrenToiThieu");

		if (sanCaoTrenToiThieu != null) {
			setSanCaoTrenToiThieu(sanCaoTrenToiThieu);
		}

		Integer coCongTrinhRuaTay = (Integer)attributes.get("coCongTrinhRuaTay");

		if (coCongTrinhRuaTay != null) {
			setCoCongTrinhRuaTay(coCongTrinhRuaTay);
		}

		String chiTietCongTrinhRuaTay = (String)attributes.get(
				"chiTietCongTrinhRuaTay");

		if (chiTietCongTrinhRuaTay != null) {
			setChiTietCongTrinhRuaTay(chiTietCongTrinhRuaTay);
		}

		String anhBeChua = (String)attributes.get("anhBeChua");

		if (anhBeChua != null) {
			setAnhBeChua(anhBeChua);
		}

		Integer napBeConTot = (Integer)attributes.get("napBeConTot");

		if (napBeConTot != null) {
			setNapBeConTot(napBeConTot);
		}

		Integer cuaPhanBitKin = (Integer)attributes.get("cuaPhanBitKin");

		if (cuaPhanBitKin != null) {
			setCuaPhanBitKin(cuaPhanBitKin);
		}

		Integer tranRaNgoai = (Integer)attributes.get("tranRaNgoai");

		if (tranRaNgoai != null) {
			setTranRaNgoai(tranRaNgoai);
		}

		Integer nuocThaiDiDau = (Integer)attributes.get("nuocThaiDiDau");

		if (nuocThaiDiDau != null) {
			setNuocThaiDiDau(nuocThaiDiDau);
		}

		Integer khoangCachNguonNuoc = (Integer)attributes.get(
				"khoangCachNguonNuoc");

		if (khoangCachNguonNuoc != null) {
			setKhoangCachNguonNuoc(khoangCachNguonNuoc);
		}

		Integer ngapKhiMuaLon = (Integer)attributes.get("ngapKhiMuaLon");

		if (ngapKhiMuaLon != null) {
			setNgapKhiMuaLon(ngapKhiMuaLon);
		}

		String tenCongTrinh = (String)attributes.get("tenCongTrinh");

		if (tenCongTrinh != null) {
			setTenCongTrinh(tenCongTrinh);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public int getThongTinKiemDemCongTrinhId() {
		return _thongTinKiemDemCongTrinhId;
	}

	@Override
	public void setThongTinKiemDemCongTrinhId(int thongTinKiemDemCongTrinhId) {
		_columnBitmask |= THONGTINKIEMDEMCONGTRINHID_COLUMN_BITMASK;

		if (!_setOriginalThongTinKiemDemCongTrinhId) {
			_setOriginalThongTinKiemDemCongTrinhId = true;

			_originalThongTinKiemDemCongTrinhId = _thongTinKiemDemCongTrinhId;
		}

		_thongTinKiemDemCongTrinhId = thongTinKiemDemCongTrinhId;
	}

	public int getOriginalThongTinKiemDemCongTrinhId() {
		return _originalThongTinKiemDemCongTrinhId;
	}

	@Override
	public int getSoHoTieu() {
		return _soHoTieu;
	}

	@Override
	public void setSoHoTieu(int soHoTieu) {
		_soHoTieu = soHoTieu;
	}

	@Override
	public String getLoaiNhaTieu() {
		if (_loaiNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNhaTieu;
		}
	}

	@Override
	public void setLoaiNhaTieu(String loaiNhaTieu) {
		_loaiNhaTieu = loaiNhaTieu;
	}

	@Override
	public String getAnhToanCanh() {
		if (_anhToanCanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhToanCanh;
		}
	}

	@Override
	public void setAnhToanCanh(String anhToanCanh) {
		_anhToanCanh = anhToanCanh;
	}

	@Override
	public String getAnhTrongNhaTieu() {
		if (_anhTrongNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhTrongNhaTieu;
		}
	}

	@Override
	public void setAnhTrongNhaTieu(String anhTrongNhaTieu) {
		_anhTrongNhaTieu = anhTrongNhaTieu;
	}

	@Override
	public int getVeSinhSachSe() {
		return _veSinhSachSe;
	}

	@Override
	public void setVeSinhSachSe(int veSinhSachSe) {
		_veSinhSachSe = veSinhSachSe;
	}

	@Override
	public int getDeLamVeSinh() {
		return _deLamVeSinh;
	}

	@Override
	public void setDeLamVeSinh(int deLamVeSinh) {
		_deLamVeSinh = deLamVeSinh;
	}

	@Override
	public int getMuiVeSinh() {
		return _muiVeSinh;
	}

	@Override
	public void setMuiVeSinh(int muiVeSinh) {
		_muiVeSinh = muiVeSinh;
	}

	@Override
	public int getPhiaTrenKinDao() {
		return _phiaTrenKinDao;
	}

	@Override
	public void setPhiaTrenKinDao(int phiaTrenKinDao) {
		_phiaTrenKinDao = phiaTrenKinDao;
	}

	@Override
	public int getDuCheMuaGio() {
		return _duCheMuaGio;
	}

	@Override
	public void setDuCheMuaGio(int duCheMuaGio) {
		_duCheMuaGio = duCheMuaGio;
	}

	@Override
	public int getSanCaoTrenToiThieu() {
		return _sanCaoTrenToiThieu;
	}

	@Override
	public void setSanCaoTrenToiThieu(int sanCaoTrenToiThieu) {
		_sanCaoTrenToiThieu = sanCaoTrenToiThieu;
	}

	@Override
	public int getCoCongTrinhRuaTay() {
		return _coCongTrinhRuaTay;
	}

	@Override
	public void setCoCongTrinhRuaTay(int coCongTrinhRuaTay) {
		_coCongTrinhRuaTay = coCongTrinhRuaTay;
	}

	@Override
	public String getChiTietCongTrinhRuaTay() {
		if (_chiTietCongTrinhRuaTay == null) {
			return StringPool.BLANK;
		}
		else {
			return _chiTietCongTrinhRuaTay;
		}
	}

	@Override
	public void setChiTietCongTrinhRuaTay(String chiTietCongTrinhRuaTay) {
		_chiTietCongTrinhRuaTay = chiTietCongTrinhRuaTay;
	}

	@Override
	public String getAnhBeChua() {
		if (_anhBeChua == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhBeChua;
		}
	}

	@Override
	public void setAnhBeChua(String anhBeChua) {
		_anhBeChua = anhBeChua;
	}

	@Override
	public int getNapBeConTot() {
		return _napBeConTot;
	}

	@Override
	public void setNapBeConTot(int napBeConTot) {
		_napBeConTot = napBeConTot;
	}

	@Override
	public int getCuaPhanBitKin() {
		return _cuaPhanBitKin;
	}

	@Override
	public void setCuaPhanBitKin(int cuaPhanBitKin) {
		_cuaPhanBitKin = cuaPhanBitKin;
	}

	@Override
	public int getTranRaNgoai() {
		return _tranRaNgoai;
	}

	@Override
	public void setTranRaNgoai(int tranRaNgoai) {
		_tranRaNgoai = tranRaNgoai;
	}

	@Override
	public int getNuocThaiDiDau() {
		return _nuocThaiDiDau;
	}

	@Override
	public void setNuocThaiDiDau(int nuocThaiDiDau) {
		_nuocThaiDiDau = nuocThaiDiDau;
	}

	@Override
	public int getKhoangCachNguonNuoc() {
		return _khoangCachNguonNuoc;
	}

	@Override
	public void setKhoangCachNguonNuoc(int khoangCachNguonNuoc) {
		_khoangCachNguonNuoc = khoangCachNguonNuoc;
	}

	@Override
	public int getNgapKhiMuaLon() {
		return _ngapKhiMuaLon;
	}

	@Override
	public void setNgapKhiMuaLon(int ngapKhiMuaLon) {
		_ngapKhiMuaLon = ngapKhiMuaLon;
	}

	@Override
	public String getTenCongTrinh() {
		if (_tenCongTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCongTrinh;
		}
	}

	@Override
	public void setTenCongTrinh(String tenCongTrinh) {
		_tenCongTrinh = tenCongTrinh;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ChiTietKiemDemCongTrinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChiTietKiemDemCongTrinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChiTietKiemDemCongTrinhImpl chiTietKiemDemCongTrinhImpl = new ChiTietKiemDemCongTrinhImpl();

		chiTietKiemDemCongTrinhImpl.setId(getId());
		chiTietKiemDemCongTrinhImpl.setThongTinKiemDemCongTrinhId(getThongTinKiemDemCongTrinhId());
		chiTietKiemDemCongTrinhImpl.setSoHoTieu(getSoHoTieu());
		chiTietKiemDemCongTrinhImpl.setLoaiNhaTieu(getLoaiNhaTieu());
		chiTietKiemDemCongTrinhImpl.setAnhToanCanh(getAnhToanCanh());
		chiTietKiemDemCongTrinhImpl.setAnhTrongNhaTieu(getAnhTrongNhaTieu());
		chiTietKiemDemCongTrinhImpl.setVeSinhSachSe(getVeSinhSachSe());
		chiTietKiemDemCongTrinhImpl.setDeLamVeSinh(getDeLamVeSinh());
		chiTietKiemDemCongTrinhImpl.setMuiVeSinh(getMuiVeSinh());
		chiTietKiemDemCongTrinhImpl.setPhiaTrenKinDao(getPhiaTrenKinDao());
		chiTietKiemDemCongTrinhImpl.setDuCheMuaGio(getDuCheMuaGio());
		chiTietKiemDemCongTrinhImpl.setSanCaoTrenToiThieu(getSanCaoTrenToiThieu());
		chiTietKiemDemCongTrinhImpl.setCoCongTrinhRuaTay(getCoCongTrinhRuaTay());
		chiTietKiemDemCongTrinhImpl.setChiTietCongTrinhRuaTay(getChiTietCongTrinhRuaTay());
		chiTietKiemDemCongTrinhImpl.setAnhBeChua(getAnhBeChua());
		chiTietKiemDemCongTrinhImpl.setNapBeConTot(getNapBeConTot());
		chiTietKiemDemCongTrinhImpl.setCuaPhanBitKin(getCuaPhanBitKin());
		chiTietKiemDemCongTrinhImpl.setTranRaNgoai(getTranRaNgoai());
		chiTietKiemDemCongTrinhImpl.setNuocThaiDiDau(getNuocThaiDiDau());
		chiTietKiemDemCongTrinhImpl.setKhoangCachNguonNuoc(getKhoangCachNguonNuoc());
		chiTietKiemDemCongTrinhImpl.setNgapKhiMuaLon(getNgapKhiMuaLon());
		chiTietKiemDemCongTrinhImpl.setTenCongTrinh(getTenCongTrinh());

		chiTietKiemDemCongTrinhImpl.resetOriginalValues();

		return chiTietKiemDemCongTrinhImpl;
	}

	@Override
	public int compareTo(ChiTietKiemDemCongTrinh chiTietKiemDemCongTrinh) {
		int value = 0;

		if (getId() < chiTietKiemDemCongTrinh.getId()) {
			value = -1;
		}
		else if (getId() > chiTietKiemDemCongTrinh.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChiTietKiemDemCongTrinh)) {
			return false;
		}

		ChiTietKiemDemCongTrinh chiTietKiemDemCongTrinh = (ChiTietKiemDemCongTrinh)obj;

		int primaryKey = chiTietKiemDemCongTrinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChiTietKiemDemCongTrinhModelImpl chiTietKiemDemCongTrinhModelImpl = this;

		chiTietKiemDemCongTrinhModelImpl._originalThongTinKiemDemCongTrinhId = chiTietKiemDemCongTrinhModelImpl._thongTinKiemDemCongTrinhId;

		chiTietKiemDemCongTrinhModelImpl._setOriginalThongTinKiemDemCongTrinhId = false;

		chiTietKiemDemCongTrinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChiTietKiemDemCongTrinh> toCacheModel() {
		ChiTietKiemDemCongTrinhCacheModel chiTietKiemDemCongTrinhCacheModel = new ChiTietKiemDemCongTrinhCacheModel();

		chiTietKiemDemCongTrinhCacheModel.id = getId();

		chiTietKiemDemCongTrinhCacheModel.thongTinKiemDemCongTrinhId = getThongTinKiemDemCongTrinhId();

		chiTietKiemDemCongTrinhCacheModel.soHoTieu = getSoHoTieu();

		chiTietKiemDemCongTrinhCacheModel.loaiNhaTieu = getLoaiNhaTieu();

		String loaiNhaTieu = chiTietKiemDemCongTrinhCacheModel.loaiNhaTieu;

		if ((loaiNhaTieu != null) && (loaiNhaTieu.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.loaiNhaTieu = null;
		}

		chiTietKiemDemCongTrinhCacheModel.anhToanCanh = getAnhToanCanh();

		String anhToanCanh = chiTietKiemDemCongTrinhCacheModel.anhToanCanh;

		if ((anhToanCanh != null) && (anhToanCanh.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.anhToanCanh = null;
		}

		chiTietKiemDemCongTrinhCacheModel.anhTrongNhaTieu = getAnhTrongNhaTieu();

		String anhTrongNhaTieu = chiTietKiemDemCongTrinhCacheModel.anhTrongNhaTieu;

		if ((anhTrongNhaTieu != null) && (anhTrongNhaTieu.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.anhTrongNhaTieu = null;
		}

		chiTietKiemDemCongTrinhCacheModel.veSinhSachSe = getVeSinhSachSe();

		chiTietKiemDemCongTrinhCacheModel.deLamVeSinh = getDeLamVeSinh();

		chiTietKiemDemCongTrinhCacheModel.muiVeSinh = getMuiVeSinh();

		chiTietKiemDemCongTrinhCacheModel.phiaTrenKinDao = getPhiaTrenKinDao();

		chiTietKiemDemCongTrinhCacheModel.duCheMuaGio = getDuCheMuaGio();

		chiTietKiemDemCongTrinhCacheModel.sanCaoTrenToiThieu = getSanCaoTrenToiThieu();

		chiTietKiemDemCongTrinhCacheModel.coCongTrinhRuaTay = getCoCongTrinhRuaTay();

		chiTietKiemDemCongTrinhCacheModel.chiTietCongTrinhRuaTay = getChiTietCongTrinhRuaTay();

		String chiTietCongTrinhRuaTay = chiTietKiemDemCongTrinhCacheModel.chiTietCongTrinhRuaTay;

		if ((chiTietCongTrinhRuaTay != null) &&
				(chiTietCongTrinhRuaTay.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.chiTietCongTrinhRuaTay = null;
		}

		chiTietKiemDemCongTrinhCacheModel.anhBeChua = getAnhBeChua();

		String anhBeChua = chiTietKiemDemCongTrinhCacheModel.anhBeChua;

		if ((anhBeChua != null) && (anhBeChua.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.anhBeChua = null;
		}

		chiTietKiemDemCongTrinhCacheModel.napBeConTot = getNapBeConTot();

		chiTietKiemDemCongTrinhCacheModel.cuaPhanBitKin = getCuaPhanBitKin();

		chiTietKiemDemCongTrinhCacheModel.tranRaNgoai = getTranRaNgoai();

		chiTietKiemDemCongTrinhCacheModel.nuocThaiDiDau = getNuocThaiDiDau();

		chiTietKiemDemCongTrinhCacheModel.khoangCachNguonNuoc = getKhoangCachNguonNuoc();

		chiTietKiemDemCongTrinhCacheModel.ngapKhiMuaLon = getNgapKhiMuaLon();

		chiTietKiemDemCongTrinhCacheModel.tenCongTrinh = getTenCongTrinh();

		String tenCongTrinh = chiTietKiemDemCongTrinhCacheModel.tenCongTrinh;

		if ((tenCongTrinh != null) && (tenCongTrinh.length() == 0)) {
			chiTietKiemDemCongTrinhCacheModel.tenCongTrinh = null;
		}

		return chiTietKiemDemCongTrinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongTinKiemDemCongTrinhId=");
		sb.append(getThongTinKiemDemCongTrinhId());
		sb.append(", soHoTieu=");
		sb.append(getSoHoTieu());
		sb.append(", loaiNhaTieu=");
		sb.append(getLoaiNhaTieu());
		sb.append(", anhToanCanh=");
		sb.append(getAnhToanCanh());
		sb.append(", anhTrongNhaTieu=");
		sb.append(getAnhTrongNhaTieu());
		sb.append(", veSinhSachSe=");
		sb.append(getVeSinhSachSe());
		sb.append(", deLamVeSinh=");
		sb.append(getDeLamVeSinh());
		sb.append(", muiVeSinh=");
		sb.append(getMuiVeSinh());
		sb.append(", phiaTrenKinDao=");
		sb.append(getPhiaTrenKinDao());
		sb.append(", duCheMuaGio=");
		sb.append(getDuCheMuaGio());
		sb.append(", sanCaoTrenToiThieu=");
		sb.append(getSanCaoTrenToiThieu());
		sb.append(", coCongTrinhRuaTay=");
		sb.append(getCoCongTrinhRuaTay());
		sb.append(", chiTietCongTrinhRuaTay=");
		sb.append(getChiTietCongTrinhRuaTay());
		sb.append(", anhBeChua=");
		sb.append(getAnhBeChua());
		sb.append(", napBeConTot=");
		sb.append(getNapBeConTot());
		sb.append(", cuaPhanBitKin=");
		sb.append(getCuaPhanBitKin());
		sb.append(", tranRaNgoai=");
		sb.append(getTranRaNgoai());
		sb.append(", nuocThaiDiDau=");
		sb.append(getNuocThaiDiDau());
		sb.append(", khoangCachNguonNuoc=");
		sb.append(getKhoangCachNguonNuoc());
		sb.append(", ngapKhiMuaLon=");
		sb.append(getNgapKhiMuaLon());
		sb.append(", tenCongTrinh=");
		sb.append(getTenCongTrinh());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.sol.ns.vesinhmoitruong.dao.model.ChiTietKiemDemCongTrinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinKiemDemCongTrinhId</column-name><column-value><![CDATA[");
		sb.append(getThongTinKiemDemCongTrinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHoTieu</column-name><column-value><![CDATA[");
		sb.append(getSoHoTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhToanCanh</column-name><column-value><![CDATA[");
		sb.append(getAnhToanCanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhTrongNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getAnhTrongNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>veSinhSachSe</column-name><column-value><![CDATA[");
		sb.append(getVeSinhSachSe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deLamVeSinh</column-name><column-value><![CDATA[");
		sb.append(getDeLamVeSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>muiVeSinh</column-name><column-value><![CDATA[");
		sb.append(getMuiVeSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phiaTrenKinDao</column-name><column-value><![CDATA[");
		sb.append(getPhiaTrenKinDao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duCheMuaGio</column-name><column-value><![CDATA[");
		sb.append(getDuCheMuaGio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sanCaoTrenToiThieu</column-name><column-value><![CDATA[");
		sb.append(getSanCaoTrenToiThieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coCongTrinhRuaTay</column-name><column-value><![CDATA[");
		sb.append(getCoCongTrinhRuaTay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiTietCongTrinhRuaTay</column-name><column-value><![CDATA[");
		sb.append(getChiTietCongTrinhRuaTay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhBeChua</column-name><column-value><![CDATA[");
		sb.append(getAnhBeChua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>napBeConTot</column-name><column-value><![CDATA[");
		sb.append(getNapBeConTot());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuaPhanBitKin</column-name><column-value><![CDATA[");
		sb.append(getCuaPhanBitKin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tranRaNgoai</column-name><column-value><![CDATA[");
		sb.append(getTranRaNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocThaiDiDau</column-name><column-value><![CDATA[");
		sb.append(getNuocThaiDiDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khoangCachNguonNuoc</column-name><column-value><![CDATA[");
		sb.append(getKhoangCachNguonNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngapKhiMuaLon</column-name><column-value><![CDATA[");
		sb.append(getNgapKhiMuaLon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCongTrinh</column-name><column-value><![CDATA[");
		sb.append(getTenCongTrinh());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChiTietKiemDemCongTrinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ChiTietKiemDemCongTrinh.class
		};
	private int _id;
	private int _thongTinKiemDemCongTrinhId;
	private int _originalThongTinKiemDemCongTrinhId;
	private boolean _setOriginalThongTinKiemDemCongTrinhId;
	private int _soHoTieu;
	private String _loaiNhaTieu;
	private String _anhToanCanh;
	private String _anhTrongNhaTieu;
	private int _veSinhSachSe;
	private int _deLamVeSinh;
	private int _muiVeSinh;
	private int _phiaTrenKinDao;
	private int _duCheMuaGio;
	private int _sanCaoTrenToiThieu;
	private int _coCongTrinhRuaTay;
	private String _chiTietCongTrinhRuaTay;
	private String _anhBeChua;
	private int _napBeConTot;
	private int _cuaPhanBitKin;
	private int _tranRaNgoai;
	private int _nuocThaiDiDau;
	private int _khoangCachNguonNuoc;
	private int _ngapKhiMuaLon;
	private String _tenCongTrinh;
	private long _columnBitmask;
	private ChiTietKiemDemCongTrinh _escapedModel;
}