/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGDModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ThongTinKiemDemHoGD service. Represents a row in the &quot;ME_THONGTINKIEMDEMHOGD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGDModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongTinKiemDemHoGDImpl}.
 * </p>
 *
 * @author BinhTH
 * @see ThongTinKiemDemHoGDImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGDModel
 * @generated
 */
public class ThongTinKiemDemHoGDModelImpl extends BaseModelImpl<ThongTinKiemDemHoGD>
	implements ThongTinKiemDemHoGDModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong tin kiem dem ho g d model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD} interface instead.
	 */
	public static final String TABLE_NAME = "ME_THONGTINKIEMDEMHOGD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "VESINHGIADINHID", Types.INTEGER },
			{ "KEHOACHKIEMDEMVESINHID", Types.INTEGER },
			{ "MATINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "THONXOM", Types.VARCHAR },
			{ "TENCHUHO", Types.VARCHAR },
			{ "GIOITINHCHUHO", Types.INTEGER },
			{ "NGAYKIEMDEM", Types.TIMESTAMP },
			{ "TIMTHAYNHA", Types.INTEGER },
			{ "CONGUOIONHA", Types.INTEGER },
			{ "SONGUOITRONGHO", Types.INTEGER },
			{ "HOTENNGUOITRALOI", Types.VARCHAR },
			{ "LACHUHOKHONG", Types.INTEGER },
			{ "GIOITINHNGUOITRALOI", Types.VARCHAR },
			{ "TENDANTOC", Types.VARCHAR },
			{ "KINHDO", Types.VARCHAR },
			{ "VIDO", Types.VARCHAR },
			{ "THANHPHANHOGD", Types.INTEGER },
			{ "CHUHODUNGDS", Types.INTEGER },
			{ "LYDOKHONGDUNGDS", Types.VARCHAR },
			{ "TENCHUHOHIENTAI", Types.VARCHAR },
			{ "GIOITINHCHUHOHIENTAI", Types.INTEGER },
			{ "CONHATIEU", Types.INTEGER },
			{ "LOAINGUONNUOC", Types.VARCHAR },
			{ "LOAINHATIEU", Types.VARCHAR },
			{ "ANHTOANCANh", Types.VARCHAR },
			{ "ANHTRONGNHATIEU", Types.VARCHAR },
			{ "THANGXAYDUNG", Types.INTEGER },
			{ "NAMXAYDUNG", Types.INTEGER },
			{ "NGUONVON", Types.INTEGER },
			{ "CHITIETVONVAY", Types.VARCHAR },
			{ "DUOCCAITAO", Types.INTEGER },
			{ "LOAINHATIEUCU", Types.VARCHAR },
			{ "ANHBECHUA", Types.VARCHAR },
			{ "VESINHSACHSE", Types.INTEGER },
			{ "DELAMVESINH", Types.INTEGER },
			{ "MUIVESINH", Types.INTEGER },
			{ "PHIATRENKINDAO", Types.INTEGER },
			{ "DUCHEMUAGIO", Types.INTEGER },
			{ "SANCAOTRENTOITHIEU", Types.INTEGER },
			{ "NAPBECONTOT", Types.INTEGER },
			{ "CUAPHANBITKIN", Types.INTEGER },
			{ "TRANRANGOAI", Types.INTEGER },
			{ "NUOCTHAIDIDAU", Types.INTEGER },
			{ "KHOANGCACHNGUONNUOC", Types.INTEGER },
			{ "NGAPKHIMUALON", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "DAKETTHUCDIEUTRA", Types.INTEGER },
			{ "LYDOKHONGHOANTHANH", Types.VARCHAR },
			{ "IMEI", Types.VARCHAR },
			{ "TAIKHOAN", Types.VARCHAR },
			{ "DANHGIAKIEMDEM", Types.INTEGER },
			{ "SAVEPOINT", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_THONGTINKIEMDEMHOGD (ID INTEGER not null primary key,VESINHGIADINHID INTEGER,KEHOACHKIEMDEMVESINHID INTEGER,MATINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,THONXOM VARCHAR(75) null,TENCHUHO VARCHAR(75) null,GIOITINHCHUHO INTEGER,NGAYKIEMDEM DATE null,TIMTHAYNHA INTEGER,CONGUOIONHA INTEGER,SONGUOITRONGHO INTEGER,HOTENNGUOITRALOI VARCHAR(75) null,LACHUHOKHONG INTEGER,GIOITINHNGUOITRALOI VARCHAR(75) null,TENDANTOC VARCHAR(75) null,KINHDO VARCHAR(75) null,VIDO VARCHAR(75) null,THANHPHANHOGD INTEGER,CHUHODUNGDS INTEGER,LYDOKHONGDUNGDS VARCHAR(75) null,TENCHUHOHIENTAI VARCHAR(75) null,GIOITINHCHUHOHIENTAI INTEGER,CONHATIEU INTEGER,LOAINGUONNUOC VARCHAR(75) null,LOAINHATIEU VARCHAR(75) null,ANHTOANCANh VARCHAR(75) null,ANHTRONGNHATIEU VARCHAR(75) null,THANGXAYDUNG INTEGER,NAMXAYDUNG INTEGER,NGUONVON INTEGER,CHITIETVONVAY VARCHAR(75) null,DUOCCAITAO INTEGER,LOAINHATIEUCU VARCHAR(75) null,ANHBECHUA VARCHAR(75) null,VESINHSACHSE INTEGER,DELAMVESINH INTEGER,MUIVESINH INTEGER,PHIATRENKINDAO INTEGER,DUCHEMUAGIO INTEGER,SANCAOTRENTOITHIEU INTEGER,NAPBECONTOT INTEGER,CUAPHANBITKIN INTEGER,TRANRANGOAI INTEGER,NUOCTHAIDIDAU INTEGER,KHOANGCACHNGUONNUOC INTEGER,NGAPKHIMUALON INTEGER,GHICHU VARCHAR(75) null,DAKETTHUCDIEUTRA INTEGER,LYDOKHONGHOANTHANH VARCHAR(75) null,IMEI VARCHAR(75) null,TAIKHOAN VARCHAR(75) null,DANHGIAKIEMDEM INTEGER,SAVEPOINT DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ME_THONGTINKIEMDEMHOGD";
	public static final String ORDER_BY_JPQL = " ORDER BY thongTinKiemDemHoGD.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_THONGTINKIEMDEMHOGD.ID ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD"),
			true);
	public static long DAKETTHUCDIEUTRA_COLUMN_BITMASK = 1L;
	public static long DANHGIAKIEMDEM_COLUMN_BITMASK = 2L;
	public static long KEHOACHKIEMDEMVESINHID_COLUMN_BITMASK = 4L;
	public static long VESINHGIADINHID_COLUMN_BITMASK = 8L;
	public static long ID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD"));

	public ThongTinKiemDemHoGDModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThongTinKiemDemHoGD.class;
	}

	@Override
	public String getModelClassName() {
		return ThongTinKiemDemHoGD.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("veSinhGiaDinhId", getVeSinhGiaDinhId());
		attributes.put("keHoachKiemDemVeSinhId", getKeHoachKiemDemVeSinhId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("thonXom", getThonXom());
		attributes.put("tenChuHo", getTenChuHo());
		attributes.put("gioiTinhChuHo", getGioiTinhChuHo());
		attributes.put("ngayKiemDem", getNgayKiemDem());
		attributes.put("timThayNha", getTimThayNha());
		attributes.put("coNguoiONha", getCoNguoiONha());
		attributes.put("soNguoiTrongHo", getSoNguoiTrongHo());
		attributes.put("hoTenNguoiTraLoi", getHoTenNguoiTraLoi());
		attributes.put("laChuHoKhong", getLaChuHoKhong());
		attributes.put("gioiTinhNguoiTraLoi", getGioiTinhNguoiTraLoi());
		attributes.put("tenDanToc", getTenDanToc());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("thanhPhanHoGD", getThanhPhanHoGD());
		attributes.put("chuHoDungDS", getChuHoDungDS());
		attributes.put("lyDoKhongDungDS", getLyDoKhongDungDS());
		attributes.put("tenChuHoHienTai", getTenChuHoHienTai());
		attributes.put("gioiTinhChuHoHienTai", getGioiTinhChuHoHienTai());
		attributes.put("coNhaTieu", getCoNhaTieu());
		attributes.put("loaiNguonNuoc", getLoaiNguonNuoc());
		attributes.put("loaiNhaTieu", getLoaiNhaTieu());
		attributes.put("anhToanCanh", getAnhToanCanh());
		attributes.put("anhTrongNhaTieu", getAnhTrongNhaTieu());
		attributes.put("thangXayDung", getThangXayDung());
		attributes.put("namXayDung", getNamXayDung());
		attributes.put("nguonVon", getNguonVon());
		attributes.put("chiTietVonVay", getChiTietVonVay());
		attributes.put("duocCaiTao", getDuocCaiTao());
		attributes.put("loaiNhaTieuCu", getLoaiNhaTieuCu());
		attributes.put("anhBeChua", getAnhBeChua());
		attributes.put("veSinhSachSe", getVeSinhSachSe());
		attributes.put("deLamVeSinh", getDeLamVeSinh());
		attributes.put("muiVeSinh", getMuiVeSinh());
		attributes.put("phiaTrenKinDao", getPhiaTrenKinDao());
		attributes.put("duCheMuaGio", getDuCheMuaGio());
		attributes.put("sanCaoTrenToiThieu", getSanCaoTrenToiThieu());
		attributes.put("napBeConTot", getNapBeConTot());
		attributes.put("cuaPhanBitKin", getCuaPhanBitKin());
		attributes.put("tranRaNgoai", getTranRaNgoai());
		attributes.put("nuocThaiDiDau", getNuocThaiDiDau());
		attributes.put("khoangCachNguonNuoc", getKhoangCachNguonNuoc());
		attributes.put("ngapKhiMuaLon", getNgapKhiMuaLon());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("daKetThucDieuTra", getDaKetThucDieuTra());
		attributes.put("lyDoKhongHoanThanh", getLyDoKhongHoanThanh());
		attributes.put("imei", getImei());
		attributes.put("taiKhoan", getTaiKhoan());
		attributes.put("danhGiaKiemDem", getDanhGiaKiemDem());
		attributes.put("savePoint", getSavePoint());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer veSinhGiaDinhId = (Integer)attributes.get("veSinhGiaDinhId");

		if (veSinhGiaDinhId != null) {
			setVeSinhGiaDinhId(veSinhGiaDinhId);
		}

		Integer keHoachKiemDemVeSinhId = (Integer)attributes.get(
				"keHoachKiemDemVeSinhId");

		if (keHoachKiemDemVeSinhId != null) {
			setKeHoachKiemDemVeSinhId(keHoachKiemDemVeSinhId);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String thonXom = (String)attributes.get("thonXom");

		if (thonXom != null) {
			setThonXom(thonXom);
		}

		String tenChuHo = (String)attributes.get("tenChuHo");

		if (tenChuHo != null) {
			setTenChuHo(tenChuHo);
		}

		Integer gioiTinhChuHo = (Integer)attributes.get("gioiTinhChuHo");

		if (gioiTinhChuHo != null) {
			setGioiTinhChuHo(gioiTinhChuHo);
		}

		Date ngayKiemDem = (Date)attributes.get("ngayKiemDem");

		if (ngayKiemDem != null) {
			setNgayKiemDem(ngayKiemDem);
		}

		Integer timThayNha = (Integer)attributes.get("timThayNha");

		if (timThayNha != null) {
			setTimThayNha(timThayNha);
		}

		Integer coNguoiONha = (Integer)attributes.get("coNguoiONha");

		if (coNguoiONha != null) {
			setCoNguoiONha(coNguoiONha);
		}

		Integer soNguoiTrongHo = (Integer)attributes.get("soNguoiTrongHo");

		if (soNguoiTrongHo != null) {
			setSoNguoiTrongHo(soNguoiTrongHo);
		}

		String hoTenNguoiTraLoi = (String)attributes.get("hoTenNguoiTraLoi");

		if (hoTenNguoiTraLoi != null) {
			setHoTenNguoiTraLoi(hoTenNguoiTraLoi);
		}

		Integer laChuHoKhong = (Integer)attributes.get("laChuHoKhong");

		if (laChuHoKhong != null) {
			setLaChuHoKhong(laChuHoKhong);
		}

		String gioiTinhNguoiTraLoi = (String)attributes.get(
				"gioiTinhNguoiTraLoi");

		if (gioiTinhNguoiTraLoi != null) {
			setGioiTinhNguoiTraLoi(gioiTinhNguoiTraLoi);
		}

		String tenDanToc = (String)attributes.get("tenDanToc");

		if (tenDanToc != null) {
			setTenDanToc(tenDanToc);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		Integer thanhPhanHoGD = (Integer)attributes.get("thanhPhanHoGD");

		if (thanhPhanHoGD != null) {
			setThanhPhanHoGD(thanhPhanHoGD);
		}

		Integer chuHoDungDS = (Integer)attributes.get("chuHoDungDS");

		if (chuHoDungDS != null) {
			setChuHoDungDS(chuHoDungDS);
		}

		String lyDoKhongDungDS = (String)attributes.get("lyDoKhongDungDS");

		if (lyDoKhongDungDS != null) {
			setLyDoKhongDungDS(lyDoKhongDungDS);
		}

		String tenChuHoHienTai = (String)attributes.get("tenChuHoHienTai");

		if (tenChuHoHienTai != null) {
			setTenChuHoHienTai(tenChuHoHienTai);
		}

		Integer gioiTinhChuHoHienTai = (Integer)attributes.get(
				"gioiTinhChuHoHienTai");

		if (gioiTinhChuHoHienTai != null) {
			setGioiTinhChuHoHienTai(gioiTinhChuHoHienTai);
		}

		Integer coNhaTieu = (Integer)attributes.get("coNhaTieu");

		if (coNhaTieu != null) {
			setCoNhaTieu(coNhaTieu);
		}

		String loaiNguonNuoc = (String)attributes.get("loaiNguonNuoc");

		if (loaiNguonNuoc != null) {
			setLoaiNguonNuoc(loaiNguonNuoc);
		}

		String loaiNhaTieu = (String)attributes.get("loaiNhaTieu");

		if (loaiNhaTieu != null) {
			setLoaiNhaTieu(loaiNhaTieu);
		}

		String anhToanCanh = (String)attributes.get("anhToanCanh");

		if (anhToanCanh != null) {
			setAnhToanCanh(anhToanCanh);
		}

		String anhTrongNhaTieu = (String)attributes.get("anhTrongNhaTieu");

		if (anhTrongNhaTieu != null) {
			setAnhTrongNhaTieu(anhTrongNhaTieu);
		}

		Integer thangXayDung = (Integer)attributes.get("thangXayDung");

		if (thangXayDung != null) {
			setThangXayDung(thangXayDung);
		}

		Integer namXayDung = (Integer)attributes.get("namXayDung");

		if (namXayDung != null) {
			setNamXayDung(namXayDung);
		}

		Integer nguonVon = (Integer)attributes.get("nguonVon");

		if (nguonVon != null) {
			setNguonVon(nguonVon);
		}

		String chiTietVonVay = (String)attributes.get("chiTietVonVay");

		if (chiTietVonVay != null) {
			setChiTietVonVay(chiTietVonVay);
		}

		Integer duocCaiTao = (Integer)attributes.get("duocCaiTao");

		if (duocCaiTao != null) {
			setDuocCaiTao(duocCaiTao);
		}

		String loaiNhaTieuCu = (String)attributes.get("loaiNhaTieuCu");

		if (loaiNhaTieuCu != null) {
			setLoaiNhaTieuCu(loaiNhaTieuCu);
		}

		String anhBeChua = (String)attributes.get("anhBeChua");

		if (anhBeChua != null) {
			setAnhBeChua(anhBeChua);
		}

		Integer veSinhSachSe = (Integer)attributes.get("veSinhSachSe");

		if (veSinhSachSe != null) {
			setVeSinhSachSe(veSinhSachSe);
		}

		Integer deLamVeSinh = (Integer)attributes.get("deLamVeSinh");

		if (deLamVeSinh != null) {
			setDeLamVeSinh(deLamVeSinh);
		}

		Integer muiVeSinh = (Integer)attributes.get("muiVeSinh");

		if (muiVeSinh != null) {
			setMuiVeSinh(muiVeSinh);
		}

		Integer phiaTrenKinDao = (Integer)attributes.get("phiaTrenKinDao");

		if (phiaTrenKinDao != null) {
			setPhiaTrenKinDao(phiaTrenKinDao);
		}

		Integer duCheMuaGio = (Integer)attributes.get("duCheMuaGio");

		if (duCheMuaGio != null) {
			setDuCheMuaGio(duCheMuaGio);
		}

		Integer sanCaoTrenToiThieu = (Integer)attributes.get(
				"sanCaoTrenToiThieu");

		if (sanCaoTrenToiThieu != null) {
			setSanCaoTrenToiThieu(sanCaoTrenToiThieu);
		}

		Integer napBeConTot = (Integer)attributes.get("napBeConTot");

		if (napBeConTot != null) {
			setNapBeConTot(napBeConTot);
		}

		Integer cuaPhanBitKin = (Integer)attributes.get("cuaPhanBitKin");

		if (cuaPhanBitKin != null) {
			setCuaPhanBitKin(cuaPhanBitKin);
		}

		Integer tranRaNgoai = (Integer)attributes.get("tranRaNgoai");

		if (tranRaNgoai != null) {
			setTranRaNgoai(tranRaNgoai);
		}

		Integer nuocThaiDiDau = (Integer)attributes.get("nuocThaiDiDau");

		if (nuocThaiDiDau != null) {
			setNuocThaiDiDau(nuocThaiDiDau);
		}

		Integer khoangCachNguonNuoc = (Integer)attributes.get(
				"khoangCachNguonNuoc");

		if (khoangCachNguonNuoc != null) {
			setKhoangCachNguonNuoc(khoangCachNguonNuoc);
		}

		Integer ngapKhiMuaLon = (Integer)attributes.get("ngapKhiMuaLon");

		if (ngapKhiMuaLon != null) {
			setNgapKhiMuaLon(ngapKhiMuaLon);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer daKetThucDieuTra = (Integer)attributes.get("daKetThucDieuTra");

		if (daKetThucDieuTra != null) {
			setDaKetThucDieuTra(daKetThucDieuTra);
		}

		String lyDoKhongHoanThanh = (String)attributes.get("lyDoKhongHoanThanh");

		if (lyDoKhongHoanThanh != null) {
			setLyDoKhongHoanThanh(lyDoKhongHoanThanh);
		}

		String imei = (String)attributes.get("imei");

		if (imei != null) {
			setImei(imei);
		}

		String taiKhoan = (String)attributes.get("taiKhoan");

		if (taiKhoan != null) {
			setTaiKhoan(taiKhoan);
		}

		Integer danhGiaKiemDem = (Integer)attributes.get("danhGiaKiemDem");

		if (danhGiaKiemDem != null) {
			setDanhGiaKiemDem(danhGiaKiemDem);
		}

		Date savePoint = (Date)attributes.get("savePoint");

		if (savePoint != null) {
			setSavePoint(savePoint);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public int getVeSinhGiaDinhId() {
		return _veSinhGiaDinhId;
	}

	@Override
	public void setVeSinhGiaDinhId(int veSinhGiaDinhId) {
		_columnBitmask |= VESINHGIADINHID_COLUMN_BITMASK;

		if (!_setOriginalVeSinhGiaDinhId) {
			_setOriginalVeSinhGiaDinhId = true;

			_originalVeSinhGiaDinhId = _veSinhGiaDinhId;
		}

		_veSinhGiaDinhId = veSinhGiaDinhId;
	}

	public int getOriginalVeSinhGiaDinhId() {
		return _originalVeSinhGiaDinhId;
	}

	@Override
	public int getKeHoachKiemDemVeSinhId() {
		return _keHoachKiemDemVeSinhId;
	}

	@Override
	public void setKeHoachKiemDemVeSinhId(int keHoachKiemDemVeSinhId) {
		_columnBitmask |= KEHOACHKIEMDEMVESINHID_COLUMN_BITMASK;

		if (!_setOriginalKeHoachKiemDemVeSinhId) {
			_setOriginalKeHoachKiemDemVeSinhId = true;

			_originalKeHoachKiemDemVeSinhId = _keHoachKiemDemVeSinhId;
		}

		_keHoachKiemDemVeSinhId = keHoachKiemDemVeSinhId;
	}

	public int getOriginalKeHoachKiemDemVeSinhId() {
		return _originalKeHoachKiemDemVeSinhId;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_maTinh = maTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getThonXom() {
		if (_thonXom == null) {
			return StringPool.BLANK;
		}
		else {
			return _thonXom;
		}
	}

	@Override
	public void setThonXom(String thonXom) {
		_thonXom = thonXom;
	}

	@Override
	public String getTenChuHo() {
		if (_tenChuHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHo;
		}
	}

	@Override
	public void setTenChuHo(String tenChuHo) {
		_tenChuHo = tenChuHo;
	}

	@Override
	public int getGioiTinhChuHo() {
		return _gioiTinhChuHo;
	}

	@Override
	public void setGioiTinhChuHo(int gioiTinhChuHo) {
		_gioiTinhChuHo = gioiTinhChuHo;
	}

	@Override
	public Date getNgayKiemDem() {
		return _ngayKiemDem;
	}

	@Override
	public void setNgayKiemDem(Date ngayKiemDem) {
		_ngayKiemDem = ngayKiemDem;
	}

	@Override
	public int getTimThayNha() {
		return _timThayNha;
	}

	@Override
	public void setTimThayNha(int timThayNha) {
		_timThayNha = timThayNha;
	}

	@Override
	public int getCoNguoiONha() {
		return _coNguoiONha;
	}

	@Override
	public void setCoNguoiONha(int coNguoiONha) {
		_coNguoiONha = coNguoiONha;
	}

	@Override
	public int getSoNguoiTrongHo() {
		return _soNguoiTrongHo;
	}

	@Override
	public void setSoNguoiTrongHo(int soNguoiTrongHo) {
		_soNguoiTrongHo = soNguoiTrongHo;
	}

	@Override
	public String getHoTenNguoiTraLoi() {
		if (_hoTenNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenNguoiTraLoi;
		}
	}

	@Override
	public void setHoTenNguoiTraLoi(String hoTenNguoiTraLoi) {
		_hoTenNguoiTraLoi = hoTenNguoiTraLoi;
	}

	@Override
	public int getLaChuHoKhong() {
		return _laChuHoKhong;
	}

	@Override
	public void setLaChuHoKhong(int laChuHoKhong) {
		_laChuHoKhong = laChuHoKhong;
	}

	@Override
	public String getGioiTinhNguoiTraLoi() {
		if (_gioiTinhNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _gioiTinhNguoiTraLoi;
		}
	}

	@Override
	public void setGioiTinhNguoiTraLoi(String gioiTinhNguoiTraLoi) {
		_gioiTinhNguoiTraLoi = gioiTinhNguoiTraLoi;
	}

	@Override
	public String getTenDanToc() {
		if (_tenDanToc == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDanToc;
		}
	}

	@Override
	public void setTenDanToc(String tenDanToc) {
		_tenDanToc = tenDanToc;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public int getThanhPhanHoGD() {
		return _thanhPhanHoGD;
	}

	@Override
	public void setThanhPhanHoGD(int thanhPhanHoGD) {
		_thanhPhanHoGD = thanhPhanHoGD;
	}

	@Override
	public int getChuHoDungDS() {
		return _chuHoDungDS;
	}

	@Override
	public void setChuHoDungDS(int chuHoDungDS) {
		_chuHoDungDS = chuHoDungDS;
	}

	@Override
	public String getLyDoKhongDungDS() {
		if (_lyDoKhongDungDS == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDungDS;
		}
	}

	@Override
	public void setLyDoKhongDungDS(String lyDoKhongDungDS) {
		_lyDoKhongDungDS = lyDoKhongDungDS;
	}

	@Override
	public String getTenChuHoHienTai() {
		if (_tenChuHoHienTai == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHoHienTai;
		}
	}

	@Override
	public void setTenChuHoHienTai(String tenChuHoHienTai) {
		_tenChuHoHienTai = tenChuHoHienTai;
	}

	@Override
	public int getGioiTinhChuHoHienTai() {
		return _gioiTinhChuHoHienTai;
	}

	@Override
	public void setGioiTinhChuHoHienTai(int gioiTinhChuHoHienTai) {
		_gioiTinhChuHoHienTai = gioiTinhChuHoHienTai;
	}

	@Override
	public int getCoNhaTieu() {
		return _coNhaTieu;
	}

	@Override
	public void setCoNhaTieu(int coNhaTieu) {
		_coNhaTieu = coNhaTieu;
	}

	@Override
	public String getLoaiNguonNuoc() {
		if (_loaiNguonNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNguonNuoc;
		}
	}

	@Override
	public void setLoaiNguonNuoc(String loaiNguonNuoc) {
		_loaiNguonNuoc = loaiNguonNuoc;
	}

	@Override
	public String getLoaiNhaTieu() {
		if (_loaiNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNhaTieu;
		}
	}

	@Override
	public void setLoaiNhaTieu(String loaiNhaTieu) {
		_loaiNhaTieu = loaiNhaTieu;
	}

	@Override
	public String getAnhToanCanh() {
		if (_anhToanCanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhToanCanh;
		}
	}

	@Override
	public void setAnhToanCanh(String anhToanCanh) {
		_anhToanCanh = anhToanCanh;
	}

	@Override
	public String getAnhTrongNhaTieu() {
		if (_anhTrongNhaTieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhTrongNhaTieu;
		}
	}

	@Override
	public void setAnhTrongNhaTieu(String anhTrongNhaTieu) {
		_anhTrongNhaTieu = anhTrongNhaTieu;
	}

	@Override
	public int getThangXayDung() {
		return _thangXayDung;
	}

	@Override
	public void setThangXayDung(int thangXayDung) {
		_thangXayDung = thangXayDung;
	}

	@Override
	public int getNamXayDung() {
		return _namXayDung;
	}

	@Override
	public void setNamXayDung(int namXayDung) {
		_namXayDung = namXayDung;
	}

	@Override
	public int getNguonVon() {
		return _nguonVon;
	}

	@Override
	public void setNguonVon(int nguonVon) {
		_nguonVon = nguonVon;
	}

	@Override
	public String getChiTietVonVay() {
		if (_chiTietVonVay == null) {
			return StringPool.BLANK;
		}
		else {
			return _chiTietVonVay;
		}
	}

	@Override
	public void setChiTietVonVay(String chiTietVonVay) {
		_chiTietVonVay = chiTietVonVay;
	}

	@Override
	public int getDuocCaiTao() {
		return _duocCaiTao;
	}

	@Override
	public void setDuocCaiTao(int duocCaiTao) {
		_duocCaiTao = duocCaiTao;
	}

	@Override
	public String getLoaiNhaTieuCu() {
		if (_loaiNhaTieuCu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNhaTieuCu;
		}
	}

	@Override
	public void setLoaiNhaTieuCu(String loaiNhaTieuCu) {
		_loaiNhaTieuCu = loaiNhaTieuCu;
	}

	@Override
	public String getAnhBeChua() {
		if (_anhBeChua == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhBeChua;
		}
	}

	@Override
	public void setAnhBeChua(String anhBeChua) {
		_anhBeChua = anhBeChua;
	}

	@Override
	public int getVeSinhSachSe() {
		return _veSinhSachSe;
	}

	@Override
	public void setVeSinhSachSe(int veSinhSachSe) {
		_veSinhSachSe = veSinhSachSe;
	}

	@Override
	public int getDeLamVeSinh() {
		return _deLamVeSinh;
	}

	@Override
	public void setDeLamVeSinh(int deLamVeSinh) {
		_deLamVeSinh = deLamVeSinh;
	}

	@Override
	public int getMuiVeSinh() {
		return _muiVeSinh;
	}

	@Override
	public void setMuiVeSinh(int muiVeSinh) {
		_muiVeSinh = muiVeSinh;
	}

	@Override
	public int getPhiaTrenKinDao() {
		return _phiaTrenKinDao;
	}

	@Override
	public void setPhiaTrenKinDao(int phiaTrenKinDao) {
		_phiaTrenKinDao = phiaTrenKinDao;
	}

	@Override
	public int getDuCheMuaGio() {
		return _duCheMuaGio;
	}

	@Override
	public void setDuCheMuaGio(int duCheMuaGio) {
		_duCheMuaGio = duCheMuaGio;
	}

	@Override
	public int getSanCaoTrenToiThieu() {
		return _sanCaoTrenToiThieu;
	}

	@Override
	public void setSanCaoTrenToiThieu(int sanCaoTrenToiThieu) {
		_sanCaoTrenToiThieu = sanCaoTrenToiThieu;
	}

	@Override
	public int getNapBeConTot() {
		return _napBeConTot;
	}

	@Override
	public void setNapBeConTot(int napBeConTot) {
		_napBeConTot = napBeConTot;
	}

	@Override
	public int getCuaPhanBitKin() {
		return _cuaPhanBitKin;
	}

	@Override
	public void setCuaPhanBitKin(int cuaPhanBitKin) {
		_cuaPhanBitKin = cuaPhanBitKin;
	}

	@Override
	public int getTranRaNgoai() {
		return _tranRaNgoai;
	}

	@Override
	public void setTranRaNgoai(int tranRaNgoai) {
		_tranRaNgoai = tranRaNgoai;
	}

	@Override
	public int getNuocThaiDiDau() {
		return _nuocThaiDiDau;
	}

	@Override
	public void setNuocThaiDiDau(int nuocThaiDiDau) {
		_nuocThaiDiDau = nuocThaiDiDau;
	}

	@Override
	public int getKhoangCachNguonNuoc() {
		return _khoangCachNguonNuoc;
	}

	@Override
	public void setKhoangCachNguonNuoc(int khoangCachNguonNuoc) {
		_khoangCachNguonNuoc = khoangCachNguonNuoc;
	}

	@Override
	public int getNgapKhiMuaLon() {
		return _ngapKhiMuaLon;
	}

	@Override
	public void setNgapKhiMuaLon(int ngapKhiMuaLon) {
		_ngapKhiMuaLon = ngapKhiMuaLon;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getDaKetThucDieuTra() {
		return _daKetThucDieuTra;
	}

	@Override
	public void setDaKetThucDieuTra(int daKetThucDieuTra) {
		_columnBitmask |= DAKETTHUCDIEUTRA_COLUMN_BITMASK;

		if (!_setOriginalDaKetThucDieuTra) {
			_setOriginalDaKetThucDieuTra = true;

			_originalDaKetThucDieuTra = _daKetThucDieuTra;
		}

		_daKetThucDieuTra = daKetThucDieuTra;
	}

	public int getOriginalDaKetThucDieuTra() {
		return _originalDaKetThucDieuTra;
	}

	@Override
	public String getLyDoKhongHoanThanh() {
		if (_lyDoKhongHoanThanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongHoanThanh;
		}
	}

	@Override
	public void setLyDoKhongHoanThanh(String lyDoKhongHoanThanh) {
		_lyDoKhongHoanThanh = lyDoKhongHoanThanh;
	}

	@Override
	public String getImei() {
		if (_imei == null) {
			return StringPool.BLANK;
		}
		else {
			return _imei;
		}
	}

	@Override
	public void setImei(String imei) {
		_imei = imei;
	}

	@Override
	public String getTaiKhoan() {
		if (_taiKhoan == null) {
			return StringPool.BLANK;
		}
		else {
			return _taiKhoan;
		}
	}

	@Override
	public void setTaiKhoan(String taiKhoan) {
		_taiKhoan = taiKhoan;
	}

	@Override
	public int getDanhGiaKiemDem() {
		return _danhGiaKiemDem;
	}

	@Override
	public void setDanhGiaKiemDem(int danhGiaKiemDem) {
		_columnBitmask |= DANHGIAKIEMDEM_COLUMN_BITMASK;

		if (!_setOriginalDanhGiaKiemDem) {
			_setOriginalDanhGiaKiemDem = true;

			_originalDanhGiaKiemDem = _danhGiaKiemDem;
		}

		_danhGiaKiemDem = danhGiaKiemDem;
	}

	public int getOriginalDanhGiaKiemDem() {
		return _originalDanhGiaKiemDem;
	}

	@Override
	public Date getSavePoint() {
		return _savePoint;
	}

	@Override
	public void setSavePoint(Date savePoint) {
		_savePoint = savePoint;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ThongTinKiemDemHoGD toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ThongTinKiemDemHoGD)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThongTinKiemDemHoGDImpl thongTinKiemDemHoGDImpl = new ThongTinKiemDemHoGDImpl();

		thongTinKiemDemHoGDImpl.setId(getId());
		thongTinKiemDemHoGDImpl.setVeSinhGiaDinhId(getVeSinhGiaDinhId());
		thongTinKiemDemHoGDImpl.setKeHoachKiemDemVeSinhId(getKeHoachKiemDemVeSinhId());
		thongTinKiemDemHoGDImpl.setMaTinh(getMaTinh());
		thongTinKiemDemHoGDImpl.setMaHuyen(getMaHuyen());
		thongTinKiemDemHoGDImpl.setMaXa(getMaXa());
		thongTinKiemDemHoGDImpl.setThonXom(getThonXom());
		thongTinKiemDemHoGDImpl.setTenChuHo(getTenChuHo());
		thongTinKiemDemHoGDImpl.setGioiTinhChuHo(getGioiTinhChuHo());
		thongTinKiemDemHoGDImpl.setNgayKiemDem(getNgayKiemDem());
		thongTinKiemDemHoGDImpl.setTimThayNha(getTimThayNha());
		thongTinKiemDemHoGDImpl.setCoNguoiONha(getCoNguoiONha());
		thongTinKiemDemHoGDImpl.setSoNguoiTrongHo(getSoNguoiTrongHo());
		thongTinKiemDemHoGDImpl.setHoTenNguoiTraLoi(getHoTenNguoiTraLoi());
		thongTinKiemDemHoGDImpl.setLaChuHoKhong(getLaChuHoKhong());
		thongTinKiemDemHoGDImpl.setGioiTinhNguoiTraLoi(getGioiTinhNguoiTraLoi());
		thongTinKiemDemHoGDImpl.setTenDanToc(getTenDanToc());
		thongTinKiemDemHoGDImpl.setKinhDo(getKinhDo());
		thongTinKiemDemHoGDImpl.setViDo(getViDo());
		thongTinKiemDemHoGDImpl.setThanhPhanHoGD(getThanhPhanHoGD());
		thongTinKiemDemHoGDImpl.setChuHoDungDS(getChuHoDungDS());
		thongTinKiemDemHoGDImpl.setLyDoKhongDungDS(getLyDoKhongDungDS());
		thongTinKiemDemHoGDImpl.setTenChuHoHienTai(getTenChuHoHienTai());
		thongTinKiemDemHoGDImpl.setGioiTinhChuHoHienTai(getGioiTinhChuHoHienTai());
		thongTinKiemDemHoGDImpl.setCoNhaTieu(getCoNhaTieu());
		thongTinKiemDemHoGDImpl.setLoaiNguonNuoc(getLoaiNguonNuoc());
		thongTinKiemDemHoGDImpl.setLoaiNhaTieu(getLoaiNhaTieu());
		thongTinKiemDemHoGDImpl.setAnhToanCanh(getAnhToanCanh());
		thongTinKiemDemHoGDImpl.setAnhTrongNhaTieu(getAnhTrongNhaTieu());
		thongTinKiemDemHoGDImpl.setThangXayDung(getThangXayDung());
		thongTinKiemDemHoGDImpl.setNamXayDung(getNamXayDung());
		thongTinKiemDemHoGDImpl.setNguonVon(getNguonVon());
		thongTinKiemDemHoGDImpl.setChiTietVonVay(getChiTietVonVay());
		thongTinKiemDemHoGDImpl.setDuocCaiTao(getDuocCaiTao());
		thongTinKiemDemHoGDImpl.setLoaiNhaTieuCu(getLoaiNhaTieuCu());
		thongTinKiemDemHoGDImpl.setAnhBeChua(getAnhBeChua());
		thongTinKiemDemHoGDImpl.setVeSinhSachSe(getVeSinhSachSe());
		thongTinKiemDemHoGDImpl.setDeLamVeSinh(getDeLamVeSinh());
		thongTinKiemDemHoGDImpl.setMuiVeSinh(getMuiVeSinh());
		thongTinKiemDemHoGDImpl.setPhiaTrenKinDao(getPhiaTrenKinDao());
		thongTinKiemDemHoGDImpl.setDuCheMuaGio(getDuCheMuaGio());
		thongTinKiemDemHoGDImpl.setSanCaoTrenToiThieu(getSanCaoTrenToiThieu());
		thongTinKiemDemHoGDImpl.setNapBeConTot(getNapBeConTot());
		thongTinKiemDemHoGDImpl.setCuaPhanBitKin(getCuaPhanBitKin());
		thongTinKiemDemHoGDImpl.setTranRaNgoai(getTranRaNgoai());
		thongTinKiemDemHoGDImpl.setNuocThaiDiDau(getNuocThaiDiDau());
		thongTinKiemDemHoGDImpl.setKhoangCachNguonNuoc(getKhoangCachNguonNuoc());
		thongTinKiemDemHoGDImpl.setNgapKhiMuaLon(getNgapKhiMuaLon());
		thongTinKiemDemHoGDImpl.setGhiChu(getGhiChu());
		thongTinKiemDemHoGDImpl.setDaKetThucDieuTra(getDaKetThucDieuTra());
		thongTinKiemDemHoGDImpl.setLyDoKhongHoanThanh(getLyDoKhongHoanThanh());
		thongTinKiemDemHoGDImpl.setImei(getImei());
		thongTinKiemDemHoGDImpl.setTaiKhoan(getTaiKhoan());
		thongTinKiemDemHoGDImpl.setDanhGiaKiemDem(getDanhGiaKiemDem());
		thongTinKiemDemHoGDImpl.setSavePoint(getSavePoint());

		thongTinKiemDemHoGDImpl.resetOriginalValues();

		return thongTinKiemDemHoGDImpl;
	}

	@Override
	public int compareTo(ThongTinKiemDemHoGD thongTinKiemDemHoGD) {
		int value = 0;

		if (getId() < thongTinKiemDemHoGD.getId()) {
			value = -1;
		}
		else if (getId() > thongTinKiemDemHoGD.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ThongTinKiemDemHoGD)) {
			return false;
		}

		ThongTinKiemDemHoGD thongTinKiemDemHoGD = (ThongTinKiemDemHoGD)obj;

		int primaryKey = thongTinKiemDemHoGD.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ThongTinKiemDemHoGDModelImpl thongTinKiemDemHoGDModelImpl = this;

		thongTinKiemDemHoGDModelImpl._originalVeSinhGiaDinhId = thongTinKiemDemHoGDModelImpl._veSinhGiaDinhId;

		thongTinKiemDemHoGDModelImpl._setOriginalVeSinhGiaDinhId = false;

		thongTinKiemDemHoGDModelImpl._originalKeHoachKiemDemVeSinhId = thongTinKiemDemHoGDModelImpl._keHoachKiemDemVeSinhId;

		thongTinKiemDemHoGDModelImpl._setOriginalKeHoachKiemDemVeSinhId = false;

		thongTinKiemDemHoGDModelImpl._originalDaKetThucDieuTra = thongTinKiemDemHoGDModelImpl._daKetThucDieuTra;

		thongTinKiemDemHoGDModelImpl._setOriginalDaKetThucDieuTra = false;

		thongTinKiemDemHoGDModelImpl._originalDanhGiaKiemDem = thongTinKiemDemHoGDModelImpl._danhGiaKiemDem;

		thongTinKiemDemHoGDModelImpl._setOriginalDanhGiaKiemDem = false;

		thongTinKiemDemHoGDModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ThongTinKiemDemHoGD> toCacheModel() {
		ThongTinKiemDemHoGDCacheModel thongTinKiemDemHoGDCacheModel = new ThongTinKiemDemHoGDCacheModel();

		thongTinKiemDemHoGDCacheModel.id = getId();

		thongTinKiemDemHoGDCacheModel.veSinhGiaDinhId = getVeSinhGiaDinhId();

		thongTinKiemDemHoGDCacheModel.keHoachKiemDemVeSinhId = getKeHoachKiemDemVeSinhId();

		thongTinKiemDemHoGDCacheModel.maTinh = getMaTinh();

		String maTinh = thongTinKiemDemHoGDCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.maTinh = null;
		}

		thongTinKiemDemHoGDCacheModel.maHuyen = getMaHuyen();

		String maHuyen = thongTinKiemDemHoGDCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.maHuyen = null;
		}

		thongTinKiemDemHoGDCacheModel.maXa = getMaXa();

		String maXa = thongTinKiemDemHoGDCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.maXa = null;
		}

		thongTinKiemDemHoGDCacheModel.thonXom = getThonXom();

		String thonXom = thongTinKiemDemHoGDCacheModel.thonXom;

		if ((thonXom != null) && (thonXom.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.thonXom = null;
		}

		thongTinKiemDemHoGDCacheModel.tenChuHo = getTenChuHo();

		String tenChuHo = thongTinKiemDemHoGDCacheModel.tenChuHo;

		if ((tenChuHo != null) && (tenChuHo.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.tenChuHo = null;
		}

		thongTinKiemDemHoGDCacheModel.gioiTinhChuHo = getGioiTinhChuHo();

		Date ngayKiemDem = getNgayKiemDem();

		if (ngayKiemDem != null) {
			thongTinKiemDemHoGDCacheModel.ngayKiemDem = ngayKiemDem.getTime();
		}
		else {
			thongTinKiemDemHoGDCacheModel.ngayKiemDem = Long.MIN_VALUE;
		}

		thongTinKiemDemHoGDCacheModel.timThayNha = getTimThayNha();

		thongTinKiemDemHoGDCacheModel.coNguoiONha = getCoNguoiONha();

		thongTinKiemDemHoGDCacheModel.soNguoiTrongHo = getSoNguoiTrongHo();

		thongTinKiemDemHoGDCacheModel.hoTenNguoiTraLoi = getHoTenNguoiTraLoi();

		String hoTenNguoiTraLoi = thongTinKiemDemHoGDCacheModel.hoTenNguoiTraLoi;

		if ((hoTenNguoiTraLoi != null) && (hoTenNguoiTraLoi.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.hoTenNguoiTraLoi = null;
		}

		thongTinKiemDemHoGDCacheModel.laChuHoKhong = getLaChuHoKhong();

		thongTinKiemDemHoGDCacheModel.gioiTinhNguoiTraLoi = getGioiTinhNguoiTraLoi();

		String gioiTinhNguoiTraLoi = thongTinKiemDemHoGDCacheModel.gioiTinhNguoiTraLoi;

		if ((gioiTinhNguoiTraLoi != null) &&
				(gioiTinhNguoiTraLoi.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.gioiTinhNguoiTraLoi = null;
		}

		thongTinKiemDemHoGDCacheModel.tenDanToc = getTenDanToc();

		String tenDanToc = thongTinKiemDemHoGDCacheModel.tenDanToc;

		if ((tenDanToc != null) && (tenDanToc.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.tenDanToc = null;
		}

		thongTinKiemDemHoGDCacheModel.kinhDo = getKinhDo();

		String kinhDo = thongTinKiemDemHoGDCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.kinhDo = null;
		}

		thongTinKiemDemHoGDCacheModel.viDo = getViDo();

		String viDo = thongTinKiemDemHoGDCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.viDo = null;
		}

		thongTinKiemDemHoGDCacheModel.thanhPhanHoGD = getThanhPhanHoGD();

		thongTinKiemDemHoGDCacheModel.chuHoDungDS = getChuHoDungDS();

		thongTinKiemDemHoGDCacheModel.lyDoKhongDungDS = getLyDoKhongDungDS();

		String lyDoKhongDungDS = thongTinKiemDemHoGDCacheModel.lyDoKhongDungDS;

		if ((lyDoKhongDungDS != null) && (lyDoKhongDungDS.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.lyDoKhongDungDS = null;
		}

		thongTinKiemDemHoGDCacheModel.tenChuHoHienTai = getTenChuHoHienTai();

		String tenChuHoHienTai = thongTinKiemDemHoGDCacheModel.tenChuHoHienTai;

		if ((tenChuHoHienTai != null) && (tenChuHoHienTai.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.tenChuHoHienTai = null;
		}

		thongTinKiemDemHoGDCacheModel.gioiTinhChuHoHienTai = getGioiTinhChuHoHienTai();

		thongTinKiemDemHoGDCacheModel.coNhaTieu = getCoNhaTieu();

		thongTinKiemDemHoGDCacheModel.loaiNguonNuoc = getLoaiNguonNuoc();

		String loaiNguonNuoc = thongTinKiemDemHoGDCacheModel.loaiNguonNuoc;

		if ((loaiNguonNuoc != null) && (loaiNguonNuoc.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.loaiNguonNuoc = null;
		}

		thongTinKiemDemHoGDCacheModel.loaiNhaTieu = getLoaiNhaTieu();

		String loaiNhaTieu = thongTinKiemDemHoGDCacheModel.loaiNhaTieu;

		if ((loaiNhaTieu != null) && (loaiNhaTieu.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.loaiNhaTieu = null;
		}

		thongTinKiemDemHoGDCacheModel.anhToanCanh = getAnhToanCanh();

		String anhToanCanh = thongTinKiemDemHoGDCacheModel.anhToanCanh;

		if ((anhToanCanh != null) && (anhToanCanh.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.anhToanCanh = null;
		}

		thongTinKiemDemHoGDCacheModel.anhTrongNhaTieu = getAnhTrongNhaTieu();

		String anhTrongNhaTieu = thongTinKiemDemHoGDCacheModel.anhTrongNhaTieu;

		if ((anhTrongNhaTieu != null) && (anhTrongNhaTieu.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.anhTrongNhaTieu = null;
		}

		thongTinKiemDemHoGDCacheModel.thangXayDung = getThangXayDung();

		thongTinKiemDemHoGDCacheModel.namXayDung = getNamXayDung();

		thongTinKiemDemHoGDCacheModel.nguonVon = getNguonVon();

		thongTinKiemDemHoGDCacheModel.chiTietVonVay = getChiTietVonVay();

		String chiTietVonVay = thongTinKiemDemHoGDCacheModel.chiTietVonVay;

		if ((chiTietVonVay != null) && (chiTietVonVay.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.chiTietVonVay = null;
		}

		thongTinKiemDemHoGDCacheModel.duocCaiTao = getDuocCaiTao();

		thongTinKiemDemHoGDCacheModel.loaiNhaTieuCu = getLoaiNhaTieuCu();

		String loaiNhaTieuCu = thongTinKiemDemHoGDCacheModel.loaiNhaTieuCu;

		if ((loaiNhaTieuCu != null) && (loaiNhaTieuCu.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.loaiNhaTieuCu = null;
		}

		thongTinKiemDemHoGDCacheModel.anhBeChua = getAnhBeChua();

		String anhBeChua = thongTinKiemDemHoGDCacheModel.anhBeChua;

		if ((anhBeChua != null) && (anhBeChua.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.anhBeChua = null;
		}

		thongTinKiemDemHoGDCacheModel.veSinhSachSe = getVeSinhSachSe();

		thongTinKiemDemHoGDCacheModel.deLamVeSinh = getDeLamVeSinh();

		thongTinKiemDemHoGDCacheModel.muiVeSinh = getMuiVeSinh();

		thongTinKiemDemHoGDCacheModel.phiaTrenKinDao = getPhiaTrenKinDao();

		thongTinKiemDemHoGDCacheModel.duCheMuaGio = getDuCheMuaGio();

		thongTinKiemDemHoGDCacheModel.sanCaoTrenToiThieu = getSanCaoTrenToiThieu();

		thongTinKiemDemHoGDCacheModel.napBeConTot = getNapBeConTot();

		thongTinKiemDemHoGDCacheModel.cuaPhanBitKin = getCuaPhanBitKin();

		thongTinKiemDemHoGDCacheModel.tranRaNgoai = getTranRaNgoai();

		thongTinKiemDemHoGDCacheModel.nuocThaiDiDau = getNuocThaiDiDau();

		thongTinKiemDemHoGDCacheModel.khoangCachNguonNuoc = getKhoangCachNguonNuoc();

		thongTinKiemDemHoGDCacheModel.ngapKhiMuaLon = getNgapKhiMuaLon();

		thongTinKiemDemHoGDCacheModel.ghiChu = getGhiChu();

		String ghiChu = thongTinKiemDemHoGDCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.ghiChu = null;
		}

		thongTinKiemDemHoGDCacheModel.daKetThucDieuTra = getDaKetThucDieuTra();

		thongTinKiemDemHoGDCacheModel.lyDoKhongHoanThanh = getLyDoKhongHoanThanh();

		String lyDoKhongHoanThanh = thongTinKiemDemHoGDCacheModel.lyDoKhongHoanThanh;

		if ((lyDoKhongHoanThanh != null) && (lyDoKhongHoanThanh.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.lyDoKhongHoanThanh = null;
		}

		thongTinKiemDemHoGDCacheModel.imei = getImei();

		String imei = thongTinKiemDemHoGDCacheModel.imei;

		if ((imei != null) && (imei.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.imei = null;
		}

		thongTinKiemDemHoGDCacheModel.taiKhoan = getTaiKhoan();

		String taiKhoan = thongTinKiemDemHoGDCacheModel.taiKhoan;

		if ((taiKhoan != null) && (taiKhoan.length() == 0)) {
			thongTinKiemDemHoGDCacheModel.taiKhoan = null;
		}

		thongTinKiemDemHoGDCacheModel.danhGiaKiemDem = getDanhGiaKiemDem();

		Date savePoint = getSavePoint();

		if (savePoint != null) {
			thongTinKiemDemHoGDCacheModel.savePoint = savePoint.getTime();
		}
		else {
			thongTinKiemDemHoGDCacheModel.savePoint = Long.MIN_VALUE;
		}

		return thongTinKiemDemHoGDCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(111);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", veSinhGiaDinhId=");
		sb.append(getVeSinhGiaDinhId());
		sb.append(", keHoachKiemDemVeSinhId=");
		sb.append(getKeHoachKiemDemVeSinhId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", thonXom=");
		sb.append(getThonXom());
		sb.append(", tenChuHo=");
		sb.append(getTenChuHo());
		sb.append(", gioiTinhChuHo=");
		sb.append(getGioiTinhChuHo());
		sb.append(", ngayKiemDem=");
		sb.append(getNgayKiemDem());
		sb.append(", timThayNha=");
		sb.append(getTimThayNha());
		sb.append(", coNguoiONha=");
		sb.append(getCoNguoiONha());
		sb.append(", soNguoiTrongHo=");
		sb.append(getSoNguoiTrongHo());
		sb.append(", hoTenNguoiTraLoi=");
		sb.append(getHoTenNguoiTraLoi());
		sb.append(", laChuHoKhong=");
		sb.append(getLaChuHoKhong());
		sb.append(", gioiTinhNguoiTraLoi=");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append(", tenDanToc=");
		sb.append(getTenDanToc());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", thanhPhanHoGD=");
		sb.append(getThanhPhanHoGD());
		sb.append(", chuHoDungDS=");
		sb.append(getChuHoDungDS());
		sb.append(", lyDoKhongDungDS=");
		sb.append(getLyDoKhongDungDS());
		sb.append(", tenChuHoHienTai=");
		sb.append(getTenChuHoHienTai());
		sb.append(", gioiTinhChuHoHienTai=");
		sb.append(getGioiTinhChuHoHienTai());
		sb.append(", coNhaTieu=");
		sb.append(getCoNhaTieu());
		sb.append(", loaiNguonNuoc=");
		sb.append(getLoaiNguonNuoc());
		sb.append(", loaiNhaTieu=");
		sb.append(getLoaiNhaTieu());
		sb.append(", anhToanCanh=");
		sb.append(getAnhToanCanh());
		sb.append(", anhTrongNhaTieu=");
		sb.append(getAnhTrongNhaTieu());
		sb.append(", thangXayDung=");
		sb.append(getThangXayDung());
		sb.append(", namXayDung=");
		sb.append(getNamXayDung());
		sb.append(", nguonVon=");
		sb.append(getNguonVon());
		sb.append(", chiTietVonVay=");
		sb.append(getChiTietVonVay());
		sb.append(", duocCaiTao=");
		sb.append(getDuocCaiTao());
		sb.append(", loaiNhaTieuCu=");
		sb.append(getLoaiNhaTieuCu());
		sb.append(", anhBeChua=");
		sb.append(getAnhBeChua());
		sb.append(", veSinhSachSe=");
		sb.append(getVeSinhSachSe());
		sb.append(", deLamVeSinh=");
		sb.append(getDeLamVeSinh());
		sb.append(", muiVeSinh=");
		sb.append(getMuiVeSinh());
		sb.append(", phiaTrenKinDao=");
		sb.append(getPhiaTrenKinDao());
		sb.append(", duCheMuaGio=");
		sb.append(getDuCheMuaGio());
		sb.append(", sanCaoTrenToiThieu=");
		sb.append(getSanCaoTrenToiThieu());
		sb.append(", napBeConTot=");
		sb.append(getNapBeConTot());
		sb.append(", cuaPhanBitKin=");
		sb.append(getCuaPhanBitKin());
		sb.append(", tranRaNgoai=");
		sb.append(getTranRaNgoai());
		sb.append(", nuocThaiDiDau=");
		sb.append(getNuocThaiDiDau());
		sb.append(", khoangCachNguonNuoc=");
		sb.append(getKhoangCachNguonNuoc());
		sb.append(", ngapKhiMuaLon=");
		sb.append(getNgapKhiMuaLon());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", daKetThucDieuTra=");
		sb.append(getDaKetThucDieuTra());
		sb.append(", lyDoKhongHoanThanh=");
		sb.append(getLyDoKhongHoanThanh());
		sb.append(", imei=");
		sb.append(getImei());
		sb.append(", taiKhoan=");
		sb.append(getTaiKhoan());
		sb.append(", danhGiaKiemDem=");
		sb.append(getDanhGiaKiemDem());
		sb.append(", savePoint=");
		sb.append(getSavePoint());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(169);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.vesinhmoitruong.dao.model.ThongTinKiemDemHoGD");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>veSinhGiaDinhId</column-name><column-value><![CDATA[");
		sb.append(getVeSinhGiaDinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keHoachKiemDemVeSinhId</column-name><column-value><![CDATA[");
		sb.append(getKeHoachKiemDemVeSinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thonXom</column-name><column-value><![CDATA[");
		sb.append(getThonXom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHo</column-name><column-value><![CDATA[");
		sb.append(getTenChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhChuHo</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKiemDem</column-name><column-value><![CDATA[");
		sb.append(getNgayKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timThayNha</column-name><column-value><![CDATA[");
		sb.append(getTimThayNha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coNguoiONha</column-name><column-value><![CDATA[");
		sb.append(getCoNguoiONha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiTrongHo</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiTrongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laChuHoKhong</column-name><column-value><![CDATA[");
		sb.append(getLaChuHoKhong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDanToc</column-name><column-value><![CDATA[");
		sb.append(getTenDanToc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhPhanHoGD</column-name><column-value><![CDATA[");
		sb.append(getThanhPhanHoGD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuHoDungDS</column-name><column-value><![CDATA[");
		sb.append(getChuHoDungDS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDungDS</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDungDS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHoHienTai</column-name><column-value><![CDATA[");
		sb.append(getTenChuHoHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhChuHoHienTai</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhChuHoHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNguonNuoc</column-name><column-value><![CDATA[");
		sb.append(getLoaiNguonNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhToanCanh</column-name><column-value><![CDATA[");
		sb.append(getAnhToanCanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhTrongNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getAnhTrongNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thangXayDung</column-name><column-value><![CDATA[");
		sb.append(getThangXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namXayDung</column-name><column-value><![CDATA[");
		sb.append(getNamXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguonVon</column-name><column-value><![CDATA[");
		sb.append(getNguonVon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiTietVonVay</column-name><column-value><![CDATA[");
		sb.append(getChiTietVonVay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duocCaiTao</column-name><column-value><![CDATA[");
		sb.append(getDuocCaiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNhaTieuCu</column-name><column-value><![CDATA[");
		sb.append(getLoaiNhaTieuCu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhBeChua</column-name><column-value><![CDATA[");
		sb.append(getAnhBeChua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>veSinhSachSe</column-name><column-value><![CDATA[");
		sb.append(getVeSinhSachSe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deLamVeSinh</column-name><column-value><![CDATA[");
		sb.append(getDeLamVeSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>muiVeSinh</column-name><column-value><![CDATA[");
		sb.append(getMuiVeSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phiaTrenKinDao</column-name><column-value><![CDATA[");
		sb.append(getPhiaTrenKinDao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duCheMuaGio</column-name><column-value><![CDATA[");
		sb.append(getDuCheMuaGio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sanCaoTrenToiThieu</column-name><column-value><![CDATA[");
		sb.append(getSanCaoTrenToiThieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>napBeConTot</column-name><column-value><![CDATA[");
		sb.append(getNapBeConTot());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuaPhanBitKin</column-name><column-value><![CDATA[");
		sb.append(getCuaPhanBitKin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tranRaNgoai</column-name><column-value><![CDATA[");
		sb.append(getTranRaNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocThaiDiDau</column-name><column-value><![CDATA[");
		sb.append(getNuocThaiDiDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khoangCachNguonNuoc</column-name><column-value><![CDATA[");
		sb.append(getKhoangCachNguonNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngapKhiMuaLon</column-name><column-value><![CDATA[");
		sb.append(getNgapKhiMuaLon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daKetThucDieuTra</column-name><column-value><![CDATA[");
		sb.append(getDaKetThucDieuTra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongHoanThanh</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongHoanThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imei</column-name><column-value><![CDATA[");
		sb.append(getImei());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoan</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danhGiaKiemDem</column-name><column-value><![CDATA[");
		sb.append(getDanhGiaKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>savePoint</column-name><column-value><![CDATA[");
		sb.append(getSavePoint());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ThongTinKiemDemHoGD.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ThongTinKiemDemHoGD.class
		};
	private int _id;
	private int _veSinhGiaDinhId;
	private int _originalVeSinhGiaDinhId;
	private boolean _setOriginalVeSinhGiaDinhId;
	private int _keHoachKiemDemVeSinhId;
	private int _originalKeHoachKiemDemVeSinhId;
	private boolean _setOriginalKeHoachKiemDemVeSinhId;
	private String _maTinh;
	private String _maHuyen;
	private String _maXa;
	private String _thonXom;
	private String _tenChuHo;
	private int _gioiTinhChuHo;
	private Date _ngayKiemDem;
	private int _timThayNha;
	private int _coNguoiONha;
	private int _soNguoiTrongHo;
	private String _hoTenNguoiTraLoi;
	private int _laChuHoKhong;
	private String _gioiTinhNguoiTraLoi;
	private String _tenDanToc;
	private String _kinhDo;
	private String _viDo;
	private int _thanhPhanHoGD;
	private int _chuHoDungDS;
	private String _lyDoKhongDungDS;
	private String _tenChuHoHienTai;
	private int _gioiTinhChuHoHienTai;
	private int _coNhaTieu;
	private String _loaiNguonNuoc;
	private String _loaiNhaTieu;
	private String _anhToanCanh;
	private String _anhTrongNhaTieu;
	private int _thangXayDung;
	private int _namXayDung;
	private int _nguonVon;
	private String _chiTietVonVay;
	private int _duocCaiTao;
	private String _loaiNhaTieuCu;
	private String _anhBeChua;
	private int _veSinhSachSe;
	private int _deLamVeSinh;
	private int _muiVeSinh;
	private int _phiaTrenKinDao;
	private int _duCheMuaGio;
	private int _sanCaoTrenToiThieu;
	private int _napBeConTot;
	private int _cuaPhanBitKin;
	private int _tranRaNgoai;
	private int _nuocThaiDiDau;
	private int _khoangCachNguonNuoc;
	private int _ngapKhiMuaLon;
	private String _ghiChu;
	private int _daKetThucDieuTra;
	private int _originalDaKetThucDieuTra;
	private boolean _setOriginalDaKetThucDieuTra;
	private String _lyDoKhongHoanThanh;
	private String _imei;
	private String _taiKhoan;
	private int _danhGiaKiemDem;
	private int _originalDanhGiaKiemDem;
	private boolean _setOriginalDanhGiaKiemDem;
	private Date _savePoint;
	private long _columnBitmask;
	private ThongTinKiemDemHoGD _escapedModel;
}