/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.cmon.user.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserMapping service. Represents a row in the &quot;DM_USERMAPPING&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.cmon.user.dao.model.impl.UserMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.cmon.user.dao.model.impl.UserMappingImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see UserMapping
 * @see vn.dtt.cmon.user.dao.model.impl.UserMappingImpl
 * @see vn.dtt.cmon.user.dao.model.impl.UserMappingModelImpl
 * @generated
 */
public interface UserMappingModel extends BaseModel<UserMapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user mapping model instance should use the {@link UserMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this user mapping.
	 *
	 * @return the primary key of this user mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user mapping.
	 *
	 * @param primaryKey the primary key of this user mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this user mapping.
	 *
	 * @return the ID of this user mapping
	 */
	public long getId();

	/**
	 * Sets the ID of this user mapping.
	 *
	 * @param id the ID of this user mapping
	 */
	public void setId(long id);

	/**
	 * Returns the name of this user mapping.
	 *
	 * @return the name of this user mapping
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user mapping.
	 *
	 * @param name the name of this user mapping
	 */
	public void setName(String name);

	/**
	 * Returns the user ID of this user mapping.
	 *
	 * @return the user ID of this user mapping
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user mapping.
	 *
	 * @param userId the user ID of this user mapping
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user mapping.
	 *
	 * @return the user uuid of this user mapping
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user mapping.
	 *
	 * @param userUuid the user uuid of this user mapping
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user type of this user mapping.
	 *
	 * @return the user type of this user mapping
	 */
	public int getUserType();

	/**
	 * Sets the user type of this user mapping.
	 *
	 * @param userType the user type of this user mapping
	 */
	public void setUserType(int userType);

	/**
	 * Returns the org code1 of this user mapping.
	 *
	 * @return the org code1 of this user mapping
	 */
	@AutoEscape
	public String getOrgCode1();

	/**
	 * Sets the org code1 of this user mapping.
	 *
	 * @param orgCode1 the org code1 of this user mapping
	 */
	public void setOrgCode1(String orgCode1);

	/**
	 * Returns the org code2 of this user mapping.
	 *
	 * @return the org code2 of this user mapping
	 */
	@AutoEscape
	public String getOrgCode2();

	/**
	 * Sets the org code2 of this user mapping.
	 *
	 * @param orgCode2 the org code2 of this user mapping
	 */
	public void setOrgCode2(String orgCode2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserMapping userMapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserMapping> toCacheModel();

	@Override
	public UserMapping toEscapedModel();

	@Override
	public UserMapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}