/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC;
import vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOCModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the THONGTINKIEMDEMNUOC service. Represents a row in the &quot;me_thongtinkiemdemnuoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOCModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link THONGTINKIEMDEMNUOCImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see THONGTINKIEMDEMNUOCImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC
 * @see vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOCModel
 * @generated
 */
public class THONGTINKIEMDEMNUOCModelImpl extends BaseModelImpl<THONGTINKIEMDEMNUOC>
	implements THONGTINKIEMDEMNUOCModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t h o n g t i n k i e m d e m n u o c model instance should use the {@link vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC} interface instead.
	 */
	public static final String TABLE_NAME = "me_thongtinkiemdemnuoc";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "daunoinuocid", Types.BIGINT },
			{ "kehoachkiemdemnuocid", Types.INTEGER },
			{ "matinh", Types.VARCHAR },
			{ "mahuyen", Types.VARCHAR },
			{ "maxa", Types.VARCHAR },
			{ "thonxom", Types.VARCHAR },
			{ "tenchuho", Types.VARCHAR },
			{ "gioitinhchuho", Types.INTEGER },
			{ "ngaykiemdem", Types.TIMESTAMP },
			{ "timthaynha", Types.INTEGER },
			{ "conguoionha", Types.INTEGER },
			{ "hotennguoitraloi", Types.VARCHAR },
			{ "lachuhokhong", Types.INTEGER },
			{ "gioitinhnguoitraloi", Types.VARCHAR },
			{ "tendantoc", Types.VARCHAR },
			{ "kinhdo", Types.VARCHAR },
			{ "vido", Types.VARCHAR },
			{ "songuoitrongho", Types.INTEGER },
			{ "thanhphanhogd", Types.INTEGER },
			{ "chuhodungds", Types.INTEGER },
			{ "lydokhongdungds", Types.VARCHAR },
			{ "tenchuhohientai", Types.VARCHAR },
			{ "gioitinhchuhohientai", Types.INTEGER },
			{ "daunoichua", Types.INTEGER },
			{ "anhdaunoi", Types.VARCHAR },
			{ "thoigiandauhopdong", Types.TIMESTAMP },
			{ "thoigiandaunoithucte", Types.TIMESTAMP },
			{ "voinuocchaykhong", Types.INTEGER },
			{ "nuoctrongkhong", Types.INTEGER },
			{ "maunuoc", Types.VARCHAR },
			{ "muinuoc", Types.VARCHAR },
			{ "vinuoc", Types.VARCHAR },
			{ "loaikhac", Types.VARCHAR },
			{ "datungduckhong", Types.INTEGER },
			{ "maunuoctungco", Types.VARCHAR },
			{ "muinuoctungco", Types.VARCHAR },
			{ "vinuoctungco", Types.VARCHAR },
			{ "loaikhactungco", Types.VARCHAR },
			{ "cobechuanuoc", Types.INTEGER },
			{ "tinhtrangbe", Types.INTEGER },
			{ "anhbechua", Types.VARCHAR },
			{ "bimatnuoc", Types.INTEGER },
			{ "solanmatnuoc", Types.INTEGER },
			{ "sogiotrungbinh", Types.INTEGER },
			{ "soserydongho", Types.VARCHAR },
			{ "chisodongho", Types.VARCHAR },
			{ "anhdongho", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR },
			{ "daketthucdieutra", Types.INTEGER },
			{ "lydokhonghoanthanh", Types.VARCHAR },
			{ "imei", Types.VARCHAR },
			{ "taikhoan", Types.VARCHAR },
			{ "danhgiakiemdem", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table me_thongtinkiemdemnuoc (id LONG not null primary key,daunoinuocid LONG,kehoachkiemdemnuocid INTEGER,matinh VARCHAR(75) null,mahuyen VARCHAR(75) null,maxa VARCHAR(75) null,thonxom VARCHAR(75) null,tenchuho VARCHAR(75) null,gioitinhchuho INTEGER,ngaykiemdem DATE null,timthaynha INTEGER,conguoionha INTEGER,hotennguoitraloi VARCHAR(75) null,lachuhokhong INTEGER,gioitinhnguoitraloi VARCHAR(75) null,tendantoc VARCHAR(75) null,kinhdo VARCHAR(75) null,vido VARCHAR(75) null,songuoitrongho INTEGER,thanhphanhogd INTEGER,chuhodungds INTEGER,lydokhongdungds VARCHAR(75) null,tenchuhohientai VARCHAR(75) null,gioitinhchuhohientai INTEGER,daunoichua INTEGER,anhdaunoi VARCHAR(75) null,thoigiandauhopdong DATE null,thoigiandaunoithucte DATE null,voinuocchaykhong INTEGER,nuoctrongkhong INTEGER,maunuoc VARCHAR(75) null,muinuoc VARCHAR(75) null,vinuoc VARCHAR(75) null,loaikhac VARCHAR(75) null,datungduckhong INTEGER,maunuoctungco VARCHAR(75) null,muinuoctungco VARCHAR(75) null,vinuoctungco VARCHAR(75) null,loaikhactungco VARCHAR(75) null,cobechuanuoc INTEGER,tinhtrangbe INTEGER,anhbechua VARCHAR(75) null,bimatnuoc INTEGER,solanmatnuoc INTEGER,sogiotrungbinh INTEGER,soserydongho VARCHAR(75) null,chisodongho VARCHAR(75) null,anhdongho VARCHAR(75) null,ghichu VARCHAR(75) null,daketthucdieutra INTEGER,lydokhonghoanthanh VARCHAR(75) null,imei VARCHAR(75) null,taikhoan VARCHAR(75) null,danhgiakiemdem INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table me_thongtinkiemdemnuoc";
	public static final String ORDER_BY_JPQL = " ORDER BY thongtinkiemdemnuoc.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY me_thongtinkiemdemnuoc.id DESC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC"),
			true);
	public static long DAKETTHUCDIEUTRA_COLUMN_BITMASK = 1L;
	public static long DANHGIAKIEMDEM_COLUMN_BITMASK = 2L;
	public static long DAUNOINUOCID_COLUMN_BITMASK = 4L;
	public static long KEHOACHKIEMDEMNUOCID_COLUMN_BITMASK = 8L;
	public static long ID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC"));

	public THONGTINKIEMDEMNUOCModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return THONGTINKIEMDEMNUOC.class;
	}

	@Override
	public String getModelClassName() {
		return THONGTINKIEMDEMNUOC.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("dauNoiNuocId", getDauNoiNuocId());
		attributes.put("keHoachKiemDemNuocId", getKeHoachKiemDemNuocId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("thonXom", getThonXom());
		attributes.put("tenChuHo", getTenChuHo());
		attributes.put("gioiTinhChuHo", getGioiTinhChuHo());
		attributes.put("ngayKiemDem", getNgayKiemDem());
		attributes.put("timThayNha", getTimThayNha());
		attributes.put("coNguoiONha", getCoNguoiONha());
		attributes.put("hoTenNguoiTraLoi", getHoTenNguoiTraLoi());
		attributes.put("laChuHoKhong", getLaChuHoKhong());
		attributes.put("gioiTinhNguoiTraLoi", getGioiTinhNguoiTraLoi());
		attributes.put("tenDanToc", getTenDanToc());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("soNguoiTrongHo", getSoNguoiTrongHo());
		attributes.put("thanhPhanHoGd", getThanhPhanHoGd());
		attributes.put("chuHoDungDs", getChuHoDungDs());
		attributes.put("lyDoKhongDungDs", getLyDoKhongDungDs());
		attributes.put("tenChuHoHienTai", getTenChuHoHienTai());
		attributes.put("gioiTinhChuHoHienTai", getGioiTinhChuHoHienTai());
		attributes.put("dauNoiChua", getDauNoiChua());
		attributes.put("anhDauNoi", getAnhDauNoi());
		attributes.put("thoiGianDauHopDong", getThoiGianDauHopDong());
		attributes.put("thoiGianDauNoiThucTe", getThoiGianDauNoiThucTe());
		attributes.put("voiNuocChayKhong", getVoiNuocChayKhong());
		attributes.put("nuocTrongKhong", getNuocTrongKhong());
		attributes.put("mauNuoc", getMauNuoc());
		attributes.put("muiNuoc", getMuiNuoc());
		attributes.put("viNuoc", getViNuoc());
		attributes.put("loaiKhac", getLoaiKhac());
		attributes.put("daTungDucKhong", getDaTungDucKhong());
		attributes.put("mauNuocTungCo", getMauNuocTungCo());
		attributes.put("muiNuocTungCo", getMuiNuocTungCo());
		attributes.put("viNuocTungCo", getViNuocTungCo());
		attributes.put("loaiKhacTungCo", getLoaiKhacTungCo());
		attributes.put("coBeChuaNuoc", getCoBeChuaNuoc());
		attributes.put("tinhTrangBe", getTinhTrangBe());
		attributes.put("anhBeChua", getAnhBeChua());
		attributes.put("biMatNuoc", getBiMatNuoc());
		attributes.put("soLanMatNuoc", getSoLanMatNuoc());
		attributes.put("soGioTrungBinh", getSoGioTrungBinh());
		attributes.put("soSeRyDongHo", getSoSeRyDongHo());
		attributes.put("chiSoDongHo", getChiSoDongHo());
		attributes.put("anhDongHo", getAnhDongHo());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("daKetThucDieuTra", getDaKetThucDieuTra());
		attributes.put("lyDoKhongHoanThanh", getLyDoKhongHoanThanh());
		attributes.put("iMei", getIMei());
		attributes.put("taiKhoan", getTaiKhoan());
		attributes.put("danhGiaKiemDem", getDanhGiaKiemDem());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long dauNoiNuocId = (Long)attributes.get("dauNoiNuocId");

		if (dauNoiNuocId != null) {
			setDauNoiNuocId(dauNoiNuocId);
		}

		Integer keHoachKiemDemNuocId = (Integer)attributes.get(
				"keHoachKiemDemNuocId");

		if (keHoachKiemDemNuocId != null) {
			setKeHoachKiemDemNuocId(keHoachKiemDemNuocId);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String thonXom = (String)attributes.get("thonXom");

		if (thonXom != null) {
			setThonXom(thonXom);
		}

		String tenChuHo = (String)attributes.get("tenChuHo");

		if (tenChuHo != null) {
			setTenChuHo(tenChuHo);
		}

		Integer gioiTinhChuHo = (Integer)attributes.get("gioiTinhChuHo");

		if (gioiTinhChuHo != null) {
			setGioiTinhChuHo(gioiTinhChuHo);
		}

		Date ngayKiemDem = (Date)attributes.get("ngayKiemDem");

		if (ngayKiemDem != null) {
			setNgayKiemDem(ngayKiemDem);
		}

		Integer timThayNha = (Integer)attributes.get("timThayNha");

		if (timThayNha != null) {
			setTimThayNha(timThayNha);
		}

		Integer coNguoiONha = (Integer)attributes.get("coNguoiONha");

		if (coNguoiONha != null) {
			setCoNguoiONha(coNguoiONha);
		}

		String hoTenNguoiTraLoi = (String)attributes.get("hoTenNguoiTraLoi");

		if (hoTenNguoiTraLoi != null) {
			setHoTenNguoiTraLoi(hoTenNguoiTraLoi);
		}

		Integer laChuHoKhong = (Integer)attributes.get("laChuHoKhong");

		if (laChuHoKhong != null) {
			setLaChuHoKhong(laChuHoKhong);
		}

		String gioiTinhNguoiTraLoi = (String)attributes.get(
				"gioiTinhNguoiTraLoi");

		if (gioiTinhNguoiTraLoi != null) {
			setGioiTinhNguoiTraLoi(gioiTinhNguoiTraLoi);
		}

		String tenDanToc = (String)attributes.get("tenDanToc");

		if (tenDanToc != null) {
			setTenDanToc(tenDanToc);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		Integer soNguoiTrongHo = (Integer)attributes.get("soNguoiTrongHo");

		if (soNguoiTrongHo != null) {
			setSoNguoiTrongHo(soNguoiTrongHo);
		}

		Integer thanhPhanHoGd = (Integer)attributes.get("thanhPhanHoGd");

		if (thanhPhanHoGd != null) {
			setThanhPhanHoGd(thanhPhanHoGd);
		}

		Integer chuHoDungDs = (Integer)attributes.get("chuHoDungDs");

		if (chuHoDungDs != null) {
			setChuHoDungDs(chuHoDungDs);
		}

		String lyDoKhongDungDs = (String)attributes.get("lyDoKhongDungDs");

		if (lyDoKhongDungDs != null) {
			setLyDoKhongDungDs(lyDoKhongDungDs);
		}

		String tenChuHoHienTai = (String)attributes.get("tenChuHoHienTai");

		if (tenChuHoHienTai != null) {
			setTenChuHoHienTai(tenChuHoHienTai);
		}

		Integer gioiTinhChuHoHienTai = (Integer)attributes.get(
				"gioiTinhChuHoHienTai");

		if (gioiTinhChuHoHienTai != null) {
			setGioiTinhChuHoHienTai(gioiTinhChuHoHienTai);
		}

		Integer dauNoiChua = (Integer)attributes.get("dauNoiChua");

		if (dauNoiChua != null) {
			setDauNoiChua(dauNoiChua);
		}

		String anhDauNoi = (String)attributes.get("anhDauNoi");

		if (anhDauNoi != null) {
			setAnhDauNoi(anhDauNoi);
		}

		Date thoiGianDauHopDong = (Date)attributes.get("thoiGianDauHopDong");

		if (thoiGianDauHopDong != null) {
			setThoiGianDauHopDong(thoiGianDauHopDong);
		}

		Date thoiGianDauNoiThucTe = (Date)attributes.get("thoiGianDauNoiThucTe");

		if (thoiGianDauNoiThucTe != null) {
			setThoiGianDauNoiThucTe(thoiGianDauNoiThucTe);
		}

		Integer voiNuocChayKhong = (Integer)attributes.get("voiNuocChayKhong");

		if (voiNuocChayKhong != null) {
			setVoiNuocChayKhong(voiNuocChayKhong);
		}

		Integer nuocTrongKhong = (Integer)attributes.get("nuocTrongKhong");

		if (nuocTrongKhong != null) {
			setNuocTrongKhong(nuocTrongKhong);
		}

		String mauNuoc = (String)attributes.get("mauNuoc");

		if (mauNuoc != null) {
			setMauNuoc(mauNuoc);
		}

		String muiNuoc = (String)attributes.get("muiNuoc");

		if (muiNuoc != null) {
			setMuiNuoc(muiNuoc);
		}

		String viNuoc = (String)attributes.get("viNuoc");

		if (viNuoc != null) {
			setViNuoc(viNuoc);
		}

		String loaiKhac = (String)attributes.get("loaiKhac");

		if (loaiKhac != null) {
			setLoaiKhac(loaiKhac);
		}

		Integer daTungDucKhong = (Integer)attributes.get("daTungDucKhong");

		if (daTungDucKhong != null) {
			setDaTungDucKhong(daTungDucKhong);
		}

		String mauNuocTungCo = (String)attributes.get("mauNuocTungCo");

		if (mauNuocTungCo != null) {
			setMauNuocTungCo(mauNuocTungCo);
		}

		String muiNuocTungCo = (String)attributes.get("muiNuocTungCo");

		if (muiNuocTungCo != null) {
			setMuiNuocTungCo(muiNuocTungCo);
		}

		String viNuocTungCo = (String)attributes.get("viNuocTungCo");

		if (viNuocTungCo != null) {
			setViNuocTungCo(viNuocTungCo);
		}

		String loaiKhacTungCo = (String)attributes.get("loaiKhacTungCo");

		if (loaiKhacTungCo != null) {
			setLoaiKhacTungCo(loaiKhacTungCo);
		}

		Integer coBeChuaNuoc = (Integer)attributes.get("coBeChuaNuoc");

		if (coBeChuaNuoc != null) {
			setCoBeChuaNuoc(coBeChuaNuoc);
		}

		Integer tinhTrangBe = (Integer)attributes.get("tinhTrangBe");

		if (tinhTrangBe != null) {
			setTinhTrangBe(tinhTrangBe);
		}

		String anhBeChua = (String)attributes.get("anhBeChua");

		if (anhBeChua != null) {
			setAnhBeChua(anhBeChua);
		}

		Integer biMatNuoc = (Integer)attributes.get("biMatNuoc");

		if (biMatNuoc != null) {
			setBiMatNuoc(biMatNuoc);
		}

		Integer soLanMatNuoc = (Integer)attributes.get("soLanMatNuoc");

		if (soLanMatNuoc != null) {
			setSoLanMatNuoc(soLanMatNuoc);
		}

		Integer soGioTrungBinh = (Integer)attributes.get("soGioTrungBinh");

		if (soGioTrungBinh != null) {
			setSoGioTrungBinh(soGioTrungBinh);
		}

		String soSeRyDongHo = (String)attributes.get("soSeRyDongHo");

		if (soSeRyDongHo != null) {
			setSoSeRyDongHo(soSeRyDongHo);
		}

		String chiSoDongHo = (String)attributes.get("chiSoDongHo");

		if (chiSoDongHo != null) {
			setChiSoDongHo(chiSoDongHo);
		}

		String anhDongHo = (String)attributes.get("anhDongHo");

		if (anhDongHo != null) {
			setAnhDongHo(anhDongHo);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer daKetThucDieuTra = (Integer)attributes.get("daKetThucDieuTra");

		if (daKetThucDieuTra != null) {
			setDaKetThucDieuTra(daKetThucDieuTra);
		}

		String lyDoKhongHoanThanh = (String)attributes.get("lyDoKhongHoanThanh");

		if (lyDoKhongHoanThanh != null) {
			setLyDoKhongHoanThanh(lyDoKhongHoanThanh);
		}

		String iMei = (String)attributes.get("iMei");

		if (iMei != null) {
			setIMei(iMei);
		}

		String taiKhoan = (String)attributes.get("taiKhoan");

		if (taiKhoan != null) {
			setTaiKhoan(taiKhoan);
		}

		Integer danhGiaKiemDem = (Integer)attributes.get("danhGiaKiemDem");

		if (danhGiaKiemDem != null) {
			setDanhGiaKiemDem(danhGiaKiemDem);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public long getDauNoiNuocId() {
		return _dauNoiNuocId;
	}

	@Override
	public void setDauNoiNuocId(long dauNoiNuocId) {
		_columnBitmask |= DAUNOINUOCID_COLUMN_BITMASK;

		if (!_setOriginalDauNoiNuocId) {
			_setOriginalDauNoiNuocId = true;

			_originalDauNoiNuocId = _dauNoiNuocId;
		}

		_dauNoiNuocId = dauNoiNuocId;
	}

	public long getOriginalDauNoiNuocId() {
		return _originalDauNoiNuocId;
	}

	@Override
	public int getKeHoachKiemDemNuocId() {
		return _keHoachKiemDemNuocId;
	}

	@Override
	public void setKeHoachKiemDemNuocId(int keHoachKiemDemNuocId) {
		_columnBitmask |= KEHOACHKIEMDEMNUOCID_COLUMN_BITMASK;

		if (!_setOriginalKeHoachKiemDemNuocId) {
			_setOriginalKeHoachKiemDemNuocId = true;

			_originalKeHoachKiemDemNuocId = _keHoachKiemDemNuocId;
		}

		_keHoachKiemDemNuocId = keHoachKiemDemNuocId;
	}

	public int getOriginalKeHoachKiemDemNuocId() {
		return _originalKeHoachKiemDemNuocId;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_maTinh = maTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getThonXom() {
		if (_thonXom == null) {
			return StringPool.BLANK;
		}
		else {
			return _thonXom;
		}
	}

	@Override
	public void setThonXom(String thonXom) {
		_thonXom = thonXom;
	}

	@Override
	public String getTenChuHo() {
		if (_tenChuHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHo;
		}
	}

	@Override
	public void setTenChuHo(String tenChuHo) {
		_tenChuHo = tenChuHo;
	}

	@Override
	public int getGioiTinhChuHo() {
		return _gioiTinhChuHo;
	}

	@Override
	public void setGioiTinhChuHo(int gioiTinhChuHo) {
		_gioiTinhChuHo = gioiTinhChuHo;
	}

	@Override
	public Date getNgayKiemDem() {
		return _ngayKiemDem;
	}

	@Override
	public void setNgayKiemDem(Date ngayKiemDem) {
		_ngayKiemDem = ngayKiemDem;
	}

	@Override
	public int getTimThayNha() {
		return _timThayNha;
	}

	@Override
	public void setTimThayNha(int timThayNha) {
		_timThayNha = timThayNha;
	}

	@Override
	public int getCoNguoiONha() {
		return _coNguoiONha;
	}

	@Override
	public void setCoNguoiONha(int coNguoiONha) {
		_coNguoiONha = coNguoiONha;
	}

	@Override
	public String getHoTenNguoiTraLoi() {
		if (_hoTenNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenNguoiTraLoi;
		}
	}

	@Override
	public void setHoTenNguoiTraLoi(String hoTenNguoiTraLoi) {
		_hoTenNguoiTraLoi = hoTenNguoiTraLoi;
	}

	@Override
	public int getLaChuHoKhong() {
		return _laChuHoKhong;
	}

	@Override
	public void setLaChuHoKhong(int laChuHoKhong) {
		_laChuHoKhong = laChuHoKhong;
	}

	@Override
	public String getGioiTinhNguoiTraLoi() {
		if (_gioiTinhNguoiTraLoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _gioiTinhNguoiTraLoi;
		}
	}

	@Override
	public void setGioiTinhNguoiTraLoi(String gioiTinhNguoiTraLoi) {
		_gioiTinhNguoiTraLoi = gioiTinhNguoiTraLoi;
	}

	@Override
	public String getTenDanToc() {
		if (_tenDanToc == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDanToc;
		}
	}

	@Override
	public void setTenDanToc(String tenDanToc) {
		_tenDanToc = tenDanToc;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public int getSoNguoiTrongHo() {
		return _soNguoiTrongHo;
	}

	@Override
	public void setSoNguoiTrongHo(int soNguoiTrongHo) {
		_soNguoiTrongHo = soNguoiTrongHo;
	}

	@Override
	public int getThanhPhanHoGd() {
		return _thanhPhanHoGd;
	}

	@Override
	public void setThanhPhanHoGd(int thanhPhanHoGd) {
		_thanhPhanHoGd = thanhPhanHoGd;
	}

	@Override
	public int getChuHoDungDs() {
		return _chuHoDungDs;
	}

	@Override
	public void setChuHoDungDs(int chuHoDungDs) {
		_chuHoDungDs = chuHoDungDs;
	}

	@Override
	public String getLyDoKhongDungDs() {
		if (_lyDoKhongDungDs == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDungDs;
		}
	}

	@Override
	public void setLyDoKhongDungDs(String lyDoKhongDungDs) {
		_lyDoKhongDungDs = lyDoKhongDungDs;
	}

	@Override
	public String getTenChuHoHienTai() {
		if (_tenChuHoHienTai == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHoHienTai;
		}
	}

	@Override
	public void setTenChuHoHienTai(String tenChuHoHienTai) {
		_tenChuHoHienTai = tenChuHoHienTai;
	}

	@Override
	public int getGioiTinhChuHoHienTai() {
		return _gioiTinhChuHoHienTai;
	}

	@Override
	public void setGioiTinhChuHoHienTai(int gioiTinhChuHoHienTai) {
		_gioiTinhChuHoHienTai = gioiTinhChuHoHienTai;
	}

	@Override
	public int getDauNoiChua() {
		return _dauNoiChua;
	}

	@Override
	public void setDauNoiChua(int dauNoiChua) {
		_dauNoiChua = dauNoiChua;
	}

	@Override
	public String getAnhDauNoi() {
		if (_anhDauNoi == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhDauNoi;
		}
	}

	@Override
	public void setAnhDauNoi(String anhDauNoi) {
		_anhDauNoi = anhDauNoi;
	}

	@Override
	public Date getThoiGianDauHopDong() {
		return _thoiGianDauHopDong;
	}

	@Override
	public void setThoiGianDauHopDong(Date thoiGianDauHopDong) {
		_thoiGianDauHopDong = thoiGianDauHopDong;
	}

	@Override
	public Date getThoiGianDauNoiThucTe() {
		return _thoiGianDauNoiThucTe;
	}

	@Override
	public void setThoiGianDauNoiThucTe(Date thoiGianDauNoiThucTe) {
		_thoiGianDauNoiThucTe = thoiGianDauNoiThucTe;
	}

	@Override
	public int getVoiNuocChayKhong() {
		return _voiNuocChayKhong;
	}

	@Override
	public void setVoiNuocChayKhong(int voiNuocChayKhong) {
		_voiNuocChayKhong = voiNuocChayKhong;
	}

	@Override
	public int getNuocTrongKhong() {
		return _nuocTrongKhong;
	}

	@Override
	public void setNuocTrongKhong(int nuocTrongKhong) {
		_nuocTrongKhong = nuocTrongKhong;
	}

	@Override
	public String getMauNuoc() {
		if (_mauNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _mauNuoc;
		}
	}

	@Override
	public void setMauNuoc(String mauNuoc) {
		_mauNuoc = mauNuoc;
	}

	@Override
	public String getMuiNuoc() {
		if (_muiNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _muiNuoc;
		}
	}

	@Override
	public void setMuiNuoc(String muiNuoc) {
		_muiNuoc = muiNuoc;
	}

	@Override
	public String getViNuoc() {
		if (_viNuoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _viNuoc;
		}
	}

	@Override
	public void setViNuoc(String viNuoc) {
		_viNuoc = viNuoc;
	}

	@Override
	public String getLoaiKhac() {
		if (_loaiKhac == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiKhac;
		}
	}

	@Override
	public void setLoaiKhac(String loaiKhac) {
		_loaiKhac = loaiKhac;
	}

	@Override
	public int getDaTungDucKhong() {
		return _daTungDucKhong;
	}

	@Override
	public void setDaTungDucKhong(int daTungDucKhong) {
		_daTungDucKhong = daTungDucKhong;
	}

	@Override
	public String getMauNuocTungCo() {
		if (_mauNuocTungCo == null) {
			return StringPool.BLANK;
		}
		else {
			return _mauNuocTungCo;
		}
	}

	@Override
	public void setMauNuocTungCo(String mauNuocTungCo) {
		_mauNuocTungCo = mauNuocTungCo;
	}

	@Override
	public String getMuiNuocTungCo() {
		if (_muiNuocTungCo == null) {
			return StringPool.BLANK;
		}
		else {
			return _muiNuocTungCo;
		}
	}

	@Override
	public void setMuiNuocTungCo(String muiNuocTungCo) {
		_muiNuocTungCo = muiNuocTungCo;
	}

	@Override
	public String getViNuocTungCo() {
		if (_viNuocTungCo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viNuocTungCo;
		}
	}

	@Override
	public void setViNuocTungCo(String viNuocTungCo) {
		_viNuocTungCo = viNuocTungCo;
	}

	@Override
	public String getLoaiKhacTungCo() {
		if (_loaiKhacTungCo == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiKhacTungCo;
		}
	}

	@Override
	public void setLoaiKhacTungCo(String loaiKhacTungCo) {
		_loaiKhacTungCo = loaiKhacTungCo;
	}

	@Override
	public int getCoBeChuaNuoc() {
		return _coBeChuaNuoc;
	}

	@Override
	public void setCoBeChuaNuoc(int coBeChuaNuoc) {
		_coBeChuaNuoc = coBeChuaNuoc;
	}

	@Override
	public int getTinhTrangBe() {
		return _tinhTrangBe;
	}

	@Override
	public void setTinhTrangBe(int tinhTrangBe) {
		_tinhTrangBe = tinhTrangBe;
	}

	@Override
	public String getAnhBeChua() {
		if (_anhBeChua == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhBeChua;
		}
	}

	@Override
	public void setAnhBeChua(String anhBeChua) {
		_anhBeChua = anhBeChua;
	}

	@Override
	public int getBiMatNuoc() {
		return _biMatNuoc;
	}

	@Override
	public void setBiMatNuoc(int biMatNuoc) {
		_biMatNuoc = biMatNuoc;
	}

	@Override
	public int getSoLanMatNuoc() {
		return _soLanMatNuoc;
	}

	@Override
	public void setSoLanMatNuoc(int soLanMatNuoc) {
		_soLanMatNuoc = soLanMatNuoc;
	}

	@Override
	public int getSoGioTrungBinh() {
		return _soGioTrungBinh;
	}

	@Override
	public void setSoGioTrungBinh(int soGioTrungBinh) {
		_soGioTrungBinh = soGioTrungBinh;
	}

	@Override
	public String getSoSeRyDongHo() {
		if (_soSeRyDongHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _soSeRyDongHo;
		}
	}

	@Override
	public void setSoSeRyDongHo(String soSeRyDongHo) {
		_soSeRyDongHo = soSeRyDongHo;
	}

	@Override
	public String getChiSoDongHo() {
		if (_chiSoDongHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _chiSoDongHo;
		}
	}

	@Override
	public void setChiSoDongHo(String chiSoDongHo) {
		_chiSoDongHo = chiSoDongHo;
	}

	@Override
	public String getAnhDongHo() {
		if (_anhDongHo == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhDongHo;
		}
	}

	@Override
	public void setAnhDongHo(String anhDongHo) {
		_anhDongHo = anhDongHo;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getDaKetThucDieuTra() {
		return _daKetThucDieuTra;
	}

	@Override
	public void setDaKetThucDieuTra(int daKetThucDieuTra) {
		_columnBitmask |= DAKETTHUCDIEUTRA_COLUMN_BITMASK;

		if (!_setOriginalDaKetThucDieuTra) {
			_setOriginalDaKetThucDieuTra = true;

			_originalDaKetThucDieuTra = _daKetThucDieuTra;
		}

		_daKetThucDieuTra = daKetThucDieuTra;
	}

	public int getOriginalDaKetThucDieuTra() {
		return _originalDaKetThucDieuTra;
	}

	@Override
	public String getLyDoKhongHoanThanh() {
		if (_lyDoKhongHoanThanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongHoanThanh;
		}
	}

	@Override
	public void setLyDoKhongHoanThanh(String lyDoKhongHoanThanh) {
		_lyDoKhongHoanThanh = lyDoKhongHoanThanh;
	}

	@Override
	public String getIMei() {
		if (_iMei == null) {
			return StringPool.BLANK;
		}
		else {
			return _iMei;
		}
	}

	@Override
	public void setIMei(String iMei) {
		_iMei = iMei;
	}

	@Override
	public String getTaiKhoan() {
		if (_taiKhoan == null) {
			return StringPool.BLANK;
		}
		else {
			return _taiKhoan;
		}
	}

	@Override
	public void setTaiKhoan(String taiKhoan) {
		_taiKhoan = taiKhoan;
	}

	@Override
	public int getDanhGiaKiemDem() {
		return _danhGiaKiemDem;
	}

	@Override
	public void setDanhGiaKiemDem(int danhGiaKiemDem) {
		_columnBitmask |= DANHGIAKIEMDEM_COLUMN_BITMASK;

		if (!_setOriginalDanhGiaKiemDem) {
			_setOriginalDanhGiaKiemDem = true;

			_originalDanhGiaKiemDem = _danhGiaKiemDem;
		}

		_danhGiaKiemDem = danhGiaKiemDem;
	}

	public int getOriginalDanhGiaKiemDem() {
		return _originalDanhGiaKiemDem;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			THONGTINKIEMDEMNUOC.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public THONGTINKIEMDEMNUOC toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (THONGTINKIEMDEMNUOC)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		THONGTINKIEMDEMNUOCImpl thongtinkiemdemnuocImpl = new THONGTINKIEMDEMNUOCImpl();

		thongtinkiemdemnuocImpl.setId(getId());
		thongtinkiemdemnuocImpl.setDauNoiNuocId(getDauNoiNuocId());
		thongtinkiemdemnuocImpl.setKeHoachKiemDemNuocId(getKeHoachKiemDemNuocId());
		thongtinkiemdemnuocImpl.setMaTinh(getMaTinh());
		thongtinkiemdemnuocImpl.setMaHuyen(getMaHuyen());
		thongtinkiemdemnuocImpl.setMaXa(getMaXa());
		thongtinkiemdemnuocImpl.setThonXom(getThonXom());
		thongtinkiemdemnuocImpl.setTenChuHo(getTenChuHo());
		thongtinkiemdemnuocImpl.setGioiTinhChuHo(getGioiTinhChuHo());
		thongtinkiemdemnuocImpl.setNgayKiemDem(getNgayKiemDem());
		thongtinkiemdemnuocImpl.setTimThayNha(getTimThayNha());
		thongtinkiemdemnuocImpl.setCoNguoiONha(getCoNguoiONha());
		thongtinkiemdemnuocImpl.setHoTenNguoiTraLoi(getHoTenNguoiTraLoi());
		thongtinkiemdemnuocImpl.setLaChuHoKhong(getLaChuHoKhong());
		thongtinkiemdemnuocImpl.setGioiTinhNguoiTraLoi(getGioiTinhNguoiTraLoi());
		thongtinkiemdemnuocImpl.setTenDanToc(getTenDanToc());
		thongtinkiemdemnuocImpl.setKinhDo(getKinhDo());
		thongtinkiemdemnuocImpl.setViDo(getViDo());
		thongtinkiemdemnuocImpl.setSoNguoiTrongHo(getSoNguoiTrongHo());
		thongtinkiemdemnuocImpl.setThanhPhanHoGd(getThanhPhanHoGd());
		thongtinkiemdemnuocImpl.setChuHoDungDs(getChuHoDungDs());
		thongtinkiemdemnuocImpl.setLyDoKhongDungDs(getLyDoKhongDungDs());
		thongtinkiemdemnuocImpl.setTenChuHoHienTai(getTenChuHoHienTai());
		thongtinkiemdemnuocImpl.setGioiTinhChuHoHienTai(getGioiTinhChuHoHienTai());
		thongtinkiemdemnuocImpl.setDauNoiChua(getDauNoiChua());
		thongtinkiemdemnuocImpl.setAnhDauNoi(getAnhDauNoi());
		thongtinkiemdemnuocImpl.setThoiGianDauHopDong(getThoiGianDauHopDong());
		thongtinkiemdemnuocImpl.setThoiGianDauNoiThucTe(getThoiGianDauNoiThucTe());
		thongtinkiemdemnuocImpl.setVoiNuocChayKhong(getVoiNuocChayKhong());
		thongtinkiemdemnuocImpl.setNuocTrongKhong(getNuocTrongKhong());
		thongtinkiemdemnuocImpl.setMauNuoc(getMauNuoc());
		thongtinkiemdemnuocImpl.setMuiNuoc(getMuiNuoc());
		thongtinkiemdemnuocImpl.setViNuoc(getViNuoc());
		thongtinkiemdemnuocImpl.setLoaiKhac(getLoaiKhac());
		thongtinkiemdemnuocImpl.setDaTungDucKhong(getDaTungDucKhong());
		thongtinkiemdemnuocImpl.setMauNuocTungCo(getMauNuocTungCo());
		thongtinkiemdemnuocImpl.setMuiNuocTungCo(getMuiNuocTungCo());
		thongtinkiemdemnuocImpl.setViNuocTungCo(getViNuocTungCo());
		thongtinkiemdemnuocImpl.setLoaiKhacTungCo(getLoaiKhacTungCo());
		thongtinkiemdemnuocImpl.setCoBeChuaNuoc(getCoBeChuaNuoc());
		thongtinkiemdemnuocImpl.setTinhTrangBe(getTinhTrangBe());
		thongtinkiemdemnuocImpl.setAnhBeChua(getAnhBeChua());
		thongtinkiemdemnuocImpl.setBiMatNuoc(getBiMatNuoc());
		thongtinkiemdemnuocImpl.setSoLanMatNuoc(getSoLanMatNuoc());
		thongtinkiemdemnuocImpl.setSoGioTrungBinh(getSoGioTrungBinh());
		thongtinkiemdemnuocImpl.setSoSeRyDongHo(getSoSeRyDongHo());
		thongtinkiemdemnuocImpl.setChiSoDongHo(getChiSoDongHo());
		thongtinkiemdemnuocImpl.setAnhDongHo(getAnhDongHo());
		thongtinkiemdemnuocImpl.setGhiChu(getGhiChu());
		thongtinkiemdemnuocImpl.setDaKetThucDieuTra(getDaKetThucDieuTra());
		thongtinkiemdemnuocImpl.setLyDoKhongHoanThanh(getLyDoKhongHoanThanh());
		thongtinkiemdemnuocImpl.setIMei(getIMei());
		thongtinkiemdemnuocImpl.setTaiKhoan(getTaiKhoan());
		thongtinkiemdemnuocImpl.setDanhGiaKiemDem(getDanhGiaKiemDem());

		thongtinkiemdemnuocImpl.resetOriginalValues();

		return thongtinkiemdemnuocImpl;
	}

	@Override
	public int compareTo(THONGTINKIEMDEMNUOC thongtinkiemdemnuoc) {
		int value = 0;

		if (getId() < thongtinkiemdemnuoc.getId()) {
			value = -1;
		}
		else if (getId() > thongtinkiemdemnuoc.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof THONGTINKIEMDEMNUOC)) {
			return false;
		}

		THONGTINKIEMDEMNUOC thongtinkiemdemnuoc = (THONGTINKIEMDEMNUOC)obj;

		long primaryKey = thongtinkiemdemnuoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		THONGTINKIEMDEMNUOCModelImpl thongtinkiemdemnuocModelImpl = this;

		thongtinkiemdemnuocModelImpl._originalDauNoiNuocId = thongtinkiemdemnuocModelImpl._dauNoiNuocId;

		thongtinkiemdemnuocModelImpl._setOriginalDauNoiNuocId = false;

		thongtinkiemdemnuocModelImpl._originalKeHoachKiemDemNuocId = thongtinkiemdemnuocModelImpl._keHoachKiemDemNuocId;

		thongtinkiemdemnuocModelImpl._setOriginalKeHoachKiemDemNuocId = false;

		thongtinkiemdemnuocModelImpl._originalDaKetThucDieuTra = thongtinkiemdemnuocModelImpl._daKetThucDieuTra;

		thongtinkiemdemnuocModelImpl._setOriginalDaKetThucDieuTra = false;

		thongtinkiemdemnuocModelImpl._originalDanhGiaKiemDem = thongtinkiemdemnuocModelImpl._danhGiaKiemDem;

		thongtinkiemdemnuocModelImpl._setOriginalDanhGiaKiemDem = false;

		thongtinkiemdemnuocModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<THONGTINKIEMDEMNUOC> toCacheModel() {
		THONGTINKIEMDEMNUOCCacheModel thongtinkiemdemnuocCacheModel = new THONGTINKIEMDEMNUOCCacheModel();

		thongtinkiemdemnuocCacheModel.id = getId();

		thongtinkiemdemnuocCacheModel.dauNoiNuocId = getDauNoiNuocId();

		thongtinkiemdemnuocCacheModel.keHoachKiemDemNuocId = getKeHoachKiemDemNuocId();

		thongtinkiemdemnuocCacheModel.maTinh = getMaTinh();

		String maTinh = thongtinkiemdemnuocCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			thongtinkiemdemnuocCacheModel.maTinh = null;
		}

		thongtinkiemdemnuocCacheModel.maHuyen = getMaHuyen();

		String maHuyen = thongtinkiemdemnuocCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			thongtinkiemdemnuocCacheModel.maHuyen = null;
		}

		thongtinkiemdemnuocCacheModel.maXa = getMaXa();

		String maXa = thongtinkiemdemnuocCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			thongtinkiemdemnuocCacheModel.maXa = null;
		}

		thongtinkiemdemnuocCacheModel.thonXom = getThonXom();

		String thonXom = thongtinkiemdemnuocCacheModel.thonXom;

		if ((thonXom != null) && (thonXom.length() == 0)) {
			thongtinkiemdemnuocCacheModel.thonXom = null;
		}

		thongtinkiemdemnuocCacheModel.tenChuHo = getTenChuHo();

		String tenChuHo = thongtinkiemdemnuocCacheModel.tenChuHo;

		if ((tenChuHo != null) && (tenChuHo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.tenChuHo = null;
		}

		thongtinkiemdemnuocCacheModel.gioiTinhChuHo = getGioiTinhChuHo();

		Date ngayKiemDem = getNgayKiemDem();

		if (ngayKiemDem != null) {
			thongtinkiemdemnuocCacheModel.ngayKiemDem = ngayKiemDem.getTime();
		}
		else {
			thongtinkiemdemnuocCacheModel.ngayKiemDem = Long.MIN_VALUE;
		}

		thongtinkiemdemnuocCacheModel.timThayNha = getTimThayNha();

		thongtinkiemdemnuocCacheModel.coNguoiONha = getCoNguoiONha();

		thongtinkiemdemnuocCacheModel.hoTenNguoiTraLoi = getHoTenNguoiTraLoi();

		String hoTenNguoiTraLoi = thongtinkiemdemnuocCacheModel.hoTenNguoiTraLoi;

		if ((hoTenNguoiTraLoi != null) && (hoTenNguoiTraLoi.length() == 0)) {
			thongtinkiemdemnuocCacheModel.hoTenNguoiTraLoi = null;
		}

		thongtinkiemdemnuocCacheModel.laChuHoKhong = getLaChuHoKhong();

		thongtinkiemdemnuocCacheModel.gioiTinhNguoiTraLoi = getGioiTinhNguoiTraLoi();

		String gioiTinhNguoiTraLoi = thongtinkiemdemnuocCacheModel.gioiTinhNguoiTraLoi;

		if ((gioiTinhNguoiTraLoi != null) &&
				(gioiTinhNguoiTraLoi.length() == 0)) {
			thongtinkiemdemnuocCacheModel.gioiTinhNguoiTraLoi = null;
		}

		thongtinkiemdemnuocCacheModel.tenDanToc = getTenDanToc();

		String tenDanToc = thongtinkiemdemnuocCacheModel.tenDanToc;

		if ((tenDanToc != null) && (tenDanToc.length() == 0)) {
			thongtinkiemdemnuocCacheModel.tenDanToc = null;
		}

		thongtinkiemdemnuocCacheModel.kinhDo = getKinhDo();

		String kinhDo = thongtinkiemdemnuocCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.kinhDo = null;
		}

		thongtinkiemdemnuocCacheModel.viDo = getViDo();

		String viDo = thongtinkiemdemnuocCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.viDo = null;
		}

		thongtinkiemdemnuocCacheModel.soNguoiTrongHo = getSoNguoiTrongHo();

		thongtinkiemdemnuocCacheModel.thanhPhanHoGd = getThanhPhanHoGd();

		thongtinkiemdemnuocCacheModel.chuHoDungDs = getChuHoDungDs();

		thongtinkiemdemnuocCacheModel.lyDoKhongDungDs = getLyDoKhongDungDs();

		String lyDoKhongDungDs = thongtinkiemdemnuocCacheModel.lyDoKhongDungDs;

		if ((lyDoKhongDungDs != null) && (lyDoKhongDungDs.length() == 0)) {
			thongtinkiemdemnuocCacheModel.lyDoKhongDungDs = null;
		}

		thongtinkiemdemnuocCacheModel.tenChuHoHienTai = getTenChuHoHienTai();

		String tenChuHoHienTai = thongtinkiemdemnuocCacheModel.tenChuHoHienTai;

		if ((tenChuHoHienTai != null) && (tenChuHoHienTai.length() == 0)) {
			thongtinkiemdemnuocCacheModel.tenChuHoHienTai = null;
		}

		thongtinkiemdemnuocCacheModel.gioiTinhChuHoHienTai = getGioiTinhChuHoHienTai();

		thongtinkiemdemnuocCacheModel.dauNoiChua = getDauNoiChua();

		thongtinkiemdemnuocCacheModel.anhDauNoi = getAnhDauNoi();

		String anhDauNoi = thongtinkiemdemnuocCacheModel.anhDauNoi;

		if ((anhDauNoi != null) && (anhDauNoi.length() == 0)) {
			thongtinkiemdemnuocCacheModel.anhDauNoi = null;
		}

		Date thoiGianDauHopDong = getThoiGianDauHopDong();

		if (thoiGianDauHopDong != null) {
			thongtinkiemdemnuocCacheModel.thoiGianDauHopDong = thoiGianDauHopDong.getTime();
		}
		else {
			thongtinkiemdemnuocCacheModel.thoiGianDauHopDong = Long.MIN_VALUE;
		}

		Date thoiGianDauNoiThucTe = getThoiGianDauNoiThucTe();

		if (thoiGianDauNoiThucTe != null) {
			thongtinkiemdemnuocCacheModel.thoiGianDauNoiThucTe = thoiGianDauNoiThucTe.getTime();
		}
		else {
			thongtinkiemdemnuocCacheModel.thoiGianDauNoiThucTe = Long.MIN_VALUE;
		}

		thongtinkiemdemnuocCacheModel.voiNuocChayKhong = getVoiNuocChayKhong();

		thongtinkiemdemnuocCacheModel.nuocTrongKhong = getNuocTrongKhong();

		thongtinkiemdemnuocCacheModel.mauNuoc = getMauNuoc();

		String mauNuoc = thongtinkiemdemnuocCacheModel.mauNuoc;

		if ((mauNuoc != null) && (mauNuoc.length() == 0)) {
			thongtinkiemdemnuocCacheModel.mauNuoc = null;
		}

		thongtinkiemdemnuocCacheModel.muiNuoc = getMuiNuoc();

		String muiNuoc = thongtinkiemdemnuocCacheModel.muiNuoc;

		if ((muiNuoc != null) && (muiNuoc.length() == 0)) {
			thongtinkiemdemnuocCacheModel.muiNuoc = null;
		}

		thongtinkiemdemnuocCacheModel.viNuoc = getViNuoc();

		String viNuoc = thongtinkiemdemnuocCacheModel.viNuoc;

		if ((viNuoc != null) && (viNuoc.length() == 0)) {
			thongtinkiemdemnuocCacheModel.viNuoc = null;
		}

		thongtinkiemdemnuocCacheModel.loaiKhac = getLoaiKhac();

		String loaiKhac = thongtinkiemdemnuocCacheModel.loaiKhac;

		if ((loaiKhac != null) && (loaiKhac.length() == 0)) {
			thongtinkiemdemnuocCacheModel.loaiKhac = null;
		}

		thongtinkiemdemnuocCacheModel.daTungDucKhong = getDaTungDucKhong();

		thongtinkiemdemnuocCacheModel.mauNuocTungCo = getMauNuocTungCo();

		String mauNuocTungCo = thongtinkiemdemnuocCacheModel.mauNuocTungCo;

		if ((mauNuocTungCo != null) && (mauNuocTungCo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.mauNuocTungCo = null;
		}

		thongtinkiemdemnuocCacheModel.muiNuocTungCo = getMuiNuocTungCo();

		String muiNuocTungCo = thongtinkiemdemnuocCacheModel.muiNuocTungCo;

		if ((muiNuocTungCo != null) && (muiNuocTungCo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.muiNuocTungCo = null;
		}

		thongtinkiemdemnuocCacheModel.viNuocTungCo = getViNuocTungCo();

		String viNuocTungCo = thongtinkiemdemnuocCacheModel.viNuocTungCo;

		if ((viNuocTungCo != null) && (viNuocTungCo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.viNuocTungCo = null;
		}

		thongtinkiemdemnuocCacheModel.loaiKhacTungCo = getLoaiKhacTungCo();

		String loaiKhacTungCo = thongtinkiemdemnuocCacheModel.loaiKhacTungCo;

		if ((loaiKhacTungCo != null) && (loaiKhacTungCo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.loaiKhacTungCo = null;
		}

		thongtinkiemdemnuocCacheModel.coBeChuaNuoc = getCoBeChuaNuoc();

		thongtinkiemdemnuocCacheModel.tinhTrangBe = getTinhTrangBe();

		thongtinkiemdemnuocCacheModel.anhBeChua = getAnhBeChua();

		String anhBeChua = thongtinkiemdemnuocCacheModel.anhBeChua;

		if ((anhBeChua != null) && (anhBeChua.length() == 0)) {
			thongtinkiemdemnuocCacheModel.anhBeChua = null;
		}

		thongtinkiemdemnuocCacheModel.biMatNuoc = getBiMatNuoc();

		thongtinkiemdemnuocCacheModel.soLanMatNuoc = getSoLanMatNuoc();

		thongtinkiemdemnuocCacheModel.soGioTrungBinh = getSoGioTrungBinh();

		thongtinkiemdemnuocCacheModel.soSeRyDongHo = getSoSeRyDongHo();

		String soSeRyDongHo = thongtinkiemdemnuocCacheModel.soSeRyDongHo;

		if ((soSeRyDongHo != null) && (soSeRyDongHo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.soSeRyDongHo = null;
		}

		thongtinkiemdemnuocCacheModel.chiSoDongHo = getChiSoDongHo();

		String chiSoDongHo = thongtinkiemdemnuocCacheModel.chiSoDongHo;

		if ((chiSoDongHo != null) && (chiSoDongHo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.chiSoDongHo = null;
		}

		thongtinkiemdemnuocCacheModel.anhDongHo = getAnhDongHo();

		String anhDongHo = thongtinkiemdemnuocCacheModel.anhDongHo;

		if ((anhDongHo != null) && (anhDongHo.length() == 0)) {
			thongtinkiemdemnuocCacheModel.anhDongHo = null;
		}

		thongtinkiemdemnuocCacheModel.ghiChu = getGhiChu();

		String ghiChu = thongtinkiemdemnuocCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			thongtinkiemdemnuocCacheModel.ghiChu = null;
		}

		thongtinkiemdemnuocCacheModel.daKetThucDieuTra = getDaKetThucDieuTra();

		thongtinkiemdemnuocCacheModel.lyDoKhongHoanThanh = getLyDoKhongHoanThanh();

		String lyDoKhongHoanThanh = thongtinkiemdemnuocCacheModel.lyDoKhongHoanThanh;

		if ((lyDoKhongHoanThanh != null) && (lyDoKhongHoanThanh.length() == 0)) {
			thongtinkiemdemnuocCacheModel.lyDoKhongHoanThanh = null;
		}

		thongtinkiemdemnuocCacheModel.iMei = getIMei();

		String iMei = thongtinkiemdemnuocCacheModel.iMei;

		if ((iMei != null) && (iMei.length() == 0)) {
			thongtinkiemdemnuocCacheModel.iMei = null;
		}

		thongtinkiemdemnuocCacheModel.taiKhoan = getTaiKhoan();

		String taiKhoan = thongtinkiemdemnuocCacheModel.taiKhoan;

		if ((taiKhoan != null) && (taiKhoan.length() == 0)) {
			thongtinkiemdemnuocCacheModel.taiKhoan = null;
		}

		thongtinkiemdemnuocCacheModel.danhGiaKiemDem = getDanhGiaKiemDem();

		return thongtinkiemdemnuocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(109);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", dauNoiNuocId=");
		sb.append(getDauNoiNuocId());
		sb.append(", keHoachKiemDemNuocId=");
		sb.append(getKeHoachKiemDemNuocId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", thonXom=");
		sb.append(getThonXom());
		sb.append(", tenChuHo=");
		sb.append(getTenChuHo());
		sb.append(", gioiTinhChuHo=");
		sb.append(getGioiTinhChuHo());
		sb.append(", ngayKiemDem=");
		sb.append(getNgayKiemDem());
		sb.append(", timThayNha=");
		sb.append(getTimThayNha());
		sb.append(", coNguoiONha=");
		sb.append(getCoNguoiONha());
		sb.append(", hoTenNguoiTraLoi=");
		sb.append(getHoTenNguoiTraLoi());
		sb.append(", laChuHoKhong=");
		sb.append(getLaChuHoKhong());
		sb.append(", gioiTinhNguoiTraLoi=");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append(", tenDanToc=");
		sb.append(getTenDanToc());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", soNguoiTrongHo=");
		sb.append(getSoNguoiTrongHo());
		sb.append(", thanhPhanHoGd=");
		sb.append(getThanhPhanHoGd());
		sb.append(", chuHoDungDs=");
		sb.append(getChuHoDungDs());
		sb.append(", lyDoKhongDungDs=");
		sb.append(getLyDoKhongDungDs());
		sb.append(", tenChuHoHienTai=");
		sb.append(getTenChuHoHienTai());
		sb.append(", gioiTinhChuHoHienTai=");
		sb.append(getGioiTinhChuHoHienTai());
		sb.append(", dauNoiChua=");
		sb.append(getDauNoiChua());
		sb.append(", anhDauNoi=");
		sb.append(getAnhDauNoi());
		sb.append(", thoiGianDauHopDong=");
		sb.append(getThoiGianDauHopDong());
		sb.append(", thoiGianDauNoiThucTe=");
		sb.append(getThoiGianDauNoiThucTe());
		sb.append(", voiNuocChayKhong=");
		sb.append(getVoiNuocChayKhong());
		sb.append(", nuocTrongKhong=");
		sb.append(getNuocTrongKhong());
		sb.append(", mauNuoc=");
		sb.append(getMauNuoc());
		sb.append(", muiNuoc=");
		sb.append(getMuiNuoc());
		sb.append(", viNuoc=");
		sb.append(getViNuoc());
		sb.append(", loaiKhac=");
		sb.append(getLoaiKhac());
		sb.append(", daTungDucKhong=");
		sb.append(getDaTungDucKhong());
		sb.append(", mauNuocTungCo=");
		sb.append(getMauNuocTungCo());
		sb.append(", muiNuocTungCo=");
		sb.append(getMuiNuocTungCo());
		sb.append(", viNuocTungCo=");
		sb.append(getViNuocTungCo());
		sb.append(", loaiKhacTungCo=");
		sb.append(getLoaiKhacTungCo());
		sb.append(", coBeChuaNuoc=");
		sb.append(getCoBeChuaNuoc());
		sb.append(", tinhTrangBe=");
		sb.append(getTinhTrangBe());
		sb.append(", anhBeChua=");
		sb.append(getAnhBeChua());
		sb.append(", biMatNuoc=");
		sb.append(getBiMatNuoc());
		sb.append(", soLanMatNuoc=");
		sb.append(getSoLanMatNuoc());
		sb.append(", soGioTrungBinh=");
		sb.append(getSoGioTrungBinh());
		sb.append(", soSeRyDongHo=");
		sb.append(getSoSeRyDongHo());
		sb.append(", chiSoDongHo=");
		sb.append(getChiSoDongHo());
		sb.append(", anhDongHo=");
		sb.append(getAnhDongHo());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", daKetThucDieuTra=");
		sb.append(getDaKetThucDieuTra());
		sb.append(", lyDoKhongHoanThanh=");
		sb.append(getLyDoKhongHoanThanh());
		sb.append(", iMei=");
		sb.append(getIMei());
		sb.append(", taiKhoan=");
		sb.append(getTaiKhoan());
		sb.append(", danhGiaKiemDem=");
		sb.append(getDanhGiaKiemDem());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(166);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.tramcap.dao.model.THONGTINKIEMDEMNUOC");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dauNoiNuocId</column-name><column-value><![CDATA[");
		sb.append(getDauNoiNuocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keHoachKiemDemNuocId</column-name><column-value><![CDATA[");
		sb.append(getKeHoachKiemDemNuocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thonXom</column-name><column-value><![CDATA[");
		sb.append(getThonXom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHo</column-name><column-value><![CDATA[");
		sb.append(getTenChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhChuHo</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKiemDem</column-name><column-value><![CDATA[");
		sb.append(getNgayKiemDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timThayNha</column-name><column-value><![CDATA[");
		sb.append(getTimThayNha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coNguoiONha</column-name><column-value><![CDATA[");
		sb.append(getCoNguoiONha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laChuHoKhong</column-name><column-value><![CDATA[");
		sb.append(getLaChuHoKhong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhNguoiTraLoi</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhNguoiTraLoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDanToc</column-name><column-value><![CDATA[");
		sb.append(getTenDanToc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiTrongHo</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiTrongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhPhanHoGd</column-name><column-value><![CDATA[");
		sb.append(getThanhPhanHoGd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuHoDungDs</column-name><column-value><![CDATA[");
		sb.append(getChuHoDungDs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDungDs</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDungDs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHoHienTai</column-name><column-value><![CDATA[");
		sb.append(getTenChuHoHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinhChuHoHienTai</column-name><column-value><![CDATA[");
		sb.append(getGioiTinhChuHoHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dauNoiChua</column-name><column-value><![CDATA[");
		sb.append(getDauNoiChua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhDauNoi</column-name><column-value><![CDATA[");
		sb.append(getAnhDauNoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiGianDauHopDong</column-name><column-value><![CDATA[");
		sb.append(getThoiGianDauHopDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiGianDauNoiThucTe</column-name><column-value><![CDATA[");
		sb.append(getThoiGianDauNoiThucTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>voiNuocChayKhong</column-name><column-value><![CDATA[");
		sb.append(getVoiNuocChayKhong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocTrongKhong</column-name><column-value><![CDATA[");
		sb.append(getNuocTrongKhong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mauNuoc</column-name><column-value><![CDATA[");
		sb.append(getMauNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>muiNuoc</column-name><column-value><![CDATA[");
		sb.append(getMuiNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viNuoc</column-name><column-value><![CDATA[");
		sb.append(getViNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiKhac</column-name><column-value><![CDATA[");
		sb.append(getLoaiKhac());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daTungDucKhong</column-name><column-value><![CDATA[");
		sb.append(getDaTungDucKhong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mauNuocTungCo</column-name><column-value><![CDATA[");
		sb.append(getMauNuocTungCo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>muiNuocTungCo</column-name><column-value><![CDATA[");
		sb.append(getMuiNuocTungCo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viNuocTungCo</column-name><column-value><![CDATA[");
		sb.append(getViNuocTungCo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiKhacTungCo</column-name><column-value><![CDATA[");
		sb.append(getLoaiKhacTungCo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coBeChuaNuoc</column-name><column-value><![CDATA[");
		sb.append(getCoBeChuaNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tinhTrangBe</column-name><column-value><![CDATA[");
		sb.append(getTinhTrangBe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhBeChua</column-name><column-value><![CDATA[");
		sb.append(getAnhBeChua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>biMatNuoc</column-name><column-value><![CDATA[");
		sb.append(getBiMatNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLanMatNuoc</column-name><column-value><![CDATA[");
		sb.append(getSoLanMatNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGioTrungBinh</column-name><column-value><![CDATA[");
		sb.append(getSoGioTrungBinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soSeRyDongHo</column-name><column-value><![CDATA[");
		sb.append(getSoSeRyDongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiSoDongHo</column-name><column-value><![CDATA[");
		sb.append(getChiSoDongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhDongHo</column-name><column-value><![CDATA[");
		sb.append(getAnhDongHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daKetThucDieuTra</column-name><column-value><![CDATA[");
		sb.append(getDaKetThucDieuTra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongHoanThanh</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongHoanThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iMei</column-name><column-value><![CDATA[");
		sb.append(getIMei());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoan</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danhGiaKiemDem</column-name><column-value><![CDATA[");
		sb.append(getDanhGiaKiemDem());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = THONGTINKIEMDEMNUOC.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			THONGTINKIEMDEMNUOC.class
		};
	private long _id;
	private long _dauNoiNuocId;
	private long _originalDauNoiNuocId;
	private boolean _setOriginalDauNoiNuocId;
	private int _keHoachKiemDemNuocId;
	private int _originalKeHoachKiemDemNuocId;
	private boolean _setOriginalKeHoachKiemDemNuocId;
	private String _maTinh;
	private String _maHuyen;
	private String _maXa;
	private String _thonXom;
	private String _tenChuHo;
	private int _gioiTinhChuHo;
	private Date _ngayKiemDem;
	private int _timThayNha;
	private int _coNguoiONha;
	private String _hoTenNguoiTraLoi;
	private int _laChuHoKhong;
	private String _gioiTinhNguoiTraLoi;
	private String _tenDanToc;
	private String _kinhDo;
	private String _viDo;
	private int _soNguoiTrongHo;
	private int _thanhPhanHoGd;
	private int _chuHoDungDs;
	private String _lyDoKhongDungDs;
	private String _tenChuHoHienTai;
	private int _gioiTinhChuHoHienTai;
	private int _dauNoiChua;
	private String _anhDauNoi;
	private Date _thoiGianDauHopDong;
	private Date _thoiGianDauNoiThucTe;
	private int _voiNuocChayKhong;
	private int _nuocTrongKhong;
	private String _mauNuoc;
	private String _muiNuoc;
	private String _viNuoc;
	private String _loaiKhac;
	private int _daTungDucKhong;
	private String _mauNuocTungCo;
	private String _muiNuocTungCo;
	private String _viNuocTungCo;
	private String _loaiKhacTungCo;
	private int _coBeChuaNuoc;
	private int _tinhTrangBe;
	private String _anhBeChua;
	private int _biMatNuoc;
	private int _soLanMatNuoc;
	private int _soGioTrungBinh;
	private String _soSeRyDongHo;
	private String _chiSoDongHo;
	private String _anhDongHo;
	private String _ghiChu;
	private int _daKetThucDieuTra;
	private int _originalDaKetThucDieuTra;
	private boolean _setOriginalDaKetThucDieuTra;
	private String _lyDoKhongHoanThanh;
	private String _iMei;
	private String _taiKhoan;
	private int _danhGiaKiemDem;
	private int _originalDanhGiaKiemDem;
	private boolean _setOriginalDanhGiaKiemDem;
	private long _columnBitmask;
	private THONGTINKIEMDEMNUOC _escapedModel;
}