/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.tramcap.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc;
import vn.dtt.sol.ns.tramcap.dao.model.TramCapNuocModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TramCapNuoc service. Represents a row in the &quot;ME_TRAMCAPNUOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.tramcap.dao.model.TramCapNuocModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TramCapNuocImpl}.
 * </p>
 *
 * @author khoa.vu
 * @see TramCapNuocImpl
 * @see vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc
 * @see vn.dtt.sol.ns.tramcap.dao.model.TramCapNuocModel
 * @generated
 */
public class TramCapNuocModelImpl extends BaseModelImpl<TramCapNuoc>
	implements TramCapNuocModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tram cap nuoc model instance should use the {@link vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc} interface instead.
	 */
	public static final String TABLE_NAME = "ME_TRAMCAPNUOC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MATRAM", Types.VARCHAR },
			{ "TENTRAM", Types.VARCHAR },
			{ "MATINH", Types.VARCHAR },
			{ "TENTINH", Types.VARCHAR },
			{ "MAHUYEN", Types.VARCHAR },
			{ "TENHUYEN", Types.VARCHAR },
			{ "MAXA", Types.VARCHAR },
			{ "TENXA", Types.VARCHAR },
			{ "DIACHI", Types.VARCHAR },
			{ "KINHDO", Types.VARCHAR },
			{ "VIDO", Types.VARCHAR },
			{ "LOAIHINH", Types.INTEGER },
			{ "LOAIMOHINH", Types.VARCHAR },
			{ "TENMOHINH", Types.VARCHAR },
			{ "CONGXUATTHIETKE", Types.INTEGER },
			{ "TONGDAUNOITHIETKE", Types.INTEGER },
			{ "SONUOICAPTHIETKE", Types.INTEGER },
			{ "TINHTRANGDUAN", Types.INTEGER },
			{ "TIENDOXAYDUNG", Types.INTEGER },
			{ "NAMXAYDUNG", Types.INTEGER },
			{ "NAMHOANTHANH", Types.INTEGER },
			{ "NGAYVANHANH", Types.TIMESTAMP },
			{ "BOMAYVANHANH", Types.INTEGER },
			{ "CHICHU", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "IDNGUOITAO", Types.BIGINT },
			{ "IDNGUOIDANHGIA", Types.BIGINT },
			{ "NGAYDANHGIA", Types.TIMESTAMP },
			{ "TRANGTHAICAPNUOC", Types.INTEGER },
			{ "CONGXUATTHUCTE", Types.INTEGER },
			{ "TONGDAUNOITHUCTE", Types.INTEGER },
			{ "SONGUOICAPTHUCTE", Types.INTEGER },
			{ "TONGCHIPHI", Types.INTEGER },
			{ "TONGDOANHTTHU", Types.INTEGER },
			{ "NUOCDATTIEUCHUAN", Types.INTEGER },
			{ "NUOCCOASEN", Types.INTEGER },
			{ "NUOCTHATTHOAT", Types.INTEGER },
			{ "TRANGTHAIDANHGIA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ME_TRAMCAPNUOC (ID LONG not null primary key,MATRAM VARCHAR(75) null,TENTRAM VARCHAR(75) null,MATINH VARCHAR(75) null,TENTINH VARCHAR(75) null,MAHUYEN VARCHAR(75) null,TENHUYEN VARCHAR(75) null,MAXA VARCHAR(75) null,TENXA VARCHAR(75) null,DIACHI VARCHAR(75) null,KINHDO VARCHAR(75) null,VIDO VARCHAR(75) null,LOAIHINH INTEGER,LOAIMOHINH VARCHAR(75) null,TENMOHINH VARCHAR(75) null,CONGXUATTHIETKE INTEGER,TONGDAUNOITHIETKE INTEGER,SONUOICAPTHIETKE INTEGER,TINHTRANGDUAN INTEGER,TIENDOXAYDUNG INTEGER,NAMXAYDUNG INTEGER,NAMHOANTHANH INTEGER,NGAYVANHANH DATE null,BOMAYVANHANH INTEGER,CHICHU VARCHAR(75) null,NGAYTAO DATE null,IDNGUOITAO LONG,IDNGUOIDANHGIA LONG,NGAYDANHGIA DATE null,TRANGTHAICAPNUOC INTEGER,CONGXUATTHUCTE INTEGER,TONGDAUNOITHUCTE INTEGER,SONGUOICAPTHUCTE INTEGER,TONGCHIPHI INTEGER,TONGDOANHTTHU INTEGER,NUOCDATTIEUCHUAN INTEGER,NUOCCOASEN INTEGER,NUOCTHATTHOAT INTEGER,TRANGTHAIDANHGIA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ME_TRAMCAPNUOC";
	public static final String ORDER_BY_JPQL = " ORDER BY tramCapNuoc.tenTram ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ME_TRAMCAPNUOC.TENTRAM ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc"),
			true);
	public static long MATINH_COLUMN_BITMASK = 1L;
	public static long TENTRAM_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc"));

	public TramCapNuocModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TramCapNuoc.class;
	}

	@Override
	public String getModelClassName() {
		return TramCapNuoc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTram", getMaTram());
		attributes.put("tenTram", getTenTram());
		attributes.put("maTinh", getMaTinh());
		attributes.put("tenTinh", getTenTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("tenHuyen", getTenHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("tenXa", getTenXa());
		attributes.put("diaChi", getDiaChi());
		attributes.put("kinhDo", getKinhDo());
		attributes.put("viDo", getViDo());
		attributes.put("loaiHinh", getLoaiHinh());
		attributes.put("maMoHinh", getMaMoHinh());
		attributes.put("tenMoHinh", getTenMoHinh());
		attributes.put("congXuatThietKe", getCongXuatThietKe());
		attributes.put("tongDauNoiThietKe", getTongDauNoiThietKe());
		attributes.put("soNguoiCapThietKe", getSoNguoiCapThietKe());
		attributes.put("tinhTrangDuAn", getTinhTrangDuAn());
		attributes.put("tienDoXayDung", getTienDoXayDung());
		attributes.put("namXayDung", getNamXayDung());
		attributes.put("namHoanThanh", getNamHoanThanh());
		attributes.put("ngayVanHanh", getNgayVanHanh());
		attributes.put("boMayVanHanh", getBoMayVanHanh());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("idNguoiDanhGia", getIdNguoiDanhGia());
		attributes.put("ngayDanhGia", getNgayDanhGia());
		attributes.put("trangThaiCapNuoc", getTrangThaiCapNuoc());
		attributes.put("congXuatThucTe", getCongXuatThucTe());
		attributes.put("tongDauNoiThucTe", getTongDauNoiThucTe());
		attributes.put("soNguoiCapThucTe", getSoNguoiCapThucTe());
		attributes.put("tongChiPhi", getTongChiPhi());
		attributes.put("tongDoanhThu", getTongDoanhThu());
		attributes.put("nuocDatTieuChuan", getNuocDatTieuChuan());
		attributes.put("nuocCoAsen", getNuocCoAsen());
		attributes.put("nuocThatThoat", getNuocThatThoat());
		attributes.put("trangThaiDanhGia", getTrangThaiDanhGia());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTram = (String)attributes.get("maTram");

		if (maTram != null) {
			setMaTram(maTram);
		}

		String tenTram = (String)attributes.get("tenTram");

		if (tenTram != null) {
			setTenTram(tenTram);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String tenTinh = (String)attributes.get("tenTinh");

		if (tenTinh != null) {
			setTenTinh(tenTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String tenHuyen = (String)attributes.get("tenHuyen");

		if (tenHuyen != null) {
			setTenHuyen(tenHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String tenXa = (String)attributes.get("tenXa");

		if (tenXa != null) {
			setTenXa(tenXa);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		String kinhDo = (String)attributes.get("kinhDo");

		if (kinhDo != null) {
			setKinhDo(kinhDo);
		}

		String viDo = (String)attributes.get("viDo");

		if (viDo != null) {
			setViDo(viDo);
		}

		Integer loaiHinh = (Integer)attributes.get("loaiHinh");

		if (loaiHinh != null) {
			setLoaiHinh(loaiHinh);
		}

		String maMoHinh = (String)attributes.get("maMoHinh");

		if (maMoHinh != null) {
			setMaMoHinh(maMoHinh);
		}

		String tenMoHinh = (String)attributes.get("tenMoHinh");

		if (tenMoHinh != null) {
			setTenMoHinh(tenMoHinh);
		}

		Integer congXuatThietKe = (Integer)attributes.get("congXuatThietKe");

		if (congXuatThietKe != null) {
			setCongXuatThietKe(congXuatThietKe);
		}

		Integer tongDauNoiThietKe = (Integer)attributes.get("tongDauNoiThietKe");

		if (tongDauNoiThietKe != null) {
			setTongDauNoiThietKe(tongDauNoiThietKe);
		}

		Integer soNguoiCapThietKe = (Integer)attributes.get("soNguoiCapThietKe");

		if (soNguoiCapThietKe != null) {
			setSoNguoiCapThietKe(soNguoiCapThietKe);
		}

		Integer tinhTrangDuAn = (Integer)attributes.get("tinhTrangDuAn");

		if (tinhTrangDuAn != null) {
			setTinhTrangDuAn(tinhTrangDuAn);
		}

		Integer tienDoXayDung = (Integer)attributes.get("tienDoXayDung");

		if (tienDoXayDung != null) {
			setTienDoXayDung(tienDoXayDung);
		}

		Integer namXayDung = (Integer)attributes.get("namXayDung");

		if (namXayDung != null) {
			setNamXayDung(namXayDung);
		}

		Integer namHoanThanh = (Integer)attributes.get("namHoanThanh");

		if (namHoanThanh != null) {
			setNamHoanThanh(namHoanThanh);
		}

		Date ngayVanHanh = (Date)attributes.get("ngayVanHanh");

		if (ngayVanHanh != null) {
			setNgayVanHanh(ngayVanHanh);
		}

		Integer boMayVanHanh = (Integer)attributes.get("boMayVanHanh");

		if (boMayVanHanh != null) {
			setBoMayVanHanh(boMayVanHanh);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Long idNguoiTao = (Long)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		Long idNguoiDanhGia = (Long)attributes.get("idNguoiDanhGia");

		if (idNguoiDanhGia != null) {
			setIdNguoiDanhGia(idNguoiDanhGia);
		}

		Date ngayDanhGia = (Date)attributes.get("ngayDanhGia");

		if (ngayDanhGia != null) {
			setNgayDanhGia(ngayDanhGia);
		}

		Integer trangThaiCapNuoc = (Integer)attributes.get("trangThaiCapNuoc");

		if (trangThaiCapNuoc != null) {
			setTrangThaiCapNuoc(trangThaiCapNuoc);
		}

		Integer congXuatThucTe = (Integer)attributes.get("congXuatThucTe");

		if (congXuatThucTe != null) {
			setCongXuatThucTe(congXuatThucTe);
		}

		Integer tongDauNoiThucTe = (Integer)attributes.get("tongDauNoiThucTe");

		if (tongDauNoiThucTe != null) {
			setTongDauNoiThucTe(tongDauNoiThucTe);
		}

		Integer soNguoiCapThucTe = (Integer)attributes.get("soNguoiCapThucTe");

		if (soNguoiCapThucTe != null) {
			setSoNguoiCapThucTe(soNguoiCapThucTe);
		}

		Integer tongChiPhi = (Integer)attributes.get("tongChiPhi");

		if (tongChiPhi != null) {
			setTongChiPhi(tongChiPhi);
		}

		Integer tongDoanhThu = (Integer)attributes.get("tongDoanhThu");

		if (tongDoanhThu != null) {
			setTongDoanhThu(tongDoanhThu);
		}

		Integer nuocDatTieuChuan = (Integer)attributes.get("nuocDatTieuChuan");

		if (nuocDatTieuChuan != null) {
			setNuocDatTieuChuan(nuocDatTieuChuan);
		}

		Integer nuocCoAsen = (Integer)attributes.get("nuocCoAsen");

		if (nuocCoAsen != null) {
			setNuocCoAsen(nuocCoAsen);
		}

		Integer nuocThatThoat = (Integer)attributes.get("nuocThatThoat");

		if (nuocThatThoat != null) {
			setNuocThatThoat(nuocThatThoat);
		}

		Integer trangThaiDanhGia = (Integer)attributes.get("trangThaiDanhGia");

		if (trangThaiDanhGia != null) {
			setTrangThaiDanhGia(trangThaiDanhGia);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getMaTram() {
		if (_maTram == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTram;
		}
	}

	@Override
	public void setMaTram(String maTram) {
		_maTram = maTram;
	}

	@Override
	public String getTenTram() {
		if (_tenTram == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTram;
		}
	}

	@Override
	public void setTenTram(String tenTram) {
		_columnBitmask = -1L;

		if (_originalTenTram == null) {
			_originalTenTram = _tenTram;
		}

		_tenTram = tenTram;
	}

	public String getOriginalTenTram() {
		return GetterUtil.getString(_originalTenTram);
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_columnBitmask |= MATINH_COLUMN_BITMASK;

		if (_originalMaTinh == null) {
			_originalMaTinh = _maTinh;
		}

		_maTinh = maTinh;
	}

	public String getOriginalMaTinh() {
		return GetterUtil.getString(_originalMaTinh);
	}

	@Override
	public String getTenTinh() {
		if (_tenTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTinh;
		}
	}

	@Override
	public void setTenTinh(String tenTinh) {
		_tenTinh = tenTinh;
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getTenHuyen() {
		if (_tenHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenHuyen;
		}
	}

	@Override
	public void setTenHuyen(String tenHuyen) {
		_tenHuyen = tenHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getTenXa() {
		if (_tenXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenXa;
		}
	}

	@Override
	public void setTenXa(String tenXa) {
		_tenXa = tenXa;
	}

	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@Override
	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	@Override
	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	@Override
	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	@Override
	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	@Override
	public int getLoaiHinh() {
		return _loaiHinh;
	}

	@Override
	public void setLoaiHinh(int loaiHinh) {
		_loaiHinh = loaiHinh;
	}

	@Override
	public String getMaMoHinh() {
		if (_maMoHinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maMoHinh;
		}
	}

	@Override
	public void setMaMoHinh(String maMoHinh) {
		_maMoHinh = maMoHinh;
	}

	@Override
	public String getTenMoHinh() {
		if (_tenMoHinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenMoHinh;
		}
	}

	@Override
	public void setTenMoHinh(String tenMoHinh) {
		_tenMoHinh = tenMoHinh;
	}

	@Override
	public int getCongXuatThietKe() {
		return _congXuatThietKe;
	}

	@Override
	public void setCongXuatThietKe(int congXuatThietKe) {
		_congXuatThietKe = congXuatThietKe;
	}

	@Override
	public int getTongDauNoiThietKe() {
		return _tongDauNoiThietKe;
	}

	@Override
	public void setTongDauNoiThietKe(int tongDauNoiThietKe) {
		_tongDauNoiThietKe = tongDauNoiThietKe;
	}

	@Override
	public int getSoNguoiCapThietKe() {
		return _soNguoiCapThietKe;
	}

	@Override
	public void setSoNguoiCapThietKe(int soNguoiCapThietKe) {
		_soNguoiCapThietKe = soNguoiCapThietKe;
	}

	@Override
	public int getTinhTrangDuAn() {
		return _tinhTrangDuAn;
	}

	@Override
	public void setTinhTrangDuAn(int tinhTrangDuAn) {
		_tinhTrangDuAn = tinhTrangDuAn;
	}

	@Override
	public int getTienDoXayDung() {
		return _tienDoXayDung;
	}

	@Override
	public void setTienDoXayDung(int tienDoXayDung) {
		_tienDoXayDung = tienDoXayDung;
	}

	@Override
	public int getNamXayDung() {
		return _namXayDung;
	}

	@Override
	public void setNamXayDung(int namXayDung) {
		_namXayDung = namXayDung;
	}

	@Override
	public int getNamHoanThanh() {
		return _namHoanThanh;
	}

	@Override
	public void setNamHoanThanh(int namHoanThanh) {
		_namHoanThanh = namHoanThanh;
	}

	@Override
	public Date getNgayVanHanh() {
		return _ngayVanHanh;
	}

	@Override
	public void setNgayVanHanh(Date ngayVanHanh) {
		_ngayVanHanh = ngayVanHanh;
	}

	@Override
	public int getBoMayVanHanh() {
		return _boMayVanHanh;
	}

	@Override
	public void setBoMayVanHanh(int boMayVanHanh) {
		_boMayVanHanh = boMayVanHanh;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public long getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(long idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public long getIdNguoiDanhGia() {
		return _idNguoiDanhGia;
	}

	@Override
	public void setIdNguoiDanhGia(long idNguoiDanhGia) {
		_idNguoiDanhGia = idNguoiDanhGia;
	}

	@Override
	public Date getNgayDanhGia() {
		return _ngayDanhGia;
	}

	@Override
	public void setNgayDanhGia(Date ngayDanhGia) {
		_ngayDanhGia = ngayDanhGia;
	}

	@Override
	public int getTrangThaiCapNuoc() {
		return _trangThaiCapNuoc;
	}

	@Override
	public void setTrangThaiCapNuoc(int trangThaiCapNuoc) {
		_trangThaiCapNuoc = trangThaiCapNuoc;
	}

	@Override
	public int getCongXuatThucTe() {
		return _congXuatThucTe;
	}

	@Override
	public void setCongXuatThucTe(int congXuatThucTe) {
		_congXuatThucTe = congXuatThucTe;
	}

	@Override
	public int getTongDauNoiThucTe() {
		return _tongDauNoiThucTe;
	}

	@Override
	public void setTongDauNoiThucTe(int tongDauNoiThucTe) {
		_tongDauNoiThucTe = tongDauNoiThucTe;
	}

	@Override
	public int getSoNguoiCapThucTe() {
		return _soNguoiCapThucTe;
	}

	@Override
	public void setSoNguoiCapThucTe(int soNguoiCapThucTe) {
		_soNguoiCapThucTe = soNguoiCapThucTe;
	}

	@Override
	public int getTongChiPhi() {
		return _tongChiPhi;
	}

	@Override
	public void setTongChiPhi(int tongChiPhi) {
		_tongChiPhi = tongChiPhi;
	}

	@Override
	public int getTongDoanhThu() {
		return _tongDoanhThu;
	}

	@Override
	public void setTongDoanhThu(int tongDoanhThu) {
		_tongDoanhThu = tongDoanhThu;
	}

	@Override
	public int getNuocDatTieuChuan() {
		return _nuocDatTieuChuan;
	}

	@Override
	public void setNuocDatTieuChuan(int nuocDatTieuChuan) {
		_nuocDatTieuChuan = nuocDatTieuChuan;
	}

	@Override
	public int getNuocCoAsen() {
		return _nuocCoAsen;
	}

	@Override
	public void setNuocCoAsen(int nuocCoAsen) {
		_nuocCoAsen = nuocCoAsen;
	}

	@Override
	public int getNuocThatThoat() {
		return _nuocThatThoat;
	}

	@Override
	public void setNuocThatThoat(int nuocThatThoat) {
		_nuocThatThoat = nuocThatThoat;
	}

	@Override
	public int getTrangThaiDanhGia() {
		return _trangThaiDanhGia;
	}

	@Override
	public void setTrangThaiDanhGia(int trangThaiDanhGia) {
		_trangThaiDanhGia = trangThaiDanhGia;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TramCapNuoc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TramCapNuoc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TramCapNuoc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TramCapNuocImpl tramCapNuocImpl = new TramCapNuocImpl();

		tramCapNuocImpl.setId(getId());
		tramCapNuocImpl.setMaTram(getMaTram());
		tramCapNuocImpl.setTenTram(getTenTram());
		tramCapNuocImpl.setMaTinh(getMaTinh());
		tramCapNuocImpl.setTenTinh(getTenTinh());
		tramCapNuocImpl.setMaHuyen(getMaHuyen());
		tramCapNuocImpl.setTenHuyen(getTenHuyen());
		tramCapNuocImpl.setMaXa(getMaXa());
		tramCapNuocImpl.setTenXa(getTenXa());
		tramCapNuocImpl.setDiaChi(getDiaChi());
		tramCapNuocImpl.setKinhDo(getKinhDo());
		tramCapNuocImpl.setViDo(getViDo());
		tramCapNuocImpl.setLoaiHinh(getLoaiHinh());
		tramCapNuocImpl.setMaMoHinh(getMaMoHinh());
		tramCapNuocImpl.setTenMoHinh(getTenMoHinh());
		tramCapNuocImpl.setCongXuatThietKe(getCongXuatThietKe());
		tramCapNuocImpl.setTongDauNoiThietKe(getTongDauNoiThietKe());
		tramCapNuocImpl.setSoNguoiCapThietKe(getSoNguoiCapThietKe());
		tramCapNuocImpl.setTinhTrangDuAn(getTinhTrangDuAn());
		tramCapNuocImpl.setTienDoXayDung(getTienDoXayDung());
		tramCapNuocImpl.setNamXayDung(getNamXayDung());
		tramCapNuocImpl.setNamHoanThanh(getNamHoanThanh());
		tramCapNuocImpl.setNgayVanHanh(getNgayVanHanh());
		tramCapNuocImpl.setBoMayVanHanh(getBoMayVanHanh());
		tramCapNuocImpl.setGhiChu(getGhiChu());
		tramCapNuocImpl.setNgayTao(getNgayTao());
		tramCapNuocImpl.setIdNguoiTao(getIdNguoiTao());
		tramCapNuocImpl.setIdNguoiDanhGia(getIdNguoiDanhGia());
		tramCapNuocImpl.setNgayDanhGia(getNgayDanhGia());
		tramCapNuocImpl.setTrangThaiCapNuoc(getTrangThaiCapNuoc());
		tramCapNuocImpl.setCongXuatThucTe(getCongXuatThucTe());
		tramCapNuocImpl.setTongDauNoiThucTe(getTongDauNoiThucTe());
		tramCapNuocImpl.setSoNguoiCapThucTe(getSoNguoiCapThucTe());
		tramCapNuocImpl.setTongChiPhi(getTongChiPhi());
		tramCapNuocImpl.setTongDoanhThu(getTongDoanhThu());
		tramCapNuocImpl.setNuocDatTieuChuan(getNuocDatTieuChuan());
		tramCapNuocImpl.setNuocCoAsen(getNuocCoAsen());
		tramCapNuocImpl.setNuocThatThoat(getNuocThatThoat());
		tramCapNuocImpl.setTrangThaiDanhGia(getTrangThaiDanhGia());

		tramCapNuocImpl.resetOriginalValues();

		return tramCapNuocImpl;
	}

	@Override
	public int compareTo(TramCapNuoc tramCapNuoc) {
		int value = 0;

		value = getTenTram().compareTo(tramCapNuoc.getTenTram());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TramCapNuoc)) {
			return false;
		}

		TramCapNuoc tramCapNuoc = (TramCapNuoc)obj;

		long primaryKey = tramCapNuoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TramCapNuocModelImpl tramCapNuocModelImpl = this;

		tramCapNuocModelImpl._originalTenTram = tramCapNuocModelImpl._tenTram;

		tramCapNuocModelImpl._originalMaTinh = tramCapNuocModelImpl._maTinh;

		tramCapNuocModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TramCapNuoc> toCacheModel() {
		TramCapNuocCacheModel tramCapNuocCacheModel = new TramCapNuocCacheModel();

		tramCapNuocCacheModel.id = getId();

		tramCapNuocCacheModel.maTram = getMaTram();

		String maTram = tramCapNuocCacheModel.maTram;

		if ((maTram != null) && (maTram.length() == 0)) {
			tramCapNuocCacheModel.maTram = null;
		}

		tramCapNuocCacheModel.tenTram = getTenTram();

		String tenTram = tramCapNuocCacheModel.tenTram;

		if ((tenTram != null) && (tenTram.length() == 0)) {
			tramCapNuocCacheModel.tenTram = null;
		}

		tramCapNuocCacheModel.maTinh = getMaTinh();

		String maTinh = tramCapNuocCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			tramCapNuocCacheModel.maTinh = null;
		}

		tramCapNuocCacheModel.tenTinh = getTenTinh();

		String tenTinh = tramCapNuocCacheModel.tenTinh;

		if ((tenTinh != null) && (tenTinh.length() == 0)) {
			tramCapNuocCacheModel.tenTinh = null;
		}

		tramCapNuocCacheModel.maHuyen = getMaHuyen();

		String maHuyen = tramCapNuocCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			tramCapNuocCacheModel.maHuyen = null;
		}

		tramCapNuocCacheModel.tenHuyen = getTenHuyen();

		String tenHuyen = tramCapNuocCacheModel.tenHuyen;

		if ((tenHuyen != null) && (tenHuyen.length() == 0)) {
			tramCapNuocCacheModel.tenHuyen = null;
		}

		tramCapNuocCacheModel.maXa = getMaXa();

		String maXa = tramCapNuocCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			tramCapNuocCacheModel.maXa = null;
		}

		tramCapNuocCacheModel.tenXa = getTenXa();

		String tenXa = tramCapNuocCacheModel.tenXa;

		if ((tenXa != null) && (tenXa.length() == 0)) {
			tramCapNuocCacheModel.tenXa = null;
		}

		tramCapNuocCacheModel.diaChi = getDiaChi();

		String diaChi = tramCapNuocCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			tramCapNuocCacheModel.diaChi = null;
		}

		tramCapNuocCacheModel.kinhDo = getKinhDo();

		String kinhDo = tramCapNuocCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			tramCapNuocCacheModel.kinhDo = null;
		}

		tramCapNuocCacheModel.viDo = getViDo();

		String viDo = tramCapNuocCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			tramCapNuocCacheModel.viDo = null;
		}

		tramCapNuocCacheModel.loaiHinh = getLoaiHinh();

		tramCapNuocCacheModel.maMoHinh = getMaMoHinh();

		String maMoHinh = tramCapNuocCacheModel.maMoHinh;

		if ((maMoHinh != null) && (maMoHinh.length() == 0)) {
			tramCapNuocCacheModel.maMoHinh = null;
		}

		tramCapNuocCacheModel.tenMoHinh = getTenMoHinh();

		String tenMoHinh = tramCapNuocCacheModel.tenMoHinh;

		if ((tenMoHinh != null) && (tenMoHinh.length() == 0)) {
			tramCapNuocCacheModel.tenMoHinh = null;
		}

		tramCapNuocCacheModel.congXuatThietKe = getCongXuatThietKe();

		tramCapNuocCacheModel.tongDauNoiThietKe = getTongDauNoiThietKe();

		tramCapNuocCacheModel.soNguoiCapThietKe = getSoNguoiCapThietKe();

		tramCapNuocCacheModel.tinhTrangDuAn = getTinhTrangDuAn();

		tramCapNuocCacheModel.tienDoXayDung = getTienDoXayDung();

		tramCapNuocCacheModel.namXayDung = getNamXayDung();

		tramCapNuocCacheModel.namHoanThanh = getNamHoanThanh();

		Date ngayVanHanh = getNgayVanHanh();

		if (ngayVanHanh != null) {
			tramCapNuocCacheModel.ngayVanHanh = ngayVanHanh.getTime();
		}
		else {
			tramCapNuocCacheModel.ngayVanHanh = Long.MIN_VALUE;
		}

		tramCapNuocCacheModel.boMayVanHanh = getBoMayVanHanh();

		tramCapNuocCacheModel.ghiChu = getGhiChu();

		String ghiChu = tramCapNuocCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			tramCapNuocCacheModel.ghiChu = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			tramCapNuocCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			tramCapNuocCacheModel.ngayTao = Long.MIN_VALUE;
		}

		tramCapNuocCacheModel.idNguoiTao = getIdNguoiTao();

		tramCapNuocCacheModel.idNguoiDanhGia = getIdNguoiDanhGia();

		Date ngayDanhGia = getNgayDanhGia();

		if (ngayDanhGia != null) {
			tramCapNuocCacheModel.ngayDanhGia = ngayDanhGia.getTime();
		}
		else {
			tramCapNuocCacheModel.ngayDanhGia = Long.MIN_VALUE;
		}

		tramCapNuocCacheModel.trangThaiCapNuoc = getTrangThaiCapNuoc();

		tramCapNuocCacheModel.congXuatThucTe = getCongXuatThucTe();

		tramCapNuocCacheModel.tongDauNoiThucTe = getTongDauNoiThucTe();

		tramCapNuocCacheModel.soNguoiCapThucTe = getSoNguoiCapThucTe();

		tramCapNuocCacheModel.tongChiPhi = getTongChiPhi();

		tramCapNuocCacheModel.tongDoanhThu = getTongDoanhThu();

		tramCapNuocCacheModel.nuocDatTieuChuan = getNuocDatTieuChuan();

		tramCapNuocCacheModel.nuocCoAsen = getNuocCoAsen();

		tramCapNuocCacheModel.nuocThatThoat = getNuocThatThoat();

		tramCapNuocCacheModel.trangThaiDanhGia = getTrangThaiDanhGia();

		return tramCapNuocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(79);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTram=");
		sb.append(getMaTram());
		sb.append(", tenTram=");
		sb.append(getTenTram());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", tenTinh=");
		sb.append(getTenTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", tenHuyen=");
		sb.append(getTenHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", tenXa=");
		sb.append(getTenXa());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", loaiHinh=");
		sb.append(getLoaiHinh());
		sb.append(", maMoHinh=");
		sb.append(getMaMoHinh());
		sb.append(", tenMoHinh=");
		sb.append(getTenMoHinh());
		sb.append(", congXuatThietKe=");
		sb.append(getCongXuatThietKe());
		sb.append(", tongDauNoiThietKe=");
		sb.append(getTongDauNoiThietKe());
		sb.append(", soNguoiCapThietKe=");
		sb.append(getSoNguoiCapThietKe());
		sb.append(", tinhTrangDuAn=");
		sb.append(getTinhTrangDuAn());
		sb.append(", tienDoXayDung=");
		sb.append(getTienDoXayDung());
		sb.append(", namXayDung=");
		sb.append(getNamXayDung());
		sb.append(", namHoanThanh=");
		sb.append(getNamHoanThanh());
		sb.append(", ngayVanHanh=");
		sb.append(getNgayVanHanh());
		sb.append(", boMayVanHanh=");
		sb.append(getBoMayVanHanh());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", idNguoiDanhGia=");
		sb.append(getIdNguoiDanhGia());
		sb.append(", ngayDanhGia=");
		sb.append(getNgayDanhGia());
		sb.append(", trangThaiCapNuoc=");
		sb.append(getTrangThaiCapNuoc());
		sb.append(", congXuatThucTe=");
		sb.append(getCongXuatThucTe());
		sb.append(", tongDauNoiThucTe=");
		sb.append(getTongDauNoiThucTe());
		sb.append(", soNguoiCapThucTe=");
		sb.append(getSoNguoiCapThucTe());
		sb.append(", tongChiPhi=");
		sb.append(getTongChiPhi());
		sb.append(", tongDoanhThu=");
		sb.append(getTongDoanhThu());
		sb.append(", nuocDatTieuChuan=");
		sb.append(getNuocDatTieuChuan());
		sb.append(", nuocCoAsen=");
		sb.append(getNuocCoAsen());
		sb.append(", nuocThatThoat=");
		sb.append(getNuocThatThoat());
		sb.append(", trangThaiDanhGia=");
		sb.append(getTrangThaiDanhGia());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(121);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.sol.ns.tramcap.dao.model.TramCapNuoc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTram</column-name><column-value><![CDATA[");
		sb.append(getMaTram());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTram</column-name><column-value><![CDATA[");
		sb.append(getTenTram());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTinh</column-name><column-value><![CDATA[");
		sb.append(getTenTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenHuyen</column-name><column-value><![CDATA[");
		sb.append(getTenHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenXa</column-name><column-value><![CDATA[");
		sb.append(getTenXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinh</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maMoHinh</column-name><column-value><![CDATA[");
		sb.append(getMaMoHinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenMoHinh</column-name><column-value><![CDATA[");
		sb.append(getTenMoHinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>congXuatThietKe</column-name><column-value><![CDATA[");
		sb.append(getCongXuatThietKe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongDauNoiThietKe</column-name><column-value><![CDATA[");
		sb.append(getTongDauNoiThietKe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiCapThietKe</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiCapThietKe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tinhTrangDuAn</column-name><column-value><![CDATA[");
		sb.append(getTinhTrangDuAn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tienDoXayDung</column-name><column-value><![CDATA[");
		sb.append(getTienDoXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namXayDung</column-name><column-value><![CDATA[");
		sb.append(getNamXayDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namHoanThanh</column-name><column-value><![CDATA[");
		sb.append(getNamHoanThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayVanHanh</column-name><column-value><![CDATA[");
		sb.append(getNgayVanHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>boMayVanHanh</column-name><column-value><![CDATA[");
		sb.append(getBoMayVanHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiDanhGia</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiDanhGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDanhGia</column-name><column-value><![CDATA[");
		sb.append(getNgayDanhGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiCapNuoc</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiCapNuoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>congXuatThucTe</column-name><column-value><![CDATA[");
		sb.append(getCongXuatThucTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongDauNoiThucTe</column-name><column-value><![CDATA[");
		sb.append(getTongDauNoiThucTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNguoiCapThucTe</column-name><column-value><![CDATA[");
		sb.append(getSoNguoiCapThucTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongChiPhi</column-name><column-value><![CDATA[");
		sb.append(getTongChiPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongDoanhThu</column-name><column-value><![CDATA[");
		sb.append(getTongDoanhThu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocDatTieuChuan</column-name><column-value><![CDATA[");
		sb.append(getNuocDatTieuChuan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocCoAsen</column-name><column-value><![CDATA[");
		sb.append(getNuocCoAsen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nuocThatThoat</column-name><column-value><![CDATA[");
		sb.append(getNuocThatThoat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiDanhGia</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiDanhGia());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TramCapNuoc.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TramCapNuoc.class
		};
	private long _id;
	private String _maTram;
	private String _tenTram;
	private String _originalTenTram;
	private String _maTinh;
	private String _originalMaTinh;
	private String _tenTinh;
	private String _maHuyen;
	private String _tenHuyen;
	private String _maXa;
	private String _tenXa;
	private String _diaChi;
	private String _kinhDo;
	private String _viDo;
	private int _loaiHinh;
	private String _maMoHinh;
	private String _tenMoHinh;
	private int _congXuatThietKe;
	private int _tongDauNoiThietKe;
	private int _soNguoiCapThietKe;
	private int _tinhTrangDuAn;
	private int _tienDoXayDung;
	private int _namXayDung;
	private int _namHoanThanh;
	private Date _ngayVanHanh;
	private int _boMayVanHanh;
	private String _ghiChu;
	private Date _ngayTao;
	private long _idNguoiTao;
	private long _idNguoiDanhGia;
	private Date _ngayDanhGia;
	private int _trangThaiCapNuoc;
	private int _congXuatThucTe;
	private int _tongDauNoiThucTe;
	private int _soNguoiCapThucTe;
	private int _tongChiPhi;
	private int _tongDoanhThu;
	private int _nuocDatTieuChuan;
	private int _nuocCoAsen;
	private int _nuocThatThoat;
	private int _trangThaiDanhGia;
	private long _columnBitmask;
	private TramCapNuoc _escapedModel;
}