/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.sol.ns.vesinhmoitruong.dao.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake;
import vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFakeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DanhGiaVeSinhXaNewFake service. Represents a row in the &quot;DanhGiaVeSinhXaNewFake&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFakeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhGiaVeSinhXaNewFakeImpl}.
 * </p>
 *
 * @author BinhTH
 * @see DanhGiaVeSinhXaNewFakeImpl
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake
 * @see vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFakeModel
 * @generated
 */
public class DanhGiaVeSinhXaNewFakeModelImpl extends BaseModelImpl<DanhGiaVeSinhXaNewFake>
	implements DanhGiaVeSinhXaNewFakeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh gia ve sinh xa new fake model instance should use the {@link vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake} interface instead.
	 */
	public static final String TABLE_NAME = "DanhGiaVeSinhXaNewFake";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.INTEGER },
			{ "maTinh", Types.VARCHAR },
			{ "maHuyen", Types.VARCHAR },
			{ "maXa", Types.VARCHAR },
			{ "maTinhStr", Types.VARCHAR },
			{ "maHuyenStr", Types.VARCHAR },
			{ "maXaStr", Types.VARCHAR },
			{ "nam", Types.INTEGER },
			{ "soDan", Types.INTEGER },
			{ "tongSoHGD", Types.INTEGER },
			{ "soHGDCoNhaTieu", Types.INTEGER },
			{ "soHGDCoNhaTieuHVS", Types.INTEGER },
			{ "soNhaTieuHVSXayMoi", Types.INTEGER },
			{ "tiLeHGDCoNhaTieu", Types.INTEGER },
			{ "tiLeHGDCoNhaTieuHVS", Types.INTEGER },
			{ "tongSoTruongHoc", Types.INTEGER },
			{ "soTruongHocHVS", Types.INTEGER },
			{ "tongSoTramYTe", Types.INTEGER },
			{ "soTramYTeHVS", Types.INTEGER },
			{ "tiLeTruongHocHVS", Types.INTEGER },
			{ "tiLeTramYTeHVS", Types.INTEGER },
			{ "ketLuanVSTX", Types.INTEGER },
			{ "ghiChu", Types.VARCHAR },
			{ "baoCaoDLI", Types.INTEGER },
			{ "ngayTao", Types.TIMESTAMP },
			{ "idNguoiTao", Types.INTEGER },
			{ "dangKyVSTX", Types.INTEGER },
			{ "soNhaTieuHVSMoi", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table DanhGiaVeSinhXaNewFake (id_ INTEGER not null primary key,maTinh VARCHAR(75) null,maHuyen VARCHAR(75) null,maXa VARCHAR(75) null,maTinhStr VARCHAR(75) null,maHuyenStr VARCHAR(75) null,maXaStr VARCHAR(75) null,nam INTEGER,soDan INTEGER,tongSoHGD INTEGER,soHGDCoNhaTieu INTEGER,soHGDCoNhaTieuHVS INTEGER,soNhaTieuHVSXayMoi INTEGER,tiLeHGDCoNhaTieu INTEGER,tiLeHGDCoNhaTieuHVS INTEGER,tongSoTruongHoc INTEGER,soTruongHocHVS INTEGER,tongSoTramYTe INTEGER,soTramYTeHVS INTEGER,tiLeTruongHocHVS INTEGER,tiLeTramYTeHVS INTEGER,ketLuanVSTX INTEGER,ghiChu VARCHAR(75) null,baoCaoDLI INTEGER,ngayTao DATE null,idNguoiTao INTEGER,dangKyVSTX INTEGER,soNhaTieuHVSMoi INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table DanhGiaVeSinhXaNewFake";
	public static final String ORDER_BY_JPQL = " ORDER BY danhGiaVeSinhXaNewFake.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DanhGiaVeSinhXaNewFake.id_ ASC";
	public static final String DATA_SOURCE = "dmDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake"),
			true);
	public static long MATINH_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake"));

	public DanhGiaVeSinhXaNewFakeModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DanhGiaVeSinhXaNewFake.class;
	}

	@Override
	public String getModelClassName() {
		return DanhGiaVeSinhXaNewFake.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTinh", getMaTinh());
		attributes.put("maHuyen", getMaHuyen());
		attributes.put("maXa", getMaXa());
		attributes.put("maTinhStr", getMaTinhStr());
		attributes.put("maHuyenStr", getMaHuyenStr());
		attributes.put("maXaStr", getMaXaStr());
		attributes.put("nam", getNam());
		attributes.put("soDan", getSoDan());
		attributes.put("tongSoHGD", getTongSoHGD());
		attributes.put("soHGDCoNhaTieu", getSoHGDCoNhaTieu());
		attributes.put("soHGDCoNhaTieuHVS", getSoHGDCoNhaTieuHVS());
		attributes.put("soNhaTieuHVSXayMoi", getSoNhaTieuHVSXayMoi());
		attributes.put("tiLeHGDCoNhaTieu", getTiLeHGDCoNhaTieu());
		attributes.put("tiLeHGDCoNhaTieuHVS", getTiLeHGDCoNhaTieuHVS());
		attributes.put("tongSoTruongHoc", getTongSoTruongHoc());
		attributes.put("soTruongHocHVS", getSoTruongHocHVS());
		attributes.put("tongSoTramYTe", getTongSoTramYTe());
		attributes.put("soTramYTeHVS", getSoTramYTeHVS());
		attributes.put("tiLeTruongHocHVS", getTiLeTruongHocHVS());
		attributes.put("tiLeTramYTeHVS", getTiLeTramYTeHVS());
		attributes.put("ketLuanVSTX", getKetLuanVSTX());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("baoCaoDLI", getBaoCaoDLI());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("idNguoiTao", getIdNguoiTao());
		attributes.put("dangKyVSTX", getDangKyVSTX());
		attributes.put("soNhaTieuHVSMoi", getSoNhaTieuHVSMoi());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTinh = (String)attributes.get("maTinh");

		if (maTinh != null) {
			setMaTinh(maTinh);
		}

		String maHuyen = (String)attributes.get("maHuyen");

		if (maHuyen != null) {
			setMaHuyen(maHuyen);
		}

		String maXa = (String)attributes.get("maXa");

		if (maXa != null) {
			setMaXa(maXa);
		}

		String maTinhStr = (String)attributes.get("maTinhStr");

		if (maTinhStr != null) {
			setMaTinhStr(maTinhStr);
		}

		String maHuyenStr = (String)attributes.get("maHuyenStr");

		if (maHuyenStr != null) {
			setMaHuyenStr(maHuyenStr);
		}

		String maXaStr = (String)attributes.get("maXaStr");

		if (maXaStr != null) {
			setMaXaStr(maXaStr);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Integer soDan = (Integer)attributes.get("soDan");

		if (soDan != null) {
			setSoDan(soDan);
		}

		Integer tongSoHGD = (Integer)attributes.get("tongSoHGD");

		if (tongSoHGD != null) {
			setTongSoHGD(tongSoHGD);
		}

		Integer soHGDCoNhaTieu = (Integer)attributes.get("soHGDCoNhaTieu");

		if (soHGDCoNhaTieu != null) {
			setSoHGDCoNhaTieu(soHGDCoNhaTieu);
		}

		Integer soHGDCoNhaTieuHVS = (Integer)attributes.get("soHGDCoNhaTieuHVS");

		if (soHGDCoNhaTieuHVS != null) {
			setSoHGDCoNhaTieuHVS(soHGDCoNhaTieuHVS);
		}

		Integer soNhaTieuHVSXayMoi = (Integer)attributes.get(
				"soNhaTieuHVSXayMoi");

		if (soNhaTieuHVSXayMoi != null) {
			setSoNhaTieuHVSXayMoi(soNhaTieuHVSXayMoi);
		}

		Integer tiLeHGDCoNhaTieu = (Integer)attributes.get("tiLeHGDCoNhaTieu");

		if (tiLeHGDCoNhaTieu != null) {
			setTiLeHGDCoNhaTieu(tiLeHGDCoNhaTieu);
		}

		Integer tiLeHGDCoNhaTieuHVS = (Integer)attributes.get(
				"tiLeHGDCoNhaTieuHVS");

		if (tiLeHGDCoNhaTieuHVS != null) {
			setTiLeHGDCoNhaTieuHVS(tiLeHGDCoNhaTieuHVS);
		}

		Integer tongSoTruongHoc = (Integer)attributes.get("tongSoTruongHoc");

		if (tongSoTruongHoc != null) {
			setTongSoTruongHoc(tongSoTruongHoc);
		}

		Integer soTruongHocHVS = (Integer)attributes.get("soTruongHocHVS");

		if (soTruongHocHVS != null) {
			setSoTruongHocHVS(soTruongHocHVS);
		}

		Integer tongSoTramYTe = (Integer)attributes.get("tongSoTramYTe");

		if (tongSoTramYTe != null) {
			setTongSoTramYTe(tongSoTramYTe);
		}

		Integer soTramYTeHVS = (Integer)attributes.get("soTramYTeHVS");

		if (soTramYTeHVS != null) {
			setSoTramYTeHVS(soTramYTeHVS);
		}

		Integer tiLeTruongHocHVS = (Integer)attributes.get("tiLeTruongHocHVS");

		if (tiLeTruongHocHVS != null) {
			setTiLeTruongHocHVS(tiLeTruongHocHVS);
		}

		Integer tiLeTramYTeHVS = (Integer)attributes.get("tiLeTramYTeHVS");

		if (tiLeTramYTeHVS != null) {
			setTiLeTramYTeHVS(tiLeTramYTeHVS);
		}

		Integer ketLuanVSTX = (Integer)attributes.get("ketLuanVSTX");

		if (ketLuanVSTX != null) {
			setKetLuanVSTX(ketLuanVSTX);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Integer baoCaoDLI = (Integer)attributes.get("baoCaoDLI");

		if (baoCaoDLI != null) {
			setBaoCaoDLI(baoCaoDLI);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Integer idNguoiTao = (Integer)attributes.get("idNguoiTao");

		if (idNguoiTao != null) {
			setIdNguoiTao(idNguoiTao);
		}

		Integer dangKyVSTX = (Integer)attributes.get("dangKyVSTX");

		if (dangKyVSTX != null) {
			setDangKyVSTX(dangKyVSTX);
		}

		Integer soNhaTieuHVSMoi = (Integer)attributes.get("soNhaTieuHVSMoi");

		if (soNhaTieuHVSMoi != null) {
			setSoNhaTieuHVSMoi(soNhaTieuHVSMoi);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getMaTinh() {
		if (_maTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinh;
		}
	}

	@Override
	public void setMaTinh(String maTinh) {
		_columnBitmask |= MATINH_COLUMN_BITMASK;

		if (_originalMaTinh == null) {
			_originalMaTinh = _maTinh;
		}

		_maTinh = maTinh;
	}

	public String getOriginalMaTinh() {
		return GetterUtil.getString(_originalMaTinh);
	}

	@Override
	public String getMaHuyen() {
		if (_maHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyen;
		}
	}

	@Override
	public void setMaHuyen(String maHuyen) {
		_maHuyen = maHuyen;
	}

	@Override
	public String getMaXa() {
		if (_maXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXa;
		}
	}

	@Override
	public void setMaXa(String maXa) {
		_maXa = maXa;
	}

	@Override
	public String getMaTinhStr() {
		if (_maTinhStr == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhStr;
		}
	}

	@Override
	public void setMaTinhStr(String maTinhStr) {
		_maTinhStr = maTinhStr;
	}

	@Override
	public String getMaHuyenStr() {
		if (_maHuyenStr == null) {
			return StringPool.BLANK;
		}
		else {
			return _maHuyenStr;
		}
	}

	@Override
	public void setMaHuyenStr(String maHuyenStr) {
		_maHuyenStr = maHuyenStr;
	}

	@Override
	public String getMaXaStr() {
		if (_maXaStr == null) {
			return StringPool.BLANK;
		}
		else {
			return _maXaStr;
		}
	}

	@Override
	public void setMaXaStr(String maXaStr) {
		_maXaStr = maXaStr;
	}

	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_nam = nam;
	}

	@Override
	public int getSoDan() {
		return _soDan;
	}

	@Override
	public void setSoDan(int soDan) {
		_soDan = soDan;
	}

	@Override
	public int getTongSoHGD() {
		return _tongSoHGD;
	}

	@Override
	public void setTongSoHGD(int tongSoHGD) {
		_tongSoHGD = tongSoHGD;
	}

	@Override
	public int getSoHGDCoNhaTieu() {
		return _soHGDCoNhaTieu;
	}

	@Override
	public void setSoHGDCoNhaTieu(int soHGDCoNhaTieu) {
		_soHGDCoNhaTieu = soHGDCoNhaTieu;
	}

	@Override
	public int getSoHGDCoNhaTieuHVS() {
		return _soHGDCoNhaTieuHVS;
	}

	@Override
	public void setSoHGDCoNhaTieuHVS(int soHGDCoNhaTieuHVS) {
		_soHGDCoNhaTieuHVS = soHGDCoNhaTieuHVS;
	}

	@Override
	public int getSoNhaTieuHVSXayMoi() {
		return _soNhaTieuHVSXayMoi;
	}

	@Override
	public void setSoNhaTieuHVSXayMoi(int soNhaTieuHVSXayMoi) {
		_soNhaTieuHVSXayMoi = soNhaTieuHVSXayMoi;
	}

	@Override
	public int getTiLeHGDCoNhaTieu() {
		return _tiLeHGDCoNhaTieu;
	}

	@Override
	public void setTiLeHGDCoNhaTieu(int tiLeHGDCoNhaTieu) {
		_tiLeHGDCoNhaTieu = tiLeHGDCoNhaTieu;
	}

	@Override
	public int getTiLeHGDCoNhaTieuHVS() {
		return _tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public void setTiLeHGDCoNhaTieuHVS(int tiLeHGDCoNhaTieuHVS) {
		_tiLeHGDCoNhaTieuHVS = tiLeHGDCoNhaTieuHVS;
	}

	@Override
	public int getTongSoTruongHoc() {
		return _tongSoTruongHoc;
	}

	@Override
	public void setTongSoTruongHoc(int tongSoTruongHoc) {
		_tongSoTruongHoc = tongSoTruongHoc;
	}

	@Override
	public int getSoTruongHocHVS() {
		return _soTruongHocHVS;
	}

	@Override
	public void setSoTruongHocHVS(int soTruongHocHVS) {
		_soTruongHocHVS = soTruongHocHVS;
	}

	@Override
	public int getTongSoTramYTe() {
		return _tongSoTramYTe;
	}

	@Override
	public void setTongSoTramYTe(int tongSoTramYTe) {
		_tongSoTramYTe = tongSoTramYTe;
	}

	@Override
	public int getSoTramYTeHVS() {
		return _soTramYTeHVS;
	}

	@Override
	public void setSoTramYTeHVS(int soTramYTeHVS) {
		_soTramYTeHVS = soTramYTeHVS;
	}

	@Override
	public int getTiLeTruongHocHVS() {
		return _tiLeTruongHocHVS;
	}

	@Override
	public void setTiLeTruongHocHVS(int tiLeTruongHocHVS) {
		_tiLeTruongHocHVS = tiLeTruongHocHVS;
	}

	@Override
	public int getTiLeTramYTeHVS() {
		return _tiLeTramYTeHVS;
	}

	@Override
	public void setTiLeTramYTeHVS(int tiLeTramYTeHVS) {
		_tiLeTramYTeHVS = tiLeTramYTeHVS;
	}

	@Override
	public int getKetLuanVSTX() {
		return _ketLuanVSTX;
	}

	@Override
	public void setKetLuanVSTX(int ketLuanVSTX) {
		_ketLuanVSTX = ketLuanVSTX;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public int getBaoCaoDLI() {
		return _baoCaoDLI;
	}

	@Override
	public void setBaoCaoDLI(int baoCaoDLI) {
		_baoCaoDLI = baoCaoDLI;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public int getIdNguoiTao() {
		return _idNguoiTao;
	}

	@Override
	public void setIdNguoiTao(int idNguoiTao) {
		_idNguoiTao = idNguoiTao;
	}

	@Override
	public int getDangKyVSTX() {
		return _dangKyVSTX;
	}

	@Override
	public void setDangKyVSTX(int dangKyVSTX) {
		_dangKyVSTX = dangKyVSTX;
	}

	@Override
	public int getSoNhaTieuHVSMoi() {
		return _soNhaTieuHVSMoi;
	}

	@Override
	public void setSoNhaTieuHVSMoi(int soNhaTieuHVSMoi) {
		_soNhaTieuHVSMoi = soNhaTieuHVSMoi;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DanhGiaVeSinhXaNewFake toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DanhGiaVeSinhXaNewFake)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DanhGiaVeSinhXaNewFakeImpl danhGiaVeSinhXaNewFakeImpl = new DanhGiaVeSinhXaNewFakeImpl();

		danhGiaVeSinhXaNewFakeImpl.setId(getId());
		danhGiaVeSinhXaNewFakeImpl.setMaTinh(getMaTinh());
		danhGiaVeSinhXaNewFakeImpl.setMaHuyen(getMaHuyen());
		danhGiaVeSinhXaNewFakeImpl.setMaXa(getMaXa());
		danhGiaVeSinhXaNewFakeImpl.setMaTinhStr(getMaTinhStr());
		danhGiaVeSinhXaNewFakeImpl.setMaHuyenStr(getMaHuyenStr());
		danhGiaVeSinhXaNewFakeImpl.setMaXaStr(getMaXaStr());
		danhGiaVeSinhXaNewFakeImpl.setNam(getNam());
		danhGiaVeSinhXaNewFakeImpl.setSoDan(getSoDan());
		danhGiaVeSinhXaNewFakeImpl.setTongSoHGD(getTongSoHGD());
		danhGiaVeSinhXaNewFakeImpl.setSoHGDCoNhaTieu(getSoHGDCoNhaTieu());
		danhGiaVeSinhXaNewFakeImpl.setSoHGDCoNhaTieuHVS(getSoHGDCoNhaTieuHVS());
		danhGiaVeSinhXaNewFakeImpl.setSoNhaTieuHVSXayMoi(getSoNhaTieuHVSXayMoi());
		danhGiaVeSinhXaNewFakeImpl.setTiLeHGDCoNhaTieu(getTiLeHGDCoNhaTieu());
		danhGiaVeSinhXaNewFakeImpl.setTiLeHGDCoNhaTieuHVS(getTiLeHGDCoNhaTieuHVS());
		danhGiaVeSinhXaNewFakeImpl.setTongSoTruongHoc(getTongSoTruongHoc());
		danhGiaVeSinhXaNewFakeImpl.setSoTruongHocHVS(getSoTruongHocHVS());
		danhGiaVeSinhXaNewFakeImpl.setTongSoTramYTe(getTongSoTramYTe());
		danhGiaVeSinhXaNewFakeImpl.setSoTramYTeHVS(getSoTramYTeHVS());
		danhGiaVeSinhXaNewFakeImpl.setTiLeTruongHocHVS(getTiLeTruongHocHVS());
		danhGiaVeSinhXaNewFakeImpl.setTiLeTramYTeHVS(getTiLeTramYTeHVS());
		danhGiaVeSinhXaNewFakeImpl.setKetLuanVSTX(getKetLuanVSTX());
		danhGiaVeSinhXaNewFakeImpl.setGhiChu(getGhiChu());
		danhGiaVeSinhXaNewFakeImpl.setBaoCaoDLI(getBaoCaoDLI());
		danhGiaVeSinhXaNewFakeImpl.setNgayTao(getNgayTao());
		danhGiaVeSinhXaNewFakeImpl.setIdNguoiTao(getIdNguoiTao());
		danhGiaVeSinhXaNewFakeImpl.setDangKyVSTX(getDangKyVSTX());
		danhGiaVeSinhXaNewFakeImpl.setSoNhaTieuHVSMoi(getSoNhaTieuHVSMoi());

		danhGiaVeSinhXaNewFakeImpl.resetOriginalValues();

		return danhGiaVeSinhXaNewFakeImpl;
	}

	@Override
	public int compareTo(DanhGiaVeSinhXaNewFake danhGiaVeSinhXaNewFake) {
		int value = 0;

		if (getId() < danhGiaVeSinhXaNewFake.getId()) {
			value = -1;
		}
		else if (getId() > danhGiaVeSinhXaNewFake.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DanhGiaVeSinhXaNewFake)) {
			return false;
		}

		DanhGiaVeSinhXaNewFake danhGiaVeSinhXaNewFake = (DanhGiaVeSinhXaNewFake)obj;

		int primaryKey = danhGiaVeSinhXaNewFake.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhGiaVeSinhXaNewFakeModelImpl danhGiaVeSinhXaNewFakeModelImpl = this;

		danhGiaVeSinhXaNewFakeModelImpl._originalMaTinh = danhGiaVeSinhXaNewFakeModelImpl._maTinh;

		danhGiaVeSinhXaNewFakeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhGiaVeSinhXaNewFake> toCacheModel() {
		DanhGiaVeSinhXaNewFakeCacheModel danhGiaVeSinhXaNewFakeCacheModel = new DanhGiaVeSinhXaNewFakeCacheModel();

		danhGiaVeSinhXaNewFakeCacheModel.id = getId();

		danhGiaVeSinhXaNewFakeCacheModel.maTinh = getMaTinh();

		String maTinh = danhGiaVeSinhXaNewFakeCacheModel.maTinh;

		if ((maTinh != null) && (maTinh.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maTinh = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.maHuyen = getMaHuyen();

		String maHuyen = danhGiaVeSinhXaNewFakeCacheModel.maHuyen;

		if ((maHuyen != null) && (maHuyen.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maHuyen = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.maXa = getMaXa();

		String maXa = danhGiaVeSinhXaNewFakeCacheModel.maXa;

		if ((maXa != null) && (maXa.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maXa = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.maTinhStr = getMaTinhStr();

		String maTinhStr = danhGiaVeSinhXaNewFakeCacheModel.maTinhStr;

		if ((maTinhStr != null) && (maTinhStr.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maTinhStr = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.maHuyenStr = getMaHuyenStr();

		String maHuyenStr = danhGiaVeSinhXaNewFakeCacheModel.maHuyenStr;

		if ((maHuyenStr != null) && (maHuyenStr.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maHuyenStr = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.maXaStr = getMaXaStr();

		String maXaStr = danhGiaVeSinhXaNewFakeCacheModel.maXaStr;

		if ((maXaStr != null) && (maXaStr.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.maXaStr = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.nam = getNam();

		danhGiaVeSinhXaNewFakeCacheModel.soDan = getSoDan();

		danhGiaVeSinhXaNewFakeCacheModel.tongSoHGD = getTongSoHGD();

		danhGiaVeSinhXaNewFakeCacheModel.soHGDCoNhaTieu = getSoHGDCoNhaTieu();

		danhGiaVeSinhXaNewFakeCacheModel.soHGDCoNhaTieuHVS = getSoHGDCoNhaTieuHVS();

		danhGiaVeSinhXaNewFakeCacheModel.soNhaTieuHVSXayMoi = getSoNhaTieuHVSXayMoi();

		danhGiaVeSinhXaNewFakeCacheModel.tiLeHGDCoNhaTieu = getTiLeHGDCoNhaTieu();

		danhGiaVeSinhXaNewFakeCacheModel.tiLeHGDCoNhaTieuHVS = getTiLeHGDCoNhaTieuHVS();

		danhGiaVeSinhXaNewFakeCacheModel.tongSoTruongHoc = getTongSoTruongHoc();

		danhGiaVeSinhXaNewFakeCacheModel.soTruongHocHVS = getSoTruongHocHVS();

		danhGiaVeSinhXaNewFakeCacheModel.tongSoTramYTe = getTongSoTramYTe();

		danhGiaVeSinhXaNewFakeCacheModel.soTramYTeHVS = getSoTramYTeHVS();

		danhGiaVeSinhXaNewFakeCacheModel.tiLeTruongHocHVS = getTiLeTruongHocHVS();

		danhGiaVeSinhXaNewFakeCacheModel.tiLeTramYTeHVS = getTiLeTramYTeHVS();

		danhGiaVeSinhXaNewFakeCacheModel.ketLuanVSTX = getKetLuanVSTX();

		danhGiaVeSinhXaNewFakeCacheModel.ghiChu = getGhiChu();

		String ghiChu = danhGiaVeSinhXaNewFakeCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			danhGiaVeSinhXaNewFakeCacheModel.ghiChu = null;
		}

		danhGiaVeSinhXaNewFakeCacheModel.baoCaoDLI = getBaoCaoDLI();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhGiaVeSinhXaNewFakeCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhGiaVeSinhXaNewFakeCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danhGiaVeSinhXaNewFakeCacheModel.idNguoiTao = getIdNguoiTao();

		danhGiaVeSinhXaNewFakeCacheModel.dangKyVSTX = getDangKyVSTX();

		danhGiaVeSinhXaNewFakeCacheModel.soNhaTieuHVSMoi = getSoNhaTieuHVSMoi();

		return danhGiaVeSinhXaNewFakeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(57);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTinh=");
		sb.append(getMaTinh());
		sb.append(", maHuyen=");
		sb.append(getMaHuyen());
		sb.append(", maXa=");
		sb.append(getMaXa());
		sb.append(", maTinhStr=");
		sb.append(getMaTinhStr());
		sb.append(", maHuyenStr=");
		sb.append(getMaHuyenStr());
		sb.append(", maXaStr=");
		sb.append(getMaXaStr());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", soDan=");
		sb.append(getSoDan());
		sb.append(", tongSoHGD=");
		sb.append(getTongSoHGD());
		sb.append(", soHGDCoNhaTieu=");
		sb.append(getSoHGDCoNhaTieu());
		sb.append(", soHGDCoNhaTieuHVS=");
		sb.append(getSoHGDCoNhaTieuHVS());
		sb.append(", soNhaTieuHVSXayMoi=");
		sb.append(getSoNhaTieuHVSXayMoi());
		sb.append(", tiLeHGDCoNhaTieu=");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append(", tiLeHGDCoNhaTieuHVS=");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append(", tongSoTruongHoc=");
		sb.append(getTongSoTruongHoc());
		sb.append(", soTruongHocHVS=");
		sb.append(getSoTruongHocHVS());
		sb.append(", tongSoTramYTe=");
		sb.append(getTongSoTramYTe());
		sb.append(", soTramYTeHVS=");
		sb.append(getSoTramYTeHVS());
		sb.append(", tiLeTruongHocHVS=");
		sb.append(getTiLeTruongHocHVS());
		sb.append(", tiLeTramYTeHVS=");
		sb.append(getTiLeTramYTeHVS());
		sb.append(", ketLuanVSTX=");
		sb.append(getKetLuanVSTX());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", baoCaoDLI=");
		sb.append(getBaoCaoDLI());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", idNguoiTao=");
		sb.append(getIdNguoiTao());
		sb.append(", dangKyVSTX=");
		sb.append(getDangKyVSTX());
		sb.append(", soNhaTieuHVSMoi=");
		sb.append(getSoNhaTieuHVSMoi());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(88);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.sol.ns.vesinhmoitruong.dao.model.DanhGiaVeSinhXaNewFake");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinh</column-name><column-value><![CDATA[");
		sb.append(getMaTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXa</column-name><column-value><![CDATA[");
		sb.append(getMaXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhStr</column-name><column-value><![CDATA[");
		sb.append(getMaTinhStr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maHuyenStr</column-name><column-value><![CDATA[");
		sb.append(getMaHuyenStr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maXaStr</column-name><column-value><![CDATA[");
		sb.append(getMaXaStr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDan</column-name><column-value><![CDATA[");
		sb.append(getSoDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoHGD</column-name><column-value><![CDATA[");
		sb.append(getTongSoHGD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHGDCoNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getSoHGDCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHGDCoNhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getSoHGDCoNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNhaTieuHVSXayMoi</column-name><column-value><![CDATA[");
		sb.append(getSoNhaTieuHVSXayMoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieu</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeHGDCoNhaTieuHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeHGDCoNhaTieuHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoTruongHoc</column-name><column-value><![CDATA[");
		sb.append(getTongSoTruongHoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTruongHocHVS</column-name><column-value><![CDATA[");
		sb.append(getSoTruongHocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoTramYTe</column-name><column-value><![CDATA[");
		sb.append(getTongSoTramYTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTramYTeHVS</column-name><column-value><![CDATA[");
		sb.append(getSoTramYTeHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTruongHocHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTruongHocHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeTramYTeHVS</column-name><column-value><![CDATA[");
		sb.append(getTiLeTramYTeHVS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketLuanVSTX</column-name><column-value><![CDATA[");
		sb.append(getKetLuanVSTX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>baoCaoDLI</column-name><column-value><![CDATA[");
		sb.append(getBaoCaoDLI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNguoiTao</column-name><column-value><![CDATA[");
		sb.append(getIdNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dangKyVSTX</column-name><column-value><![CDATA[");
		sb.append(getDangKyVSTX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNhaTieuHVSMoi</column-name><column-value><![CDATA[");
		sb.append(getSoNhaTieuHVSMoi());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhGiaVeSinhXaNewFake.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DanhGiaVeSinhXaNewFake.class
		};
	private int _id;
	private String _maTinh;
	private String _originalMaTinh;
	private String _maHuyen;
	private String _maXa;
	private String _maTinhStr;
	private String _maHuyenStr;
	private String _maXaStr;
	private int _nam;
	private int _soDan;
	private int _tongSoHGD;
	private int _soHGDCoNhaTieu;
	private int _soHGDCoNhaTieuHVS;
	private int _soNhaTieuHVSXayMoi;
	private int _tiLeHGDCoNhaTieu;
	private int _tiLeHGDCoNhaTieuHVS;
	private int _tongSoTruongHoc;
	private int _soTruongHocHVS;
	private int _tongSoTramYTe;
	private int _soTramYTeHVS;
	private int _tiLeTruongHocHVS;
	private int _tiLeTramYTeHVS;
	private int _ketLuanVSTX;
	private String _ghiChu;
	private int _baoCaoDLI;
	private Date _ngayTao;
	private int _idNguoiTao;
	private int _dangKyVSTX;
	private int _soNhaTieuHVSMoi;
	private long _columnBitmask;
	private DanhGiaVeSinhXaNewFake _escapedModel;
}